### ISSUE TITLE
Fix snapshots/ad-blocker issue

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero#10]
See here.
http://forums.zotero.org/discussion/19871/snapshot-the-attached-file-could-not-be-found/
With the ad-block-plus plugin installed, snapshots sometimes are created, but later don't open. The New York Times is a popular victim. A user suggests it might be connected to googleads.

**Comment by dstillman** [comment]
Obsoleted by SingleFile support, which saves rendered pages as they exist in the browser

https://forums.zotero.org/discussion/85306/available-for-beta-testing-improved-webpage-snapshots#latest
