### ISSUE TITLE
incorect collapse="year-suffix" interpretation for no-names variables

### ISSUE THREAD

**Issue by libora** [zotero/zotero#1000]
Example 1: 
2 documents with the same author and year of publication
output seems like this: (ANSORGE 2005a; b)

Example 2:
2 document without authors (is used term "anonymous") and the same year of publication:
output seem like this: (ANON. 2012a, ANON.b)

Example 3:
2 document without authors and with the same short-title and the same year of publication; in the style is used incorrect code:
`<names variable="title-short">
      <name form="short" and="symbol" font-variant="uppercase"/>
  </names>`
output seem like this: (SHORT TITLE 2016a; b)

Zotero thread is here: https://forums.zotero.org/discussion/58906/names-variabletitleshort/

**Comment by rmzelle** [comment]
@libora, this is the wrong place to report this.

The issue is limited to CSL/citeproc-js, and it's not even clear that the user is using a valid CSL style. No reason to bother the Zotero devs with this.

**Comment by libora** [comment]
@rmzelle yes you are right, user BCSHFS uses incorrect CSL style, but I try it on iso690-author-date-cs style (I change collapse="year" to collapse="year-suffix"). The second example is evidently wrong; the third example shows that citeproc-js is able create correct output from uncorrect CSL.

**Comment by rmzelle** [comment]
> The second example is evidently wrong;

Even if this is the case, it's better to discuss this in the forums.

> the third example shows that citeproc-js is able create correct output from uncorrect CSL.

We should never recommend that users use incorrect CSL code, though. We should either try to find a solution that is valid CSL, or, if we find that this is impossible, propose changes to CSL and/or the CSL processor if we want to support the requirement.
