### ISSUE TITLE
wrong cites

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [zotero/zotero#1009]
Örgütsel sessizlik, bireyin örgütün durumuyla ilgili davranışsal, zihinsel ve duygusal gerçek ifadelerini bu durumu değiştirme ya da düzeltme yeteneği olan kişilerden esirgemesi biçiminde tanımlanabilir (Bogosian ve Stefanchin, 2013b; Dedahanov, Kim ve Rhee, 2015; Kahveci ve Demirtaş, 2013; Elizabeth W. Morrison ve Milliken, 2000; Pinder ve Harlos, 2001a; Van Dyne ve diğerleri, 2003).

As you see above paragraph, there are someting wrong. Sometimes Zotero adds both author name and surname like Elizabeth W. Morrison. Sometimes if there are 3 and more authors, zotero cites all authors surname but sometimes only fist authors surname. I used apa-tr.csl. What is the problem I don't understand. Please help me. I write my PhD thesis libreoffice and it's zotero extenstion. In addition, I use standalone zotero version 4.0.29.10.

**Comment by gracile-fr** [comment]
You should post your message to the Zotero forums: https://forums.zotero.org/discussions/
