### ISSUE TITLE
5.0: Add item(s) by identifier ignores collection

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#1028]
By adding an item by identifier (e.g. `10.5281/zenodo.55073`) while I am currently in some (sub)collection seems to do nothing. Actually, it adds the item but does not assign it to the current collection.

**Comment by dstillman** [comment]
Fixed in r5. (This only happened with identifiers that failed from CrossRef and relied on another search translator.)

**Comment by zuphilip** [comment]
Okay, another example was `978-3-8006-4582-4` but I haven't tested it now with r5.

**Comment by dstillman** [comment]
Yeah, that works in r5.
