### ISSUE TITLE
Schema update step for HTTP Dates in feed items

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1035]
Not sure if we need to bother with this, but previously added feed items with HTTP Dates cause an error to be continuously logged:

> [JavaScript Error: "TypeError: date.getMonth is not a function" {file: "chrome://zotero/content/xpcom/itemTreeView.js" line: 1069}]
> Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1069:20

They also don't show values for Date in the middle or right panes.

Feed items will age out, but only if they're read, right? So beta users would need to mark those items as read and then wait for the expiration?

**Comment by adomasven** [comment]
> Feed items will age out, but only if they're read, right? So beta users would need to mark those items as read and then wait for the expiration?

Yes, only after being marked read. I don't know, we could add some temporary exception handling code?

**Comment by dstillman** [comment]
Yeah, I guess that's easiest. Throw in a `new Date` if it's not an SQL date, and we'll take that out at some point?

**Comment by dstillman** [comment]
All items now expire, so not worth worrying about this.
