### ISSUE TITLE
Feed syncing

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#1036]
Some to-do's that surfaced while discussing this on IRC:

1. Don't change `version` on [syncedSetting update] (https://github.com/adomasven/zotero/blob/3dabd63a0aeb5e9ffb138c6e1d11d37a2c87f1f3/chrome/content/zotero/xpcom/syncedSettings.js#L141) (bug).
2. Add an `onSync(name, oldValue, newValue, conflict)` hook to syncedSettings, where 
  ```conflict = newVersion>oldVersion && !synced```

3. Add a `type=sync, event=finish` notifier event after sync is finished.

Afterwards, `Zotero.Feeds.fromJSON()` should be invoked in an `onSync` handler, which creates new feeds. Feed update should be kicked-off in the post-sync notifier event handler.

**Comment by dstillman** [comment]
Also, it seems we're not updating the synced setting when name or setting changes are made to feeds.
