### ISSUE TITLE
Dependent styles don't inherit "class" from their parent

### ISSUE THREAD

**Issue by rmzelle** [zotero/zotero#1039]
We just got a report* that dependent styles don't properly inherit the "class" of the independent-parent style, if the parent is of `class="note"`. It was also brought up in 2014**, and I'm a bit surprised it isn't reported more often.

\* https://github.com/citation-style-language/styles/pull/2103#issuecomment-226115085
** https://forums.zotero.org/discussion/35220/dependent-styles-dont-insert-notes

I'm pretty sure that `Zotero.Style.prototype.__defineGetter__("class", ...);` should retrieve the "class" from the parent for dependent styles, similar to how `Zotero.Style.prototype.__defineGetter__("hasBibliography",...);` works. See https://github.com/zotero/zotero/blob/045554dd8e58a8a02bbac2cf621790db67797944/chrome/content/zotero/xpcom/style.js#L711 and 
 https://github.com/zotero/zotero/blob/045554dd8e58a8a02bbac2cf621790db67797944/chrome/content/zotero/xpcom/style.js#L721.

**Comment by rmzelle** [comment]
Should I prepare a patch against "master"? (Does "master" still work as a Firefox plugin, or would I have to build Standalone to test this in this branch?)

**Comment by dstillman** [comment]
Yes, we'd need this against master. It still works with Firefox.
