### ISSUE TITLE
4.0: ItemFields.getName returns still "version"

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#1049]
In the JavaScript API the function `ItemFields.getName` returns still "version" for the corresponding field used in computerProgram:
```
> Zotero.ItemFields.getName(81)

"version"
```
This has changed to "versionNumber" see https://groups.google.com/forum/#!msg/zotero-dev/FWCP_R5S_hg/ditgqvOpDwAJ .

I tested this with Zotero 4.0.29.10 and it seems that this is already fixed in Zotero 5.0. Is maybe the commit https://github.com/zotero/zotero/commit/43a2045aecff9bf1efcf50841519b1ac2ec85c3e missing for the 4.0 branch?

**Comment by dstillman** [comment]
Yeah, we can't make data changes on 4.0, so this isn't changing there.

**Comment by zuphilip** [comment]
Okay, I see.

However, "versionNumber" is already used in the mapping to CSL https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/utilities.js#L64 which might be okay because we also have
```javascript
if (field == 'versionNumber') field = 'version'; // Until https://github.com/zotero/zotero/issues/670
```
https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/utilities.js#L1515

**Comment by zuphilip** [comment]
(Just mumble to myself here ...)
