### ISSUE TITLE
"No updates available" when behind website and Github releases

### ISSUE THREAD

**Issue by kevinmickey** [zotero/zotero#1066]
When I go to About, I see I am using version 4.0.28.8.  When I "check for updates", I see "no updates available".  However, zotero.org currently offers 4.0.29.5, and the latest release on Github is 4.0.29.9.

**Comment by dstillman** [comment]
Automatic updates on OS X aren't currently available, if that's what you're referring to. They'll work again with the next release. In the meantime, you can install 4.0.29.5 manually from zotero.org.

**Comment by kevinmickey** [comment]
OK, thanks!  (Just to be explicit, I am manually going to Help -> Check for updates, but that probably is the same as an automatic update.)
