### ISSUE TITLE
picture can not show correctly in  note

### ISSUE THREAD

**Issue by Lmaths** [zotero/zotero#1071]
I add a picture which is an attachment of item to note of the same item, but the picture can not be shown correctly, it's just a block. But when I create a reporter from this item, the picture is shown.

I use firefox 48, and the latest zotero.

Any help will be appreciated!

**Comment by dstillman** [comment]
Please post to the [https://forums.zotero.org/](Zotero Forums] for support — this tracker is for developer use only.

(It's also not clear to me what you're trying to do. Generally speaking, notes in images aren't supported, but we'd need to know exactly how you're trying to add it. You can provide more details in the forums.)
