### ISSUE TITLE
Retrieve Metadata for PDF fails since update to Firefox 48

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#1076]
After updating to Firefox 48 the retrieve Metadata for PDF fails, e.g. D329389730. Moreover, I guess that the enormous amount of blue errors for Google Scholar in the [recent translators errors](https://repo.zotero.org/errors) is reflecting the same problem.

The error points to [translate_firefox.js](https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/translation/translate_firefox.js#L116) and reads:
> TypeError: Proxy.create is not a function

It is mentioned in the [release notes of FF48](https://developer.mozilla.org/de/Firefox/Releases/48) that the deprecated Proxy API is removed and suggested to use the [standard Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) instead. Can you fix this from here?

**Comment by dstillman** [comment]
Oh, that's no good. That's actually not what the errors page is showing, though  — those are nearly all from Zotero Standalone, I'd guess due to some cookie-related issue. No errors get reported automatically after the `Proxy.create` error in Firefox.

I'll fix this, though — thanks for catching this.

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/zotero/commit/b4e6584417ef0e96b86a1079cda1aaa4eb09861c

**Comment by dstillman** [comment]
Should be fixed in 4.0.29.11-beta.r2+b4e6584 of the <a href="https://www.zotero.org/support/dev_builds">4.0 Beta</a>

**Comment by dstillman** [comment]
Fixed in 4.0.29.11, available now
