### ISSUE TITLE
nsTransferable.js is no longer available in Firefox 49+ and it breaks the add-on

### ISSUE THREAD

**Issue by helieh** [zotero/zotero#1077]
I'm getting this error in Firefox Nightly console:

```uncaught exception: Error opening input stream (invalid filename?):           chrome://global/content/nsTransferable.js```

Code:

> subscriptLoader.loadSubScript("chrome://global/content/nsTransferable.js", zContext);

components\zotero-service.js

**Comment by dstillman** [comment]
Fixed in the latest <a href="https://www.zotero.org/support/dev_builds">4.0 Beta</a> — thanks.
