### ISSUE TITLE
Can anyone read ENDNOTE's styles files

### ISSUE THREAD

**Issue by biolee** [zotero/zotero#1079]
Output styles

Choose from 6,000+ styles to generate perfectly formatted EndNote references, from APA to Zygote.

download link [http://endnote.com/downloads/dla/styles.zip](styles.zip)

**Comment by dstillman** [comment]
No, sorry.

Note that the [Zotero style page](https://www.zotero.org/styles) offers 8000+ styles. If what you need isn't available there, you can [request a new style](https://github.com/citation-style-language/styles/wiki/Requesting-Styles).
