### ISSUE TITLE
programmatically add tag

### ISSUE THREAD

**Issue by damlatien** [zotero/zotero#1080]
I am using firefox & zotero connector, v5.0
I would like to add a tag to the last item scraped (`item.tags.push(tag)`) using the function `scrapeThisPage` from `browser.js` as soon as the function has completed. Adding code just after `if(page.translators && page.translators.length) {}` ensures that the call is made when the saving completed. However, I do not know how to access to some kind of `lastitem` property from there. 

I tried to access the `newItems` property when a translator is available on the page using `page.translate.newItems[i].tags.push(tag);` but then `page.translate.newItems[i].tags` is undefined ??

Anyway, I am also willing to add tag when the item is just a webpage w/o necessarily any translator activated
Can anyone help me ?

**Comment by dstillman** [comment]
https://groups.google.com/d/msg/zotero-dev/OTcYK8BDEwE/wMBHvJAFAgAJ
