### ISSUE TITLE
CSL processor prints "NaN" when letter is in hyphens

### ISSUE THREAD

**Issue by pedrom34** [zotero/zotero#1085]
At least in the case of an encyclopedia article, when collection number contains a letter in hyphens, the CSL processor prints NaN instead.
For example, this: 

> **30-431-A-10**

or this:

> **30-431-B-10**

will prints this:

> **30-431-NaN-10**

I posted this issue to the Zotero Forums as well: [https://forums.zotero.org/discussion/61796/issue-not-solved-yet-mistake-in-citation-when-creating-a-bibliography/#Item_0](url)

**Comment by dstillman** [comment]
This is a [citeproc-js](https://github.com/Juris-M/citeproc-js) issue. @fbennett will need to take a look, but the forums are the right place for that.
