### ISSUE TITLE
extend to biorxiv

### ISSUE THREAD

**Issue by meereeum** [zotero/zotero#1092]
Articles from biorxiv (e.g. http://biorxiv.org/content/early/2016/08/31/072413) are currently imported as web pages. Would be great if there was proper parsing/import of fields, as there is for arxiv.

:thumbs: for the good work!

**Comment by dstillman** [comment]
Please post support requests to the [Zotero Forums](https://forums.zotero.org/) — this issue tracker is for developer use only.

(Note that the page you link to is supported in a properly functioning installation by the HighWire 2.0 translator, so this isn't actually a translator request — all the more reason why these sorts of things should go to the forums. In your forums post, provide a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> for a load of that page.)
