### ISSUE TITLE
Can't reduce Firebug window size (space stays gray)

### ISSUE THREAD

**Issue by JBPressac** [zotero/zotero#1093]
Hello,
FYI, there is a pending issue on the Firebug repository (from more than one year) about a bug occuring when Zotero is activated: [Can't reduce Firebug window size (space stays gray)](https://github.com/firebug/firebug/issues/7946). 
Thank you,

**Comment by dstillman** [comment]
Zotero for Firefox will be going away in the near future (as will all XUL-based extensions eventually), so I'm afraid this isn't something we're going to investigate.
