### ISSUE TITLE
dataObjectUtilities.equals() misdescription?

### ISSUE THREAD

**Issue by fbennett** [zotero/zotero#1094]
It may not be in use yet, but the comment and the code of `Zotero.dataObjectUtilities.equals()` seem to be at odds with one another:

https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/data/dataObjectUtilities.js#L163

**Comment by dstillman** [comment]
Sorry, could you elaborate?

**Comment by dstillman** [comment]
(It appears to be true that it's not used, however.)

**Comment by fbennett** [comment]
Line 161 says, "True if objects are the same, false if not." The function loops over the keys and values of the object, and returns "true" if a difference is found. If no differences are found, the loop completes and the function returns "false." If no-differences-found == objects-are-the-same, the return values inside the loop should be "false," and the final default return value should be "true," I think.

**Comment by dstillman** [comment]
Ah, OK — yeah, I think this was just a dead end on the way to `*Changed()` and `*Diff()`, which are what are actually used here. I've fixed it, though this function can probably just be removed at some point. Thanks.
