### ISSUE TITLE
citeproc-js tag 1.1.133: variables added via Extra field

### ISSUE THREAD

**Issue by fbennett** [zotero/zotero#1099]
I've made some changes to the Extra (CSL "note") field parsing in citeproc-js that are now available at [tag 1.1.133](https://github.com/Juris-M/citeproc-js/tree/1.1.133). Documentation on the syntax recognized by the processor is up in the processor manual on [ReadTheDocs](http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cheater-syntax-for-odd-fields).

The new code should recognize both simple line-entry syntax suggested by Dan and others, and the uglier brace-entry syntax that was in there already. I've also fixed bugs in the parsing of name variables.

The new syntax option will be welcomed by everyone, I think, but before deployment it would be good to check that this new version plays well with the pre-parsing of DOI (and others?) in current Zotero code.

**Comment by dstillman** [comment]
> before deployment it would be good to check that this new version plays well with the pre-parsing of DOI (and others?) in current Zotero code

Are you referring just to https://github.com/zotero/zotero/pull/1089, or do you have other kinds of breakage in mind?

**Comment by dstillman** [comment]
But we could theoretically remove <a href="https://github.com/zotero/zotero/blob/e34c9e04e8dcd457066f5f7c3760035ba68a27ff/chrome/content/zotero/xpcom/utilities.js#L1766">all Extra-field parsing</a> along with this update, right?

**Comment by dstillman** [comment]
1.1.133 is now available in the latest <a href="https://www.zotero.org/support/dev_builds">4.0 Beta</a>.

**Comment by fbennett** [comment]
>> before deployment it would be good to check that this new version plays well with the pre-parsing of DOI (and others?) in current Zotero code

> Are you referring just to #1089, or do you have other kinds of breakage in mind?

It was just a vague recollection of the parsing issue in that one, yeah. No other worries that I can think of.

**Comment by fbennett** [comment]
> But we could theoretically remove all Extra-field parsing along with this update, right?

Yep. The processor will remove the entries after they're parsed, too, which would save a revision on the client side. (Might be worth checking first that an entry at the top of the Extra field doesn't leave behind a stray space before the proper content of the field---I didn't test for that, come to think of it.)

**Comment by fbennett** [comment]
@dstillman Some further issues are addressed by commits leading to processor tag [1.1.135](https://github.com/Juris-M/citeproc-js/commits/1.1.135). They are:
* Fixed failure of the `type` setting, noted in #846;
* Constrained both entry types (braced-entry and line-entry) to the top of the field; **[1]**
* Trimmed extra space from the field after removal of entries to protect against potential glitch noted immediately above;
* Provided for braced-entry objects within a line-entry object (exercised in [CheaterNames](https://github.com/Juris-M/citeproc-js/blob/master/tests/fixtures/local/name_CheaterNames.txt) test);
* Permitted overwrites of date values, in response to a comment by @nickbart on the [citeproc-js tracker](https://github.com/Juris-M/citeproc-js/issues/6).

The code for this should be in a finished state now. If any of it is unacceptable to the project, just let me know and I'll add options to disable bits that you don't want to have running in Zotero.

**[1]** With line-entry syntax, there is a risk of false positives in the field content. The risk is still there, but constraining to the top of the field reduces it, along with a regexp applied to variable names (documented in the [processor manual](http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cheater-syntax-for-odd-fields)). Possibly @rmzelle, @adam3smith, @nickbart and @bwiernik will have views on this?

**Comment by bwiernik** [comment]
A few thoughts:

regex for variable names requires they be the start of a line, yes? If not, users who have something like "Section editor:" or "Working title:" as user-specified variables might have many false positives. 

What is the casing requirement for variable names with line syntax?

Only conflict I can think of with top of field requirement is the Zotero Google Scholar Citations plugin, which places citation counts at the top of the Extra field (for sorting in Zotero window). I'm not sure how current parsing of PMID etc in Zotero conflicts with this (if at all), but the new citeproc parsing will break for any users using that plugin.

**Comment by bwiernik** [comment]
(Obviously don't think Zotero should be constrained by any particular plugin's conventions, just a data structure to be aware of)

**Comment by fbennett** [comment]
> regex for variable names requires they be the start of a line, yes?
Yes ([regexp](https://github.com/Juris-M/citeproc-js/blob/master/src/load.js#L464), applied to individual lines after line-splitting).
> What is the casing requirement for variable names with line syntax?
The current [note in the processor manual](http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#variable-names-tip) applies to both types of entry.
> Zotero Google Scholar Citations plugin
Oh, that's not good. But if the plugin put a label on the bare number inserted at the top of the Zotero "extra" field (something like: "citation-count: 50") ZGSC would no longer interfere with styles that render the Extra field (as I think it does at present). Data on existing items would need to be converted, but I wonder if the author of the plugin might be persuaded to go that route?

**Comment by bwiernik** [comment]
The plugin previously had a label, but the author removed it so that the Extra column could be narrowed to only show the citation count when sorting. Generally, I think users of ZGSC accept that it interferes with note-rendering styles (most users probably aren't aware). 

More generally, I wonder how many users store data at top of Extra field for sorting?

**Comment by bwiernik** [comment]
Would allowing non-CSL data on first line work? Or is that getting too hack-y/idiosyncratic?

**Comment by fbennett** [comment]
Ach. Sort out one traffic-jam of workarounds, and slam straight into another flock of them.

> Would allowing non-CSL data on first line work? Or is that getting too hack-y/idiosyncratic?

As we know to our cost, I never saw an idiosyncratic hack I didn't like. I do like this one, though. Small impact for a big gain.

If the top-of-field constraint were removed, there would be more pressure to impose strict conditions on recognized variable names (something like "valid in CSL but not available on this item type"). That would be horribly complex: every application would need to provide its own item-type-specific lists, and we would need to track fields available in all versions of CSL above 1.0 somewhere. Given the (tiny) scale of the false-positive problem, it wouldn't be worth it---but the increase in false positives from removing the top-of-field constraint would still be a headache for you guys.

So this seems like a nice choice among the alternatives. I'll code it up and test it, but wait a few hours for further feedback before pushing it to a processor release.

**Comment by bwiernik** [comment]
With start of line restriction, I'm not sure the false positives would be very problematic

**Comment by fbennett** [comment]
Not very, but the population is huge, and anything that can go wrong eventually will.

It's coded and tested. If we don't have any objections, I'll push it as a fresh 1.1.136 release at the end of the day.

**Comment by adam3smith** [comment]
I'm not particularly worried about false positives if we're testing for both top of the fiels and colon -- though might make sense to make the regex non-greedy for efficiency?
You should announce this over xbiblio, still, though, since non-Zotero folks are going to potentially encounter (or, on the plus side: benefit from) it.

**Comment by fbennett** [comment]
> might make sense to make the regex non-greedy for efficiency?

I don't see how lazy matching would improve the efficiency of [NOTE_FIELDS_REGEXP](https://github.com/Juris-M/citeproc-js/blob/master/src/load.js#L463) or [NOTE_FIELD_REGEXP](https://github.com/Juris-M/citeproc-js/blob/master/src/load.js#L464). The colon isn't included in its preceding pattern, and same for the close-brace, so it's a straight shot to result in both cases. Might be I have something to learn here, though.

**Comment by bwiernik** [comment]
> But we could theoretically remove all Extra-field parsing along with this update, right?

If you don't remove Extra field parsing, I just noticed that the DOI parsing is incomplete. It assumes a long form DOI (10.dddd/...) but users should also be able to give a short DOI (10/...)

**Comment by adam3smith** [comment]
> I don't see how lazy matching would improve the efficiency of NOTE_FIELDS_REGEXP

yeah, sorry, it doesn't.

**Comment by fbennett** [comment]
Push of 1.1.136 coming up in a couple of hours, sorry (in an orientation
session for incoming students). Will post when it's out.

**Comment by fbennett** [comment]
There we go. <a href="https://github.com/Juris-M/citeproc-js/tree/1.1.136">Tag 1.1.136</a> is now up. Over the previous tag, it adds the feature suggested by @bwiernik above, to allow parsing to continue if the first line is not in "cheater syntax." That avoids breaking things for people who use the first line for item sorting, citation counts, or short descriptions.

**Comment by dstillman** [comment]
4.0 Beta updated to 1.1.136
