### ISSUE TITLE
citeproc-js tag 1.1.137: variables added via Extra field (followup)

### ISSUE THREAD

**Issue by fbennett** [zotero/zotero#1105]
One more update to this. There are two items.
* (1) Nick Bart @nickbart (and others) pointed out that blocking the parse where data exists in the first-class field interferes with usability (sorry, I haven't been able to find the link). The clear example was with date ranges: if the user entered a date range for **issued** in cheater syntax, requiring the **Date** field to be empty meant that date sorts became useless for those items.
* (2) Emiliano @retorquere  reported a [bug in Juris-M](https://github.com/Juris-M/zotero/issues/24) triggered by the 1.1.136 release. The primary bug doesn't affect Zotero, but the issue itself might be of interest to the team.

For (1), this revision removes the empty-field constraint for date fields. (For the other field types, the constraint remains, since I can't think of a use-case where cheater-syntax entries provide any processing advantages.)

The issue at (2) arises from an extension to the translator framework in Juris-M. `CSL` exposes the [parseNoteFieldHacks()](https://github.com/Juris-M/citeproc-js/blob/master/src/load.js#L257) method that `citeproc-js` uses to perform the field parse. Juris-M runs this method across the **extra** field before submitting items for translation, providing it with an argument `validFieldsForType`, an object with `true` properties for CSL fields that can be mapped into the item. When the argument is provided, the parser will leave unrecognized entries in place (so that they can be picked up by the processor when the item is rendered), but normalizing them to line-entry syntax.

With the recent refactoring, I carelessly dropped `validFieldsForType` element from the function signature, which triggered Emiliano's bug. With a Juris-M built with the [1.1.137](https://github.com/Juris-M/citeproc-js/tree/1.1.137) processor version, all of Emiliano's tests [pass](https://github.com/Juris-M/zotero/issues/24). Feel free to pick up the code or copy it from `CSL` if you like what it does.

**Comment by retorquere** [comment]
This isn't yet in a Juris-M release, right?

**Comment by fbennett** [comment]
Not a full release yet. Will take another day to get it out - teaching term
is starting, lots to do.

**Comment by retorquere** [comment]
No rush, I've set up my testing harness to force-pick the beta.
