### ISSUE TITLE
Add item by moving file?

### ISSUE THREAD

**Issue by QiangF** [zotero/zotero#1106]
Hi everyone,
Comparing to add item by storing copy of file, the benifit of adding by moving file is to save disk sapce and avoid clutterin working area. Is this easy to implement?
Thank you!

**Comment by dstillman** [comment]
Hi — please post feature requests to the Zotero Forums. This tracker is used by developers for tracking confirmed issues discussed there.

You can move files into Zotero by dragging them into Zotero with the standard OS-specific modifier key for cross-disk moving — on macOS it's Cmd. There's no equivalent menu command.
