### ISSUE TITLE
Change "Known Translator Issue" error message

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1119]
Since absolutely everyone thinks it's saying that the error they just received is a known issue

**Comment by dstillman** [comment]
I apparently changed this [2.5 years ago](ba89dbf0ae0617a14c269bf6f831f47653cfb566).

**Comment by gracile-fr** [comment]
(correct link : https://github.com/zotero/zotero/commit/ba89dbf0ae0617a14c269bf6f831f47653cfb566 )
