### ISSUE TITLE
5.0: RSS Feeds

### ISSUE THREAD

**Issue by trenkert** [zotero/zotero#1126]
Zotero's internal search does not include items from subscribed RSS feeds. 

Also: would it be possible to subscribe to rss feeds within a subcollection and have Zotero automatically download the fulltext pdf if available?

**Comment by dstillman** [comment]
Not sure what you mean by "internal search". The search bar can filter items in feeds. Do you mean that you can't select a feed library in the Advanced Search window?

> would it be possible to subscribe to rss feeds within a subcollection and have Zotero automatically download the fulltext pdf if available?

Can you elaborate on that?

**Comment by dstillman** [comment]
(Also, since we're nearing the end of the beta period, and particularly for feature requests, better to post things like this to the forums going forward for wider discussion.)

**Comment by adomasven** [comment]
> Would it be possible to subscribe to rss feeds within a subcollection and have Zotero automatically download the fulltext pdf if available?

We have tested with translating the feed items in-place (i.e. downloading the PDF and rich metadata), but there are various technical reasons why we cannot do that reliably. To retrieve rich metadata about particular items you find interesting you should drag them into your library or collections.

> Zotero's internal search does not include items from subscribed RSS feeds.

If this is regarding search when citing: similar reasoning. RSS feed items contain little data to cite properly. Dragging items of interest into your library will retrieve rich metadata and allow citing them.

**Comment by trenkert** [comment]
@dstillman @adomasven To clarify the issues:

> Zotero's internal search does not include items from subscribed RSS feeds.

This has been resolved after I restarted FF. But other difficulties persist:

- In Advanced Search, individual feeds serve as libraries, meaning you cannot search across different feeds within the same search. For scientists who need to leep track of the feeds of 15-40 journals, this is not practical.

- If Zotero could handle "Feeds" as a library and each feed as a collection, this would work better. 

- It would be even more practical if these feeds (as collections) were not restricted to be located within the library "Feeds" but could be placed anywhere. For instance: let's say I have a project on age research for which I have my own collection and where I want to be notified of everything published in 5 journals. It would be great if I could place these feeds within a subfolder of my collection "age research". 

- Additional ideas: 
- For advanced search it would be more useful, IMO, if there was a property "feed" belonging to items from news feeds which could be chosen as a filter if needed. 
- feed items should be able to use standard zotero tags. 

> RSS feed items contain little data to cite properly. 

Perhaps it would be useful to warn users when "citing" a rss-item or to give them the choice to exclude rss-items from being exported. 


> We have tested with translating the feed items in-place (i.e. downloading the PDF and rich metadata), but there are various technical reasons why we cannot do that reliably. To retrieve rich metadata about particular items you find interesting you should drag them into your library or collections.

Ah, ok. I'll do that.

**Comment by dstillman** [comment]
The ability to searching across feeds — both in the main pane and Advanced Search — is planned, and being able to organize feeds into collections will likely happen as well.

> feed items should be able to use standard zotero tags

The feed items are just intended to be a temporary staging area. If you want to keep them, add tags, etc., you would add them to a library.

> Perhaps it would be useful to warn users when "citing" a rss-item or to give them the choice to exclude rss-items from being exported.

Oh, that's just a bug — they're not supposed to show up in the Quick Format bar. We'll fix that.

**Comment by trenkert** [comment]
I see, thanks for clarifying this!
