### ISSUE TITLE
5.0 Beta Inserted Pictures disappear Report ID# 2099517457

### ISSUE THREAD

**Issue by SparksinTexas** [zotero/zotero#1137]
Trial 1 
Created a journal article
Created a link to a word document that is on my hard-drive under that journal article
Pasted (Shift-Insert) a picture into the note section of the link (see attached screenshot)
As soon as my database synced the picture disappeared

Trial 2  
Saved a picture to my harddrive
Drug the picture from my file manager over to the Zotero link I created in trial 1 
Database synced -- picture did not disappear

Trial 3 
Created a Child Note under my journal article
Shift-Insert to paste the picture into the note section of the link
Database synced -- picture did not disappear

Summary: I can use Shift-Insert to paste a picture from my clipboard into a Child Note but I cannot use that method to insert a picture into a link.

Windows 10
Surface Pro 3
Zotero Stand-Alone is what I am using for this test
Chrome Interface when I am working online

![capture zotero error](https://cloud.githubusercontent.com/assets/18615402/21445125/c01c986e-c87a-11e6-870c-a8161366efe8.JPG)

**Comment by SparksinTexas** [comment]
Report ID # 789822699

Update:  I closed my Zotero database and when I opened it again the pictures were gone.  It doesn't matter if I paste the picture from my clipboard or if I drag the picture over from my clipboard.

Child Notes that I pasted pictures into before I downloaded the Beta 5.0 are still intact.

I am also getting this error now that I restarted my Zotero: An error occurred during syncing: Child items cannot be assigned to collections.  

I assumed that it was talking about the Child Note that I created in trial #3 so I moved the child note to the trash and then deleted it permanently.  I am still getting that error when I try to sync.

**Comment by dstillman** [comment]
Nothing new to 5.0 here — notes in images have just never been supported, and the fact that you can add them at all under some circumstances is a fluke. (Obviously it would be better if Zotero either supported them for real or fully prevented adding them.) You can add images to items as child attachments.

If you can provide a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> for the sync error, though, we can take a look at that.

**Comment by SparksinTexas** [comment]
Debug ID # D1795627368

I'm new to this program but I've used it for a few weeks.  Before I upgraded to Beta 5.0 yesterday, I could create a child note, paste (shift-insert) a picture into it, and it saved fine.

Now it never works.

I fixed the sync error.  I had a link to a PDF that had become unattached to its parent.  Once I deleted it then the program synced fine.  Regrettably, I had not turned on debugging before I fixed it so I don't know how the PDF became unattached.

I saved a Debug log of me pasting a picture into a child-note, syncing, and the picture disappearing.

**Comment by dstillman** [comment]
Right, but as I say, this has never been supported. In 4.0 these would've just caused sync errors, because the resulting notes would have been too large to sync. The sync architecture in 5.0 filters them out instead.

We're hoping to properly support images in notes at some point and count them against the file sync quota, but at the moment it's just not something that's intended to work.

We'll try to track down the "Child items cannot be assigned to collections" error, though.

**Comment by GCamp6** [comment]
May be this is helpful...

https://forums.zotero.org/discussion/64345/5-0-beta-bug-impossible-pasting-images-in-notes#latest
