### ISSUE TITLE
Edit Citation ignores rich-text formatting

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1138]
Insert a citation, edit it, show editor, make a word bold, click OK. The bold text is not applied to the original citation.

@fbennett, it seems like https://github.com/zotero/zotero/pull/939 broke this — moving `unescapeHTML()` up in that function means the `<strong>`/etc. tags are stripped before they're converted to RTF. I'm not totally clear on what that patch and the one it was following up were doing, so maybe you could take a look at this?

**Comment by fbennett** [comment]
Will do.

**Comment by KarlHegbloom** [comment]
Can you make it so that html, such as <abbr> is stripped prior to sorting,
but left in the returned result? I Wan to put it into abbrev filter
outputs. Also,  some Wikipedia pages get given <i> around parts of the
title, and it affects sort order but should not.
