### ISSUE TITLE
Fully parameterize methods in db.js

### ISSUE THREAD

**Issue by fbennett** [zotero/zotero#1141]
While refactoring the Abbrevs Filter to support async database operations, I've run into a snag. The plugin piggy-backs on the Zotero SQLite infrastructure to instantiate a connection to a separate database of abbreviations. This worked under 4.0, but in the 5.0 version of db.js, calls bound to the Zotero.DB instance are made in ten locations. As a result, certain calls on a separate database instance will operate instead on the main Zotero DB (which I discovered when the plugin began corrupting the database by scrubbing its version table).

If I'm reading things correctly, the static calls could be bound instead to the database connection held by the instance. I can attempt a patch, but it's likely to need some cleaning up; I'm a little out of my depth in the async code still.

**Comment by dstillman** [comment]
> calls bound to the Zotero.DB instance are made in ten locations

What do you mean by this? This seems to work as expected for me.

**Comment by fbennett** [comment]
It works fine on the primary database managed by Zotero (or Juris-M). But the abbreviations filter instantiates a separate database:
``` javascript
    this.db = new this.Zotero.DBConnection("abbrevs-filter");
```
Where `this` is the plugin instance. As part of its installation process, the plugin sets up the tables for the `abbrevs-filter` database if required:
``` javascript
var sql = Zotero.File.getContentsFromURL("resource://abbrevs-filter/schema/abbrevs-filter.sql");
var version = parseInt(sql.match(/^-- ([0-9]+)/)[1]);
    var tableExists = yield this.db.tableExists("abbreviations");
    if (!tableExists) {
        yield this.db.executeTransaction(function* () {
            yield this.db.executeSQLFile(sql);
            yield this.setDBVersion('abbreviations', version);
        }.bind(this))
    }
```
The SQL file loaded by the function contains the following statement, among others:
``` javascript
DROP TABLE IF EXISTS version;
CREATE TABLE version (
	schema TEXT NOT NULL,
	version INTEGER NOT NULL
);
```
The statement is meant to create an empty table in the `abbrevs-filter` database to hold version information; but the code for the `executeSQLFile` method writes the change to the `Zotero.DB` connection instead:
``` javascript
Zotero.DBConnection.prototype.executeSQLFile = Zotero.Promise.coroutine(function* (sql) {
	var nonCommentRE = /^[^-]/;
	var trailingCommentRE = /^(.*?)(?:--.+)?$/;
	
	sql = sql.trim()
		// Ugly hack to parse triggers with embedded semicolons
		.replace(/;---/g, "TEMPSEMI")
		.split("\n")
		.filter(function (x) nonCommentRE.test(x))
		.map(function (x) x.match(trailingCommentRE)[1])
		.join("");
	if (sql.substr(-1) == ";") {
		sql = sql.substr(0, sql.length - 1);
	}
	
	var statements = sql.split(";")
		.map(function (x) x.replace(/TEMPSEMI/g, ";"));
	
	this.requireTransaction();
	
	var statement;
	while (statement = statements.shift()) {
		yield Zotero.DB.queryAsync(statement); <---- writes to Zotero DB
	}
});
```
So when the plugin installs its tables, they are written into the Zotero (or Jurism) database; and where there is a table of the same name (as with `version`), the table is dropped, with unfortunate consequences.

I have worked out some changes to `db.js` that seem to assure that operations are directed at the database controlled by the instance; but I'm not sure whether the code is intended for use in managing the primary Zotero database only. If not, I can file a pull request of the changes; otherwise, I can set up the plugin to block operation with mainstream Zotero, to avoid nasty surprises.

**Comment by dstillman** [comment]
> executeSQLFile

Ah, OK — that's all I needed to know. I had only tested `queryAsync`, which used the correct `DBConnection` instance. Should be fixed now.

**Comment by fbennett** [comment]
Excellent, thanks!
