### ISSUE TITLE
Feeds and Group Libraries need twisties

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#1142]
Feeds and group libraries should be totally collapsible with their own top-level twisties, like My Library. This change can coincide with the revised indenting proposed by @johanneskrtek.

**Comment by dstillman** [comment]
The lack of twisties is on purpose. The equivalent to My Library being collapsible is individual group libraries being collapsible, which they are. "Group Libraries" is a header — i.e., one level up. And its being collapsible was an endless source of user confusion, with people thinking their group libraries hadn't synced.

"Feeds" I could see having a twisty, but to the extent that it's equivalent to "Group Libraries" — a non-selectable header — it makes sense that it doesn't have one. (I'm actually not actually sure if a non-selectable row can even have a twisty, though we should probably make it selectable and show entries from all your feeds combined. We can revisit at that point.)
