### ISSUE TITLE
Show PDF icon for linked PDFs

### ISSUE THREAD

**Issue by WiliTest** [zotero/zotero#1171]
For the moment we don’t know what kind of external files are linked to the entry since they (pdf,mp3,mp4...) are all shown with the same icon (black &white with a chain on it). It would be nice to know what kind of (external) attachement is link to the entry.

**Comment by gracile-fr** [comment]
Please post feature requests to the Zotero Forums — this tracker is for developer use only. (PDFs have their own icon, see also: https://github.com/zotero/zotero/pull/298 )

**Comment by WiliTest** [comment]
thanks, sorry for that.

**Comment by gracile-fr** [comment]
( https://forums.zotero.org/discussion/64327/f-request-adding-new-icon-showing-type-of-external-files-at-least-for-pdf-zot5 )

**Comment by dstillman** [comment]
We can do this for PDFs if we can show the link clearly enough.

**Comment by dstillman** [comment]
Closed by 8cd5b09053bcddd3258596b50867766ad4ae7f99 and c735423996bdbba202b362233c8b6c22e3ca31fd
