### ISSUE TITLE
Cannot move standalone attachment to an existing item

### ISSUE THREAD

**Issue by parchd-1** [zotero/zotero#1178]
A pdf attached from "Store copy of file" cannot be dragged and dropped onto an existing item to turn it into an attachment.
This was possible in Zotero for Firefox (latest stable version), but doesn't seem to work in Zotero 5 standalone.

Running:
5.0-beta.142+bb0fa73 on Linux

**Comment by dstillman** [comment]
This works fine for me. <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a>?

**Comment by parchd-1** [comment]
I know it is inconvenient, but I'm a bit reluctant to use the debug submit function, as the filepaths in there reveal my real identity.

I'm attaching a version with those paths replaced.

The actions taken were:
* create Book item "Test"
* add stored pdf
* drag pdf to "Test" item

"Test" is highlighted as the mouse hovers over it during drag + drop, but the item does not move there upon release.

[zotero-debug.txt](https://github.com/zotero/zotero/files/789410/zotero-debug.txt)

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/zotero/commit/1ff1fabb315ffb6f12e77df5e689434161792911 in 147.
