### ISSUE TITLE
Snapshot saving/cookie management problems

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#1208]
[MathSciNet](http://www.ams.org/mathscinet-getitem?mr=3278772) is being extremely evil/stupid about how they serve their item pages. Included in the request is

```
                <script type="text/javascript">
		<!--
			if( getRequestObject() && getCookie('hasJavascript')==null ){
				setCookie( 'hasJavascript', 1 );
				if( getCookie('hasJavascript') )
					window.location.reload();
			}
		-->
		</script>
```

Which, if the cookie `hasJavascript` does not exist, serves empty body. Connectors do pass cookies, including the `hasJavascript` one to standalone, but on the first snapshot save it fails to save the contents. If you try to save the item again, the snapshot contents are fetched, but other resources (css, js, images) are missing. That makes no sense, since we manage cookies for individual sessions separately and they do not persist between item-saves/attachment-fetches/Zotero.HTTP.processDocument-calls.

Concerns CookieSandbox and nsIWebBrowserPersists/hiddenBrowser magic.

**Comment by dstillman** [comment]
Obsoleted by SingleFile support, which saves rendered pages as they exist in the browser
