### ISSUE TITLE
Bundle PDF tools

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1215]
Now that we're Standalone only, we should bundle platform-specific pdfinfo/pdftotext.

(This is partly for zotero-standalone-build, but the client code will need to look for it in the program directory. Update code can be removed, since we can just bundle updates with new versions.)

This will also help in situations where the data directory is noexec: https://forums.zotero.org/discussion/54622/

**Comment by cboulanger** [comment]
+1 I cannot run pdfinfo/pdftotext at work because of the security restrictions. It would seem that this is / will be the case for a lot of users.

**Comment by dstillman** [comment]
We're working on this currently, so it'll happen pretty soon.

**Comment by dstillman** [comment]
Done in https://github.com/zotero/zotero-standalone-build/commit/be36f054754b2c9c021a4791d40530c97545c11d (January 2018)

**Comment by cboulanger** [comment]
Thank you!!
