### ISSUE TITLE
Show note link URL on hover

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1220]
Requested <a href="https://forums.zotero.org/discussion/comment/274482/#Comment_274482">here</a>, but I'm not sure where it should go. Might be easiest to show in the tooltip over the first button, where it currently "Open link" — it could instead say "Open http://example.com".

**Comment by spetrescu** [comment]
Can I work on this? Or has this been solved already?

**Comment by dstillman** [comment]
The new note editor in the Zotero 6 beta does this.
