### ISSUE TITLE
Emptying trash of child item leaves parent item in view (grayed out)

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1227]

**Comment by fcheslack** [comment]
https://github.com/zotero/zotero/issues/866

**Comment by MarioJose** [comment]
This issue occur in 5.0.7 version.

Steps to generate debug output:
- Delete a attached note
- Go to "Trash"
- Select "Empty trash"
The item still in "Trash" panel.

Debug output attached.

[zotero_debug_trash_empty.txt](https://github.com/zotero/zotero/files/1174581/zotero_debug_trash_empty.txt)

**Comment by dstillman** [comment]
Duplicate of #866
