### ISSUE TITLE
ONLYOFFICE integration

### ISSUE THREAD

**Issue by baimafeima** [zotero/zotero#1228]
Could you add ONLYOFFICE integration? https://www.onlyoffice.com
Currently, only LibreOffice is supported.

**Comment by dstillman** [comment]
Please post feature requests to the Zotero Forums. This tracker is for development use only.

But no, this isn't something we have any plans to support. (I've never actually heard of ONLYOFFICE before, for what it's worth.)

**Comment by baimafeima** [comment]
> Please post feature requests to the Zotero Forums.

I have mentioned this already some time ago. Feature requests are _typically_ handled via GitHub and more effectively than via separate forums. It is _unreasonable_ to expect users to sign up at 100 different forums for each software they make suggestions for.
