### ISSUE TITLE
Make non-processed code unrunnable

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1233]
With a sufficiently advanced browser, it's currently possible to run from either the root or from the `build` directory even with `async`/`await`/etc. To make sure we're always testing the right code, we should probably do something that makes the root code unrunnable. Maybe just rename `chrome.manifest` to `chrome.manifest.in` and rename it in the build script? Other ideas?

**Comment by retorquere** [comment]
`install.rdf` is a required file, right? My build scripts generate `install.rdf` from `package.json` just before zipping up the XPI.

**Comment by dstillman** [comment]
I would be highly surprised if you could still get through a startup from the root.
