### ISSUE TITLE
New default tag colors

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#1244]
Let's make them prettier.

**Comment by tnajdek** [comment]
Some prior discussion:

https://forums.zotero.org/discussion/comment/228548

Also, a relevant PR:

https://github.com/zotero/zotero/pull/1198

**Comment by stakats** [comment]
Tested them in a build. They look great. Please commit ASAP.

```
			colorPicker.colors = [
				'#f66', '#ff8c19', '#999',
				'#5fb236', '#009980', '#2ea8e5',
				'#576dd9', '#a28ae5', '#a6507b'
			];

```

**Comment by stakats** [comment]
We can work on the contours later. I don't have strong feelings there.

**Comment by dstillman** [comment]
Done in 081f6bc77d775d97fbbb2f456628c99072fcb27d
