### ISSUE TITLE
Add shortcuts keys

### ISSUE THREAD

**Issue by EliaOrselli** [zotero/zotero#1247]
Hello,
I'd like to suggest a couple of shortcuts keys to add:
1) duplicate item
2) add another author field
As I'm manually creating items from archival sources (mostly letters) these two features would would greatly simplify my work.

Anyway, thanks a lot for all your work with zotero

**Comment by dstillman** [comment]
Please post feature requests to the Zotero Forums.

(But you can press Shift-Return to add new creator rows.)
