### ISSUE TITLE
Schema in Jason-LD is compatible with ZOTERO or wich one should I choose for a good and detailed description?

### ISSUE THREAD

**Issue by colomet** [zotero/zotero#1249]
We have a site, we are creating all the metadata with scheema and now we would like to make it compatible with ZOTERO. Which other type of metadata should we to use?

DC, COinS, ZOTERO RDF???

**Comment by gracile-fr** [comment]
https://www.zotero.org/support/dev/exposing_metadata
(This tracker is for development use only. If you have questions, you can consult and post to the <a href="https://groups.google.com/group/zotero-dev">zotero-dev mailing list</a>. And for user support questions : https://forums.zotero.org/ )
