### ISSUE TITLE
Don't update feed read status if all dates are the same

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1269]
https://twitter.com/paregorios/status/887700288546754562

All dates in ScienceDirect feeds get reset on each update, which marks all entries as unread. We should probably just check whether all dates are the same and not change any to unread if they are. I'm not sure how easily we can do this given that they're processed in an iterator, though.

**Comment by adomasven** [comment]
Bad idea. The more crippled feeds are supported, the more crippled feeds exists. ScienceDirect should fix their feeds.

**Comment by dstillman** [comment]
OK, agreed.
