### ISSUE TITLE
GUI option to disable quick search (and always wait for user to press enter to execute search instead)

### ISSUE THREAD

**Issue by cossio** [zotero/zotero#1270]
I have a large library. When I begin typing into the search box, Zotero gets very slow, trying to find only the first few characters of my search. I would prefer to type the full search terms, and then hit enter to execute the search. 

Moreover, I constantly forget typing the initial `"` to begin the search (which would disable quick search for the current search), so I end up clogging zotero for some time. Thus in my case, the quick search function is completely useless. And I suspect this is the same for any user that has a large enough library. Instead of forcing us to begin the search with `"`, maybe a better option is to add a GUI config to disable quick search for good? So that instead the search bar always waits for the user to press enter to conduct the search.

**Comment by gracile-fr** [comment]
I could imagine at best a hidden preference for this, but I think this has to be discussed on the [Zotero forums](http://forums.zotero.org) like all feature requests (please post there). This tracker is for development use only.

**Comment by cossio** [comment]
https://forums.zotero.org/discussion/66638/disable-quicksearch#latest
