### ISSUE TITLE
Z5: itemToExportFormat mangles "relations" (I think)

### ISSUE THREAD

**Issue by retorquere** [zotero/zotero#1282]
When I call itemToExportFormat, I get back `relations` fields that look like

`"relations":{"0":["[","o"],"2":["b"],"3":["j"],"4":["e"],"5":["c"],"6":["t"],"7":[" "],"8":["O"],"9":["b"],"10":["j"],"11":["e"],"12":["c"],"13":["t"],"14":["]"]}` which is probably a toJSON call that thinks it has an array but which is actually a string which is actually an accidental cast of an object to a string.

I don't use `relations`, so it's not a problem for me, but I thought you night want to know.

**Comment by dstillman** [comment]
I'm not seeing that.

1. Create two items
1. Add one as related item of the other
1. `JSON.stringify(Zotero.Utilities.Internal.itemToExportFormat(Zotero.Items.get(2)), null, "  ")`

```json
{
  "version": 0,
  "itemType": "book",
  "title": "A",
  "creators": [],
  "tags": [],
  "collections": [],
  "relations": {
    "dc:relation": [
      "http://zotero.org/users/local/FdGfTTCP/items/SMYTPIR6"
    ]
  },
  "dateAdded": "2017-08-07T22:05:47Z",
  "dateModified": "2017-08-07T22:05:48Z",
  "uri": "http://zotero.org/users/local/FdGfTTCP/items/4H58F2YK",
  "attachments": [],
  "notes": []
}
```

**Comment by retorquere** [comment]
I was seeing this on items that didn't have any relations, but I'll investigate further. How do you execute chrome JS on a stock Zotero BTW? I tried starting with `-jsconsole` but it only jas the error loggin, it doesn't have the command line that I'm used to seeing.

**Comment by retorquere** [comment]
NM, I have mozrepl going, and it looks OK there. This issue can be closed for now.

**Comment by retorquere** [comment]
Got it, it was just a logging artefact in BBT.

**Comment by retorquere** [comment]
Found the actual cause (I think!). When a reference is exported, the translator is offered a property on the item which looks like

```
relations: {}
```

if the item has no relations, and like

```
relations: { "dc:relations": [ <array or URIs> ] }
```

when it does. When I offer this same structure on import, Zotero says `object found, converting to string`, and that's what I'm finding. I *think*. I strip the `relations` field now on import and that takes care of it of course, but I'm not wholly sure what I should offer to roundtrip relations.

**Comment by dstillman** [comment]
Do you remember the steps to reproduce this? This should be prevented, obviously, but do we think it happens with the stock translators? There was a report of this [in the wild](https://forums.zotero.org/discussion/67752/an-error-occurred-during-syncing-unsupported-predicate-0).

**Comment by dstillman** [comment]
OK, I'm not sure if there were cases of our own translators triggering this, but I can reproduce it.
