### ISSUE TITLE
Add search operator OR to "Advanced Search"

### ISSUE THREAD

**Issue by insanetesterftw** [zotero/zotero#1302]
Right now **Advanced Search** only allows search operations with **AND**.

It's very common for users to search for *search term 1* **OR** *search term 2*.

It's also very common to use a combination of both **AND** and **OR**.

Thank you.

**Comment by bwiernik** [comment]
Please try to keep feature requests or usage questions on the Zotero forums. This issue tracker is intended only for developer use.

(You can set Advanced Search to meet 'any' of the criteria, versus 'all'. This will combine the terms using Boolean OR.)

**Comment by dstillman** [comment]
And you can combine operators by chaining saved searches.
