### ISSUE TITLE
Add changelog to GitHub releases

### ISSUE THREAD

**Issue by baimafeima** [zotero/zotero#1309]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by dstillman** [comment]
We write a changelog for end users for each release:

https://www.zotero.org/support/5.0_changelog

Obviously you're welcome to follow along with commits the rest of the time.
