### ISSUE TITLE
Advance online publication

### ISSUE THREAD

**Issue by wuchichou** [zotero/zotero#1313]
I find nature provides advance online publication to make the author declare their paper as soon as when the peer-preview process is finished(for more detail: http://www.nature.com/authors/author_resources/about_aop.html). So there are two dates for that paper entry: one is the online publication date, the other is press publication date. I want to keep both dates when I do the citation. However, there is only one date entry in zotero Journal Aticle type. How could I handle this?
This problem also comes up when I deal with the preprint version of journal articles.

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums.
