### ISSUE TITLE
"Delete collection and items..." fails on empty collection

### ISSUE THREAD

**Issue by retorquere** [zotero/zotero#1314]
When I select "Delete collection and items..." on an empty collection the collection remains undeleted and the error log says

```
[JavaScript Error: "Error(s) encountered during statement execution: near " ": syntax error [QUERY: INSERT OR IGNORE INTO deletedItems (itemID) VALUES ] [PARAMS: ] [ERROR: near " ": syntax error]" {file: "chrome://zotero/content/xpcom/db.js" line: 703}]
```

(no extensions installed)

**Comment by retorquere** [comment]
I got the sequence wrong. Here's what I'm seeing:

1. I import the attached file (Zotero RDF format)
2. I select the imported collection and select "Delete collection and items..."
3. I try to empty trash, and I see the following error in the log:

```
[JavaScript Error: "parentCollection.removeItem is not a function" {file: "chrome://zotero/content/xpcom/data/item.js" line: 4014}]
```

Debug ID: D1142663975

After a restart of Zotero, I can empty the trash

[My Library.rdf.txt](https://github.com/zotero/zotero/files/1295602/My.Library.rdf.txt)

**Comment by dstillman** [comment]
Thanks! We were actually seeing related errors in forum reports but didn't know how to reproduce. Should be fixed in the latest <a href="https://www.zotero.org/support/dev_builds">5.0 Beta</a>.

**Comment by retorquere** [comment]
My pleasure, I was just glad it wasn't me causing it this time around :smile:

**Comment by retorquere** [comment]
Is there a timeline for this to show up in a new release? I prefer to test against the release version usually, but this issue is turning up in my test suite.

**Comment by retorquere** [comment]
The original scenario I sketched does still thrigger an error, I know have it reproducible in both 5.0.18 and 5.0beta from today; I've opened a [new issue](https://github.com/zotero/zotero/issues/1317).
