### ISSUE TITLE
"Delete collection..."/"Delete collection and items..." fails on empty collection

### ISSUE THREAD

**Issue by retorquere** [zotero/zotero#1317]
Tested with both 5.0.18 and 5.0beta downloaded 2017-09-18; Debug ID: 1318857074

Scenario:

1. Import [these Zotero RDF references](https://github.com/zotero/zotero/files/1310725/My.Library.rdf.txt)
2. Select the library, select all references, move to trash
3. Empty trash
4. Select collection "My.Library.rdf", right-click, select "Delete collection..."
5. Select collection "My.Library.rdf", right-click, select "Delete collection and items..."

The collection stays in place, and in the log I see

```
[JavaScript Error: "Error(s) encountered during statement execution: near " ": syntax error [QUERY: INSERT OR IGNORE INTO deletedItems (itemID) VALUES ] [PARAMS: ] [ERROR: near " ": syntax error]" {file: "chrome://zotero/content/xpcom/db.js" line: 703}]

[JavaScript Error: "Error(s) encountered during statement execution: near " ": syntax error [QUERY: INSERT OR IGNORE INTO deletedItems (itemID) VALUES ] [PARAMS: ] [ERROR: near " ": syntax error]" {file: "chrome://zotero/content/xpcom/db.js" line: 703}]
```

**Comment by dstillman** [comment]
OK, try the latest beta.
