### ISSUE TITLE
Integration error due to control character in JSON

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1327]
https://forums.zotero.org/discussion/67876/error-report-id-615245584

**Comment by adomasven** [comment]
That's just <a href="https://stackoverflow.com/a/17487154/3199106">invalid JSON</a>, which means a corrupt field. We don't ever write invalid JSON into documents, so this isn't our bug.

**Comment by dstillman** [comment]
It's definitely invalid JSON — I just want to make sure we're not leaving people with broken documents. But it seems like when the "A field code in this document is corrupted" error is logged we're now prompting people to remove the field, which is fine. It wasn't clear to me from the user's report that that was what was happening.

**Comment by adomasven** [comment]
I can't attest for the current integration code, it might prompt the user with the wrong box and/or handle it wrong. The code in https://github.com/zotero/zotero/pull/1242 works as intended
