### ISSUE TITLE
Can't import bibtex in 5.0.22

### ISSUE THREAD

**Issue by Carpani** [zotero/zotero#1332]
Hello. I'm using Zotero 5.0.22 (I think the next which is refers in these posts) on fedora 25.

The installation was only an expanded from the tar.bz2 from zotero site.

I can't import my bibtex or biblatex files. Even, those exported by the same version of zotero.

There's something to do?

I'm attaching the log  ([ZoteroImportBib-renExtHtml.txt](https://github.com/zotero/zotero/files/1366935/ZoteroImportBib-renExtHtml.txt))
and the .bib ([OpenFING.txt](https://github.com/zotero/zotero/files/1366932/OpenFING.txt)
)....

The extensions of the files must be changed.

Thanks.
FDO.

**Comment by dstillman** [comment]
Please post support requests to the forums — this tracker is for developer use only.

You have a translator from Better BibTeX installed, which is causing this problem. It's not a Zotero issue.
