### ISSUE TITLE
Text cursor in note editor won't stop jumping back to the beginning

### ISSUE THREAD

**Issue by Toover** [zotero/zotero#1336]
Hello,
I am using Zotero stand-alone for my bibliography, this is a great tool, thanks to all.
On a new computer (running Fedora 26) I installed the latest version of Zotero (5.0.22) and started working with it.
I associated my account and the synchronization finished successfully.
Now, if I...
**Protocol**
1. Select a stored PDF file in the library. The right-side widget shows me its note.
2. Start editing the note, by typing text.
3. Wait few seconds for the inactivity to be detected...

**Expected**
... and I can keep on typing.

**Observed**
... and the text cursor jumps back to the beginning!

**Consequence**
When I resume typing it enters text at the beginning, the edition of file notes is unusable!

**Notes**
On a similar computer (Fedora 26, too) running an older version of Zotero (I don't know which version), it works.
At first I thought the problem was because of the automatic synchronization that happens anytime inactivity is detected, but disabling it did not change athing.

Report ID, just in case: 546019011

**Comment by Toover** [comment]
Sorry, I forgot: on a similar computer (Fedora 26, too) running an older version of Zotero (I don't know which version), it works.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/294824/#Comment_294824
