### ISSUE TITLE
macOS Sierra/Yosemite Crashes When Running Zotero

### ISSUE THREAD

**Issue by kwrobert** [zotero/zotero#1345]
Hello!

This is an insane, weird bug I'm hoping to get to the bottom of. 

Whenever I run Zotero on OSX (problem exists on both Yosemite and Sierra) on a mid-2014 Retina Macbook Pro, the OS will crash at random times. The screen goes black, then the OS shuts down. 

I'm 95% confident it's Zotero. I brought my machine to an Apple retailer, and all the hardware diagnostics passed. I reinstalled the OS, and everything worked fine until I installed Zotero. As soon as I installed Zotero and left it open for a short period of time, my machine crashed. I have since uninstalled Zotero and have not experienced any crashes. 

I've had no luck figuring out what exactly Zotero is doing to cause the crash. For the record, I am using my own Linux server as a WebDAV host for all my files. That's the only nonstandard configuration I can think of. 

I would be willing to post logs, configs, etc. to help provide more information about my set up and otherwise help in any way I can. I would _really_ love to get this figured out as Zotero is an indispensable tool for my work. 

Thanks!

**Comment by dstillman** [comment]
(Note that support requests [should go to the Zotero Forums](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md), not here.)

Really the only thing I can suggest would be to try upgrading to High Sierra — that's a pretty crazy bug, and it seems fairly outside the bounds of what a program should be able to do on its own. There also haven't been any other reports of this, and I'm not sure there's much we'd be able to do to debug it remotely, so hoping that it goes away in 10.13 is probably your best bet here. There might be some info from the time of shutdown in the system logs, but that's not really something we can review from here.

If you do keep seeing it, you can obviously watch in Activity Monitor to see if Zotero's memory usage is climbing or anything like that, but even that wouldn't normally manifest itself as a black screen.

**Comment by dstillman** [comment]
Closing this unless it reappears in High Sierra (and even then I can't imagine it's anything we can fix on our end).
