### ISSUE TITLE
Export RSS Feed

### ISSUE THREAD

**Issue by raivivek** [zotero/zotero#1352]
Hi,

I added a bunch of feed items in Zotero. However, I'm finding it inconvenient to read because it does not show a summary of the item and I have to go Online for viewing each item. I want to know if it's possible to have the preview functionality in-pane (or something similar) or just quickly export all feed links that I can feed to another feedreader.

Thanks!

**Comment by adomasven** [comment]
Please post feature requests on [Zotero Forums](https://forums.zotero.org/). This tracker is for developer use only.

**Comment by raivivek** [comment]
Thanks! Posted here https://forums.zotero.org/discussion/68479/export-rss-feed-collection#latest

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/issues/986
