### ISSUE TITLE
Add Linux flatpak package with Zotero 5.0

### ISSUE THREAD

**Issue by jacknlliu** [zotero/zotero#1355]
The Zotero 5.0 version on Linux platform need a standalone program. But with modern Linux packaging method, only a archived package is not a good method. We need a modern package which easy to install and use, I recommend use [flatpak](http://flatpak.org/) to do this.

**Comment by Maltimore** [comment]
Have you seen this?
https://github.com/flathub/org.zotero.Zotero

**Comment by jacknlliu** [comment]
@Maltimore  Yes, we're using it. Thanks for your attention.

**Comment by Maltimore** [comment]
@jacknlliu ok great. I was just wondering why the issue is still open then?

**Comment by jacknlliu** [comment]
yeah, we should close it, thanks

**Comment by nekohayo** [comment]
Shouldn't this be mentioned on https://www.zotero.org/support/installation and https://www.zotero.org/download/ then?

**Comment by nekohayo** [comment]
...a user-palatable link to point to could be https://flathub.org/apps/details/org.zotero.Zotero for example

**Comment by carlocastoldi** [comment]
Sorry for necro, but is there any plan to use [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal/)s?
