### ISSUE TITLE
support sinon <= 1.7.6

### ISSUE THREAD

**Issue by legrostdg** [zotero/zotero#1357]
I'm trying to update the Zotero packages in Debian. That's a big task, as the code changed a lot since 4.x. In particular, every dependency as to be packaged in Debian, which is quite difficult with the javascript ecosystem, especially as we can only have one given version of a package at a time.

I've noticed that sinon is required to be ^2.3.1. Would it be possible to allow ^1.7.6 (the version currently in Debian sid)? This is used by a lot of packages, and it will be hard to update all these package to support the newer version of sinon.

Thanks!

**Comment by dstillman** [comment]
No, sorry, Sinon 2.0 has breaking changes and we've already changed our tests to account for them.
