### ISSUE TITLE
please provide tarballs with submodules

### ISSUE THREAD

**Issue by legrostdg** [zotero/zotero#1358]
I would help packaging a lot (I'm preparing a new package for Zotero in Debian) to have submodules available in the tarballs. Would it be possible for you to do so?

**Comment by dstillman** [comment]
What do you mean by that? The tarball has all the code Zotero requires to run.

**Comment by legrostdg** [comment]
You have to provide all the source for a software to be in Debian. In particular, the submodules styles, translators, chrome/content/zotero/locale/csl are not in the tarball.

**Comment by adomasven** [comment]
The [linux tarball](https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64) includes everything Zotero requires to run, including the submodules. You are not seeing them in the tarball, because they're further archived within zotero.jar.

**Comment by legrostdg** [comment]
Mmh, ok. I did not see this tarball, just the ones on github. Maybe these ones could be removed, then? They seem useless without the submodules.

**Comment by dstillman** [comment]
Those are generated automatically in any GitHub repo when tags are created. The Zotero client build process is a [totally separate process](https://www.zotero.org/support/dev/client_coding/building_the_standalone_client).

**Comment by dstillman** [comment]
(But that's only if you actually need to recreate the build process. The Linux tarball we distribute should be runnable on most Linux systems and contains all of our source code (though it includes binary components from Firefox extracted via the linked build process).)

**Comment by legrostdg** [comment]
Yes, we need to recreate the build process for anything packaged in Debian. Thanks for the link!

**Comment by legrostdg** [comment]
... which unfortunately seems outdated. Would you mind updating this page or telling me what steps are modified?

**Comment by dstillman** [comment]
It's not outdated.

**Comment by legrostdg** [comment]
OK, then I totally misunderstood the 5.0 refactoring. I thought I just had to clone https://github.com/zotero/zotero and build this to get the new zotero-standalone. Thanks again!

**Comment by legrostdg** [comment]
Is there any plan to refactor zotero, zotero-build, zotero-standalone-build to a single repo, and maybe build something which would be javascript only? I don't want to put to much energy if everything has to be done again in a few months...

**Comment by dstillman** [comment]
Merging everything into a single repo is planned, but it's not a priority, and I doubt it will happen anytime soon.

As for JS-only, I'm not sure what you mean. There needs to be an executable one way or another. Zotero will be based on Electron at some point, and it could possibly work with a system-installed version, though given compatibility concerns I'm not sure that would be an option. In any case, it won't be happening for quite a while.

**Comment by legrostdg** [comment]
> As for JS-only, I'm not sure what you mean. There needs to be an executable one way or another. Zotero will be based on Electron at some point, and it could possibly work with a system-installed version, though given compatibility concerns I'm not sure that would be an option. In any case, it won't be happening for quite a while.

I was thinking of an electron (or whatever) based executable.

Thanks for addressing these concerns.

**Comment by legrostdg** [comment]
Last question (I hope :). Where can I find the zotero-standalone-build.git and zotero-build.git commits used in a release (I guess zotero.git is tagged appropriately)?

**Comment by dstillman** [comment]
Those aren't currently tagged — we just build with the latest available version at release time — but we can try to remember to tag zotero-standalone-build, which we've done in the past. I've just added a 5.0.24 tag. zotero-build doesn't change much, so that won't be tagged.
