### ISSUE TITLE
Show translate icon on PDFs

### ISSUE THREAD

**Issue by simonster** [zotero/zotero#136]
The proposed implementation is as follows:
1. We save the translator data (but, to avoid leaking, not the window) from the previous page displayed.
2. If
   - The new page is a PDF
   - All but the last domain are the same
   - It was arrived at via clicking a link
   - No translator of equal or higher priority can translate the current page

then show the same translate icon as we did on the previous page.

We may need to interface with the history API somehow if we want back/forward not to change translation behavior.

**Comment by bwiernik** [comment]
This seems to be largely solved by the current connector framework.

**Comment by adomasven** [comment]
PDF saving and PDF metadata retrieval are good enough to not bother with this, yes.
