### ISSUE TITLE
Support short DOI lookup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1361]
https://github.com/zotero/zotero/pull/1356 added parsing for [short DOIs](http://shortdoi.org/), but lookup doesn't actually work. This probably requires our new CrossRef REST API translator, since it doesn't look like the old API supports short DOIs.

(Side note: I'm not sure what the deal is with Airiti, since it seems like it just ends up making another doi.org request, but it's URL-encoding the DOI in its ```http://doi.org/<doi>``` requests, which causes them to fail. This only shows up when the DOI isn't recognized by earlier translators.)

**Comment by bwiernik** [comment]
http://doi.org has acknowledged that this is a bug in their resolver, but aren't confident that it will be fixed in any sort of timely manner.

**Comment by bwiernik** [comment]
This has been fixed by http://doi.org/ now. shortDOI links resolve correctly.

**Comment by dstillman** [comment]
(This might have been fixed by our recent switch to using content negotiation via doi.org instead of the old Crossref API.)
