### ISSUE TITLE
Snapshot saving fails with a crash or leaves hidden browsers open.

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#1363]
There's been a few reports of this:
- https://forums.zotero.org/discussion/68579/saving-from-espacenet-classification-index
- https://forums.zotero.org/discussion/66433/zotero-5-01-and-chrome-connector-not-saving-snapshots-and-crashing

Somewhat relevant: saving in reader-mode has [been discussed](https://github.com/zotero/zotero-connectors/issues/194) as a path of snapshot saving simplification, but perhaps that's not a good direction given that is seems we can't control issues like the above.

**Comment by dstillman** [comment]
Why would simplified snapshots not be a fix for this?

**Comment by adomasven** [comment]
Sorry, should have clarified. Unless the FX reader-mode code is written in JS (which I assume it isn't) and we can extract it into the Connectors, we'd still need to load the doc in a hidden browser within Zotero.

**Comment by dstillman** [comment]
My suggestion that we try extracting it was premised on the idea that it's in JS and we would run it in the connector. If that's not the case, we'd try to find suitable a JS library.

**Comment by dstillman** [comment]
Obsoleted by SingleFile support, which saves rendered pages in the connector
