### ISSUE TITLE
Change keyboard shortcuts(on Firefox)

### ISSUE THREAD

**Issue by antoinentl** [zotero/zotero#1366]
Issue initially posted [on the Zotero Forums](https://forums.zotero.org/discussion/68675/change-default-keyboard-shortcuts-on-firefox).

Actually the keyboard shortcut CTRL+MAJ+S on Firefox activate the developer tools (console, inspector, etc.), very useful. But if the Zotero addon (for Firefox) is active (since the wonderful Firefox 57), the keyboard shortcut CTRL+MAJ+S launch Zotero.

For people who work both *on* the web and *with* bibliographic references, Zotero and developer tools are *unavoidable*.

My question: how I can change the default keyboard shortcuts of Zotero?

**Comment by dstillman** [comment]
The forums are the right place for this. (This tracker is for developer use only.)

**Comment by antoinentl** [comment]
@dstillman Thanks. I know, I read the contributing guidelines, but the GitHub issues tracker is a good way to *cross* user issues and developer issues (in my opinion). You can delete this issue if necessary. Sorry for the inconvenience.
