### ISSUE TITLE
Zotero connector can not save CNKI webpage to zotero via proxy

### ISSUE THREAD

**Issue by l0o0** [zotero/zotero#1382]
I can access [CNKI](http://www.cnki.net/) via a proxy. But I can not save the webpage to zotero. When I disable the proxy, everything goes fine. 

Zotero 5.0.30, Zotero connector is downloaded from Firefox Add-ones. 
Is there anything else I can provide to solve this problem?

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums. (This tracker is used by developers, but many more people are involved in support in the forums.) Be sure to provide an example URL that doesn't work, a <a href="https://www.zotero.org/support/reporting_problems#provide_a_report_id">Report ID</a>, and an exact description of what's happening.
