### ISSUE TITLE
When I delete items in trash, the file in this item do not delete

### ISSUE THREAD

**Issue by god891006** [zotero/zotero#1388]
Using the relative path, when delete items in trash , file won' t delete automatically, I must delete the file manually.
It happened when I use the relative path, the absolute path works well.
If it is not a issue, can you tell me how to set the reference to delete files by using the relative path? The problem makes my folder full of useless files.

**Comment by dstillman** [comment]
Nothing to do with absolute or relative paths — Zotero never deletes linked files, only stored files.

Please post further questions to the Zotero Forums. (This issue tracker is for developer use only.)
