### ISSUE TITLE
Cannot add DOIs with reference-book type

### ISSUE THREAD

**Issue by adunning** [zotero/zotero#1395]
When adding an item using a DOI, Zotero (5.0.32) will not accept anything with the `reference-book` (i.e. encyclopedia entry) type. For example, <https://doi.org/10.1093/odnb/9780192683120.013.19839> and <https://doi.org/10.1093/benz/9780199773787.article.b00192562>, which both resolve, come up in Zotero with the 'could not find a record' error. Similarly, visiting <https://search.crossref.org/?q=alexander+neckam&type=Reference> and attempting to save the DOIs using the browser extension will not work.

**Comment by adunning** [comment]
I cannot, oddly, find any documentation indicating that `reference-book` is intended for encyclopedia entries, though it is certainly used for them in those examples. There is also `reference-entry` that seems to used for them fairly frequently, such as in <https://doi.org/10.1002/9781118351352.wbve0105>, but these are translated into a book chapter by Zotero at the moment.

**Comment by adunning** [comment]
I wrote CrossRef support, who clarify that `reference-book` is intended to be used for an entire encyclopedia or the like, whilst `reference-entry` is intended for an individual encyclopedia article. Much of the problem, then, is really with the metadata, but nonetheless `reference-book` entries shouldn't be coming up as not found.

**Comment by dstillman** [comment]
Please post all support questions and bug reports to the forums.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/69536/cannot-add-dois-with-reference-book-type
