### ISSUE TITLE
Customizable renaming rules

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1413]
À la ZotFile, though I don't know if we'd use exactly the same rules.

(I thought we had a ticket for this, but I can't find one.)

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/395176/#Comment_395176

**Comment by tnajdek** [comment]
I'll take a stab at this. I think first step is to improve the current system to accept more wildcards for fields and offer more flexibility. We can then think about adding a new UI to preferences so that this can be configured more easily without using hidden prefs.

**Comment by bwiernik** [comment]
This is the current list of wildcards Zotfile gives http://zotfile.com/

**Comment by tnajdek** [comment]
If we still want this, we should probably target Zotero 7? Should I port this to `fx102` branch?
