### ISSUE TITLE
[feature request] Short title replacing title

### ISSUE THREAD

**Issue by TimotheeGreg** [zotero/zotero#1427]
The titles of articles are always very long and it is hard to find the one we want if we have to read them.
It would be great if, when a "short title" is set, it is shown instead of the title.
It could even be used to produce the bibtex citekeys.

**Comment by dstillman** [comment]
Please post feature requests to the [Zotero Forums](https://forums.zotero.org/).

**Comment by TimotheeGreg** [comment]
Ok, sorry !
Thanks !
