### ISSUE TITLE
collection name doesn't always change (when right-click is used)

### ISSUE THREAD

**Issue by bjohas** [zotero/zotero#1432]
When I change the name of a collection by double clicking, it works fine. If I right click and then change it via the popup, it sometimes doesn't work (name of collection unchanged). (Latest Zotero, OS X, 10.11.6). 

Debug ID D1053175258 

Note that it's intermittent - I changed the name three times (all by right clicking and editing the popup). It worked the first two times, then it didn't. All of those are captured in the report.
Also, whether it works or not doesn't seem to depend on the change made. Just after the debug report, I tried making the same change again, and it worked.

**Comment by dstillman** [comment]
Please post all support requests to the forums. This tracker is for developer use only.

**Comment by bjohas** [comment]
Ah ok - thanks, no problem. I was starting to worry about the number of forum posts... but sure, I'll keep posting to the forum!
