### ISSUE TITLE
In-text citations double up after using Document Preferences dialogue

### ISSUE THREAD

**Issue by eebrown** [zotero/zotero#1434]
Bug:

1. Using Microsoft Word 16.9.1 on macOS 10.13.3 with the Zotero toolbar.
2. Have several citations in the document and a bibliography.
3. Click Document Preferences in Word add-on. Click OK.
4. In-text citations double up. E.g. From "John et. al1" becomes "John et al.11"

**Comment by adomasven** [comment]
Cannot reproduce, likely the bugs of 16.9 since resolved.
