### ISSUE TITLE
computerProgram should have DOI field

### ISSUE THREAD

**Issue by katrinleinweber** [zotero/zotero#1438]
Given https://guides.github.com/activities/citable-code/ it seems like a bug that Zotero currently removes the DOI from an entry that is converted to a `computerProgram`.

**Comment by dstillman** [comment]
[Additional fields](https://github.com/citation-style-language/zotero-bits/issues/73) are planned for the next major version of Zotero.

(Please post support queries and bug reports to the Zotero Forums, not this tracker.)
