### ISSUE TITLE
Paste of BibTeX data should be possible

### ISSUE THREAD

**Issue by koppor** [zotero/zotero#1441]
Assume, I have following entry in the clipboard:

```
@Book{Rechenberg2006a,
  title         = {Technisches Schreiben},
  publisher     = {Hanser Fachbuchverlag},
  year          = {2006},
  author        = {Peter Rechenberg},
  edition       = {3., erw. und aktualisierte Aufl.},
  isbn          = {9783446406957},
  pagetotal     = {253},
  ppn_gvk       = {511633173},
  subtitle      = {(nicht nur) für Informatiker},
}
```

I change now to Zotero and press <kbd>Ctrl</kbd>+<kbd>V</kbd>. Expected behavior: Entry appears in Zotero. Actual behavior: Nothing happens: Pasting is disabled.

Importing (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>) also does not help: Zotero shows "unsupported format".

**Comment by dstillman** [comment]
Import from Clipboard is a separate command. Check the File menu for the shortcut.

Please post feature requests and bug reports to the Zotero Forums rather than this tracker.

**Comment by koppor** [comment]
Done. Follow up at https://forums.zotero.org/discussion/70420/allow-pasting-of-bibtex-entries.
