### ISSUE TITLE
Suggestion: New Field Types for Foreign-Language Documents

### ISSUE THREAD

**Issue by SR--** [zotero/zotero#1443]
Extensions to many common styles, like Chicago, required by typical journals and book publishers, like Taylor and Francis, demand that when you cite a foreign document in a foreign language you provide:

**Translated Title
Title in the Original Writing Systems (Latin, Cyrillic, etc.)
Transliterated Title**

The same goes for **Authors, Translators, Publishers, Place Published, Secondary and Tertiary titles and authors, etc.**

Can this be included please? This is common in History and many other fields and hard to overcome (either lots of custom fields that can be used for this or painful manual editing).

Here is an example:

*Mayzelis, Il'ya (Майзелис, Илья). 1973. "Emanuel Lasker i ego kniga." (Эммануил Ласкер и его книга) [Emanuel Lasker and his book] In Kak Viktor stal shakhmatistom (Как Виктор стал шахматистом) [How Victor became a chess player] Il'ya Mayzelis (Илья Майзелис), 111–142. Moskva: Detskaya literatura.*

See the forum topic here: https://forums.zotero.org/discussion/70423/new-field-types-for-foreign-language-documents#latest

**Comment by dstillman** [comment]
All feature requests and bug reports should go to the forums, not this tracker.
