### ISSUE TITLE
Definition of custom fields associated to each pubblication

### ISSUE THREAD

**Issue by tfabbri** [zotero/zotero#1463]
Is it possible to define custom fields associated to each paper like:

- [ ] Read
- [ ] Crossref check (check of the references in the paper and the publications citing the paper considered). 
- [ ] Others ... 

In this way the user can understand from the list-view of the available papers if he/she performed his/her usual operations.

**Comment by adomasven** [comment]
In order to keep product discussions open to as many people as possible, Zotero does not use GitHub Issues for bug reports or feature requests. Please use the [Zotero Forums](https://forums.zotero.org) to report problems and suggest changes.
