### ISSUE TITLE
Store PDFs in a more "file explorer" friendly way - Folder for Collection, in that folder the PDFs of that collection

### ISSUE THREAD

**Issue by fabi94music** [zotero/zotero#1478]
Would be great if I was able to access my pdfs in a more easy way over a file explorer. 

Actual behaviour: pdfs are stored in Zotero/storage/ and within storage in cryptical folders like "3NNSWMQ5". 

Expected behaviour:
All pdfs of one collection sorted in a folder under the collection name, e.g. Zotero/storage/"Collection"/pdfinmycollection.pdf

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Please post feature requests and bug reports to the Zotero Forums.

(This is a common request, but collections != folders. Items can exist in multiple collections, so this doesn't work. But we're hoping to make it easier to navigate the data directory outside of Zotero in the future.)
