### ISSUE TITLE
how can i identify which collection are the searched items located?

### ISSUE THREAD

**Issue by fredericky123** [zotero/zotero#1483]
Every time, the search function using key words is very convenient for me to find the items I forget.
But which collection are the searched items located? I have to search the item one collection by one collection to locate it. Can we have located collection information after searching in the whole library?

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Please post all support requests to the Zotero Forums.

https://www.zotero.org/support/kb/collections_containing_an_item

**Comment by fredericky123** [comment]
very useful, thank you very much!
