### ISSUE TITLE
Open progress window prevents Zotero shutdown

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1485]
https://forums.zotero.org/discussion/71405/popup-notification-never-disappears

To reproduce, start an import and close the main Zotero window before the popup closes. The import progress window will keep the app from quitting, with no way to close it.

The progress window should add a shutdown listener and close automatically (or maybe set a close listener on its opener, if it can).

**Comment by douglasrizzo** [comment]
I'm using Zotero 5.0.95 on Manjaro Linux. I copied a Bibtex entry and used the "Import from Clipboard" functionality. The notification shown in the screenshot below appeared, but never disappeared, even after the import procedure ended. Zotero was still open in my computer, but it seems there was no timeout for the popup to disappear. When I closed Zotero, the notification went away.

If you need some kind of application log to accompany this comment, just point me on how to get it and I'll make sure to provide it once I am able to reproduce this behavior.

![image](https://user-images.githubusercontent.com/2209364/108895164-0157d180-75f2-11eb-9ad5-3f3c143dff08.png)
