### ISSUE TITLE
En dash does not get replaced by -- when exporting to biblatex

### ISSUE THREAD

**Issue by bpampel** [zotero/zotero#1506]
Hello,

the issue is already partially solved as biblatex started to accept the en dash on unicode machines ([see their github issue](https://github.com/plk/biblatex/issues/366)), but on older machines without the update the problem remains: 
If an entry in the library contains an en-dash it will not be replaced by -- upon exporting to bib(la)tex. If this entry is then cited in a tex document using biblatex the compilation fails with "undefined control sequence". Wouldn't it be better if it get's automatically replaced on export?

A minimal example that fails for me is given below.

example.tex:
```
\documentclass[a4paper]{article}
\usepackage{biblatex}
\bibliography{faulty.bib}
\begin{document}

This fails to compile if I cite~\cite{en-dash}

\printbibliography{}
\end{document}
```

faulty.bib:
```
@article{en-dash,
    author  = "Testperson",
    title   = "Title with en dash — Will not work"
}
```

**Comment by dstillman** [comment]
Please post all support requests to the <a href="https://forums.zotero.org">Zotero Forums</a>.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
