### ISSUE TITLE
Adding by DOI misses page numbers for all APS journals

### ISSUE THREAD

**Issue by jsampaio** [zotero/zotero#1514]
When adding an entry by DOI, the page number is not added for some journals. This is true for at least all the APS journals. It might be because in some online databases APS journals have their page number classed as “article-number” instead of “page”.
This bug exists at least since 2015:
https://forums.zotero.org/discussion/54197/aps-articles-missing-page-number-in-add-by-doi

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
