### ISSUE TITLE
Attachments are uploaded to ZoteroStorage when WebDAV file syncing is chosen

### ISSUE THREAD

**Issue by kernie** [zotero/zotero#1526]
Dear developers,

using ZOTERO 5.0.52 and I'm generally happy with the citation functionality and ecosystem of Zotero.

But now I have to separate attached document files from the ZoteroStorage because of compliance reasons. I tried using the WebDAV option with my personal file storage (Nextcloud) and the attachment is stored on the personal file server.

However, the file is unfortunately also synced with the ZoteroStorage, what renders my approach and the usage of Zotero useless in that case.

Is this by design? Or am I doing something wrong?

Kind regards,
Maarten

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums and we'll be happy to help.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

(Files aren't synced to multiple locations, but if you previously synced with Zotero File Storage and then switched to WebDAV without choosing to purge files, you can use Purge Storage in your storage settings on zotero.org to delete them.)
