### ISSUE TITLE
Interactive fuzzy searching through index with preview

### ISSUE THREAD

**Issue by davidovitch** [zotero/zotero#1536]
What about an interactive fuzzy-search functionality with preview? I liked the workflow described at [this](https://news.ycombinator.com/item?id=17609057) Hacker News post (and illustrated with [this](https://user-images.githubusercontent.com/1019692/34446795-12229072-ecac-11e7-856a-ec0df0de60ae.gif) animated GIF). The fuzzy-searching is based on [fzf](https://github.com/junegunn/fzf).

**Comment by bwiernik** [comment]
Please post feature requests to the Zotero forums, rather than on GitHub.

**Comment by davidovitch** [comment]
Apologises for the noise, moved to https://forums.zotero.org/discussion/72941
