### ISSUE TITLE
Higher resolution, consistent iconography

### ISSUE THREAD

**Issue by Benjamin-Lee** [zotero/zotero#1539]
The [16x16 Pastel SVG icons](https://codefisher.org/pastel-svg/), [Silk icons](http://www.famfamfam.com/lab/icons/silk/) and [Tango icons](http://tango.freedesktop.org/Tango_Desktop_Project) are showing their age, especially on a retina display.

Could we maybe go for a higher res set of icons?

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Please post all feature requests and bug reports to the Zotero Forums, not this tracker.

(A redesign with new icons is planned, but note that nearly all icons in Zotero are already high-res. Pastel SVG icons are vector versions of Silk icons, and we use the 32x32 versions at 16px, so they're 2x on most Retina displays.)
