### ISSUE TITLE
Integration tests failing after 0f1687f1c7b

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1546]
Broken in 0f1687f1c7b50635e2908e5cce4bb88d8a359a18

**Comment by dstillman** [comment]
Still failing on "should download the style and if user clicks YES"

**Comment by dstillman** [comment]
(And the connector save popup is now blank rather than displaying the name of the installed style)

**Comment by dstillman** [comment]
One problem with the integration part (possibly unrelated to the test) is that the `Zotero.Styles.install()` calls are now using destructuring assignment, but that will fail if the function returns `undefined`, which it does in a couple error cases.

**Comment by adomasven** [comment]
> One problem with the integration part (possibly unrelated to the test) is that the `Zotero.Styles.install()` calls are now using destructuring assignment, but that will fail if the function returns `undefined`, which it does in a couple error cases. Returning `false` would be fine, though.

That only happens if `silent` argument to `Zotero.Styles.install()` is false, which it is not in the places, where we use the destructuring assignment.
