### ISSUE TITLE
Document preferences does not fit on the screen with high DPI Windows and low resolutions

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#1554]
https://forums.zotero.org/discussion/73242/zotero-document-preferences-in-word-not-fitting-in-screen

Need to allow resizing and either reduce the style picker as the window is made smaller or add a scrollbar for preferences below the style picker

**Comment by dstillman** [comment]
I don't think we want to do either of those. If the dialog is too big for some screens, we should just shrink it, or dynamically shrink the style list until the window no longer runs off the screen. But I'd like to see a screenshot from that person to see how reasonable their setup is.

**Comment by adomasven** [comment]
![image](https://user-images.githubusercontent.com/5899315/44331254-bd5c4280-a471-11e8-8243-624d4e319ba1.png)

**Comment by adomasven** [comment]
This is at 960 height with 150% DPI
![image](https://user-images.githubusercontent.com/5899315/44331294-dcf36b00-a471-11e8-8f07-45d01eac9929.png)

**Comment by adomasven** [comment]
Closed with 0fd28959bf01b40544e201f83e9d87b713aa0d7c
