### ISSUE TITLE
Word integration error with document stored in OneDrive

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1576]
This is bizarre, but we've had various reports that having a document in OneDrive causes integration errors. E.g., https://forums.zotero.org/discussion/73678/error-id-944178723

We should either try to fix this or, if possible, display a warning when a document is saved in OneDrive (if we can tell from the plugin).

**Comment by dstillman** [comment]
(I guess this is Word for Windows only. Not sure which codebase would get the fix.)

**Comment by adomasven** [comment]
Closed in https://github.com/zotero/zotero-word-for-windows-integration/commit/821b86e65b9a01549d0dd3f7faf5a64cc30376a2
