### ISSUE TITLE
Identify similar / same authors before exporting

### ISSUE THREAD

**Issue by adam-ah** [zotero/zotero#1577]
Copying from BBT:
https://github.com/retorquere/zotero-better-bibtex/issues/1067

# Bug classification

This is an enhancement request.

## Non-export problems with BBT

An issue I keep running into when dealing with large number of references in the same area, is that the same author might be imported by slightly different names / versions on these references.
Let's say these names across 3 papers would all point to the same author:

Dewe, Philip
Dewe, Philip J.
Dewe, P. J.

The problem is that when I generate my references using biblatex, this will cause weird artefacts to show up both in text and in references list as the generator will try to highlight that these are different people.

Sometimes it's easy to spot because a square bracket [] pair gets added in the references list, sometimes it is hard because the in-text citation will have a prefix.

The solution is to manually fix the entries, which is fine.

Would it be easy to try to identify these entries ? Just like finding duplicates in Zotero, so the user can go through the list and fix the references before exporting / using them?

Thanks :)

**Comment by dstillman** [comment]
Please post feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org).

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
https://www.zotero.org/support/zotero_support

This will be addressed by batch editing in a future version.
