### ISSUE TITLE
Libreoffice icon dpi

### ISSUE THREAD

**Issue by bijang** [zotero/zotero#1587]
Tollbar icons not rendering well on hidpi display, on windows os, havn't had chance to check linux os

**Comment by adomasven** [comment]
Please post feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org).

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
https://www.zotero.org/support/zotero_support

The plugin provides both low and high resolution versions of icons to LibreOffice, but the highest resolution that it accepts currently is 26x26px, so I cannot imagine they look well. Either way, nothing we can do on this front at the moment.
