### ISSUE TITLE
Ability to add Color and Rating to a Paper as a whole (not a tag)

### ISSUE THREAD

**Issue by raamana** [zotero/zotero#1589]
I had been a long time user of [PapersApp](https://www.readcube.com/papers/) and really liked the ability to add a color for entire paper , and a rating (to reflect its importance or quality etc).. I think this would make a tremendous addition to Zotero.

Colored tags are helpful, I personally colors to a paper as a whole is lot easier and more useful to quickly pick out few important papers

**Comment by dstillman** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org).

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
https://www.zotero.org/support/zotero_support

(I'm not sure what you mean by "add a color for entire paper" — that's exactly what you can do with colored tags.)
