### ISSUE TITLE
Don't require built-in certs for add-on updates

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1600]
https://forums.zotero.org/discussion/74737/option-to-disable-websockets-in-general-or-at-least-for-addon-updates

`extensions.install.requireBuiltInCerts` apparently doesn't work

**Comment by tolot27** [comment]
Setting `extensions.install.requireBuiltInCerts` to `true` implies the oposite. Also, this option is only checked on installation of new plugins. To update plugins, `extensions.update.requireBuiltInCerts` should be set to `false`. Now, everything works as expected.

**Comment by tolot27** [comment]
Thanks for pointing me to the right direction. I got the information from [Bug 1308251:
Remove built-in certificate requirement for addon updates](https://bugzilla.mozilla.org/show_bug.cgi?id=1308251)

**Comment by dstillman** [comment]
Oops, sorry, gave that suggestion too quickly — thanks for catching that.

I've set both prefs to false for the next version.
