### ISSUE TITLE
zotero connector port for chromeos

### ISSUE THREAD

**Issue by jackyko1991** [zotero/zotero#1616]
I am new to chromeos and has been used zotero for long time. Recently Google docs get official zotero support, at the same time chromeos released linux environment, which standalone version can work properly.

Problem comes in when I use zotero connector for citation insertion in google doc. I get it work for by port forwarding chromeos 23199 to some local port in linux container. ChromeOS hides most linux ports except for some well known services (e.g. 22, 80, 8000)

I use this plugin(https://chrome.google.com/webstore/detail/connection-forwarder/ahaijnonphgkgnkbklchdhclailflinn) and set rule from 0.0.0.0:23199 to 127.0.0.1:23199, this will crash the chrome browser, and the things works fine if I change the rule as from 0.0.0.0:23199 to 127.0.0.1:8080

i am trying to contact the wiki writer for this temporary solution as I don't have permission to change the  official documentation. should this consider a bug or special setting for chromeos usage?

**Comment by dstillman** [comment]
You can change Zotero's port with the `httpServer.port` [hidden pref](https://www.zotero.org/support/preferences/hidden_preferences) and change `connector.url` in the Zotero Connector hidden prefs.

If you'd like to add something to the Zotero wiki, there should be instructions for how to request a wiki account when you go to edit a page. If you're seeing "Is Zotero Running?" before fixing this, we'd probably want to add something to [this page](https://www.zotero.org/support/kb/connector_zotero_unavailable).
