### ISSUE TITLE
The html entities in bibtex cannot be recognized correctly

### ISSUE THREAD

**Issue by psychelzh** [zotero/zotero#1623]
For example, the `&quot;` should be displayed as `"`.

```Tex
@MISC {283,
    TITLE = {What is a &quot;saturated&quot; model?},
    AUTHOR = {Graham Cookson (https://stats.stackexchange.com/users/215/graham-cookson)},
    HOWPUBLISHED = {Cross Validated},
    NOTE = {URL:https://stats.stackexchange.com/q/283 (version: 2010-07-20)},
    EPRINT = {https://stats.stackexchange.com/q/283},
    URL = {https://stats.stackexchange.com/q/283}
}
```

But it renders as follows:

![image](https://user-images.githubusercontent.com/13306020/51074113-011c4680-16b6-11e9-9daf-d96fd7ef9f88.png)

**Comment by dstillman** [comment]
There's no reason for this to be converted — `&quot;` isn't BibTeX.

If you just import from that page using the Save to Zotero button, Zotero will import it properly. This is just a bug in whatever generated that BiBTeX, which should've parsed the HTML properly while it was still part of a webpage.
