### ISSUE TITLE
Chicago style (author-date) formatting problems w/ latest zotero update

### ISSUE THREAD

**Issue by bnmont** [zotero/zotero#1624]
With the latest Zotero update 5.0.60, when I use Scannable Cite with the RDF/ODF scan plugin and later choose Chicago Style (author- date) for in-text citations, many of the citations are improperly formatted as Author Last Name, First Initial Date) or (Author Last Name, First Name Date). This was not an issue with version 5.0.59. Not sure if it's a plugin problem or a zotero problem.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
