### ISSUE TITLE
No document open? 

### ISSUE THREAD

**Issue by wbt** [zotero/zotero#1627]
## The Issue
I have MS Word open and the Zotero integration installed.  I recently opened Zotero to add a citation to a document that already had several Zotero citations.  It gave me a quick popup "Zotero is installing updates and will open in a few moments" or similar.  When it opened, I went back to the document and clicked to add a citation.  However, all I can get now is a popup error saying "Zotero experienced an error updating your document.  This command is not available because no document is open. [getDocument:d:\users\build\cygwin\home\build\zotero-word-for-windows-integration\build\zoterowinwordintegration\document.cpp]"  

In Zotero->Help->Report Errors, I see the following: 

> No errors have been logged since Zotero started.
>version => 5.0.59, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 5.0.59, extensions => Zotero LibreOffice Integration (5.0.14.SA.5.0.59, extension), Zotero Word for Windows Integration (5.0.10.SA.5.0.59, extension)

There is clearly a document open, and there was an error which prevents me from using the software, just before the submission deadline. 

## Desired behavior
1 (strong priority). Please allow users to turn off automatic updating. 
2. The error "no document is open" should not occur when a document is open and being edited.

**Comment by dstillman** [comment]
Please post all support requests to the Zotero Forums.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

**Comment by wbt** [comment]
I unfortunately don't have my login credentials anymore, so I won't be posting there.  (If I did, I would further note that steps like restarting Word and reinstalling the plugin didn't help).  However, you may wish to post your message above in an [Issue Template](https://github.blog/2016-02-17-issue-and-pull-request-templates/).

**Comment by dstillman** [comment]
We'll add an issue template — thanks.

To be clear, though, we're happy to help. This just isn't where support happens.
