### ISSUE TITLE
Selected tag isn't deselected when switching views

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1646]
https://forums.zotero.org/discussion/76058/beta-tag-filter-persists-even-if-changing-collection-or-library

This is a regression from Reactification.

(I would've fixed this by clearing selected items in `onItemViewChanged`, but I'm not clear why `this.selectedTags` isn't part of state, so that changing it triggers re-rendering automatically.)

**Comment by adomasven** [comment]
> (I would've fixed this by clearing selected items in `onItemViewChanged`, but I'm not clear why `this.selectedTags` isn't part of state, so that changing it triggers re-rendering automatically.)

As discussed previously, we're not using React's own state due to how tree.js is designed and rerenders are manually triggered using `this.forceUpdate()`
