### ISSUE TITLE
"this.collectionTreeRow is undefined" in tag selector notify()

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1649]
Post-Reactification of the tag selector, I'm seeing this in debug output during a local (not yet committed) test.

```
    TypeError: this.collectionTreeRow is undefined
        getTags@chrome://zotero/content/containers/tagSelector.js:270:361
        notify@chrome://zotero/content/containers/tagSelector.js:270:284
        Zotero.Notifier</this.trigger<@chrome://zotero/content/xpcom/notifier.js:137:34
```

I suspect this is a general problem, but if you're not seeing it it can wait until I commit the current test I'm working on.

**Comment by adomasven** [comment]
You would only see this error if notifications for the tag selector would somehow reach the tag selector after it has been initialized, but before an items view has been initialized. This does not happen normally.
