### ISSUE TITLE
'zotero.tagSelector.noTagsToDisplay' appears in tag selector during tests

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1661]
Localization isn't working properly during tests post-Reactification.

**Comment by dstillman** [comment]
In the console, I see messages like this:

> [React Intl] Cannot format message: "zotero.tagSelector.noTagsToDisplay", using message id as fallback.

**Comment by stephtr** [comment]
In the German version it displays "zotero.tagSelector.noTagsToDisplay":

![image](https://user-images.githubusercontent.com/5764184/61375734-e793cb80-a89f-11e9-995d-569547b70753.png)
