### ISSUE TITLE
Show X in libraries-to-sync table when a library is disabled for syncing

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1675]
When there are no groups, it's hard to realize that the absence of a checkbox means it's disabled.

https://forums.zotero.org/discussion/comment/329608/#Comment_329608

**Comment by sbennett18** [comment]
Could possibly use `chrome://zotero/skin/cross.png` and `chrome://zotero/skin/tick.png` for `treechildren::-moz-tree-checkbox` and `treechildren::-moz-tree-checkbox(checked)`, respectively.

**Comment by sbennett18** [comment]
![image](https://user-images.githubusercontent.com/1417401/56471445-98650880-6420-11e9-995e-7db9e979e896.png)
![image](https://user-images.githubusercontent.com/1417401/56471446-9b5ff900-6420-11e9-8acc-3aeec67a0661.png)

**Comment by dstillman** [comment]
We needed a quick fix here for Zotero 5.0.78 and up on Windows, so we switched to Unicode characters. We can consider using images in the future after the pane is reimplemented in HTML.
