### ISSUE TITLE
Cursor is positioned before inserted bibliography

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1682]
This seems like a regression. If I insert a citation in APA in Mac Word, press Return twice, and then insert a bibliography, 1) I lose one of the newlines and 2) the cursor is positioned before the inserted bibliography.

(I think I was also seeing some weirdness with citations, but I'm not seeing that at the moment.)

**Comment by dstillman** [comment]
Actually, these may be separate problems. This was on master, with citeproc-js 1.2.2. In 5.0.66, the cursor is positioned before the bib, but both newlines remain.

**Comment by adomasven** [comment]
Closed with https://github.com/zotero/zotero-word-for-mac-integration/commit/129e92012d2732d2fd16ac94bc42d530b0413cad
