### ISSUE TITLE
Skip document scan when automatic citation updates are disabled

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1689]
https://forums.zotero.org/discussion/comment/331445/#Comment_331445

When automatic citation updates are disabled, we should skip the potentially slow document citation scan that happens when opening the citation dialog. Instead, we should cache cited items on refresh and add to the cache when inserting citations. (If a citation is removed from the document, it will remain in the cited-items list until the next refresh, but that's fine.)

**Comment by dstillman** [comment]
This debug output from the beta seems to show a scan even with automatic updates off:

https://forums.zotero.org/discussion/comment/332502/#Comment_332502

```
(3)(+0000004): Integration: Displaying dialog chrome://zotero/content/integration/quickFormat.xul

(4)(+0000000): ZoteroMacWordIntegration: cleanup

(3)(+0002636): QuickFormat: QuickSearch: […]
```
```
(3)(+0000024): Getting cited items asynchronously

[…]

(3)(+0107088): Integration: Retrieved 198 fields in 142.568; 1.38881095336962 fields/second
```
```
(3)(+0000002): Integration: Updated session data for 198 fields in 17.364; 11.402902557014512 fields/second

[…]

(3)(+0000172): Integration: MacWord16-addEditCitation:'/Applications/Microsoft Word.app/' complete in 166.07s
```

**Comment by adomasven** [comment]
The initial interaction with the document upon Zotero restart fetches all fields. Afterwards subsequent operations don't. This is working as intended.
