### ISSUE TITLE
Add "place" field to journal articles type

### ISSUE THREAD

**Issue by Raphapere** [zotero/zotero#1701]
Moved from https://forums.zotero.org/discussion/73983/journal-article-type-missing-the-place-field/p1

I am using Zotero on linux. Version 5.0.66.
Unfortunately I seems that for the type "journal-article" there is no "Place" field to enter the Place of publication which is required by the used style.

Can you add this field on next update?

**Comment by dstillman** [comment]
https://github.com/citation-style-language/zotero-bits
