### ISSUE TITLE
DOI Manager functions

### ISSUE THREAD

**Issue by bwiernik** [zotero/zotero#1702]
Follow up from https://forums.zotero.org/discussion/77711/available-for-beta-testing-retracted-paper-notifications

The DOI Manager plugin (https://github.com/bwiernik/zotero-shortdoi/) has three functions:
1. Retrieve a DOI for items that don't have one.
1. Verify that a stored DOI is valid and clean it of URL components (cf. https://github.com/zotero/zotero/issues/556)
1. Retrieve shortDOIs (http://shortdoi.org/) for items.

The plugin can automatically be set to retrieve short or long DOIs (or verify DOIs) on import. 

If no DOI can be found, an invalid DOI is stored, or DOI lookup results in multiple possible hits, corresponding tags are added to the affected items.

Currently, the plugin stores shortDOIs by replacing the contents of the DOI field with the shortDOI. This works for citing and resolving DOI links by clicking on the DOI field or using the CrossRef lookup engine, but it breaks other functions, such as lookup through other APIs (e.g., Unpaywall, Web of Science), the Retrieve PDF function, and the RetractionWatch integration.

It would be nice to avoid this conflict, as well as integrate some or all of DOI Manager's features into Zotero itself. 

For storing shortDOIs, could we add `shortDOI: ` as a parse-able field to Extra? If present, this would replace the contents of the DOI field (or DOI stored in Extra) for export/citing. This could eventually be moved to a proper shortDOI field to permit copying as a URL or left as something parsed from Extra. This could be a hidden preference if a user using shortDOIs for some reason wanted to temporarily use the long DOIs.

Regarding the other functions:
1. DOI lookup and verifying the validity of DOIs could be incorporated into the forthcoming metadata update function
1. Retrieving shortDOI (manually or automatically on import) could also be added a function directly into Zotero

@retorquere

**Comment by retorquere** [comment]
Wouldn't `Short DOI: ...` be more in keeping with how Zotero stores other extra-fields?

**Comment by bwiernik** [comment]
The official name of these is "shortDOI". We would probably want to parse any casing and with or without spaces.

**Comment by retorquere** [comment]
I was just thinking that the citation key is stored in the `extra` field as `Citation Key: ...` where it initially was `citationkey: ...` or somesuch, and I changed it at direction of Dan to `Citation Key`. The general rule seemed to be that it would go into the `extra` field as it would be expected to display in the UI of the English version of Zotero.

**Comment by bwiernik** [comment]
What I mean is that the official name of shortened DOIs from http://shortdoi.org is "shortDOI"—camel case, no space.

**Comment by retorquere** [comment]
Before I get too far ahead on adding this to BBT -- would export translators get this field automatically in the serialized object, or would each translator do `extra` parsing on its own?

**Comment by bwiernik** [comment]
I would hold off on anything until Dan weighs in on Zotero's behavior.

**Comment by bwiernik** [comment]
@dstillman Would a PR for at least the `shortDOI:` extraction from Extra be welcome?

**Comment by dstillman** [comment]
Sure. I'm holding off on most of this because field (and Extra) handling is changing pretty dramatically soon, but if you want to add that now — I think around [here](https://github.com/zotero/zotero/blob/75712ed42d535743e05f7a571557f3160a0249b8/chrome/content/zotero/xpcom/cite.js#L637-L652), similar to the `export.citePaperJournalArticleURL` conditional — that'd be fine.

**Comment by retorquere** [comment]
Anything I should know about dramatic changes to field handling?

**Comment by bwiernik** [comment]
@dstillman I tried to add a command there to pull out shortDOI and replace DOI in the cslItem object. When I tried to test it by replacing cite.js inside the zotero.jar archive for my Zotero installation, no changes I made lead to any changes in Zotero's behavior. Is there an extra step I need to take to get the installed Zotero program to respect manual program file changes (I'm working on Windows)? Sorry for the ignorant question.

**Comment by dstillman** [comment]
It's possible there's some caching going on. I'm afraid I wouldn't recommend modifying the program files directly, and I've just removed the old Modifying Zotero Files page, which was many years old and about the Firefox extension.

The way to do this is really to [run a source install](https://www.zotero.org/support/dev/client_coding/building_the_standalone_client), but the steps for that are fairly involved, particularly on Windows. I'm hoping to simplify the build process soon, but in the meantime, if you want to just share what you have for this, I can test it and tweak it if necessary.

**Comment by bwiernik** [comment]
I submitted a PR. Sorry for the delay on this.

**Comment by bwiernik** [comment]
With shortDOI being deprecated, the remaining pieces that might be incorporated into Zotero proper would be retrieving DOIs for items that don't have them and verifying that stored DOIs are valid. These could perhaps be incorporated into an update metadata function?
