### ISSUE TITLE
Detect existing retracted items in documents

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1703]
The retraction functionality so far will detect retracted items in your library and warn you before citing one of those, but it doesn't help if you already have a retracted item in your document — and, since it encourages you to delete retracted items, risks orphaning those items in your document.

When refreshing a document, for each item that's retracted (see Checking Items below), scroll to the citation and show an alert:

```
Warning

A citation in your document has been retracted:

{{ bib entry }}

{{ if item is in library, add retraction.citeWarning.text2,
  but no view button because we're in a loop }}

[ ] Don’t warn me about this citation again

[ OK ]
```

If they check the box, add a flag to the citation metadata indicating that the item shouldn't be checked or alerted on again. If they don't, we'll just show the same alert on the next refresh.

## Checking Items

If the item is in the library (including the trash), use `Zotero.Retractions.isRetracted(item)`.

If not in the library, use `Zotero.Retractions.isRetractedData(data)`, which will optimize checking and caching fields to avoid repeated lookups. [Not yet implemented]

**Comment by dstillman** [comment]
If the same item appears more than once, only show the prompt for the first one in the loop. If the checkbox is checked and there are multiple of the same citation, mark all subsequent citations as permanently ignored.

**Comment by dstillman** [comment]
Update to the above: instead of running `async Zotero.Retractions.isRetractedData(data)` on every item, pass an array of objects to `async Zotero.Retractions.getRetractionsFromJSON(data)`, which will return an array of indexes of retracted items in the input array. (This lookup can result in an API request, so it doesn't make sense to do them individually.)

**Comment by adomasven** [comment]
I recommend to instead to make `Zotero.Retractions.isRetractedData()` synchronous and immediately return a boolean, and also potentially issue async actions in the background. We don't want citing to be slowed down by network requests, especially since not everyone using Zotero is on a good network.
