### ISSUE TITLE
Integration error in macOS 10.15

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1708]
https://forums.zotero.org/discussion/78042/update-to-catalina-or-anything-else-causes-zotero-integration-error

(I haven't tested this.)

**Comment by adomasven** [comment]
I can see the error but cannot really do any testing since script editor hangs on launch right now and makes it impossible to do any proper debugging. Based on where the error is coming though I would imagine this is a temporary bug in the OS itself.

**Comment by adomasven** [comment]
Solved after a macOS beta update
