### ISSUE TITLE
Retracted item citation warning changes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1710]
https://forums.zotero.org/discussion/comment/335113/#Comment_335113

1) The "Don’t warn me about this citation again" checkbox only works when pressing Refresh, not when the warning appears in response to Add/Edit Citation (presumably because we don't actually update the original citation in that case).

2) If you insert an item that's already retracted and click through the warning, we're continuing to show the warning when you reselect that item (e.g., from the Cited section). We either shouldn't do that (on the grounds that you chose to insert the item, which is a more active choice than just continuing with a newly detected item that was already in you paper) or we should have the same checkbox in that dialog (on the grounds that people always like to be able to click through things and deal with them later). Probably the latter?

There's also a discussion in that thread about items that are retracted and replaced with the same DOI, which may necessitate an option to mark some items with the "Retract and Replace" tag as no longer retracted. That will require an additional flag in the database to mean "this item shouldn't be shown as retracted anymore", and we could theoretically store another flag that's triggered by this checkbox that means "this item should still be shown as retracted in the item pane but shouldn't trigger a citation warning", thereby applying it to all documents.

**Comment by adomasven** [comment]
> we could theoretically store another flag that's triggered by this checkbox that means "this item should still be shown as retracted in the item pane but shouldn't trigger a citation warning", thereby applying it to all documents.

So in terms of UI, how would an user go about marking an item to not cause warning in any of the documents, given that a warning can either be triggered from either attempting to cite a retracted item, or when receiving a warning for an existing item?

**Comment by dstillman** [comment]
I think I'm suggesting we'd just add the "Don't warn me about this citation again" to the former, and in either dialog that would now just stop all future warnings in any documents. Or is there something else you mean?

For DB items, we could add a `Retractions.disableCitationWarningsForItem(item)` and use an `isRetractedWithCitationWarning()` instead of `isRetracted()`.

For embedded items, I guess `Retractions.disableCitationWarningsForJSON(jsonItem)`? And since `getRetractionsFromJSON()` is only used by integration, that can just default to checking the disabled flag?

**Comment by dstillman** [comment]
I forgot about embedded items when I suggested this above, though. Since that would require a separate storage mechanism, maybe this isn't worth it and it's enough to warn once per document. If we add the ability to disable the warning altogether for "Retract and Replace" (or journals stop this bad practice), that would deal with those cases, and the only ones left would be people who regularly cite genuinely retracted items in multiple documents. Once this checkbox is working properly, checking it once per document isn't really that onerous.

**Comment by dstillman** [comment]
(I actually suggested tying the checkbox to global state mainly because I thought it might make things easier for you in terms of fixing the above bugs, since you wouldn't have to rely on a flag in the document. But if you can fix those easily enough some other way, we could probably not bother, at least until people start complaining that they regularly cite genuinely retracted items and are tired of clicking through the warning.)

**Comment by adomasven** [comment]
Stopping all warnings in a document without storing anything in the db is easy in terms of integration changes. We could do a global block of retraction warnings for a citation and store a flag in the db, although I am not sure that's necessary. If we're happy with that I'll just add some checkboxes to the warnings.

**Comment by dstillman** [comment]
OK, let's just keep it per-document for now, then.

There's only one checkbox to add, right? To the retracted-in-the-DB-but-not-yet-added-to-the-document warning?
