### ISSUE TITLE
Scaffold: Return false from detectWeb button if target doesn't match

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1728]
Currently if you click the detectWeb button it runs detection even when the target doesn't match, which is confusing and error-prone.

Is there any reason not to have the detectWeb test the target first?

/cc @zuphilip, @adam3smith

**Comment by dstillman** [comment]
(This came up because I was testing https://github.com/zotero/translators/pull/1993 and couldn't figure out why it was still returning `computerProgram` on all pages, even though the PR changed the target.)

**Comment by adam3smith** [comment]
Yes that'd be quite useful imo

**Comment by zuphilip** [comment]
I agree, that this is a good idea and I thought that it was noted before somewhere. However, I could only found https://github.com/zotero/scaffold/pull/17 which seems to be a little different (but maybe useful as well).
