### ISSUE TITLE
Remove 'yesterday'/'today'/'tomorrow' parsing from strToDate()

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1749]
I don't think these ever actually belonged there, as evidenced by https://github.com/zotero/zotero/commit/d500b50e2e86c707a3c704505cffb644ceac17b2. These values just need to be converted on input and stored as regular dates.

We can also take out parsing of 'tomorrow' altogether.

**Comment by pagiraud** [comment]
I don't know if it's related but I noticed yesterday that writing "today", "yesterday" or "tomorrow" in Date accessed field doesn't do anything anymore. Writing "now" works fine however. Should I open a new issue for that ?

**Comment by dstillman** [comment]
@pagiraud: Fixed in https://github.com/zotero/zotero/commit/0b9f463b9f1a7bf5d59a7ce5fa00a97f5ea019d9 — thanks.
