### ISSUE TITLE
Deploy zotero on a remote server

### ISSUE THREAD

**Issue by JACKHAHA363** [zotero/zotero#1750]
Hi, I am thinking about setting up a remote server and deploy zotero on it. I would like to have my browser plugin being able to save to that server.

**Comment by dstillman** [comment]
Not quite sure what you mean here, but all support questions and feature requests should go to the [Zotero Forums](https://forums.zotero.org).

**Comment by Hugo-Trentesaux** [comment]
I opened an issue on zotero server repo to discuss the self hosting process: https://github.com/zotero/dataserver/issues/105
