### ISSUE TITLE
Incorrect export of "month" field to .bib

### ISSUE THREAD

**Issue by nicoinn** [zotero/zotero#1755]
When exporting a bibliography to .bib, all the fields are (correctly) wrapped into "{}" except month, i.e. one gets

```month = oct, ```

This causes issues with some parsers (for example bibtexparser for Python).

For coherence and maximum compatibility, month should be wrapped in curly brackets like every other field, i.e. it should be 

```month = {oct}, ```

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums at https://forums.zotero.org, where we're best able to help.
