### ISSUE TITLE
Is there possible to edit journal abbreviation manually

### ISSUE THREAD

**Issue by isfish** [zotero/zotero#1768]
Hi, 
I am new to Zotero, and one of my question is there possible to edit journal manually **via a term list** (which is similar to term lists in EndNote), because I found some journal don't have any abbreviation when I import PDF into Zotero and using the automatic PDF handling process. (maybe I can get the abbreviation by other importing methods, however, I have many PDF files now, it seems inconvenience to do that expect importing PDF ).
For example. when I imported a article published on Applied Catalysis B: Environmental, the abbreviation should be **Appl. Catal. B: Environ.** in the Journal Abbreviation field of Info Tab. However, things did not happen, it stills shown as the full name of the journal, i.e. Applied Catalsis B: Environmental. So I'd like to know is there any way to edit it **via a termlist** just like the similar function in EndNote? IF it has, please tell how to do it. Thank you!

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums at https://forums.zotero.org.
