### ISSUE TITLE
No longer possible to type a page number before making selection in Quick Format

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1774]
Regression from the fix to #1771 — it's now possible to type "p.123" or "p123" *after* making a selection (which is the [documented approach](https://www.zotero.org/support/word_processor_plugin_usage#customizing_cites)), but it used to be possible to type "smith 123", "smith p123", "smith p.123", or "smith:123" before making a selection and have the page number parsed out of the search query and still be able to make a selection based on "smith".

Because of https://github.com/zotero/zotero/issues/1770, "smith 123" maybe shouldn't work anymore, but the others still should. (Since actually searching by numbers should be pretty rare, we could consider treating a number after another search term as a page number, but maybe that's not necessary.)

**Comment by adomasven** [comment]
So to document fully the behaviour going forwards:

1. When the dialog is empty
    1. Typing "smith" will issue a search
    1. Typing "2009" will issue a search
    1. Typing "smith123", "smith:123", "smithp123", "smith p123", "smith 123" and all these permutations with "," following "smith" (e.g. "smith,123") will issue a search for "smith" and once the selection is made will add an item like "Smith, 2009, p. 123"
1. When the dialog has an item "Smith, 2009"
    1. Typing "p123", ":123", "p.123", "p 123" will set locator "p. 123" to the previous item
    1. Otherwise (1) applies
1. When the dialog has an item "Smith, 2009, p. 123" (i.e. an item with a locator)
    1. Typing "456" will append that number to the locator making it "p. 123456". **Note: impossible to search by number**
    1. Otherwise (2) applies. **Note: (2.i) will replace the current locator with a newly typed one**
