### ISSUE TITLE
Editing CSL style to remove comma after et al. when author in text is outside parentheses

### ISSUE THREAD

**Issue by alycja** [zotero/zotero#1775]
I edited Harvard1 style and added comma after each et al. in text.
(Author et al., year)

 However, comma after et al. when author in text is outside parentheses is something I do not want. 
Right now I have:
Author et al., (year)
and I would like that comma removed but I do not know how to fix it.

Also, I tried to italicize et al in text with no luck... in CSL editor it seems to work but when I apply it in my doc, it does not work. I use Qiqqa in cite.

I am attaching original "harvard1" CSL style and "MYstyle" that has some modifications (such as added comma and italicized et al that did not work):
[harvard1.docx](https://github.com/zotero/zotero/files/4054458/harvard1.docx)
[MYstyle.docx](https://github.com/zotero/zotero/files/4054460/MYstyle.docx)

Thank you very much!

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums at https://forums.zotero.org, where we're best able to help.
