### ISSUE TITLE
p123 should add page number to last citation by default when editing a citation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1783]
https://forums.zotero.org/discussion/comment/348374/#Comment_348374

Currently if you edit a citation, "p123" doesn't work unless you first press the left/right arrow keys. We should special-case it so that when you first open the quick format dialog, it considers the citation to the left of the cursor the active citation for "p123" purposes. As after left/right, "123" should remain a search.

**Comment by adomasven** [comment]
Closed with https://github.com/zotero/zotero/commit/43a38d31a7f51b2e25f3281f65c8c540cc9a2f7f
