### ISSUE TITLE
Unconventional Drag Behavior

### ISSUE THREAD

**Issue by raviteja-bhupatiraju** [zotero/zotero#1789]
When a PDF in a citation is selected, dragging in the white space of the publication list (middle pane) causes the file to be orphaned out of the citation. This is unintuitive behavior and has repeatedly caused issues for me.

Interestingly, this does not happen for HTML Snaphots, but does happen to other attachments in citations.

Please disable this drag behavior from this, shall we say, no citation's land? Dragging here should remove focus from the selected attachment, not move selected item.

Thanks.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
