### ISSUE TITLE
Right to Left languages (eg. Hebrew, Arabic, Persian)

### ISSUE THREAD

**Issue by benie01** [zotero/zotero#1791]
It's a pity that Zotero does not adequately support documents in RTL languages . Currently, when Zotero imports a RTL language document it hides 21 of the 27 fields normally displayed on the "Info" tab. I cannot even fill in the author(s) names!! Why not display all info fields, including blank ones, and let the user fill them in if he/she so wishes? When I used Mendeley (before deciding to ditch it over the encryption issue) this is what I did; Except for the document title that appeared in its native RTL language, I manually filled in all other relevant info fields in English. Currently Zotero is unfortunately useless for my purposes (cataloging documents, many of which are in a RTL language). Zotero developers: please consider this. Thank you.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Post to the Zotero Forums and link to a screenshot that shows what you're seeing. What you're describing just sounds like a bug.
