### ISSUE TITLE
WebDav Windows client?

### ISSUE THREAD

**Issue by Dextroz** [zotero/zotero#1797]
Is it possible to sync files using WebDav with the Windows client? Heading to the sync tab there is only the option to use Zotero's own servers.

Is WebDav only supported on the MacOS client?

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Please post support questions to the [Zotero Forums](https://forums.zotero.org), where we're best able to help.

WebDAV is always an option for file syncing in the preferences for My Library. Data syncing only happens via Zotero servers.
