### ISSUE TITLE
Import documents folder

### ISSUE THREAD

**Issue by cdcseacave** [zotero/zotero#1800]
New Feature: Zotero looks as what I need to manage my collection of papers. However I have already a collection of papers stored as PDF in folders per category. In order to start using Zotero I need first to import my existing papers I organized for years. For this it would be of great help an import functionality that parses all papers, read title/authors, search the web for the full Bib, and create new items in Zotero. Would this be doable any time soon?

**Comment by adomasven** [comment]
Zotero does not use GitHub Issues for bug reports or feature requests. Please post all such requests to the [Zotero Forums](https://forums.zotero.org).
