### ISSUE TITLE
Detect broken links

### ISSUE THREAD

**Issue by coffeemug13** [zotero/zotero#1805]
With the time the URLs of a library start to brake. It would be a nice feature scan the library for broken links, either because the website doesn't exist anymore or the endpoint changed. 

How should it work on Desktop:
- e.g. once per week/month scan all URLs from Desktop Installation and check whether they still exists and don't get 404. 
- articles with broken links are shown in a dedicated collection "broken links"
- to avoid missuse, restrict a manuall start of the whole library e.g. once per day

Cloud Version:
This could be also a nice feature for paid accounts, e.g. it's very likely that several independent libraries use the same URL. So if one URL in one library is broken, the others are also. With one crawl in the cloud you can mark all broken links in the library.
Benefit: If someon fixes one URL after detect as broken, you could suggest to the others this new URL (via Sync), (e.g. if everybody can reach it from internet -> security)

Thanks

**Comment by SuperKogito** [comment]
If I may, I would like to suggest using [urlchecker-python](https://github.com/urlstechie/urlchecker-python) or the [urlchecker-action](https://github.com/urlstechie/urlchecker-action) to detect broken links in all type of scripts (.md, .py, .js etc.).

**Comment by coffeemug13** [comment]
This request is about a tool-internal option. Most researchers using zotero are not script kiddies, so an external solution won‘t do it

**Comment by dstillman** [comment]
I think this would be more appropriate for a plugin.

(Please post further feature requests to the Zotero Forums. See [CONTRIBUTING](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md).)
