### ISSUE TITLE
How to use local cookies to get HTTP request for plugin when adding new item?

### ISSUE THREAD

**Issue by zhangchenkai** [zotero/zotero#1809]
I'm writing a plugin which needs to access google scholar when you add a new item from chrome extension.
I noticed some plugin would to using Notifier to set event callback, and I also did the same.
```
// Register the callback in Zotero as an item observer
let notifierID = Zotero.Notifier.registerObserver(XXX.notifierCallback, ['item']);
```
However, when I adding new item from webpage by browser extension, the log output warning me that cookies are not used:
> (3)(+0000001): Notifier.trigger('add', 'item', [1278,1279], {"1278":{},"1279":{}}) called [observers: 14]
> (3)(+0000004):  XXX start to GET https://scholar.google.com/xxx 
> (5)(+0000023): CookieSandbox: Being paranoid about channel for scholar.google.com
> (5)(+0000000): CookieSandbox: No Set-Cookie header received for scholar.google.com
> (3)(+0000004):  XXX got reCAPTCHA validation

**And without cookies google scholar will always popup reCAPTCHA validation due to the network problem in my country.**

But when I use menu click way to run my plugin, it could use Zotero's cookies, which stored previous captcha validation state, and send my request successfully.
```
// Add event listener to Zotero
window.addEventListener('load', function(e) {
  Zotero.XXX.init();
}, false);

// Using XMLHttpRequest to send request
let xhr = new XMLHttpRequest();
xhr.open('GET', url, true);
...
```

Based on the above situation, I speculate that Notifier-observer and Event-listener will provide the plugin with different running context. 
So I want to know: 
1. how to use Zotero local cookies even if I use Notifier-observer?
2. how to run the plugin automatically after the item-adding process totally done?

**Comment by dstillman** [comment]
Please post technical questions to <a href="https://groups.google.com/group/zotero-dev">zotero-dev</a>.
