### ISSUE TITLE
Update application icon to match the new website flat design?

### ISSUE THREAD

**Issue by tholop** [zotero/zotero#1813]
The current application icon ([here in the code](https://github.com/zotero/zotero/blob/master/chrome/skin/default/zotero/zotero-new-z-48px.png)) does not match the design of Zotero as introduced on the website [zotero.org/](https://www.zotero.org/).

- App icon: ![app](https://raw.githubusercontent.com/zotero/zotero/master/chrome/skin/default/zotero/zotero-new-z-48px.png)
- Website logo: ![website](https://www.zotero.org/static/images/bs4theme/zotero-logo.1519312231.svg)

I personally like the look and feel of the website, and it could be nice to make the application icon as fresh. Is there any plan for updating the application icon, or should we just consider that the design of [zotero.org/](https://www.zotero.org/) is not correlated with the design of the application?

**Comment by dstillman** [comment]
See [CONTRIBUTING](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md). All enhancements requests should be posted to the [Zotero Forums](https://forums.zotero.org).

We'll change the app icon at some point, but it's low on our list of design priorities at this time. (Note, too, that what you linked to isn't the actual app icon file. The real app icon is much higher resolution where supported (e.g., the Mac Dock).)
