### ISSUE TITLE
Can titles be displayed in two lines?

### ISSUE THREAD

**Issue by Cozyzheng** [zotero/zotero#1826]
Can titles be displayed in two lines?

I turned from Mendeley, because title is displayed in two lines in Mendeley, while Zotero can only display one line, so the title is omitted a lot, and it's a little strange (the computer screen is 13 inches). Are there any plug-ins or solutions?

Thanks a lot!

**Comment by adomasven** [comment]
See [CONTRIBUTING](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md). All enhancements requests should be posted to the [Zotero Forums](https://forums.zotero.org).

We are currently limited by the UI tree element used to display items but we will be updating the UI element very soon which might allow us or a plugin to do something like that.
