### ISSUE TITLE
There is no “DOI” in item Book Section and no “supervisor” in Thesis. 

### ISSUE THREAD

**Issue by S-Kee** [zotero/zotero#1872]
As the title says，there is no “DOI” in item Book Section and no “supervisor” in Thesis. Many conference papers are presented in the collection of papers, that is, the chapters or book section, which also have DOI. Now, the items that are not included are uniformly displayed in "extra", which is not in conformity with the requirements of many journals. I hope it can be improved.It would be great if it could be repaired

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Please post all bug reports or feature requests to the [Zotero Forums](https://forums.zotero.org).

Zotero item types and fields have been frozen for years for technical reasons, but you can enter a DOI in the Extra field as "DOI: 10.123/abc" and it will be used in bibliographies as necessary. Fields in Extra will automatically be moved to real fields once they're available.
