### ISSUE TITLE
SingleFile: Remove 'crossorigin' property on stylesheets

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1893]
Explanation at https://forums.zotero.org/discussion/85579/bug-report-katex-macros-not-displaying-correctly-in-5-0-91-beta. We should also think about whether there might be other attributes that cause CORS errors for us but wouldn't for native SingleFile/SingleFileZ.

**Comment by fletcherhaz** [comment]
[https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin](url) shows this attribute is valid for `<audio>, <img>, <link>, <script>, and <video>`. Currently, we remove audio, video, and script, but both img and link will be issues for us.

@dstillman I'm inclined to simply remove this attribute for both those two tags if that sounds good to you?

**Comment by dstillman** [comment]
That sounds right.
