### ISSUE TITLE
SingleFile: CSP blocks resource download when saving snapshots in client

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1895]
https://forums.zotero.org/discussion/85583/bug-report-longstanding-problem-with-github-snapshots

Error console shows these for all the failed images, and they have no content in `pageData.resources`:

> [JavaScript Error: "Content Security Policy: The page’s settings blocked the loading of a resource at https://avatars0.githubusercontent.com/u/20201?s=48&v=4 (“connect-src”)."]

I'm not sure why this isn't using our background fetch to circumvent CSP the same way we circumvent CORS.

**Comment by fletcherhaz** [comment]
Where are you seeing that console message. In the connector or client console? In the client, those messages are logged because we try and use the normal fetch first, which throws an error (and is logged) before trying to use the background fetch.

When I save the github page the only thing wrong that I see is the same as #1893, namely that `crossorigin=anonymous` is preventing the loading of the stylesheets.

**Comment by dstillman** [comment]
Sorry, I was on a pre-SingleFile connector build on this machine, which is why this is about saving in the client. (The OP is presumably just referring to the stylesheet issue, so that will be covered by #1893.)

When saving in the client, the CSP messages are logged to the Error Console and a bunch of images actually fail to load, with "Error saving resource:" debug messages. Doesn't matter for this page, but would matter for other cases of client-based saves, so we should figure it out.

**Comment by fletcherhaz** [comment]
I can't replicate this with [https://github.com/danluu/post-mortems/blob/master/README.md](url). When saving in the client, the messages are logged to the Error Console, but the background fetch works correctly and all the images appear. I see no "Error saving resource:" debug messages either. Possibly the client did not have the CORS fix from last week?

**Comment by dstillman** [comment]
Can no longer reproduce
