### ISSUE TITLE
SingleFile: Patch setTimeout() → window.setTimeout() and similar after recent update

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1908]
See daefc9c0aeea473851b9c4be8f6abd690b680f93

No rush (and we probably should wait, because the code could change), but we'll need to do this the next time we upgrade SingleFile.

**Comment by fletcherhaz** [comment]
Looks like that has already been changed in SingleFile (https://github.com/zotero/zotero/commit/daefc9c0aeea473851b9c4be8f6abd690b680f93#commitcomment-43543850)[url] so this will be a non-issue next time we pull in SingleFile and can probably be closed.

**Comment by dstillman** [comment]
Yep, working now. I'll leave this open to see if we can fix this more generally on our end.
