### ISSUE TITLE
Switch to Ace editor in Run JavaScript window

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1928]
We use Ace in Scaffold (Translator Editor). We should abstract that out as necessary so that we can use it from the Run JavaScript window too (in advance of [more features in that window](https://forums.zotero.org/discussion/76808/feature-request-more-options-for-the-javascript-runner/p1).

**Comment by fletcherhaz** [comment]
What kind of abstraction were you envisioning? Currently the ace editor is pretty easy to include with `scaffold/ace.html` as an iframe. Given that the only extra lines are situation specific I'm not sure how much there is to be gained from further abstraction. Unless you want to move the files out of the scaffold directory? Then we just need to rework the imports.

**Comment by dstillman** [comment]
Yeah if it's just as simple as moving it out of that directory, that's fine. I wasn't sure how closely it was tied to the Scaffold code. And I assume we'll want some slightly different configuration options here, but we can figure those out as we go.
