### ISSUE TITLE
creating a new Source-Type within a citation-Style

### ISSUE THREAD

**Issue by yasmin6314** [zotero/zotero#1931]
Hello

I have been using Zotero for many years and have come to love this program, thank you very much!

For the paper I am currently working on, I have to quote monographs from the European Pharmacopeia. To do this, we are required to cite them in a very specific manner. Therefore, it would be very helpful if I could add a new Source-Typ "Monograph" into the citation Style IEEE, which I am using for the rest of my paper. Is something like this possible?

Thank you for your help and merry Christmas
Yasmin

**Comment by dstillman** [comment]
Please post support questions to the [Zotero Forums](https://forums.zotero.org), where we're best able to help.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
