### ISSUE TITLE
while typing, new line of text will disappear and cursor will jump to very top of the notes section

### ISSUE THREAD

**Issue by MrPeeWeeMailMan** [zotero/zotero#1960]
While typing, the new line of text will unexpectedly disappear and the cursor will reappear at the beginning of the previously written text in the notes section of Zotero. This does not happen if I hit enter, to make a new line, and then backspace to return the cursor to it previous position - doing this operation seems to "protect" or "preserve" the text from this glitch. 

HELP!

**Comment by dstillman** [comment]
Please post support questions to the [Zotero Forums](https://forums.zotero.org), where we're best able to help. See <a href="https://www.zotero.org/support/zotero_support">How Zotero Support Works</a> for more information.
