### ISSUE TITLE
If I accidentally delete a category, how can I retrieve or restore it?

### ISSUE THREAD

**Issue by weizhenz96** [zotero/zotero#1968]
If I accidentally delete a category (分类文件夹), how can I retrieve or restore it (找回恢复)?

Can you add this feature into the Recycle Bin (回收站)?

**Comment by dstillman** [comment]
Please post support questions to the [Zotero Forums](https://forums.zotero.org), where we're best able to help. See [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

You can likely restore an accidentally deleted collection from one of the <a href="https://www.zotero.org/support/zotero_data#restoring_from_the_last_automatic_backup">last automatic backups</a>. Post to the forums if you need help with that.

The ability to restore collections from the trash is in development.
