### ISSUE TITLE
Zotero 5.0 release/tag issue

### ISSUE THREAD

**Issue by qqobb** [zotero/zotero#1970]
Just in case you didn't notice this yet, there's currently an issue with the GitHub releases. 

Tag 5.0 disappeared, 5.0.0 has been created after 5.0.96.1.

https://github.com/zotero/zotero/releases?after=5.0.3
https://github.com/bwiernik/zotero/releases?after=5.0.3

(I've read the issue guidelines, but I thought it's appropriate to post here in this case.)

**Comment by dstillman** [comment]
Yes, thanks, we renamed the 5.0 tag to 5.0.0 in order to create a 5.0 branch.

**Comment by dstillman** [comment]
(Hopefully @retorquere, @fbennett, and other package maintainers aren't just pulling the latest tag by date…)

**Comment by retorquere** [comment]
I'm looking at https://www.zotero.org/download/client/manifests/release/updates-linux-x86_64.json
