### ISSUE TITLE
Auto-convert additional Markdown syntax

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1975]
https://forums.zotero.org/discussion/comment/376758/#Comment_376758

E.g., "#" at the beginning of a line plus a space could convert to a header. Similar to what we do for blockquote and lists.

`**foo**` is arguably more work than `Cmd-B` but some people are used it

**Comment by bwiernik** [comment]
The ones that would be most useful for my workflows are:

1. `**bold**` and `*italic*` (perhaps `***bold-italic***` for completeness); I'm used to typing using asterisks for this
2. <code>\`code\`</code>
3. `[links](https://example.com)`

**Comment by nixsee** [comment]
I'd love this too!

**Comment by mrtcode** [comment]
All mentioned conversion rules are already implemented. See the list [here](https://github.com/zotero/zotero/issues/1976#issuecomment-877072198).
