### ISSUE TITLE
PDF reader: Context menu to copy text

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1978]
https://forums.zotero.org/discussion/comment/376837/#Comment_376837

**Comment by bjohas** [comment]
That would be really helpful for adding metadata to the metadata pane.

An alternative might be to introduce a text-select tool (as an additional tool), but I really don't mind what the solution is.

**Comment by mrtcode** [comment]
We already have a popup that appears on text selection. The question is whether the copy option should be in the popup (we had that in one of the variations) or in a context menu when right-clicked on the selection (just a single option?).

**Comment by dstillman** [comment]
Someone in the forums also requested a menu option to search Google for the selected text, but that would mean getting into search engine options, and I can’t imagine we want to deal with that when you can just copy and paste into your browser…

Not sure if there’s a thing else. (If we did show a context menu, we’d show the standard editMenuOverlay version with Cut/Paste grayed out, so it wouldn’t be totally empty.)

But I guess it’s a little weird to support right-click if there’s already something on select. Copy in the select popup feels a bit web-y and non-standard, but maybe the best option.

**Comment by dstillman** [comment]
> It happens for selected annotations (when sidebar is closed). So I guess hiding text selection popup and showing a context menu isn't that bad.

Yeah, we do it for annotations in notes, too (without even hiding the popup, currently).

> Although always disabled Cut/Paste feels quite redundant.

I was actually misremembering what other apps did here — it seems like plenty of apps don't show Cut/Paste grayed out for read-only content. A single-option popup would be bad, but we can add some general options that always appear in the context menu — annotation tools, zoom, other things from the toolbar or menus — and then when Copy is appropriate it just gets added to that. E.g., here's Preview without a selection and with a selection:

![preview-no-selection](https://user-images.githubusercontent.com/783082/110571676-e9ba3600-8125-11eb-8e3d-4a9dfa528246.png)

![preview-selection](https://user-images.githubusercontent.com/783082/110571690-ecb52680-8125-11eb-9492-dfd6fb12facc.png)

A few zoom options and Next/Preview Page would be enough to start.
