### ISSUE TITLE
Don't include quotation marks when copying text from PDF

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1987]
https://forums.zotero.org/discussion/comment/377210/#Comment_377210

This should only be done when pasting into a note, not when copying to the clipboard.

**Comment by mrtcode** [comment]
That applies only for text or for annotations as well? I.e. copied plain text annotations now look:

> This is comment: "This is highlighted text from a paragraph"

Buf if there is no comment it is just:

 > "This is highlighted text from a paragraph"

**Comment by dstillman** [comment]
I think just text, since that's where you're more likely to just be copying something  — a metadata value, an identifier, etc. — into some other context where a quotes aren't appropriate. Whereas a highlight is almost always a quote. A highlight also may have a comment attached that requires the text to be in a quotes, and it would be inconsistent to only add quotes when there was a comment.
