### ISSUE TITLE
Undo note auto-convert with Cmd-Z/Ctrl-Z

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1989]
https://forums.zotero.org/discussion/comment/377316/#Comment_377316

See Slack for an example — you can type `1. ` and it will auto-convert to a list, but you can Cmd-Z and it will convert back to the original entered text.

**Comment by dstillman** [comment]
This doesn't seem to be fixed. Sorry if my description was unclear.

The goal here is to be able to have character sequences in your note that would otherwise be auto-converted. So you should be able to type `1. `, have that auto-convert to a list, and then press Cmd-Z to convert that back to plain `1. `.

So there are two parts of this: 1) set an undo marker immediately before the auto-conversion (so it doesn't just erase the whole line, and possibly previous lines if you were typing quickly) and 2) undo the auto-conversion, but not the space that triggered it.

With `1. `, I'm currently seeing it delete the line. With `> `, it's reverting the converted blockquote to `>`, but without a space, so then I type a space and it just gets reconverted again.

**Comment by mrtcode** [comment]
If I understand correctly, you mean the auto-conversion doesn't work when you type more characters after the auto-conversion. If you just hit Cmd-Z immediately after the auto-conversion it successfully reverts to the typed sequence. This is behaviour that PM currently provides out of the box and other PM based projects have identical behaviour. But if that's not sufficient we can keep this issue open. That might involve more complex work with undo history.

Anyway, previously it was almost impossible to have unconverted `1. ` now it's possible, just need to press Cmd-Z at the right time.

Strange, but I can't reproduce the behaviour when reverted to `> ` but without space. I will try on macOS. Maybe all those things work somehow different there.

**Comment by dstillman** [comment]
> If you just hit Cmd-Z immediately after the auto-conversion it successfully reverts to the typed sequence.

No, that's not what I'm seeing. In no way can I revert to the typed sequence with a space after it. And in most cases I can't prevent it from just erasing the whole line.

**Comment by dstillman** [comment]
(But, yes, Tropy behaves the same for me, and it's bad. See Slack for how this should work.)
