### ISSUE TITLE
[FF upgrade needed] Down-arrow gets stuck at citation in note / clicking white-space next to citation selects the citation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1990]
https://forums.zotero.org/discussion/comment/377316/#Comment_377316

> When browsing through notes with down arrow key, the cursor gets stuck at a citation right before the first parenthesis. You get past the citation with right arrow key, but this isn't an intuitive solution.

**Comment by mrtcode** [comment]
Both issues are closely related and only happen for wrapped citations. So it's basically a Firefox `contenteditable` bug/nuance that no longer appears in further Firefox versions (tested on FF 66 and the latest version).

To properly fix/work around this, it might be very time consuming, but if this gets too annoying, until we upgrade to a newer FF, possible options would involve avoiding wrapping citations at white spaces and always inserting white space after citation.

**Comment by mrtcode** [comment]
Already fixed by upgrading Firefox.
