### ISSUE TITLE
Return/Enter should go to the next search match in notes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1992]
https://forums.zotero.org/discussion/comment/377322/#Comment_377322

And Shift-Enter should be equivalent to Prev.

**Comment by mrtcode** [comment]
https://forums.zotero.org/discussion/95553/note-searchbar

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/96956/unintuitive-note-search-behavior

**Comment by mrtcode** [comment]
Fixed in zotero/note-editor@4951aa31.
