### ISSUE TITLE
PDF reader: Back/Forward navigation buttons

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1997]
https://forums.zotero.org/discussion/comment/377403/#Comment_377403

> Add next and previous "view" buttons. This would be a great feature and is found in other pdf readers. Say you are in a place in the document and use a hyperlink to a figure appendix many pages below the current one. The back button, similar to the browser's one, takes you to the previous view. It would also work for scrolling with the wheel and page u/d keypresses, discarding those intermediate ones in a rapid succession of events. The best implementation that I know of this is that of the PDF-Xchange Viewer/Editor. It stores internally a list of x, y and zoom coords of all the views.

> These buttons are included for a long time in the Acrobat Reader. If you skip to a reference or to a figure, with these buttons you can always go back to the point you were reading. 

I don't know if we want to do this, but I could see it being useful.

In our case I suppose it would also work for getting back to a previous position after clicking on an annotation in the sidebar.

I'm not sure would happen when you used search and skipped through pages that way. Would each search result you stopped on create a history entry?

**Comment by dstillman** [comment]
OK, after trying a PDF with links, this actually seems pretty important. And Preview does support it, which I didn't realize — it has both `Cmd-[`/`Cmd-]` and buttons you can add to the toolbar.

The straightforward things here would be 1) links, 2) sidebar thumbnail clicks, and 3) annotation/citation clicks (from sidebar and elsewhere), with these all adding a navigation entry for the previous page position. Trying to do this for scrolling/search seems much more complicated, and I think we can ignore that for now (as Preview seems to).

**Comment by mrtcode** [comment]
I think we shouldn't add this to toolbar as it would clutter it even more. Instead, those options could go into context menu and/or menu bar.

**Comment by qqobb** [comment]
In most PDF viewers, Alt+Left brings you back to the previous view. This is just as in a browser, at least on Windows. PDF.js seems to be relying on the browser history, see https://github.com/mozilla/pdf.js/issues/10360.

**Comment by qqobb** [comment]
See also here: https://github.com/mozilla/pdf.js/pull/2921.

**Comment by mrtcode** [comment]
Navigation now works with `Cmd-[` / `Cmd-]` (or `Ctrl-[` / `Ctrl-]`).

**Comment by dstillman** [comment]
It seems this isn't creating a history entry for each annotation click?

I have three annotations on the first page of a PDF. If I click on the three annotations in succession, I would expect that Back would take me to the position of each previous annotation, even on the same page. Instead it seems to be skipping the two previous annotation clicks and just taking me to the page I was on before the first annotation click.

(I might expect the previous annotation to actually be selected in the sidebar when I go back, but that's more complicated, because what if you click on an annotation and then scroll a bit?)

**Comment by mrtcode** [comment]
Yeah, if it's on the same page, it doesn't pollute the history stack. I'm not sure we need that. Partially because annotations positioning is far from perfect anyway.

I think let's keep it as it is for now, without introducing additional complexity.

We also need to figure out where to put the buttons.

**Comment by dstillman** [comment]
Something still isn't quite right about this. I'm clicking annotations on pages 1, 2, and 3. If I then press Back twice, I would expect it to go to 2 and then 1, and then Forward to go to 2 and then 3. I'm not quite sure what's happening now, but it's not that.

**Comment by dstillman** [comment]
Or, sometimes it is, but sometimes it isn't. It seems like some actions just aren't properly triggering history entries — and maybe the same-page ignoring is contributing to that.

**Comment by mrtcode** [comment]
Well, PDF.js has something like debounce here. When you are just quickly testing things it probably looks like a bug, but when you are like normally reading PDF, this might be useful to not pollute the history.

**Comment by mrtcode** [comment]
Ok, I see some strange behaviour here. I will try to do a few fixes.

**Comment by mrtcode** [comment]
Each annotation now leaves a separate history record.

I agree, sometimes it feels that annotation should also be selected when navigating, but sometimes it can be annoying and become messy.

Also we can consider to add additional keyboard shortcuts for different OSes. I.e. we can have the same shortcuts as [FF](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) has for website back/forward navigation.

**Comment by dstillman** [comment]
Yeah, it seems like people will expect Alt-Left-Arrow and Alt-Right-Arrow (and I guess Cmd-Left/Cmd-Right on macOS) to work here. I think people were saying that's what Acrobat does?

**Comment by mrtcode** [comment]
Yeah, Acrobat Reader uses Alt/Cmd + Left/Right arrow keys (depending on the platform).

**Comment by dstillman** [comment]
We're getting a decent number of questions about this, so we should expose these as menu options, showing the most common shortcut per platform.

**Comment by mrtcode** [comment]
We can introduce `Navigation/Go` menu (although that makes menu bar different from the library tab) with back/forward options and also move `Go to First/Last page` options from `View` menu, or do the opposite and have everything in `View` menu. But, normally, navigation shouldn't be in `View` menu.

**Comment by dstillman** [comment]
Preview's Go menu is a good example here.

Changing menu bar doesn't seem like a problem.

**Comment by deklanw** [comment]
On Windows `5.0.97-beta.21+12b100fd4` the Back/Forward button on my mouse aren't working and neither are `Ctrl-[` and `Ctrl-]`

**Comment by deklanw** [comment]
@mrtcode Keyboard shortcuts are an improvement but mouse binding to Back/Forward is still missing

**Comment by sizmailov** [comment]
Having back/forward buttons would greatly improve user experience on touchscreen devices. Should we open a separate issue for this?

**Comment by flymin** [comment]
> I think we shouldn't add this to toolbar as it would clutter it even more. Instead, those options could go into context menu and/or menu bar.

Can we have the next/previous page button replaced by the back/forward ones? I really expect the latter and never use the next or previous buttons. I think I am not alone.

**Comment by VietTralala** [comment]
> @mrtcode Keyboard shortcuts are an improvement but mouse binding to Back/Forward is still missing

is there any update on this issue or a separate issue which I can subscribe to?
