### ISSUE TITLE
Toolbar not fully themed in tab mode on Linux

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1999]
https://forums.zotero.org/discussion/88089/zotero-beta-with-enabled-pdf-reader-not-fully-themed-on-linux

Not sure what the fix for this will be, since we're no longer using `-moz-appearance: toolbar` for the toolbar. (If I recall, that's what the rest of the tab bar is now, which is why it looks correct.)

**Comment by joelostblom** [comment]
I am still experiencing this issue in the Zotero 6 beta on popOS 20.10 (Gnome 40) with a dark system theme. The biggest issue for me is that the tabs are nearly impossible to read with black text on dark grey background, so most of the time I have to cycle through all open tabs until I find the one I want (screenshot below). The way the rest of the UI is themed works great since it has white text on dark grey background.

It looks like there is a fix suggested in #2013, are there any blockers for merging that or is the solution insufficient in some ways?

![image](https://user-images.githubusercontent.com/4560057/153894237-be668294-596c-48d4-98b7-e998902ea300.png)

**Comment by prototype99** [comment]
388d18d seems to be indirectly intended as a fix for this issue, however I updated to the latest beta which seems to include it and noticed no discernable change. My icon bar is dark, but I think it always was. the active tab and the column headers are still light themed. In case the icon bar issue is OS specific, I am using manjaro kde. the gtk theme is set to breath-dark. it appears that progress towards solving the issue is somewhat dependant on #2013 updating, or an alternative pull request being created

**Comment by dstillman** [comment]
No, it wasn't, which is why this is still open.

**Comment by dstillman** [comment]
(Well, it was intended to fix the column headers from the tree, but nothing else. You can confirm whether it does for you in the next beta.)

**Comment by dstillman** [comment]
The fix for the column headers is available in the latest <a href="https://www.zotero.org/support/dev_builds">Zotero beta</a>. Let us know if you're still seeing the light column headers with that.

This issue will remain open for other issues.

**Comment by 0b11001111** [comment]
Just installed the current beta (6.0.5-beta.1+bb8858569) and the issue persists

![grafik](https://user-images.githubusercontent.com/19192307/161792789-b8954c62-6848-4d04-ad5f-0fb57f33f9ed.png)

**Comment by korg91** [comment]
@dstillman Is there any update on this issue? I'm using Ubuntu 22.04 with the official dark theme, and the PDF tabs are still almost unreadable on Zotero 6.0.13:

![image](https://user-images.githubusercontent.com/3729408/186430439-812ce839-588e-4531-958c-f9d7455ec818.png)

This makes it very hard to use Zotero's built-in PDF reader. Given that Ubuntu is so popular among Linux users and I'm using one of the two official themes, I suspect that many users are affected by this issue.

**Comment by HarrisonGrodin** [comment]
It would be great if this issue were resolved. However, for a temporary fix, you can set Zotero to use a light theme.

On Ubuntu, you can edit the `Exec` line of `/usr/share/applications/zotero.desktop` to say:
```
Exec=env GTK_THEME=Yaru-blue /usr/lib/zotero/zotero --url %u
```
This launches Zotero with the (light) theme `Yaru-blue`.

**Comment by humanplayer2** [comment]
An alternative workaround is the [Zotero Night extension](https://github.com/tefkah/zotero-night). 

For it's settings to be remembered, one needs a [small manual fix](https://github.com/tefkah/zotero-night/issues/64#issuecomment-1236097028).

**Comment by FelixBrakel** [comment]
Any plans for this to be fixed in Zotero 7?

**Comment by badcodebuilder** [comment]
> You might find this workaround useful:
> 
>     1. Close Zotero.
> 
>     2. Open [your Zotero profile folder](https://www.zotero.org/support/kb/profile_directory).
> 
>     3. Inside this folder, create a sub-folder named `chrome`.
> 
>     4. Inside the folder `chrome`, create a file named `userChrome.css` with the content below.
> 
>     5. Save. Reopen Zotero and enjoy.
> 
> 
> Tested on Linux Mint 21.2 with the default dark theme.
> 
> ![Tab bar fixed](https://private-user-images.githubusercontent.com/4775490/288491029-6bcf80a0-2965-4fef-bd9b-1670d5870700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODA3MjEsIm5iZiI6MTcwMjg4MDQyMSwicGF0aCI6Ii80Nzc1NDkwLzI4ODQ5MTAyOS02YmNmODBhMC0yOTY1LTRmZWYtYmQ5Yi0xNjcwZDU4NzA3MDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDYyMDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ0YTU0Y2ExMTg3YzRmMjVlZjRjYmU5NTNiODk2YjQ0NmE3ZWQ2ZWNkZDk5NDNhZjE2ZDNiZjYxNTFmNWM1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._6HH0WNrxqXLhoZG3KkjAxPkFGaIyjkHDsusLzjGEj0)
> 
> ```css
> .tabs::before,
> .tabs::after {
> 	border-color: var(--tabs-border-color, rgba(0,0,0,.3)) !important;
> }
> 
> .tab {
> 	background: inherit !important;
> 	color: inherit !important;
> }
> #tab-bar-container .tab:not(:last-child) {
> 	border-color: var(--tabs-border-color, rgba(0,0,0,.3)) !important;
> }
> 
> #tab-bar-container .tab.selected {
> 	background: inherit !important;
> 	border-color: var(--tabs-border-color, rgba(0,0,0,.3)) !important;
> 	border-top-color: var(--tabline-color, #0a84ff) !important;
> }
> 
> #tab-bar-container .tab:not(.selected) {
> 	border-bottom-color: var(--tabs-border-color, rgba(0,0,0,.3)) !important;
> }
> 
> #tab-bar-container .tab:not(:first-child) .tab-close {
>   filter: invert(0.7);
> }
> 
> #zotero-toolbar {
> 	background: inherit !important;
> 	border-bottom: inherit !important;
> }
> ```

This solution works on Archlinux with the default dark theme, thanks a lot.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/111074/available-for-beta-testing-zotero-redesigned/p1
