### ISSUE TITLE
Better accessibility to bibliography in LibreOffice Writer (all versions)

### ISSUE THREAD

**Issue by giammi56** [zotero/zotero#2004]
After exploring the [integration of Zotero with LibreOffice](https://ask.libreoffice.org/en/question/298675/write-711-how-to-set-internal-cross-references-with-go-to-page-hyperlinks-as-automatically-done-for-a-table-of-content-on-an-exported-pdf/?answer=298726#post-id-298726), it became clear that some useful feature could be exposed to the user from implementing a simple option panel in LibreOffice.

The specific missing feature is the live hyperlink/bookmark of the references to the bibliography: the references are treated as plain text. The feature exist in LibreOffice and could be implemented in the style of the citation generated by Zotero.

[More users apparently proposed ](https://forums.zotero.org/discussion/comment/378004#Comment_378004) such feature and I strongly believe it would greatly improve the functionality of the Bibliography tool in LibreOffice.

**Comment by dstillman** [comment]
Please post all feature requests and bug reports to the forums.

https://forums.zotero.org/discussion/88370/write-7-1-1-how-to-set-internal-cross-references-with-go-to-page-hyperlinks-as-automatically-done
