### ISSUE TITLE
Tabs are broken after closing main window on macOS

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2005]
1. Open tabs
2. Close window
3. Reopen window and try to open a new tab

Similar to https://github.com/zotero/zotero/issues/1952 for extension windows

```
zotero(3)(+0000001): Notifier.trigger('open', 'file', [42028]) called [observers: 2]

zotero(3)(+0000010): Notifier.trigger('select', 'tab', [tab-QLFdbrkE], {"tab-QLFdbrkE":{"type":"reader"}}) called [observers: 5]

zotero(1)(+0000004): NS_ERROR_NOT_INITIALIZED Exception:

    [Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://zotero/content/standalone/standalone.js :: notify :: line 59"  data: no]
        notify@chrome://zotero/content/standalone/standalone.js:59:11
        Zotero.Notifier</this.trigger<@chrome://zotero/content/xpcom/notifier.js:137:38
    From previous event:
        Zotero_Tabs</this.select@chrome://zotero/content/tabs.js:208:5
        open@chrome://zotero/content/xpcom/reader.js:826:9
        ZoteroPane</this.viewPDF@chrome://zotero/content/zoteroPane.js:4307:5
        launchFile@chrome://zotero/content/zoteroPane.js:4138:11
```

**Comment by mrtcode** [comment]
It should be fixed. Although, I was programmatically reopening the main window because I was unable to do that with the keyboard shortcut. Additionally, on Linux (and probably Windows) menu bar is missing after reopening the main window. I'm wondering if anyone ever reopens it on Linux/Windows.

**Comment by dstillman** [comment]
Both Cmd-0 and clicking the Dock icon should work on macOS, but only if no other windows (e.g., Error Console) are open, if that's what you mean. (That's a longstanding Firefox issue.)
