### ISSUE TITLE
Tabs don't all close when deleting multiple PDFs

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2006]
1. Open two PDFs in separate tabs
2. Move the PDFs to the trash
3. Empty the trash

For me, one tab closes, but the other stays open, and general brokenness ensues: there are lots of errors, annotations give the appearance of being saved but actually aren't (bad!), trying to create a note results in a broken pane…

Nothing is actually saved, so there's no data corruption, but we definitely don't want to make it look like changes are being saved when they're not. (This is what I was saying previously about how ideally we would actually crash the window if saving wasn't working, though I can imagine that message passing here might make that harder.)

**Comment by mrtcode** [comment]
It was supposed to display all errors in PDF.js error bar, but at some point PDF.js renamed the function that triggers errors. The idea was to show error but still allow to copy some data. Maybe we should just display a crash message popover on the whole pdf-reader?

![Screenshot from 2021-03-17 11-20-51](https://user-images.githubusercontent.com/6362989/111444843-790dad80-8713-11eb-85e8-2b75c3f94202.png)

**Comment by mrtcode** [comment]
Now if annotation fails to be saved, a popover is shown that prevents further editing. Annotations are saved almost immediately, therefore completely blocking the pdf-reader UI shouldn't result to any significant unsaved work loss.

Other errors still get that red error bar.

![Screenshot from 2021-03-17 13-32-21](https://user-images.githubusercontent.com/6362989/111462982-c1cf6180-8727-11eb-89e1-30112aa2b72c.png)
