### ISSUE TITLE
PDF reader: Page rotation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2008]
https://forums.zotero.org/discussion/88459/pdf-reader-page-rotation-and-link-back-forward

As for state, options would 1) modify the actual file (which I don't think we want to do), 2) local state, and you just fix it on every device (probably fine), or 3) use a synced setting with all page rotations for a given PDF (probably not worth it, and maybe it doesn't always even make sense to use the same rotation on a mobile device?).

**Comment by mrtcode** [comment]
Assuming we want single page rotation here, it won't be that easy to do. The complexity of this depends on whether the new image annotations should be rendered rotated or not.

**Comment by bwiernik** [comment]
I think that modifying the actual file would be best. In nearly all cases, if a page is printed in landscape, I probably want it to be displayed in landscape?
