### ISSUE TITLE
Hide tab bar on Windows and Linux when only one tab

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2019]
https://forums.zotero.org/discussion/88440/new-tabbed-interface-absorbing-screen-real-estate

Since we can't draw in the title bar on Windows and Linux (like Firefox and Thunderbird do) unless we get rid of the menu bar, which we're not really prepared to do at this time, the tabbed window ends up taking up a lot more vertical space. (On macOS, it's only a pixel or two difference.) We should probably hide the tab bar on those platforms when there's only the library tab.

<img width="344" alt="Tab bar on Windows" src="https://user-images.githubusercontent.com/783082/112814284-230f0300-904d-11eb-9719-5d8a9aced6bb.png">

<img width="367" alt="Tab bar on Linux" src="https://user-images.githubusercontent.com/783082/112814301-26a28a00-904d-11eb-83e0-34af3173bb3c.png">

**Comment by bwiernik** [comment]
Would hiding the menu by and toggling it with Alt like Firefox does be feasible?

**Comment by jryans** [comment]
As first version, https://github.com/zotero/zotero/pull/2049 does a simple hide / show based on tab count, which actually feels fairly nice to me. I think it would be best to start with that, and then possibly extend with the Alt toggling separately if there's demand for that.

**Comment by cadadr** [comment]
If I am not missing something there seems to have been a regression here on Windows at least with Zotero 7, namely when there is a single tab open the tab bar is visible and there doesn't seem to be any way of hiding it. Is a fix for this planned?

**Comment by davidvontamar** [comment]
@cadadr, also on Linux.
