### ISSUE TITLE
Erroneous upgrade warning in note

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2024]
I'm running the latest build, but I get this when clicking on a note, even though it saved a version 2 note to the DB at that point:

![note-update-message](https://user-images.githubusercontent.com/783082/113459271-f6f3d900-93e2-11eb-99b6-9c8d8c2a0bd3.png)

I get it even after restarting.

**Comment by dstillman** [comment]
Hmm, now it went away somehow.

**Comment by mrtcode** [comment]
It can only happen when an older note-editor is loaded. Is it possible that note-editor js files were somehow cached?

**Comment by dstillman** [comment]
Yeah, it was — I also made a change to the submodule without it being reflected in the build. Not sure what was going on, but it's working now. We can keep an eye on it. Some additional logging for the submodules during building (e.g., to show when it's using remote ZIP vs. local files) might be helpful, if possible.
