### ISSUE TITLE
builds/building for "m1" apple silicon macs (macos >=11 aarch64-darwin)

### ISSUE THREAD

**Issue by 7468696e6b** [zotero/zotero#2028]
Looking for official build support and/or build instructions

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

There are no builds for Apple Silicon currently and won't be for a while, but Zotero runs fine under Rosetta 2.

**Comment by topazus** [comment]
As apple silicon processor was introduced by apple since the last year and their future product will use arm processor. do you have any plan on arm build for mac? @dstillman

**Comment by ridicolos** [comment]
I would love to see a native version.. 
sure it runs with rosetta, but emulation isn't the greatest experience you can get. Native will always be better.

**Comment by danmackinlay** [comment]
@ridicolos I believe @dstillman 's comment above is a reference to the fact that zotero does not actually use github issues but rather the more artisanal discipline of trawling the zotero. There are indeed many posts about this on the forums, e.g. https://forums.zotero.org/discussion/comment/393046#Comment_393046
