### ISSUE TITLE
PDF reader: "Show in Library" option

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2032]
It should be possible to get back to the items list with the current attachment or parent item selected. This should at least be an option in the File menu, but we may want a toolbar button or something in the item pane as well. We also discussed a right-click on the PDF tab, which I think makes sense, though it's not very discoverable.

Have to decide if all options select the parent item or if some select the attachment item itself.

**Comment by mrtcode** [comment]
This is no longer relevant. It's possible to return to parent/attachment item over File or tab menu.
