### ISSUE TITLE
PDF reader: Avoid shifting of search button on sync

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2045]
With the search button next to the sync button, the sync stop button causes the search button to shift over. We could hide that, but we have the same problem with the sync error icon, which we probably don't want to hide, so we should probably figure out a place for the search button that isn't affected by new buttons to the left of the sync button.

Not sure what the best solution is here, though one option would be to just remove the sync button from the PDF view altogether.

**Comment by mrtcode** [comment]
In the long term, all three sync-related buttons can probably be redesigned to be a single button, and maybe even moved next to tabs. But, at the moment, I can only suggest to move it between the buttons in the left side somewhere where it originally was. Although then we either need to change the icon or remove zoom in/out buttons (they could be in context menu).

Or, as you said, just remove the sync button.

**Comment by mrtcode** [comment]
Actually, when scrolling a PDF this happens every 3 seconds and is really distracting. And not only the shifting, but the rotating arrow and the appearing stop button as well. So, I guess, we should consider to remove the sync button.

**Comment by dstillman** [comment]
Yeah, let's just remove it from this view for now.
