### ISSUE TITLE
PDF reader: Support word lookup on macOS

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2057]
Word lookup on macOS (I use Cmd-Ctrl-D, but I guess it's [force click or three-finger tap](https://support.apple.com/guide/mac-help/look-up-words-mchl3983326c/mac) on a trackpad) works in our textboxes, in the new note editor, in the annotation sidebar, and even in tab titles, but it doesn't work for the PDF content itself. This is true even in Fx89 with our demo online, though the official pdf.js demo works fine.

Any idea what's causing this?

https://forums.zotero.org/discussion/comment/382772/#Comment_382772

**Comment by mrtcode** [comment]
It's because we use our own text layer and those things aren't implemented yet. The same is with #2012.
