### ISSUE TITLE
Mendely APA style: why are the cities of publication no longer reported in the inserted bibliography?

### ISSUE THREAD

**Issue by ClaudiaFredella** [zotero/zotero#2068]
**READ THIS BEFORE CREATING AN ISSUE**

Zotero does not use GitHub Issues for bug reports or feature requests.

Please post all such requests to the Zotero Forums at https://forums.zotero.org, where Zotero developers and many others can help. For confirmed bugs or agreed-upon changes, Zotero developers will create new issues in the relevant repositories.

Development questions involving code, APIs, or other technical topics can be posted to the zotero-dev mailing list at http://groups.google.com/group/zotero-dev.

See https://www.zotero.org/support/zotero_support for more information on how Zotero support works.

**Comment by jryans** [comment]
As the message above states, Zotero doesn't use GitHub issues for bug reports or support requests. Please post to the forum instead.
