### ISSUE TITLE
Preserve annotation colors in notes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2080]
https://forums.zotero.org/discussion/90158/zotero-beta-add-item-note-from-annotation-save-colors-of-annotation

It doesn't look like we're currently including colors in extracted annotations, but we should, both so that we can offer an option to display them and to allow plugins to use them. This is necessary for ZotFile parity.

**Comment by mrtcode** [comment]
We're already including annotation color for about two months.

Are there any specific requirements for plugins?

**Comment by dstillman** [comment]
Ah, OK, I must have checked an earlier annotation. The goal would just be to make it possible for a plugin like mdnotes to extract the annotation color. If it's available in the data already, that's fine.
