### ISSUE TITLE
Option to show annotation colors in notes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2081]
Once we do https://github.com/zotero/zotero/issues/2080, this could be a toggleable option in notes.

**Comment by mrtcode** [comment]
That would be a global option, stored in prefs, or per note, stored in note metadata container?

**Comment by dstillman** [comment]
Good question. You could potentially be at different phases of research in different notes and want different things, but a per-note option is sort of annoying — there would need to be a default that you'd have to change for every note that differed, or it would have to use the last-used per-note setting when creating a new note… Sort of a mess. Global is much simpler, conceptually.

A related question is whether we would want to have the color automatically applied in Quick Copy based on the display setting.

**Comment by mrtcode** [comment]
And where exactly that toggleable option would be? In three dots menu?

**Comment by dstillman** [comment]
I think it kind of has to be. Sort of weird for a global setting, but doesn't really make sense to put it in the main menus when it only applies to a small part of the UI.

**Comment by dstillman** [comment]
We do have Note Font Size in View, but that makes more sense to me than this.
