### ISSUE TITLE
Option to include annotation colors via Add Note

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2082]
Once we do https://github.com/zotero/zotero/issues/2080, we could add an option (toggleable from the citation dialog, off by default) to include annotation colors when inserting notes into word processor documents.

**Comment by mrtcode** [comment]
Whether it's good or bad, but highlighted text is already inserted with colors.

**Comment by dstillman** [comment]
Oh, that's been the case since we started saving color values?

I don't think we want that to be the default for Add Note.

**Comment by mrtcode** [comment]
> Oh, that's been the case since we started saving color values?

No, it's just for text that is highlighted with highlighter tool or "Apply Annotation Colors". Note insertion just passes HTML to word processors.

**Comment by dstillman** [comment]
Oh, I see. I guess that's fine, then. We just really need a "Remove Annotation Colors" to go with "Apply Annotation Colors".
