### ISSUE TITLE
Automatically relocate linked files within current base directory

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2084]
People frequently misuse the <a href="https://www.zotero.org/support/preferences/advanced#linked_attachment_base_directory">Linked Attachment Base Directory</a> setting and end up on a new computer with lots of missing files with absolute paths. If they can temporarily create the old folder scheme, they can fix it with the LABD setting, but otherwise they have to use Zutilo to batch-change files, which is confusing, error-prone, and I think buggy (there's something with lost first letters of filenames).

If a base directory is set and a user tries to open a linked file with an absolute path that doesn't exist, we could try to find the file within the base directory. If found, we could offer to relocate 1) just this file or 2) all files in the old location.

To test this, we'd start with just the filename and then try successive parent folders until we find a relative path or the filesystem root.

If we find a match, we could check to see how many other missing files we could fix and provide the info in the confirmation dialog.

**Comment by qqobb** [comment]
> People frequently [...] end up on a new computer with lots of missing files with absolute paths.

I just wanted to mention that a related error also occurred with missing files with *relative paths*, when the LABD setting was missing on a new computer. This happened if you had set a LABD on your old machine and then copied over the data directory to your new setup. In this case you [weren't getting the Locate dialog](https://forums.zotero.org/discussion/91294/no-locate-button).

I haven't looked at the code. Maybe you already fixed that in the meantime.
