### ISSUE TITLE
Add/Edit Citation Classic View - Multiple sources list width is too short - cannot identify sources

### ISSUE THREAD

**Issue by pback34** [zotero/zotero#2090]
Using Zotero 5.0.96.2 on Linux Mint 20.1 Cinnamon v4.8.6

I cannot determine how to widen the diaglog box of the list of multiple references cited in classic view (the box under "Keep sources cited" checkbox option on right side of window. Only 15 chars of the title are displayed, which is not enough to identify the source in all cases. Widening the window only widens the center box of all available sources.

Hovering over the sources in the right box does nothing - it should display the full title. 

Additionally, it would be useful to be able to double click/right click on the sources listed to see more options such as open reference in zotero, attached file, etc.

**Comment by dstillman** [comment]
Please post support questions to the [Zotero Forums](https://forums.zotero.org), where we're best able to help. See [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more information.

We won't be making further changes to the classic citation dialog.
