### ISSUE TITLE
File-not-found dialog and context menu not appearing on Windows for linked file with absolute macOS path

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2092]
https://forums.zotero.org/discussion/comment/385310/#Comment_385310

**Comment by dstillman** [comment]
Ideally would try to address things like this with https://github.com/zotero/zotero/issues/2084 as well.

**Comment by Rosmaninho** [comment]
This happened to me as well, but without ever touching a Mac machine.

**Comment by Rosmaninho** [comment]
This is weird to me, because I use an external PDF reader. It also does not open the PDF in external readers but it does on the built-in reader.
