### ISSUE TITLE
Use two lines for extracted annotation header

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2095]
The header line for extracted annotations — at least with the date and time — wraps to two lines in the right-hand pane:

![note-header](https://user-images.githubusercontent.com/783082/122355041-8fe4bb80-cf1f-11eb-8175-e43ce05887d8.png)

We can't really do much about font size here — the increased size is a big part of the redesign — so I think we have to use a newline:

![newline](https://user-images.githubusercontent.com/783082/122356706-09c97480-cf21-11eb-80a7-08ad85371219.png)

But then the title in the middle pane only shows "Annotations". I think we'll want to tweak Zotero.Notes.noteToTitle() so that we still show the timestamp, though I'm not sure the best way to do that. Look for `<h1>` at the beginning and handle that differently?

We should change the extraction first, in any case.

**Comment by qqobb** [comment]
Perhaps this can be fixed by using [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) characters?
