### ISSUE TITLE
Temporarily unstyled inline text while typing

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2096]
https://github.com/zotero/note-editor/pull/24#issuecomment-863057447

**Comment by mrtcode** [comment]
This issue is interesting. I can only reproduce it on macOS, it happens for all inline styles, just for `<code>` is more visible because `font-size` is different. And it's not affected by zotero/note-editor#24.

**Comment by mrtcode** [comment]
Is this still a problem? I can't reproduce it anymore. I was using macOS on a virtual machine with no graphical acceleration when I was able to reproduce.

I guess we can close this.

**Comment by dstillman** [comment]
I'm not seeing it anymore either.
