### ISSUE TITLE
[FF upgrade needed] Note editor: Can't select text from end of citation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2097]
1. Create a note with a highlight annotation
2. Click at the end of the citation following the annotation
3. Try to drag around and select text

The citation immediately shows as selected on mousedown and the selection popup (with "Go to Page"/etc.) appears, but it's not possible to select any other text by dragging the mouse.

**Comment by mrtcode** [comment]
This is probably the same as #1990, and is a Firefox bug.

**Comment by mrtcode** [comment]
Already fixed after upgrading Firefox.
