### ISSUE TITLE
Note editor: "Remove Annotation Colors" option

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2106]
Once you use "Apply Annotation Colors", you should be able to do "Remove Annotation Colors".

(It should be there just for symmetry, and without it it can be tedious to quickly remove highlighting if there's other formatting (e.g., bold) in the extracted text.)

**Comment by mrtcode** [comment]
Should it also remove highlight color that was manually set/changed for highlight annotation?

**Comment by dstillman** [comment]
More specific questions:

1) If you highlight part of the annotation with a different color, should that be cleared?

2) If you clear part of the highlighting but leave the rest in the same color (or manually highlight some of it with the same color), should the rest be cleared?

3) If you highlight the whole paragraph, including the annotation, should the annotation part be cleared (regardless of color)?

I'd probably say no to all three, since in all cases you've added new information that can't be automatically restored.

So, put another way, the highlight should be cleared if it matches the original color and covers the entire annotation text but doesn't extend beyond it.

**Comment by mrtcode** [comment]
Yeah, I was thinking the same. It should only remove what it added previously.
