### ISSUE TITLE
Note editor: "Replace with" → "Replace"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2107]
Don't need the "with" in the Replace box. Some editors do it, but I think it's clumsy, and I don't think people are confused when programs just say "Replace".

**Comment by mrtcode** [comment]
I guess it should be a toggleable "Replace" button. Although keeping that button outside of the search input box doesn't fit very well with the current design where input boxes contain buttons and stretch to 100% width.

**Comment by mrtcode** [comment]
Alright, a few mockups. Though, none of them look good enough for me. But, hopefully, they can point us in the right direction.

![Screenshot from 2021-06-23 15-42-52](https://user-images.githubusercontent.com/6362989/123100847-24797d00-d43c-11eb-9366-6f840a7f1956.png)

![Screenshot from 2021-06-23 15-42-22](https://user-images.githubusercontent.com/6362989/123100884-2b07f480-d43c-11eb-800f-a12a16da8da8.png)

![Screenshot from 2021-06-23 15-46-44](https://user-images.githubusercontent.com/6362989/123100953-3bb86a80-d43c-11eb-92b5-1381c5d2dac7.png)

![Screenshot from 2021-06-23 15-57-46](https://user-images.githubusercontent.com/6362989/123100965-3f4bf180-d43c-11eb-84e2-a768cab83edd.png)

**Comment by dstillman** [comment]
Why not just copy macOS and use a checkbox? Replace as a button is too scary/confusing — there's no way to know that it's a toggle in advance, so it seems like it will actually replace something (like the actual Replace button that then appears (which also means there are then two Replace buttons on screen in the same interface)).

**Comment by mrtcode** [comment]
Should we use the default checkbox form element, or a custom checkbox icon?

**Comment by dstillman** [comment]
We might as well try the default first.

**Comment by mrtcode** [comment]
Default checkbox looks a bit too small.

![Screenshot from 2021-06-24 12-08-51](https://user-images.githubusercontent.com/6362989/123236478-7fb37a00-d4e5-11eb-8a70-fbb36fb98ddc.png)

We can scale it, but it becomes a little bit distorted.
![Screenshot from 2021-06-24 12-11-59](https://user-images.githubusercontent.com/6362989/123236937-e8025b80-d4e5-11eb-94dc-59d82ddae0b7.png)

(Examples are on macOS)

**Comment by dstillman** [comment]
Hmm, that larger one is pretty much exactly the same size as in the General system prefs, so not sure why it's different.

We can try that and see how it looks on a Retina display.

**Comment by mrtcode** [comment]
Actually, on my system, the first one has the same size as anywhere else. Looks like things are scaled down on my system. I will just keep the original checkbox size.
