### ISSUE TITLE
Note editor: Avoid setTimeout call on every context menu popup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2111]
https://github.com/zotero/zotero/pull/2052#issuecomment-866701782

**Comment by mrtcode** [comment]
I guess you missed my forced commit before https://github.com/zotero/zotero/pull/2052#issuecomment-866775811. But no problem, I'll push it again.

**Comment by dstillman** [comment]
Ah, sorry, I did miss that. (I also just noticed `--force-with-lease` in the `git push` man page earlier today.)
