### ISSUE TITLE
PDF reader: Annotation popup appears after dragging annotation to note

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2112]
I'm pretty sure this is a regression.

**Comment by mrtcode** [comment]
Could you explain the issue a little bit more? I don't see any new behaviour.

**Comment by dstillman** [comment]
If I'm viewing a PDF and click and drag an unselected annotation to a note, when I let go of the mouse button the annotation popup opens.

**Comment by mrtcode** [comment]
Yeah it was always like that (assuming that sidebar is closed). There are dozens of little issues like this, in the UI.
