### ISSUE TITLE
pdfinfo freezes on corrupted PDF

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2120]
https://forums.zotero.org/discussion/90644/zotero-beta-hangs-importing-6gb-mendeley-library

The stock version I have (21.06.1) doesn't freeze, but our custom version does.

PDF shared via email

**Comment by mrtcode** [comment]
It seems that Xpdf `pdfinfo` and `pdftotext` 4.02 version freezes, but there is a newer 4.03 version which works well with this PDF. It means we should migrate.

Is that a priority now?

**Comment by dstillman** [comment]
In this case it was resulting in a hang of the import process from Mendeley, so it's not great.
