### ISSUE TITLE
External links to annotations

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2125]
https://forums.zotero.org/discussion/comment/386881/#Comment_386881

Presumably we'll want to just extend zotero://open-pdf with additional positioning parameters, similar to how we link to annotations from notes, rather than linking to annotation items specifically.

**Comment by dstillman** [comment]
`pageIndex` would be taken care of by the `page` parameter, right?

Still, though, even with just the rects, that's going to be fairly unusable in Markdown editors that don't hide the link itself (which I think is most/all of them). We could support this for non-annotation selections, but I think we do actually need to allow linking to annotation items directly. So it'd be `zotero://open-pdf/library/items/EVTXJSVC?page=123&annotation=[annotation-key]`, and then if the annotation was missing it would still open to the right PDF page.

**Comment by mrtcode** [comment]
> `pageIndex` would be taken care of by the `page` parameter, right?

The problem with `?page=` is that sometimes it can be `pageIndex` and sometimes `pageLabel`. We'll try to support both, firstly it'll try the number as page label and then falls back to page index. But if PDF doesn't have assigned page labels, navigating to `pageLabel` needs to extract page labels from page text which is quite inconvenient to do on navigation, but doable.

> zotero://open-pdf/library/items/EVTXJSVC?page=123&annotation=[annotation-key]

Yeah, we can navigate to specific annotation, but I have to remind that annotations, that are inserted into a note, no longer have original annotation item key (we had that initially), therefore plugins won't be able to generate link from inserted annotations.

**Comment by dstillman** [comment]
> The problem with ?page= is that sometimes it can be pageIndex and sometimes pageLabel.

Why? Why not just use the physical page? It's not like `EVTXJSVC` is meaningful outside the context of a Zotero database, I don't see why we'd need to bother with the page label.

> annotations, that are inserted into a note, no longer have original annotation item key (we had that initially), therefore plugins won't be able to generate link from inserted annotations

Hmm, good point. I'm not sure what to do about that. Do we want to revisit that concept? Should an inserted annotation include the key, with the position info as a fallback, and plugins can choose which they want to use, depending on whether they're able to hide URLs? Even within Zotero, are we sure that, if you resize an image annotation, or in the future if you can drag annotation handles to adjust them, the inserted annotation shouldn't still select that annotation in the PDF?

Even without `pageIndex`, and even if the `rects` label was just implied, I just think full positional URLs are going to be too long for most plain-text use cases. I think positional would only work if, say, it only included the four corners as actual query parameters, even when that spanned many lines or multiple columns, but that'd be pretty gross.

**Comment by mrtcode** [comment]
> > The problem with ?page= is that sometimes it can be pageIndex and sometimes pageLabel.
> 
> Why? Why not just use the physical page? It's not like `EVTXJSVC` is meaningful outside the context of a Zotero database, I don't see why we'd need to bother with the page label.

Because, I think, there already exist ZotFile generated links that include page label, and also if someone is manually setting page number it's much more likely that it'll be a page label than page index.


> Hmm, good point. I'm not sure what to do about that. Do we want to revisit that concept? Should an inserted annotation include the key, with the position info as a fallback, and plugins can choose which they want to use, depending on whether they're able to hide URLs? Even within Zotero, are we sure that, if you resize an image annotation, or in the future if you can drag annotation handles to adjust them, the inserted annotation shouldn't still select that annotation in the PDF?

We could return item key, but the idea was that inserted annotation should just live a separate life without any dependency on the original annotation. Sure, it could fallback to position if annotation with specific key no longer exists, but it's probably more consistent and simpler when inserted annotations are completely independent. But for plugins, yes, maybe it would make sense to link to annotation item key.


> Even without `pageIndex`, and even if the `rects` label was just implied, I just think full positional URLs are going to be too long for most plain-text use cases. I think positional would only work if, say, it only included the four corners as actual query parameters, even when that spanned many lines or multiple columns, but that'd be pretty gross.

A bounding box around annotation would probably be a little bit more useful than just showing a page, but a page number (index or label) is probably also enough to locate the necessary information if the annotation no longer exists. It's already proven in ZotFile.

**Comment by dstillman** [comment]
> Because, I think, there already exist ZotFile generated links that include page label, and also if someone is manually setting page number it's much more likely that it'll be a page label than page index.

No, this is always the physical page, and always has been in ZotFile. If it weren't we'd be opening the PDF to the wrong page. This is separate from what ZotFile might show in the visible text — I don't know what it uses for that — but we (and ZotFile before us) have always just opened the external PDF reader and told it to go to the specified page.

> But for plugins, yes, maybe it would make sense to link to annotation item key.

I think we might as well include the key in the data, and if plugins want to use that instead of a long position string, they can.

**Comment by mrtcode** [comment]
If we would return annotation key, it should probably be annotation item URI not just key, because notes (or part of the content) can easily circulate between different libraries. Although the ugly thing is that we already use `uri` property for attachment URI. Therefore we probably need `annotationURI` property now.

**Comment by dstillman** [comment]
Well, it would technically be redundant to have a full URI for both, because the annotation has to be in the same library. And a plugin would need to construct the open-pdf URL from the key anyway.

`uri` for the attachment isn't ideal, and maybe we want to migrate it to `attachmentURI` to be clearer, but you could sort of look at it as the annotation being identified by 1) an attachment and 2) an `annotationKey` or `position`.

**Comment by mrtcode** [comment]
Yes, it makes sense. So let's just implement `&annotation=[annotation-key]`, add `annotationKey` and migrate to `attachmentURI`.

**Comment by mrtcode** [comment]
Of course `&annotation=[annotation-key]` is only limited to annotations that were actually created. For annotations that were inserted as a text that was dragged, positioning parameters would be necessary. Or we can just ignore this and assume that `open-pdf` link is only for actually existing annotations or page index.
