### ISSUE TITLE
Encyclopedia articles and artworks can't be merged

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#2136]
`encyclopediaArticle` has `itemTypeID` 14, and that ID is specifically blacklisted in the merge routine:

https://github.com/zotero/zotero/blob/52932b6eb03f72b5fb5591ba52d8e0f4c2ef825f/chrome/content/zotero/duplicatesMerge.js#L49

[Reported on the forums.](https://forums.zotero.org/discussion/90965/why-cant-i-combine-several-items-with-the-entry-type-article-from-encyclopedia)

**Comment by AbeJellinek** [comment]
1 is `artwork`, so there's clearly something wrong here. I'm guessing that this is meant to check for `note` and `attachment`; we should do that by name, not by ID.

**Comment by dstillman** [comment]
Yeah, IDs used to be fixed, but after 4b60c6ca275ec69249b3ea81a669ae4823678d03 new installs could get different ids. All 1 and 14 references should've been updated, but I guess we missed this one.
