### ISSUE TITLE
Test breakage after #2128

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2141]
```
    ✖ [FAIL] should extract ADS bibcodes
      expected [ { PMID: '9' } ] to have a length of 2 but got 1 at
```

**Comment by AbeJellinek** [comment]
Wait, it's extracting a single digit as a PMID? Ugh. Could we just move the bibcode stuff before PMID since digits will pretty much always be detected as PMIDs?

**Comment by dstillman** [comment]
Yeah, probably makes sense for PMID to always be last, and ADS will basically never have false positives.

**Comment by dstillman** [comment]
I can update the submodule.

**Comment by AbeJellinek** [comment]
OK, great. Thanks, that should do the trick.
