### ISSUE TITLE
I can't select the text after there are annotation on the text.  

### ISSUE THREAD

**Issue by xh542428798** [zotero/zotero#2165]
When I create an annotation, I can't select the text on the annotation, like that below: I can't select the text in pink annotation and yellow rectangle

![image](https://user-images.githubusercontent.com/49368033/131149889-f29f94b9-9424-462c-beef-17928f6aa5dc.png)

**Comment by mrtcode** [comment]
You have to hold shift to select under an annotation. But please post to Zotero forums the next time.
