### ISSUE TITLE
HTML tree: `ensureRowsAreVisible()` shouldn't scroll if unnecessary

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2166]
Following up on https://github.com/zotero/zotero/commit/77f726fef3561a194346e344fdab88373a10cca8

1. Select a couple parent items and scroll them to the top of the viewport
2. Press right-arrow on the keyboard

Even though there's room for the items to expand, they're shifted down a few rows.

`ensureRowsAreVisible()` shouldn't make any scroll changes if all the rows are already in view. (Not sure if this is actually a regression, but that's the desired behavior.)

**Comment by adomasven** [comment]
That's not `ensureRowsAreVisible()` being triggered. Instead technically new rows are added to the tree when you expand an item, so all the rows below are moved down by the amount of new rows. I see that the old XUL tree didn't used to do that, but that technically requires scrolling the tree to achieve the desired effect on row expand and I'm not sure if we'll be able to do this without causing jitter.

**Comment by dstillman** [comment]
It was `ensureRowsAreVisible()`. (The telltale sign was the consistent 5-row jump, which we may actually want to reconsider, since it's sort of awkward.) The same problem occurred when `ensureRowsAreVisible()` was called on a single row. Fixed now in dadf630.

What you're describing, I believe, is what's causing the test from c5d89f6d0790b516e6515c31918a6075488c5af3 to still fail. This fix affected that test but didn't fix it — it's now off by exactly the number of items added above, since it's really testing something different. I'll write a new test for unnecessary scrolling by `ensureRowsAreVisible()` (fixed) and another for unnecessary scrolling when items are added above the current page (not fixed).
