### ISSUE TITLE
HTML tree: Skip key navigation with modifier keys pressed

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2170]
https://github.com/wshanks/Zutilo/issues/203#issuecomment-907712042 (second half)
https://forums.zotero.org/discussion/91484/in-5-0-97-beta-40-952663de7-zutilo-3-10-works-improperly

**Comment by adomasven** [comment]
I have this done, but it makes sense to just make it part of #2169, which is somewhat more involved and I'm working on it now.
