### ISSUE TITLE
Recombine some of collectionTree/itemTree into libraryTree to avoid duplication

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2173]
E.g., stuff in `onDragOver()`

https://github.com/zotero/zotero/issues/2172#issuecomment-908065362

**Comment by adomasven** [comment]
So we need to be more specific about what and why we want recombined, beyond `onDragOver()`. The current libraryTree was not a port of the original one, but rather my targeted effort at consolidating the functions that made sense to be common across the two after porting both trees separately to the HTML tree. So in my eyes I have already consolidated what there was and made sense to be shared code for the most part. Some of the functions in the original `libraryTreeView.js` were `if (itemTree) { this } else { that }` so just going off what the original had isn't a good idea.

**Comment by adomasven** [comment]
I'll consider this done, especially as there's been so much additional changes to the tree code now without this coming up.
