### ISSUE TITLE
Allow to batch renumber annotation page labels

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2181]
Annotation pages have to be manually renumbered when page label can't be correctly determined because:
- PDF doesn't have page labels information.
- PDF has page labels information but it's incorrect.
- Page label extraction from page fails:
  - Too few pages to determine page label position in PDF page. Currently at least 4 numbered pages are necessary (different label position between odd/even pages is supported).
  - PDF pages aren't continuous - gaps or additional pages between pages.
  - PDF is OCRed which means page label position is drifting.
- Single PDF page has multiple pages (more common for OCRed books).

Possible solutions:
- There could be an option called "Renumber annotation page labels starting from this page" in page context menu. When clicked it would show a popup with the current page label and suggest to enter a new page label.
- Selecting multiple annotations in annotations sidebar could also show a context menu option to manually set labels for selected annotations, starting from the first annotation page.

**Comment by mrtcode** [comment]
@dstillman

As annotations on iOS app and Zotero client can sometimes have different page labels, I think it's now even more important to have a way to re-calculate them.

Here is what I suggest:
- Double clicking annotation page label or clicking annotation context menu option "Update Page Numbers" would prompt a popup.
- The popup would have an input box with pre-entered page label and a checkbox "Update annotations in other pages accordingly".
- The popup will replace the current page label input that currently appears on double click.
- We were discussing about only updating the further pages after the current page, but I think updating all pages is a simpler concept for most users.
- For advanced use cases like updating annotations range in a single page (one PDF page has multiple physical pages) or multiple pages between gaps, you would need to select those annotations and click "Update Page Numbers" context menu option. There won't be any additional checkbox, but if selected annotations are from multiple PDF pages, they will be automatically re-calculated accordingly.

I think this would be a sweet spot between the most common simple cases and rare advanced cases.

Offtopic: I also suggest to add another annotation context menu option called "Tweak Highlight Text", because double clicking on highlight text is too difficult to discover.

**Comment by dstillman** [comment]
> We were discussing about only updating the further pages after the current page, but I think updating all pages is a simpler concept for most users.

Not sure about this as the only option. To me, updating page numbers on previous pages is a little unsettling — you're already past those, and it would feel like you had to scroll back and lose your place to review those, while you're already going to continue scrolling forward to deal with later pages.

We could just give all three options, in a drop-down or radio: "Update:" "this page"/"this page and later pages"/"all pages"

**Comment by mrtcode** [comment]
Ok, sounds good. I'll just push this to master.

**Comment by mrtcode** [comment]
Actually, I think there should the forth and probably primary option to update only selected annotations, because otherwise you can update specific annotations from a single page.

**Comment by dstillman** [comment]
I agree we need "this annotation"/"selected annotations" (depending on the selection), but I don't think should be the default. I think it'll be far more common to need to update either all annotations or all annotations going forward. I'd probably default to "this page and later pages".

What happens if there are no annotations on a page but you've updated page numbers? Will we automatically figure out that physical page 3 has page label 20 and physical page 5 has page label 22, so if you create an annotation on physical page 4 it should be page label 21?

**Comment by mrtcode** [comment]
> What happens if there are no annotations on a page but you've updated page numbers? Will we automatically figure out that physical page 3 has page label 20 and physical page 5 has page label 22, so if you create an annotation on physical page 4 it should be page label 21?

For now it won't take into account existing annotation page labels, but in future we might try to do something like that. Therefore you will need to update those again after creating new annotations.

Ok, here are the new strings that will be added:
- Update Page Number
- This annotation
- Selected annotation
- This page
- This page and later pages
- All pages

**Comment by dstillman** [comment]
"selected annotations" (plural)

We can also optimize this by not showing options that are redundant/irrelevant. E.g., if the first annotation is selected, no need to show both "this page and later pages" and "all pages". If no earlier annotations, no need to show "all pages". If all annotations are selected, only "selected annotations". If only one annotation exists, only "this annotation".

**Comment by dstillman** [comment]
Will it at least use the existing page label for annotations on the same page, if they're all the same? It would be very annoying if not.

**Comment by mrtcode** [comment]
> Will it at least use the existing page label for annotations on the same page, if they're all the same? It would be very annoying if not.

Yeah, we should be able to do that.

**Comment by mrtcode** [comment]
The work is still in progress, as I needed to implement efficient multiple annotations updating and that triggered other related work, but there are a few questions regarding the popup styling.

Here are some options:
1) ![Screenshot from 2021-12-03 17-47-19](https://user-images.githubusercontent.com/6362989/144632091-6e0b245e-3ab2-45a0-acb4-ec7f852b08fa.png)
2) ![Screenshot from 2021-12-03 17-40-55](https://user-images.githubusercontent.com/6362989/144632200-19bb5c15-cd8f-4a90-8cdb-5c46fa202e76.png)
3) ![Screenshot from 2021-12-03 17-44-08](https://user-images.githubusercontent.com/6362989/144632406-f3270d0b-1312-4d7c-830c-7bfe8e800fd3.png)

Which style fits better for pdf-reader?

The blue button already exists in our custom PDF.js styling (for password prompt), although the blue color is hard-coded and doesn't represent the current OS style and accent color on macOS.
