### ISSUE TITLE
Don't use natural sorting for Call Number field

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2194]
https://forums.zotero.org/discussion/89408/call-number-sorting

**Comment by dstillman** [comment]
Oh, though Dewey is actually a [little more complicated](https://www.mdek12.org/sites/default/files/Offices/MDE/OA/OEER/Library%20Services/Section%206/Dewey%20Decimal%20Classification%20(1).pdf):

> Here is an example of Dewey order with decimal numbers and letters:
641/Bet → 641.5/Cor → 641.5/Wol → 641.555/Ray → 641.594/Mun → 641.5945/Foo →
641.596/Mon

So `sort()` wouldn't quite work here, because it would put "641/Bet" last, since `.` < `/`:

```
[
    "0": "641.5/Cor"
    "1": "641.5/Wol"
    "2": "641.555/Ray"
    "3": "641.594/Mun"
    "4": "641.5945/Foo"
    "5": "641.596/Mon"
    "6": "641/Bet"
]
```

**Comment by MartinRushton** [comment]
The use of letters is a private extension to Dewey* and is not sanctioned in either the introduction or the manual.  It is pretty common however!  How would requiring a space before the slash run?  "641 /BET" < "641.5".  This is only required when a three digit number is used, as soon as a subdivision is included the problem evaporates.
*According to my version of "Abridged 13"
