### ISSUE TITLE
How to build and run zotero from its git master source code?

### ISSUE THREAD

**Issue by hongyi-zhao** [zotero/zotero#2198]
I've noticed that the [Zotero PDF Reader](https://www.zotero.org/support/pdf_reader_preview) is implemented in [Zotero Beta](https://www.zotero.org/support/dev_builds). I'm On Ubuntu 20.04.2 LTS, how to build and run `zotero` from its git master source code? For a related discussion, please see [here](https://github.com/retorquere/zotero-deb/issues/46).

Regards,
HY

**Comment by dstillman** [comment]
https://www.zotero.org/support/dev/client_coding/building_the_standalone_client
