### ISSUE TITLE
[New pdf] Error log

### ISSUE THREAD

**Issue by GCamp6** [zotero/zotero#2204]
## Info
I would like to share an error log from the new pdf editor.
After I open and start to read/underline the pdf (not with each pdf, just few/random) the warning red bar appears, I can just ignore it and continue to work, If I close and open the pdf again the error usually does not appear, it seems to be random/not associated with specific behavior (or not that I noticed).

I'm on win10 with Zotero 5.0.97-beta.44+fa4020f78

Please, if I can better debug the issue let me know the steps I have to follow.

### Log:

PDF.js v2.8.149 (build: 4f4cd761c)

Message: 
Stack: Win error 32 during operation delete on file C:\Users\...\storage\6GJKNK7N\.zotero-pdf-state (Impossible to open file. The file is used by another process.
)
    (No stack trace)
From previous event:
    captureStackTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:915:23
    CapturedTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:807:5
    longStackTracesCaptureStackTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:482:19
    doThenable@resource://zotero/loader.jsm -> resource://zotero/bluebird/thenables.js:60:5
    tryConvertToPromise@resource://zotero/loader.jsm -> resource://zotero/bluebird/thenables.js:28:20
    module.exports/Promise.cast@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:222:15
    Zotero.File</this.putContentsAsync@chrome://zotero/content/xpcom/file.js:410:14
    _setState@chrome://zotero/content/xpcom/reader.js:623:3265

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
