### ISSUE TITLE
Duplicated annotations from repeated/interrupted Mendeley imports?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2207]
https://forums.zotero.org/discussion/comment/390373/#Comment_390373

**Comment by tnajdek** [comment]
I tried to reproduce this but wasn't able to. I can't really see a code path where previous, undeleted annotation is not matched, other than annotation from Mendeley not having uuid (or having a different one), here is the relevant code:

https://github.com/zotero/zotero/blob/master/chrome/content/zotero/import/mendeley/mendeleyImport.js#L1559-L1586

Regardless, I've tried repeated imports, both normally and with a modified code that would interrupt abruptly, but at no point I've ended up with duplicate annotations.

**Comment by dstillman** [comment]
OK, we can close this until we hear about another instance of it. Thanks for looking into it.
