### ISSUE TITLE
Feed items are marked as unread if URL changes but GUID stays the same

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#2213]
As reported on the forums: https://forums.zotero.org/discussion/comment/390744/#Comment_390744

The relevant code is here:

https://github.com/zotero/zotero/blob/1f634f9e31d28c4fa726ea6e2c90dd428d9b1636/chrome/content/zotero/xpcom/data/feed.js#L474-L481

When a feed is refreshed, `_updateFeed` updates existing items' metadata and marks them as unread if anything has changed. This is only sensible for some field changes: if `title` or `date` is updated, the item has probably changed substantially and should no longer be considered "read." For fields like `url`, though, a change probably does *not* indicate that the content has changed, and the item should remain "read" in the user's library.

I see two options here:

1. We take feed providers at their word. If an item's GUID remains the same, it's the same item, and it should never be marked unread even if its metadata changes.
2. We replace `feedItem.hasChanged()` with a more specific check, maybe only comparing `title` and `date`. If other fields change, we still keep the item marked as read.

**Comment by dstillman** [comment]
I'm pretty sure I've used feed readers in the past that marked things as unread when they were updated, but in our case there's probably not much value in doing so — you had a chance to save the entry to your library, and either you did or you didn't. If you did, updating really becomes the province of the Zotero item. If you didn't, the updated entry probably isn't going to change that.

So I'd just use the guid here.
