### ISSUE TITLE
Improve how tabs are displayed when there are too many of them

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2232]
https://forums.zotero.org/discussion/92614/pdf-reader-beta-tab-titles-not-shown
![Screenshot 2021-10-29 at 09 56 45](https://user-images.githubusercontent.com/6362989/139417550-d68b9114-a290-4a39-9989-75acb26f5621.png)

**Comment by dstillman** [comment]
Related: https://forums.zotero.org/discussion/93418/pdf-tab-size-issue-not-downsizing-to-fit-to-window

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/94154/bug-report-942805013-unable-to-see-note-ui-in-standard-view-note-ui-dysfunctional

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/95029/note-text-does-not-wrap

**Comment by dstillman** [comment]
This can actually cut off content, so we should fix this soon.

**Comment by mrtcode** [comment]
So we have to make the tab bar scrollable, I guess.

**Comment by dstillman** [comment]
Yeah, I guess so.
