### ISSUE TITLE
Include embedded note images in generated reports

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2251]
https://forums.zotero.org/discussion/93164/generate-report-from-selected-items-cannot-get-images-from-notes

Should we include images as data URIs? I'd be worried about performance, but I guess SingleFile does it, right?

**Comment by mrtcode** [comment]
We already include image data URIs.

From performance perspective it's worse than SingleFile because, normally, websites have smaller images optimized for Web, ours are optimized for print.
