### ISSUE TITLE
Convert old-style embedded images in notes to embedded-image attachments

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2258]
https://forums.zotero.org/discussion/93250/error

This person isn't on the beta, but it reminds me that we should convert these in editable libraries (on note load? on edit?), if we don't yet, so that people who couldn't sync before will be able to do so.

**Comment by mrtcode** [comment]
It already automatically imports JPEG and PNG images on note opening. That includes Base64 image URLs and regular URLs.
