### ISSUE TITLE
Bug for pdf reader and note

### ISSUE THREAD

**Issue by xh542428798** [zotero/zotero#2260]
I annotated on the pdf using Zotero pdf reader，when I removed pdf using zotfile，the annotations are all missing！！I can't find my annotations any more。Please fix the problem，thanks very much

**Comment by xh542428798** [comment]
once I annotated on pdf，I could not change the pdf link any more，if change，the annotations that annotated before would be missing

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums. We don't use GitHub for support.

ZotFile doesn't know anything about Zotero annotations and will delete them if you use it on a file.
