### ISSUE TITLE
ERROR: npm run build under Cygwin

### ISSUE THREAD

**Issue by actforjason** [zotero/zotero#2264]
> Jason@LenovoZ /cygdrive/f/OOPs/Zotero/zotero-client
> $ npm run build
> 
> \> zotero@5.0.0 build
> \> node ./scripts/build.js
> 
> [cp] test/tests/data/zotero-4.0.sqlite.zip
> [ln] test/runtests.sh
> [ln] translators
> [cp] test/tests/data/zotero_rdf.xml
> [ln] test/resource/EventUtils.jsm
> [ln] styles
> [cp] test/tests/data/translatorExportLegacy.js
> [ln] test/install.rdf
> [ln] test/content/runtests.html
> [cp] test/tests/data/translatorExport.js
> [ln] chrome/content/zotero/xpcom/translate/src
> [sass] scss/zotero-react-client-win.scss
> [ln] test/chrome.manifest
> [cp] test/tests/data/test.txt
> [browserify] node_modules/chai-as-promised/lib/chai-as-promised.js
> [sass] scss/zotero-react-client-unix.scss
> [ln] chrome/skin/default/zotero/zotero.svg
> Error: Error: Command failed: npm ci;npm run build
> 
>     at ChildProcess.exithandler (child_process.js:308:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1048:16)
>     at Socket.<anonymous> (internal/child_process.js:439:11)
>     at Socket.emit (events.js:315:20)
>     at Pipe.<anonymous> (net.js:673:12) {
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: 'npm ci;npm run build',
>   stdout: 'Unknown command: "ci;npm"\n' +
>     '\n' +
>     'To see a list of supported npm commands, run:\n' +
>     '  npm help\n',
>   stderr: ''
> }

**Comment by dstillman** [comment]
Looks like the new submodules for the PDF reader and note editor don't build properly on Windows.

(We don't build on Windows ourselves, so I don't know when we'll get to this.)

**Comment by dstillman** [comment]
@actforjason: If you want to try to fix this right away, I'd guess it's as simple as separating that line into two in each submodule.

**Comment by actforjason** [comment]
@dstillman As you said, I changed `'npm ci;npm run build'` to two commands in each submodule, but further get error:

> Jason@LenovoZ /cygdrive/f/OOPs/Zotero/zotero-client
> $ npm run build
> 
> \> zotero@5.0.0 build
> \> node ./scripts/build.js
> 
> [cp] test/tests/data/zotero-4.0.sqlite.zip
> [ln] translators
> [ln] test/runtests.sh

> ······

> [ln] chrome.manifest
> Error: Error: Command failed: npm run build
> 'scripts' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> ���������ļ���
> 
>     at ChildProcess.exithandler (child_process.js:308:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1048:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: 'npm run build',
>   stdout: '\n' +
>     '> pdf-worker@1.0.0 build\n' +
>     '> npm run build:pdf.js && npm run build:worker\n' +
>     '\n' +
>     '\n' +
>     '> pdf-worker@1.0.0 build:pdf.js\n' +
>     '> scripts/build-pdfjs\n' +
>     '\n',
>   stderr: "'scripts' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���\r\n"
> }
>

**Comment by tnajdek** [comment]
I've run into this as well, the next step would be to tweak pdf & note editor codebases to use something like [cross-env](https://www.npmjs.com/package/cross-env). I'll try to fix this.

**Comment by dstillman** [comment]
Can't we just separate those two lines?

**Comment by dstillman** [comment]
Oh, sorry, missed @actforjason's follow-up. Not clear to me what the error is there.

**Comment by tnajdek** [comment]
I only had a quick look but I believe the issue here is that `exec` from Node's `child_process` runs the command using `cmd.exe` shell, not cygwin. Windows shell doesn't understand command separator `;` thus the first error.

To the best of my knowledge second error is happening because in this environment env variable cannot be set the same   way as on macOS or Linux, hence need for cross-env [here](https://github.com/zotero/pdf-reader/blob/9e26897099938106f6f5fb5ce714974852729fd7/package.json#L8), [here](https://github.com/zotero/pdf-worker/blob/4ad30a9fa4a96889cf913256554fb63ba32cc0c6/package.json#L9) and [here](https://github.com/zotero/note-editor/blob/34656ea6c51c46f69e357d4454a2e7ac376b2501/package.json#L6)

**Comment by mrtcode** [comment]
@tnajdek If you have an idea how to fix this, you can take this issue, if you want.
