### ISSUE TITLE
PDF reader: Inconsistent "Show in Library"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2266]
The File menu it selects the attachment, but the tab context menu selects the parent item. They should do the same thing. Probably the parent item?

**Comment by mrtcode** [comment]
Well, "File" represents PDF file, and tab represents the whole parent item (as it has parent title). But we can change that if needed.

**Comment by dstillman** [comment]
"File" is more abstract than that — e.g., lots of things in our File menu in the library view are about items. So I think it's fine and appropriate to select the parent item.

If you have an item with multiple similar files and really want to do something with a specific attachment item, I guess it'll be annoying, but that would be rare. Mostly this is just the accessible alternative to the right-click option.
