### ISSUE TITLE
Keyboard access to toolbar buttons

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2272]
https://forums.zotero.org/discussion/comment/395368/#Comment_395368
https://forums.zotero.org/discussion/93069/potential-accessibility-issues-with-video-demonstrations

**Comment by jaeschrich** [comment]
Based on https://web.archive.org/web/20201129082400/https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/XUL_accessibility_guidelines, it sounds like the recommended path to making toolbars accessible was to duplicate the functionality in menubar items. Would that be a better solution than making the toolbar itself accessible?

**Comment by dstillman** [comment]
Duplicate of #1807
