### ISSUE TITLE
Pick different shortcut for toggling tag selector

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2281]
50732d1479ea9fa839082be77d7eaf20391c2a14 used Ctrl/Cmd-Shift-T for reopening closed tabs, but that was the shortcut for toggling the tag selector. That shortcut is standard for reopening tabs, so we should pick a different key for toggling the tag selector.

https://forums.zotero.org/discussion/93545/zotero-beta-broken-toggle-tag-selector-shortcut

**Comment by qqobb** [comment]
OK, I see. Perhaps the shortcut for toggling the tag selector could just be removed from the Advanced pane of the preferences in Zotero 5.0.97-beta. There might not be a really convincing replacement. I haven't been using the shortcut, and it seems others haven't missed it either. I was just testing it.

An overhaul of the default keyboard shortcuts has been discussed some time ago. For example, getting rid off the Shift key in most cases was suggested: https://github.com/zotero/zotero/issues/1181#issuecomment-296936025. So an alternative shortcut for toggling the tag selector could be set later on (if at all), perhaps after getting opinions on this from users who've been using it.

We could add this shortcut to Zutilo in the meantime for users who need it.

**Comment by dstillman** [comment]
OK, removed for now — thanks.
