### ISSUE TITLE
Note editor: Highlight colors too dark

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2283]
Compared to ZotFile's extracted annotations, it's harder to read ours. I'm not sure if this is really a note editor issue or if we just want to use a lower opacity in the PDF reader too. I know we talked about this but I forget the details. But it seems like more of an issue in the note editor, and ZotFile appears to extract the colors at a lower opacity.

Zotero:
![zotero-annotations](https://user-images.githubusercontent.com/783082/146882304-a7285e7e-a8e0-49dc-87c7-10566d1ae7ca.png)

ZotFile:
![zotfile-annotations](https://user-images.githubusercontent.com/783082/146882291-0ee03e60-35e4-4623-bf0f-cc1cd9ce9035.png)

**Comment by mrtcode** [comment]
ZotFile sets 0.25 opacity for each color. But yes, our colors are bit too dark to me as well.

For the extraction, ZotFile finds the closest predefined color category which is useful when annotations are in random colors. We had something like that at one point, but then removed.

**Comment by dstillman** [comment]
Not sure if this is the same thing but we're not even matching the opacity of our own PDF highlights:

![Screen Shot 2022-02-11 at 3 49 20 AM](https://user-images.githubusercontent.com/783082/153561978-032d5a51-1a5f-473a-b010-31ad45999c69.png)

**Comment by mrtcode** [comment]
Ok, so this is how it looks if I adjust the colors and don't use any opacity.

We use different opacity for different annotations in PDF reader:
- Highlight: 0.5
- Image square: 0.75
- Ink: 1
- Note: 1

Ink, image and note annotations clearly need more intensive colors. For ink we were already discussing about colors that would actually remind ink. Although, currently, it’s quite convenient to be able to just pick a single color and it gets automatically adjusted depending on an annotation.

Also color/annotation icons now look washed, which means  that either we should add some filter that would increase the intensity of those icons, or just hardcode the more intensive colors.

Current colors:
<img width="1512" alt="Screenshot 2022-02-25 at 00 30 17" src="https://user-images.githubusercontent.com/6362989/155730737-61dc4985-1f7d-417c-8b25-9318b078756e.png">

Adjusted colors with no additional opacity:
<img width="1510" alt="Screenshot 2022-02-25 at 01 00 06" src="https://user-images.githubusercontent.com/6362989/155730979-f28590e2-9b39-4c51-a52c-392d61b6d452.png">

**Comment by dstillman** [comment]
Closed by https://github.com/zotero/note-editor/commit/4ff5ba2793acb6c20891724d6f040d1911df53bf and https://github.com/zotero/note-editor/commit/e04f5a3c094bbf1681ff1355ec832dcf9e14a5f8
