### ISSUE TITLE
Note editor: Option to hide title/author from annotation citation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2284]
Our citations include the author or title (when no author) over and over, which is pretty annoying, at least for a note for a single PDF, which will be most of them. ZotFile annotations include only the page number.

We probably need a menu option to hide these, similar to the annotation-colors option. And there probably should be a different default depending on how you create the note. E.g., once we have the ability to create a note from annotations from multiple items, that should obviously default to showing the author/title, but for a note created from the annotations on the same PDF, it would make sense to hide by default.

I'm not totally sure how to handle this when you export, add to Word, etc. For now, probably just a display setting in the note that doesn't affect output, but eventually it'll probably need to be an option for Markdown output.

**Comment by mrtcode** [comment]
If citations can be easily added/removed, that's probably enough. And you get the same output everywhere. 

If you want citations in Markdown or word-processor you just temporary add those to the original note and then remove after the export.

Otherwise, I guess, hidden citation nodes might accidentally appear in unexpected places, but I would need to test that. Unless that option would only somehow collapse citations but still show a few symbols of it i.e. "(...)".

If we don't want them to be visible at all, it's probably better to just remove them. Although citations that are already moved somewhere else (not after annotation) wouldn't be removed, because recreating them wouldn't be possible as well.

**Comment by dstillman** [comment]
You mean since we already let you easily get back to the PDF page from the annotation, which is all the ZotFile links did anyway, you could just hide the citations altogether? And that the citations aren't useful within a single item's notes?

My concern there would be that people might still find the page numbers useful while taking notes and reviewing annotations, even for a single PDF. Say, to get a sense of where each annotation came from without jumping back to the PDF for each one?

**Comment by mrtcode** [comment]
> You mean since we already let you easily get back to the PDF page from the annotation, which is all the ZotFile links did anyway, you could just hide the citations altogether? And the citations aren't useful in general within a single item's notes?

Yes for a single item they probably aren't useful, although if they aren't inserted by default, some people will never discover them as well.


> My concern there would be that people might still find the page numbers useful while taking notes and reviewing annotations, even for a single PDF. Say, to get a sense of where each annotation came from without jumping back to the PDF for each one?

Yes, maybe page number is useful, but you can add/remove citations at any time. Alternatively, the highlight could show more information (including page number) when hovered, if needed.

**Comment by dstillman** [comment]
> Yes, maybe page number is useful, but you can add/remove citations at any time. Alternatively, the highlight could show more information (including page number) when hovered, if needed.

Yeah, both of those are good points.

**Comment by dstillman** [comment]
> if they aren't inserted by default, some people will never discover them as well

We probably want annotation colors to 1) default to on and 2) remember the last-used setting. Maybe same for this?
