### ISSUE TITLE
HTML tree: Activating item in advanced search window doesn't focus items list in main window

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2287]
E.g., if you have the search bar selected in the main window, it stays selected when the main window is brought to the front, even though the right item is selected. Seems like `ZoteroPane.selectItems()` doesn't focus the tree?

https://github.com/zotero/zotero/blob/04fa066a14f17e99db6ad76694b034f09b467831/chrome/content/zotero/advancedSearch.js#L185

**Comment by adomasven** [comment]
Closed via 5dabe39
