### ISSUE TITLE
Add `othersAnnotationsEditable` (and `othersItemsEditable`) permissions for group libraries

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2295]
As discussed before, `othersAnnotationsEditable` would only be enabled if user is an admin. It will ensure regular users can't edit each other's annotations. I'll need to make pdf-reader to respect it, when the setting is available.

We were also discussing about `othersItemsEditable`, but this isn't important at the moment.

**Comment by dstillman** [comment]
This will just be `group.admin`.

**Comment by dstillman** [comment]
No longer necessary. Group users can only edit annotations they created but can delete any annotation.
