### ISSUE TITLE
PDF reader: Select All in annotations sidebar should select all visible annotations

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2303]
If you click either on the pane background or an individual annotation and do a Select All, all visible annotations should be selected. (E.g., if you click a color in the [color/tag selector](https://github.com/zotero/zotero/pull/2299), you should then be able to select all annotations to add to a note without needing to use Shift-click.)

**Comment by mrtcode** [comment]
I guess Cmd + A is enough for now? Or do we want "Select All" option in Edit menu as well? How about annotation context menu?

**Comment by dstillman** [comment]
Cmd-A is enough.

**Comment by mrtcode** [comment]
In some cases Cmd-A can trigger Select All when it shouldn't. Also invisible annotations can be selected when trying to select multiple filtered annotations with keyboard or Shift-Click. But those issues will be solved after the keyboard navigation rewrite, because currently annotation sidebar doesn't have its focus.

**Comment by dstillman** [comment]
Maybe this is what you're referring to, but Select All shouldn't select all annotations when just in the PDF view. Better to do nothing. If this is hard to fix at the moment, it's a little more defensible when the sidebar is open, so if we could ignore Cmd-A when the sidebar is closed, that would be OK for now.

**Comment by mrtcode** [comment]
Ok, added your suggested fix. And, yes, it was one of the things I had in mind.

If all that sidebar and tag selector stuff looks good, it can be pushed to master. Although I'm now working on that keyboard navigation and focus handling rewrite. But it might take a bit time.
