### ISSUE TITLE
PDF Reader: Annotating gets stuck if you spam drag note annotations

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#2309]
I can get the PDF reader annotation tools (and the right-click menu) to become completely stuck if I create a note annotation and drag it around quickly a few times. You don't have to move it quickly, but you have to release and drag it again pretty quickly to get things to be stuck.

**Comment by mrtcode** [comment]
I'm unable to reproduce so far. But I have a few questions:
1) Is that in Standard or Stacked view?
2) Are you using mouse or trackpad?
3) Is right-click involved when you are doing this?
4) Are you releasing the dragging when cursor is over an opened note in the right sidebar? (there were issues in past when the previous iframe doesn't receive some mouse related events if you and up in another another iframe…)
5) Is there something that you can do to unstuck things? E.g. click on the PDF view again, switch tabs, etc.?
6) Is that Linux?

Maybe a video would also be helpful.

**Comment by adomasven** [comment]
> Is that in Standard or Stacked view?

I can reproduce in both although it works without the note editor open.

> Are you using mouse or trackpad?

Mouse.

> Is right-click involved when you are doing this?

No.

> Are you releasing the dragging when cursor is over an opened note in the right sidebar? (there were issues in past when the previous iframe doesn't receive some mouse related events if you and up in another another iframe…)

No, this is dragging the note annotation inside the pdf back and forth.

> * Is there something that you can do to unstuck things? E.g. click on the PDF view again, switch tabs, etc.?

Only closing and reopening helps. I have tried a handful of things like switching tools, but nothing seems to help.

> * Is that Linux?

Yes.

> Maybe a video would also be helpful.

My screen recorder won't capture clicks for some reason, but this is it. It stops responding at second 5.

https://user-images.githubusercontent.com/5899315/150292915-a1d944f5-dda6-47a7-9c32-ce95f169b311.mp4

**Comment by mrtcode** [comment]
I see you are getting a "resizing" cursor at the time when this happens. It shouldn't be here. I'll investigate on Linux. Thanks.

<img width="101" alt="Screenshot 2022-01-20 at 09 53 51" src="https://user-images.githubusercontent.com/6362989/150296261-b99e2be1-84de-461c-a762-91a494fa7554.png">

**Comment by mrtcode** [comment]
@adomasven I still can't reproduce this. Could you inspect what element is under the resizing cursor?

**Comment by mrtcode** [comment]
Oh, actually, I was able to reproduce that on windows. So, you can ignore my previous comment.
