### ISSUE TITLE
Mendeley PDF annotation import error: r2 is undefined

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2314]
https://forums.zotero.org/discussion/comment/397837/#Comment_397837

> [JavaScript Error: "Worker 'importMendeley' failed: {"mendeleyAnnotations":[
>
> […]
>
> ,"page":1,"type":"highlight","rects":[]}],"error":"{\"fileName\":\"chrome://zotero/content/xpcom/pdfWorker/worker.js\",\"lineNumber\":52802,\"columnNumber\":9,\"message\":\"r2 is undefined\"}"}" {file: "chrome://zotero/content/xpcom/pdfWorker/manager.js" line: 352}]

**Comment by mrtcode** [comment]
It now skips highlight annotations that don't have rects. Although unclear why those don't exist.
