### ISSUE TITLE
citeproc-rs wasm loaded even when disabled

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2363]
```
zotero(3)(+0000001): require('citeproc_rs_wasm')

zotero(3)(+0000002): Loading citeproc-rs wasm binary

zotero(3)(+0000000): HTTP GET resource://zotero/citeproc_rs_wasm_bg.wasm

zotero(3)(+0000031): HTTP GET resource://zotero/citeproc_rs_wasm_bg.wasm succeeded with 200

zotero(3)(+0000000): Initializing the CiteprocRs wasm driver

zotero(3)(+0000137): CiteprocRs driver initialized successfully
```
Can we skip this when the pref is off?

**Comment by adomasven** [comment]
We can, but then you'll need to restart Zotero to switch drivers. `Zotero.Style.getCiteProc()` is a synchronous function.

**Comment by dstillman** [comment]
> We can, but then you'll need to restart Zotero to switch drivers.

That's totally fine.

**Comment by adomasven** [comment]
Actually no restart necessary, I've added a trigger on pref change. Technically if you change the pref and then immediately have to initialized citeproc it will error, but I don't think that's of concern.
