### ISSUE TITLE
Disable embedded images in notes in group libraries where `filesEditable=false`

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2364]
Trying to sync with these in place will result in an error:

![Screen Shot 2022-02-20 at 11 24 44 PM](https://user-images.githubusercontent.com/783082/154889020-7397da65-2297-464b-a490-c4d7d2568b96.png)

After syncing, the image will still appear as long as the editor is loaded, but after restarting it will be an empty rectangle.

**Comment by dstillman** [comment]
Or, rather, it will result in this error as soon as I push out a small fix. Right now it will just result in a 500 error that fails the sync.

**Comment by mrtcode** [comment]
It might still create an empty placeholder, but we will try to solve that in future with a general mechanism to remove the placeholder if image creation fails.
