### ISSUE TITLE
Punctuation no longer ignored for sorting in items list

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2372]
https://forums.zotero.org/discussion/94803/papercut-beta-import-from-nbib-items-w-square-brackets-sorted-to-top

Regression from 13f48ec5c7dfdf030bdd37de4df1c55c5e2da42b — `\p{P}` isn't supported in Firefox 60. (Sorry for not catching that.) We have XRegExp, but I think we can just hard-code the relevant characters here.

**Comment by dstillman** [comment]
Just performance, but we can test. Maybe it's fine.

**Comment by AbeJellinek** [comment]
Yeah, it compiles to a native RegExp. I moved the compilation out of `getSortTitle`, so there shouldn't be any impact on performance besides from matching more characters.
