### ISSUE TITLE
Item key missing from zotero:// URLs in unsynced libraries

### ISSUE THREAD

**Issue by ydivho12123** [zotero/zotero#2407]
Annotation export error
The correct format should be:
zotero://open-pdf/library/items/5B9R969P?page=45&annotation=E29FFLBZ
But the export format is wrong, it will be exported as:
zotero://open-pdf/library/items/items?page=45&annotation=E29FFLBZ
Platform: Windows version zotero 6.0 beta

**Comment by dstillman** [comment]
How are you exporting?

**Comment by ydivho12123** [comment]
> 

Add Note from Annotations than Right click on the annotation Export Note

**Comment by ydivho12123** [comment]
> How are you exporting?


Add Note from Annotations than Right click on the annotation Export Note

**Comment by dstillman** [comment]
That's working fine for me. Can you provide a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> for an export that produces this?

**Comment by ydivho12123** [comment]
> That's working fine for me. Can you provide a [Debug ID](https://www.zotero.org/support/debug_output#debug_output_logging) for the process that produces this?

I'm doing this for the first time, is it this?  D1869443751

**Comment by dstillman** [comment]
> TypeError: citationState.state.removeCitations is not a function

@mrtcode will need to take a look.

**Comment by mrtcode** [comment]
The incorrect URI is produced when the cited item no longer exists in the library. I guess we shouldn't add the URI in this case.

The `is not a function` error is not related to this.

**Comment by dstillman** [comment]
It looks like this happens in a non-synced library:

https://forums.zotero.org/discussion/comment/401682/#Comment_401682

**Comment by ydivho12123** [comment]
> It looks like this happens in a non-synced library:
> 
> https://forums.zotero.org/discussion/comment/401682/#Comment_401682

Thank you!! Yes after sync the problem is solved.

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/markdown-translator-builder/commit/3144e2b5fced6417eb7737d565783112d61b5496
