### ISSUE TITLE
PDF reader: Note tool becomes unselected after use

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2418]
https://forums.zotero.org/discussion/95023/lock-annotation-tool-in-new-reader

**Comment by mrtcode** [comment]
That was by design. But sure, we can change that.

**Comment by mrtcode** [comment]
Actually I think this is more annoying that useful for average Zotero user. Because



#2438

**Comment by dstillman** [comment]
Hmm, yeah, I could see this being annoying. It seems like it really depends on your individual workflow and how you use note annotations. This might actually make sense as a pref. For now, maybe we should revert and require another toolbar click, since it's more disruptive to end up with an accidental annotation than to have nothing happen and need to click the toolbar button again.
