### ISSUE TITLE
HTML tree: Light items list column header with dark theme on Linux

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2424]
https://forums.zotero.org/discussion/95111/zotero-6-ui-glitch-on-linux

(First report of this, so not universal, I don't think)

**Comment by abraemer** [comment]
I have the same issue on a standard Ubuntu 21.10 (GNOME 40.4.0 X11) with the dark theme.

**Comment by ravila4** [comment]
I can confirm this too. Same issue with the PDF reader view.

**Comment by 01tot10** [comment]
Updated to `Zotero 6.0` just now, and the first thing I noticed was the funny looking column header!
Running `Ubuntu 20.04.4 LTS` with dark theme.
Here's how things look for me:
![Screenshot from 2022-03-18 11-19-57](https://user-images.githubusercontent.com/35490779/158975591-ce225fd1-8614-452e-af56-d8c1ea0950e6.png)
