### ISSUE TITLE
Safari connector extension icon flickering and disappearing

### ISSUE THREAD

**Issue by eliasweatherfield** [zotero/zotero#2425]
I have been using the latest beta version of Zotero for a year on an installation of macOS Big Sur that was fresh at the time of the first installation of Zotero.

The Safari connector extension has never been working. For months now, restaring Safari (latest 14) or (re-)activating the extension leads to the icon appearing and disappearing a few times over the course of a minute or so before it disappears completely (for all opened tabs).

![image](https://user-images.githubusercontent.com/52037235/159005856-859398d4-eaa4-413f-9002-f19487e583ec.gif)

**Comment by dstillman** [comment]
https://www.zotero.org/support/kb/safari_compatibility

**Comment by eliasweatherfield** [comment]
OK, I thought the issue described there was a different one (namely the extension not showing up in the list of extension at all). I tried the instructions without success before, but now they work. Thanks. Keep up the good work.
