### ISSUE TITLE
Next selected duplicates set not selected after merging

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2430]
https://forums.zotero.org/discussion/95309/merge-function-not-automatically-going-to-next-set-of-duplicate-citations

HTML tree regression? Or more recent? I didn't test if this is fixed in https://github.com/zotero/zotero/pull/2406.

**Comment by AbeJellinek** [comment]
Oh, never mind, it was only working on non-Date Modified sorts because of a partial fix I had added.

**Comment by AbeJellinek** [comment]
Alright, PR is now a full fix and I think ready to merge.
