### ISSUE TITLE
Note editor: Add font color option

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2433]
Lots of demand for this.

https://forums.zotero.org/discussion/88757/new-note-editor-change-the-font-color-in-the-notes and many others
https://forums.zotero.org/discussion/95378/note-editor-text-color-options-missing

**Comment by mrtcode** [comment]
So just another toolbar button? What about colors? The current highlight colors doesn't make much sense here.

If we really want the old colors palette we could add a color swatch with three dots which would expand the colors popup.

**Comment by dstillman** [comment]
Yeah, I think just a toolbar button.

I don't think a small set of predefined colors makes much sense here. Can we just display the XUL colorpicker in a popup for now? Recent colors would be nice but we can do without for the moment (and build our own HTML custom element colorpicker if there's not something available in newer Firefox).

**Comment by mrtcode** [comment]
You mean `customcolorpicker.xul` with default colors? We can show it in a popup, but connecting that popup to note-editor won't be faster than making a popup directly in note-editor (with the same default colors as in `customcolorpicker.xul`).

**Comment by dstillman** [comment]
OK, sure.

**Comment by mrtcode** [comment]
Fixed in zotero/note-editor@5548e40b

It was unnecessary to create another issue, but, anyway, the discussion regarding further improvements to color picker is here #2464.
