### ISSUE TITLE
How to automatically move tabs to new windows when opening new items ?

### ISSUE THREAD

**Issue by mengchaoheng** [zotero/zotero#2436]
I run zotero 6 on macOS, and I have to move the tab by hand everytime I open a new item.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/43166007/159221174-57cc3f4c-5e4c-438b-a045-c41eb988731b.png">

**Comment by dstillman** [comment]
Shift-double-click in the items list to open in a new window

Please post all questions, feature requests, and bug reports to the [Zotero Forums](https://forums.zotero.org).

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
