### ISSUE TITLE
Can't paste image/ink annotation into an external text editor

### ISSUE THREAD

**Issue by ydivho12123** [zotero/zotero#2447]
After highlighting the text in the pdf reader, ctrl+c and then ctrl+shift+v can paste the link with the jump to the highlight normally. But if it is highlighted in the box, repeat this operation but cannot paste the highlighted link and any content.

**Comment by mrtcode** [comment]
Thanks for reporting, but the next time just do it in Zotero Forums. We are aware about the issue.
