### ISSUE TITLE
pdftotext cannot handle UTF8 file paths

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#245]
The current version (as well as the current version from xpdf: 3.03) cannot handle UTF8 encoded strings for file paths.

Trying to retrieve metadata for a PDF file `Lin et al. - 2007 - Whole-Genome Cartography of Estrogen Receptor α Bi.pdf` results in "Could not read text from PDF" error.

Using pdftotext from xpdf, I also get the following error:
`I/O Error: Couldn't open file 'C:\Users\Aurimas\Desktop\firefox-zotero-dev\zotero\storage\EWG44J4V\Lin et al. - 2007 - Whole-Genome Cartography of Estrogen Receptor a Bi.pdf'`

Note the change from "Receptor α Bi" to "Receptor a Bi"

I tried using `runw` to launch the PDF in adobe and it worked fine. So the `α` is being mistreated on the pdftotext level.

I looked through the code and it looks like UTF8 encoding for filenames in Windows has been sort of... abandoned (?). In PDFDoc.cc:L74-81 seem to try and create a string that would work (i.e. `fileNameU`), but then it's never used. Furthermore, `fopen` only takes `char*` rather than `wchar_t*`, but I read around that supposedly `fopen` can handle UTF8, but I'm not entirely certain how.

I don't have time right now to look any further, but perhaps this is a pretty simple fix for one of you guys.

**Comment by pcunite** [comment]
I have this issue, easy enough to test for. Create a folder named "Folder ● Fun", put a PDF file in it. Open cmd.exe, and call pdftotext. You'll get error:
I/O Error: Couldn't open file 'C:\Path\Folder ? Fun\file.pdf'

Note the bullet point replaced with ?

**Comment by dstillman** [comment]
pdftotext is no longer used.
