### ISSUE TITLE
Problem copying from PDF reader via context menu

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2454]
https://forums.zotero.org/discussion/95483/cant-copy-paste-from-pdf-in-new-built-in-reader

Not tested

**Comment by mrtcode** [comment]
I wasn't able to reproduce this so far.

**Comment by Hankfirst** [comment]
I suffered the same problem. All possible copy and paste operations do not copy text in my case. version 6.0.3

**Comment by mrtcode** [comment]
@Hankfirst Does it happen with all PDFs? Does it happen on another computer?

**Comment by mrtcode** [comment]
Closing this, because this can't be reproduced and there haven't been any reports in the last 10 days. There were commits related to copying from pdf-reader, so hopefully that helped too.
