### ISSUE TITLE
Target selector collection change doesn't take for long download?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2458]
https://forums.zotero.org/discussion/95413/bug-report-zotero-connector-download-prevent-collection-changes

Didn't test this, but probably would be a problem in this repo.

**Comment by AbeJellinek** [comment]
Huh. I can't reproduce this with the linked article. For me the large file actually causes a different issue: the download finishes and the file is attached in the client but it still appears gray in the connector progress popup.

**Comment by AbeJellinek** [comment]
OK, I actually can reproduce this, but only if you manually move the item from one collection to another inside Zotero, not from the connector, while the attachment download is in progress. I think that might be what the user did:

>1. import a paper with Zotero Connector; (with a large attachment, and maybe slow network connection)
>2. after the paper (without attachment) imported, move to other collection;
>3. wait for attachment

Do we want to try to support that? We might be able to use Notifier events to change the target (`Zotero.Server.Connector.SaveSession.prototype.update`) if an item being saved is moved from the client before the save is done, but it sounds awkward (and what do we do if a single item is moved in a multi-item save?).

**Comment by dstillman** [comment]
Oh, no, we definitely don't need to support that.
