### ISSUE TITLE
Note editor: Annotation paragraph disappears if changed to header

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2467]
https://forums.zotero.org/discussion/95569/formatting-text-in-notes

**Comment by mrtcode** [comment]
No need to convert citation to plain text when converting it to a block that doesn't support citations? It's now also removed.

**Comment by mrtcode** [comment]
I assume we are talking about highlight conversion to plain text here, not highlight nodes support in headers, or do we?

**Comment by dstillman** [comment]
Ideally we'd probably keep them active, but for now plain text is fine if the alternative is them disappearing.

**Comment by mrtcode** [comment]
Well, it's easier to add support for highlight and citation nodes in headers than fix the conversion to plain text. Just another schema upgrade is necessary.

**Comment by dstillman** [comment]
OK
