### ISSUE TITLE
Note HTML export needs formatting hints for Word Processors

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#2469]
Report https://forums.zotero.org/discussion/95526/zotero-6-add-note-in-libreoffice-does-not-retain-formatting

I've tested inserting notes into LibreOffice and Word and various formats under the Aa menu produce wrong or no formatting at all. LibreOffice doesn't even recognize the \<em\> tags for italicizing. The formatting seems to be good for Google Docs. However if you just select the note contents and Ctrl-C, the resulting paste in Word and LibreOffice is formatted well. The HTML that notes provide for Word Processors should be similar to what it provides when copying the notes to clipboard.

**Comment by mrtcode** [comment]
Well, it is actually more or less the same output, except that it's wrapped in another div container. But that doesn't seem to have any effect.

I tried to replace [this line](https://github.com/zotero/zotero/blob/ef82becf004e8192a29ca04a0d63432aaf9b7e85/chrome/content/zotero/xpcom/data/notes.js#L193) with `return '<h1>test</h1>;` and I still don't get heading in LibreOffice. So the problem is probably somewhere else.

Regarding `<em>` I'll investigate.

**Comment by adomasven** [comment]
> Well, it is actually more or less the same output, except that it's wrapped in another div container.

Do you mean when copying with Ctrl-C? Are you sure? The heading formatting doesn't work in both LibreOffice and Word (although Word selects the heading style, but that's it).

**Comment by mrtcode** [comment]
I think we firstly need to investigate why it doesn't even work when returning `return '<h1>test</h1>;` from `Zotero.getExportableNote`.

**Comment by adomasven** [comment]
It's because Word and LibreOffice does not apply any styling based on HTML elements, it only does based on style specified on those elements (or their ancestors).

**Comment by mrtcode** [comment]
Ok, I tested what we get when copying vs inserting.

With Ctrl-A and Ctrl-C this is set for 'text/html' type in clipboard:
```
<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head><body><h1 data-pm-slice="0 0 []">test</h1></body></html>
```

When inserting to LibreOffice over the plugin, this is what is returned from `Zotero.Notes.getExportableNote`.
```
<div data-schema-version="8"><h1>test</h1>
</div>
```

If I try to return from `Zotero.Notes.getExportableNote` the same output as in the first example (that was set in the clipboard) it doesn't help.

So it seems when pasting to LibreOffice the HTML is interpreted in a different way than doing the insertion. And again, the output provided in `Zotero.Notes.getExportableNote` is the mostly the same and shouldn't have any meaningful differences comparing to what you get with Ctrl-C.

**Comment by adomasven** [comment]
Hmm. Yeah, what I'm doing in terms of API is comparable to doing Insert -> Text from File... But even there if I insert something with a `<h1>` tag it works correctly. I'll look into the APIs some more, but I think in the end we will still need to address this in Zotero code.

**Comment by mrtcode** [comment]
@adomasven Any progress on this?

**Comment by adomasven** [comment]
Ok, I believe this is fixed.
