### ISSUE TITLE
Citation not included in plain text copied from note

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2476]
https://forums.zotero.org/discussion/95688/option-to-not-hyperlink-annotations-in-notes
https://forums.zotero.org/discussion/95705/cant-copy-annotation-with-citation-from-note-viewer-pane

1. Add an annotation + citation to a note
2. Select All
3. Copy
4. Paste in a plain-text editor

The annotation is copied but not the citation.

Copying to Word as rich text works.

**Comment by mrtcode** [comment]
Yes, it's missing. But shouldn't the result of copying from inside a note should be the same as copying over Edit → Copy Note. I mean to use the current note translator.

**Comment by mrtcode** [comment]
Fixed in zotero/note-editor@e720701d.
