### ISSUE TITLE
Incorrect macOS version detection in Word plugin on Apple Silicon Mac

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2477]
https://forums.zotero.org/discussion/95703/apple-silicon-m1-on-mac-os-11-6-2
https://forums.zotero.org/discussion/comment/402320/#Comment_402320

I can't reproduce this, but both reports are from Big Sur.

**Comment by dstillman** [comment]
(Actually don't know if the second one is Apple Silicon.)

**Comment by dstillman** [comment]
Another, also on Big Sur: https://forums.zotero.org/discussion/95671/confused-by-zotero-pop-up-warning-macos-compatibility

**Comment by adomasven** [comment]
Closed with https://github.com/zotero/zotero-word-for-mac-integration/commit/5b98128d75f67823b94fe17e103850a6440e3c86
