### ISSUE TITLE
How to reset the default launch application for URI attachment?

### ISSUE THREAD

**Issue by PolarisPolaris** [zotero/zotero#2478]
<img width="306" alt="Screen Shot 2022-03-26 at 18 26 44" src="https://user-images.githubusercontent.com/43163254/160235461-ec6dbfc7-f8f1-401f-be67-186b64d115d9.png">

I set the launch application to Chrome for the URI ：notion://www.notion.so/2022-pdf-9c312a54191b46c4a501. 

I want to change the default launch application but I can't find where to set it.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
