### ISSUE TITLE
Note editor: Table editing support

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2480]
https://forums.zotero.org/discussion/95227/zotero-6-note-editor-html-view and others

People want tables.

**Comment by mrtcode** [comment]
We can relatively easily add table manipulation actions that are supported in ProseMirror, but the question is where. The quickest way would be to add everything to context menu. There would be "Insert Table" option, or if you are inside a table then a submenu under "Table" option would appear with the options below (maybe not all are necessary):
- Insert column before
- Insert column after
- Delete column
- Insert row before
- Insert row after
- Delete row
- Delete table
- Merge cells
- Split cell
- Toggle header column
- Toggle header row
- Toggle header cells

Another option would be to introduce a toolbar drop-down button with icons representing those table manipulation actions (I saw this somewhere, and it was looking quite good).
But toolbar is getting crowded, and soon we'll need to figure out how to display/hide that many buttons.

Third option is to show a three dots button in the focused cell which would popup the table manipulation actions (I saw this somewhere else as well).

**Comment by dstillman** [comment]
Context menu is certainly OK to start. Icons seem confusing for this many actions.
