### ISSUE TITLE
Map Preprint archiveID to generic number (& add to Scaffold)

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero#2481]
Two related issues:
1. It'd make sense conceptually to treat archiveID as a generic "number" under the hood. It's the same idea as numbers elsewhere (e.g. for patents or public laws: a unique ID within a specific database) and also has the same CSL mapping.
2. archiveID doesn't show up in Scaffold's autocomplete yet.

**Comment by dstillman** [comment]
Oh, that was an oversight re: `number`. I'll fix.

**Comment by dstillman** [comment]
Just to clarify, if we map `archiveID` to `number`, we can't add it to types that already have another `number` (Bill Number on Bill, Docket Number on Case, Document Number for Hearing, Parent Number for Patent, Episode Number for Podcast/Radio/TV, Report Number for Report, Public Law Number for Statute). Is that OK?

**Comment by adam3smith** [comment]
@bwiernik -- see dstillman's question above. Any concern from your end? I don't have any, I think these are conceptually identical so we shouldn't ever need both.

**Comment by bwiernik** [comment]
I think that's fine. 

Do we want to just call it Preprint Number or Number instead?

**Comment by adam3smith** [comment]
Or at least preprint ID (no clear preference in ID vs number). I don't love
the "archive" in there, because it doesn't actually go together with the
other archive fields

**Comment by bwiernik** [comment]
Preprint ID sounds good

**Comment by qqobb** [comment]
> Just to clarify, if we map `archiveID` to `number`, we can't add it to types that already have another `number` (Bill Number on Bill, Docket Number on Case, Document Number for Hearing, Parent Number for Patent, Episode Number for Podcast/Radio/TV, Report Number for Report, Public Law Number for Statute). Is that OK?

I haven't followed the related discussions in detail, but this could be problematic. You can have report items that have separate arXiv IDs and report IDs. See here: https://arxiv.org/search/?query=1&searchtype=report_num

**Comment by adam3smith** [comment]
>  You can have report items that have separate arXiv IDs and report IDs

I don't think that's a problem: arXiv items can also have two DOIs (the arXiv one and the one for the published article) and we only store one of them (the journal article DOI). Same here -- we'd only store the relevant `number` -- the way we're currently saving, that'd be the arxiv ID, but if we save these as reports, it'd probably be the relevant report ID (of which items can also have multiple, see the 2nd item in that list).

**Comment by AbeJellinek** [comment]
@adam3smith: Pull the latest zotero/translators to get autocomplete and type checking for preprints.
