### ISSUE TITLE
Math support in notes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2484]
https://forums.zotero.org/discussion/88175/math-support-in-new-note-editor and many older threads

We can take a look at https://github.com/benrbray/prosemirror-math.

(Not sure what would happen on export to word processors (embedded image?) or Markdown (embedded MathML?).)

**Comment by mrtcode** [comment]
Math support is already implemented in zotero/note-editor@2276cb40.

In word processors we just get plain LaTeX text.

**Comment by pluskid** [comment]
Thanks! @mrtcode. Is there any instructions on how to enable this? It looks like the code was submitted 27 days ago. However, on Zotero 6.0.13, which was released 23 hours ago, I could not figure out how to make it work.
