### ISSUE TITLE
PDF highlights not visible in different pdf viewer

### ISSUE THREAD

**Issue by 2er0** [zotero/zotero#2486]
Highlights in the new integrated PDF viewer are not directly persisted into the open pdf. 
Instead, they are persisted at some random point in time. 
It would be nice to have a button or shortcut such as 'CTRL + S' for saving the changes to disk and to see the change.

How to reproduce on MacOS:
* Open a PDF highlight something
* Close the PDF-viewer in Zotero
* Select 'Open in File' to get a window with the file directly
* Open with Adobe PDF reader or any other PDF viewer

Tested with Adobe Acrobat PDF Reader and MacOS Preview

**Comment by dstillman** [comment]
Please post all feedback to the Zotero Forums:

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

https://www.zotero.org/support/kb/annotations_in_database
