### ISSUE TITLE
Extra spaces in Markdown note export

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2503]
In a note, type `a`, `return`, `-`, space, `b`, `return`, `return`, `shift-return`, `c`

Then export the note to Markdown.

I get this (spaces shown as dots):

```
a

-···b·

··
c
```

There are two extra spaces in the list item and two on the line from the manual line break.

**Comment by mrtcode** [comment]
Those seems to be long-standing Turndown issues, but we will need to fix those by ourselves. For some of the issues there are community suggested work-arounds, but still strange why the default behavior is like this.

**Comment by mrtcode** [comment]
I have a fix for the lists problem, but the two spaces in place of `<br>` is the [correct](https://www.markdownguide.org/basic-syntax/#line-breaks) behavior according to Markdown standards. We can only question its usefulness if there aren't any characters before the line break.
