### ISSUE TITLE
PDF worker: Ignore highlight comment if it's approximately equal to extracted text

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2517]
https://forums.zotero.org/discussion/96180/duplicate-highlight-annotations

Also, to avoid cases like [this](https://github.com/jlegewie/zotfile/issues/460).

**Comment by dstillman** [comment]
Duplicate of https://github.com/zotero/zotero/issues/2326

**Comment by mrtcode** [comment]
Huh. Sorry.
