### ISSUE TITLE
[Bugs] The font of left bar and item overlap.

### ISSUE THREAD

**Issue by A11en0** [zotero/zotero#2518]
Env:
- Debian 10
- DPI 96
- WIndows Manager: i3 gaps

Theres' a display bugs with the Zotero client which are like the following picture:
![image](https://user-images.githubusercontent.com/33925232/162384476-0c3d847a-ee22-4324-ad28-67a6a1cab222.png)

As we can see, the fonts are overlapping together.

**Comment by adomasven** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org). See [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) and [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

We'll have a fix for this soon from https://github.com/zotero/zotero/pull/2488
