### ISSUE TITLE
Word Plugin Cannot Insert Citation into Mac M1 Word and Win Word

### ISSUE THREAD

**Issue by hacker-jerry** [zotero/zotero#2520]
**READ THIS BEFORE CREATING AN ISSUE**

Zotero does not use GitHub Issues for bug reports or feature requests.

Please post all such requests to the Zotero Forums at https://forums.zotero.org, where Zotero developers and many others can help. For confirmed bugs or agreed-upon changes, Zotero developers will create new issues in the relevant repositories.

Development questions involving code, APIs, or other technical topics can be posted to the zotero-dev mailing list at http://groups.google.com/group/zotero-dev.

See https://www.zotero.org/support/zotero_support for more information on how Zotero support works.

**Comment by hacker-jerry** [comment]
Mac Big Sur 11.6,(M1)
Zotero 6.0.4,
Word 365 latest version,

cannot insert citation into Word, only numbers but no reference.


https://user-images.githubusercontent.com/57279550/162481829-7a6fba02-4916-4158-8d69-98a352742751.mov

**Comment by AbeJellinek** [comment]
>**READ THIS BEFORE CREATING AN ISSUE**
>
>Zotero does not use GitHub Issues for bug reports or feature requests.
>
>Please post all such requests to the Zotero Forums at [forums.zotero.org](https://forums.zotero.org/), where Zotero developers and many others can help. For confirmed bugs or agreed-upon changes, Zotero developers will create new issues in the relevant repositories.

See above.

(This isn't a bug; scroll down and look in the page's footer.)

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/96220/word-plugin-cannot-insert-citation-into-mac-m1-word-and-win-word
