### ISSUE TITLE
Auto-rename preference ignored when translating, file types hidden pref ignored when recognizing

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#2522]
Relevant [translation code](https://github.com/zotero/zotero/blob/abe8c39c5b644407b0d8dd88a16844c1fae36f8d/chrome/content/zotero/xpcom/translation/translate_item.js#L896), relevant [Recognize PDF code](https://github.com/zotero/zotero/blob/924d29ff7efbd4cdb0719ec38f6ba9f7b6d8a09c/chrome/content/zotero/xpcom/recognizePDF.js#L291-L293) (ignores `autoRenameFiles.fileTypes` hidden pref).

**Comment by dstillman** [comment]
If there's a bug, what are the steps to reproduce? When saving from the web, we always rename, because a filename doesn't really exist. The pref only applies to files added manually.

**Comment by AbeJellinek** [comment]
Ah, do we? I didn't realize that was intentional. I can imagine some workflows where using the basename of the URL + `.pdf` would be sensible (which is the default behavior of `Zotero.Attachments.importFromURL` if it isn't allowed to rename), but I guess not many. In that case the only actual issue here is Recognize PDF ignoring `autoRenameFiles.fileTypes`, so removing `application/pdf` won't have an effect. Not sure that pref is widely used.
