### ISSUE TITLE
Note editor: Option to disable typographic quotation marks

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2524]
https://forums.zotero.org/discussion/comment/404884/#Comment_404884

This is a ProseMirror setting, right? Is there a flag to turn it off that we can expose as a preference? Are the quotation marks localizable, or is it always `“` and `”`?

As for where to put this, we'll probably have various settings for both the PDF reader and the note editor eventually (e.g., whether to show annotation colors by default when adding annotations to notes), but we might need to redesign preferences in the Firefox/Chrome style before doing that. Apple Notes has an Edit → Substitutions menu, but that doesn't really work for us. Maybe for now just the context menu of notes, the same place we have Check Spelling?

**Comment by mrtcode** [comment]
Yes, ProseMirror currently does that, but we can disable it, if needed.

So, for this we want to create a global preference that would be enabled/disabled over context menu. How it would be called? Do we want another popup sub-menu for more global settings like automatic color?

**Comment by dstillman** [comment]
I think the color setting needs to be in actual preferences, and so we either need a temporary place for that section or we need to first switch to Firefox-style content-pane preferences. We can get away with a context menu for this because it's pretty directly about the text editor box itself.

Context-menu option can be "Smart Quotes".

**Comment by mrtcode** [comment]
But it would be a global setting stored in preferences, or it should be for the current note session, or for the current Zotero session like spell checker currently works (a side effect of the internal spell checker engine)?

> Are the quotation marks localizable, or is it always “ and ”?

I'll need to pass the current locale quotation marks from Zotero, to localize them.

**Comment by dstillman** [comment]
Global setting

**Comment by mrtcode** [comment]
Is `extensions.zotero.note.smartQuotes` ok?

**Comment by dstillman** [comment]
Sure.

**Comment by mrtcode** [comment]
Note instance has to be reloaded for the option to take an effect (ProseMirror has to be reloaded).
