### ISSUE TITLE
Open PDFs using both Zotero or other software like Quicklook.

### ISSUE THREAD

**Issue by cjlCMU** [zotero/zotero#2528]
![image](https://user-images.githubusercontent.com/102497540/162598046-0b65ead0-596f-4fdc-b1f8-066b28bd505a.png)

Quicklook is faster than the built-in PDF reader of Zotero. So I want to use two ways to open PDF Options as appropriate. Adding a shortcut for the custom PDF reader is more convenient.

**Comment by dstillman** [comment]
Please post all feature requests and bug reports to the Zotero Forums.
