### ISSUE TITLE
Note editor: Use single newlines for Return within code blocks

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2532]
https://forums.zotero.org/discussion/comment/394571/#Comment_394571

When in a code block, Return should just create a newline and stay in the block.

**Comment by mrtcode** [comment]
As I mentioned in #2533, that already works for code block, which is called "Monospace" in the toolbar. Although the naming might be a bit confusing, but "Monospace" is more universal. We don't have an input rule for code block, just for inline code.
