### ISSUE TITLE
Note editor: Show gray background for entire code block rectangle

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2533]
![Screen Shot 2022-04-11 at 6 31 56 PM](https://user-images.githubusercontent.com/783082/162844095-e6032a79-5352-43db-9639-dfc36b2d94b5.png)

Not just the background of text.

**Comment by mrtcode** [comment]
We already do that, and this is just inline code in your example. Inline code is created in the same way as in GitHub.
