### ISSUE TITLE
Note editor: Trigger multiline monospace/code block with ```

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2549]
Following up from #2532 and #2533, it should be possible to start a multiline code block with three backticks, similar to GitHub.

I'm a little unsure about conflating monospace and code. If we're only going to have one, are we sure we don't want to just call it "Code"? We're also only wrapping in `<pre>` on output, not `<pre><code>`, as in the [original Markdown spec](https://daringfireball.net/projects/markdown/syntax#precode) and [on GitHub](https://github.github.com/gfm/#fenced-code-blocks).

**Comment by mrtcode** [comment]
> If we're only going to have one, are we sure we don't want to just call it "Code"?

Well, the thing that we're calling "Monospace" is more than a regular code block. It supports formatting the text inside it. I don't see value in that, but this was inherited from TinyMCE.
