### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by XuKer** [zotero/zotero#2550]
How to adjust the font size of the translated text on the right
![image](https://user-images.githubusercontent.com/26717462/163960798-16a4500c-858e-42a4-ad68-d477be095538.png)

**Comment by dstillman** [comment]
That's not from Zotero itself. You'll need to ask the developer of the plugin you're using.

**Comment by dstillman** [comment]
(And please post all questions about Zotero itself to the Zotero Forums, not here.)
