### ISSUE TITLE
Tab scroll arrow scrolls to wrong offset

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2553]
![Screen Shot 2022-04-19 at 6 56 44 PM](https://user-images.githubusercontent.com/783082/164114624-9fb6bab2-292b-4333-87d5-4fcb419f2e1b.png)

On macOS, if I scroll all the way to the right and then press the left arrow, it seems like it tries to scroll to align the tab border but gets it slightly wrong, so I end up with two lines.

**Comment by mrtcode** [comment]
Actually, the arrows currently scroll by 200px and a single tab is 100px therefore the borders look aligned.
