### ISSUE TITLE
Wider minimum tab size?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2554]
Without favicons, maybe we need a wider minimum tab size? #2552 would help, but four characters plus an ellipsis just doesn't seem that useful. A trade-off in terms of kinetic memory, but I think we might be slightly on the wrong side of that currently.

![Screen Shot 2022-04-19 at 6 59 35 PM](https://user-images.githubusercontent.com/783082/164115144-1b150903-66ed-4865-9e31-0c51e9607254.png)

**Comment by mrtcode** [comment]
Ok, I tried to reduce padding around title and slightly increase tab width.

Before:
<img width="1149" alt="1" src="https://user-images.githubusercontent.com/6362989/164413425-09e17b0f-955d-4700-84ea-bb2a1a2caffc.png">

After:
<img width="1150" alt="2" src="https://user-images.githubusercontent.com/6362989/164413436-cc0268a0-d46e-40cb-a45c-c495544ed882.png">

Is it better?

**Comment by dstillman** [comment]
Much better. One fewer tab, but they're actually usable. I think that's worth it.
