### ISSUE TITLE
Sort Library of Congress call numbers correctly

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2567]
The Dewey people are happy, but now the LoC people are unhappy:

https://forums.zotero.org/discussion/96616/changes-to-sorting-by-call-number-in-zotero-6-0-5
https://forums.zotero.org/discussion/96677/loc-numbers-not-sorting-correctly

**Comment by AbeJellinek** [comment]
There's [an entire paper](https://ejournals.bc.edu/index.php/ital/article/download/11585/9839/) on how hard sorting LCCNs correctly is. It includes an evaluation of some existing libraries, none of which sound great. The authors wrote their own implementation, but it's [a lot of PHP](https://github.com/scodepress/shelfreader/blob/01fe8ddb4b8b616a781eac3a0d89f512e321ee72/app/Models/Callnumber.php) and feels like it might be a little bit overkill.

If the LoC people were happy enough before, should we just go back to `collation.compareString` for call numbers that look somewhat like LCCNs?

**Comment by AbeJellinek** [comment]
OK, I see, I initially missed the fact that the Dewey tweaks _did_ improve handling of Cutter fields, so we don't want to go back to the old sort method entirely for these.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/406760/#Comment_406760

**Comment by AbeJellinek** [comment]
OK, I'll see what can be done.
