### ISSUE TITLE
doc request: zoo for zotero

### ISSUE THREAD

**Issue by min-xu-ai** [zotero/zotero#2573]
see https://github.com/mickstar/Zoo-For-Zotero/issues/165

Even though zoo for zotero is not an official app, I think it should be mentioned in the doc to direct people to it. I almost missed it after hours of google search. Many forum and articles are still referring to the zotfile/dropbox kind of sync methods to get pdf files to and from tablet for annotation purpose.

**Comment by dstillman** [comment]
Zoo is listed on the [Mobile](https://www.zotero.org/support/mobile) page, which is linked from both the <a href="https://www.zotero.org/support/">main documentation</a> and from [Plugins](https://www.zotero.org/support/plugins) (which itself is linked from the <a href="https://www.zotero.org/download/">download page</a>).
