### ISSUE TITLE
Pin library tab

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2575]
It should be always pinned. And we probably want to show an icon only, like browsers do. But does the icon need to change depending on which collection is selected?

https://forums.zotero.org/discussion/96684/keep-main-tab-fixed

**Comment by dstillman** [comment]
I don't think we should show an icon only — no reason to have a smaller click target, and slower to see where in the library you're going to end up. On macOS we also always show the library tab, which essentially functions as a window title, so it would be weird if it became small when you opened a PDF. I think a regular tab with an icon is fine. We can play with other UI treatments to differentiate it as pinned.

For now I would swap in the current row's icon when we change the tab title, same as Thunderbird.

**Comment by mrtcode** [comment]
Do we want the pinned tab to be like in the newer Firefox versions? Pinned tab is before the scroll arrow.

Although if there aren't scroll arrows it should be as it is now, I guess.

**Comment by dstillman** [comment]
Yeah, I think that's right. So basically what Firefox has but pinned by default and still with text.

**Comment by mrtcode** [comment]
Ok, do we want something like that?

<img width="1160" alt="Screenshot 2022-04-28 at 16 47 41" src="https://user-images.githubusercontent.com/6362989/165767617-595145d4-be05-4d7a-bbc8-f52c319c652d.png">
<img width="1158" alt="Screenshot 2022-04-28 at 16 48 18" src="https://user-images.githubusercontent.com/6362989/165767626-5e925726-5e93-4a2e-808d-c644ac5dac89.png">
<img width="1161" alt="Screenshot 2022-04-28 at 16 48 30" src="https://user-images.githubusercontent.com/6362989/165767629-83403f5d-d90f-4d81-83d8-7ebf65603aec.png">
<img width="1158" alt="Screenshot 2022-04-28 at 16 48 54" src="https://user-images.githubusercontent.com/6362989/165767635-d57f44e4-d769-4bc3-bce4-a08501314554.png">
<img width="1158" alt="Screenshot 2022-04-28 at 16 49 37" src="https://user-images.githubusercontent.com/6362989/165767638-63085e52-a097-477c-bdf9-70eb79609fc8.png">
<img width="1163" alt="Screenshot 2022-04-28 at 16 50 09" src="https://user-images.githubusercontent.com/6362989/165767643-6534fe10-8517-49a5-b04b-07f601867487.png">

**Comment by dstillman** [comment]
Yes, that's great.
