### ISSUE TITLE
[Upgrade Firefox] Note editor: Can't enter `ŕ` in Slovak keyboard layout on macOS

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2577]
https://forums.zotero.org/discussion/comment/406718/#Comment_406718

Entered with the `+`/`=` key followed by `r`

Not sure how hard this would be to fix, but I can reproduce it.

**Comment by mrtcode** [comment]
Reverting back. Single quotes are more important than this.

**Comment by mrtcode** [comment]
Already fixed by upgrading Firefox.
