### ISSUE TITLE
"Add tags..." prevents further clicks in annotation popup

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#2585]
1. Select a highlight
2. Click "Add tags..."
3. Click somewhere else to dismiss the tag search popup
4. Click in the comment field, or "Add tags..." again, or the three-dot menu in the popup

Popup will disappear instead of activating the clicked control.

**Comment by mrtcode** [comment]
Related: https://forums.zotero.org/discussion/96943/pdf-reader-request-keep-focus-in-annotation-editing-when-leaving-and-returning-to-zotero
