### ISSUE TITLE
can not find the corresponding options in "advanced configuration - config editor"

### ISSUE THREAD

**Issue by Xieleilab** [zotero/zotero#2608]
when using the plugin"mdnotes for zotero", if i write"{{publicationTitle}}" in it, the exported markdown will automatically replace it with the reference's pulication title name, however, if i want to Modify the format of the exported content corresponding to {{publication}}，i can not find the corresponding options in "advanced configuration - config editor"

**Comment by dstillman** [comment]
You'll need to ask the plugin developer.
