### ISSUE TITLE
PDF reader: Ability to assign tags to multiple annotations via drag and drop

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2616]
https://forums.zotero.org/discussion/97007/feature-request-bulk-annotation-tagging

Same as in the library tag selector — select multiple and drag to the bottom left.

**Comment by mrtcode** [comment]
How about tab unassignment from multiple annotations? Should it unassign if you drop annotations on a tag that is already assigned to all of them?

**Comment by dstillman** [comment]
No, [same as the main tag selector](https://www.zotero.org/support/collections_and_tags#removing_tags_from_items): Cmd (Mac) or Shift (Windows/Linux) while dragging to unassign.
