### ISSUE TITLE
Link Mendeley citations in documents to imported items

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2622]
From [Mendeley Import](https://www.zotero.org/support/kb/mendeley_import):

> When using the Zotero word processor plugins, document citations created with Mendeley won’t currently be linked to imported citations in your Zotero database. Zotero’s word processor plugins can, however, read Mendeley citations and their embedded metadata, so you can continue using the same documents with Zotero and insert additional instances of those citations by choosing from the “Cited” section of the search results in the citation dialog.

We store Mendeley item UUIDs for imported items. I haven't checked what metadata Mendeley stores in field codes, but if they're using the UUID, it would be nice to automatically use the imported item, both for metadata edits and for disambiguation (e.g., so that adding the imported item from the library itself wouldn't add a duplicate bibliography entry).

We could also consider just rewriting the item as a Zotero citation on refresh, which would probably be easier, but that might cause problems for people trying to collaborate with other Mendeley users.

**Comment by adomasven** [comment]
I've downloaded Mendeley Desktop for Linux, inserted a citation into a document, imported the Mendeley library into Zotero, and checked the UUID that Mendeley Desktop puts in a LibreOffice document citation with Zotero, but I am not getting any items from ` Zotero.Relations.getByPredicateAndObject('item', 'mendeleyDB:documentUUID', UUID)`. I've also tried `remoteDocumentUUID`. @dstillman @tnajdek thoughts?

**Comment by adomasven** [comment]
Ok, so if I use a local mendeley import, I can get the related items. Given that this is not the recommended method to import, and the online import has different UUIDs than what Mendeley stores in documents, I don't think this can be done easily.

We could use Zotero's duplicate detection code to search for Mendeley imported items and link them that way in citations where we detect Mendeley's URIs, but that's quite more complicated than just linking URIs.

**Comment by dstillman** [comment]
Ugh. What about two synced Mendeley Desktop installs, though? How does the Mendeley Word plugin identify those items?

**Comment by adomasven** [comment]
Hmm, that's a good question, actually. I originally had the latest Mendeley Desktop installed, inserted some citations, then reinstalled Mendeley Desktop 1.18, synced with it, imported into Zotero, and the UUIDs matched, so they have to be stored in the remote repo somewhere. Our import is not storing them when doing an online import then, it seems? @tnajdek ?

**Comment by tnajdek** [comment]
I did a little bit of reverse engineering. Based on something in the request (User Agent maybe?), Mendeley servers inject extra key "client_data" into the response, that key is a JSON that contains "desktop_id".

We can update importer to obtain and store this correctly but it won't work for libraries that have already been imported.

**Comment by dstillman** [comment]
This is for each item? So the `desktop_id` is what we're storing as `mendeleyDB:documentUUID` for each item when doing a local import?

Shame about existing imports, but would still be great to be able to say that new imports could continue to use documents. And if a reimport would fix for people who haven't made many changes, that would be good too.

**Comment by tnajdek** [comment]
OK, I'll tweak the importer.
