### ISSUE TITLE
citeproc: Add space after first field in plain-text mode when style uses `second-field-align`

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2633]
https://forums.zotero.org/discussion/comment/408701/#Comment_408701

This affects IEEE style when pasted into a plain-text editor.

We should see if this is an easy fix in citeproc-js. If not, we can check whether it's fixed in citeproc-rs once CSL 1.0.2 support is in.

**Comment by zepinglee** [comment]
https://github.com/Juris-M/citeproc-js/blob/98a436856b5a0380b34aff14846cc22bcc1fa0fd/citeproc.js#L22263-L22265

`return str + " ";` should work.

**Comment by dstillman** [comment]
Oh, nice! That seems like the correct fix, but some of the main styles — ACS, AMA, Vancouver — already do what I originally suggested in the forums and just add a hard-coded space to the `citation-number` suffix, which means this would result in double spaces for those styles, while fixing IEEE and Nature.

I think we'll need to take this to the CSL list and get wider agreement on how to handle this. I'll post there.

Thanks for the patch!

**Comment by dstillman** [comment]
https://discourse.citationstyles.org/t/space-after-first-field-in-plain-text-mode-when-using-second-field-align/1762

**Comment by dstillman** [comment]
Rolled out in the latest <a href="https://www.zotero.org/support/dev_builds">Zotero beta</a>.

Do you want to submit this upstream to citeproc-js?

I'll submit patches for ACS/AMA/Vancouver upstream after we've released Zotero 6.0.9 with this change.

**Comment by dstillman** [comment]
I've submitted this upstream.
