### ISSUE TITLE
HTML tree: Slow sorting of new item in large library

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2634]
https://forums.zotero.org/discussion/comment/408030/#Comment_408030 shows an Zotero Connector timeout due to slow saving in a 120K library, and at least part of the problem seems to be just sorting the item into place:

```
(3)(+0000851): Sorting items list by dateModified, firstCreator, date, title, dateAdded descending for 1 item

(3)(+0005789): Sorted 1 item in 6556 ms
```

That only accounts for a little under half the timeout time, and there's some slow stuff after, but sorting a single item into the tree certainly shouldn't take 6.5 seconds. I believe we had some optimizations previously to sort single items into place without resorting the whole tree, but possible they got removed? (I might also be thinking of the tag selector, where I think we do that.)

**Comment by adomasven** [comment]
I didn't touch the sorting code:
https://github.com/zotero/zotero/blob/a406e62fd3b29d2216b3a8ee28e0b19deb9cb6da/chrome/content/zotero/itemTree.jsx#L1442-L1454

I measured it just now and sorting a full tree with 40k items for me takes 1.7-2.0s, whereas sorting a single item takes about 1.2-1.5s. So this is just the firefox sort function being not very fast and [looking on StackOverflow](https://stackoverflow.com/questions/38732480/native-javascript-sort-performing-slower-than-implemented-mergesort-and-quicksor) it seems like this isn't just our Firefox runtime either. We could try adding our own sorting function here, but that seems like a nuclear option to solve an edge case.

**Comment by adomasven** [comment]
Closing unless there's new info here. Probably much faster with fx102 anyway.
