### ISSUE TITLE
How sync my database into zotero.sqlite from Zotero Web API in commandline?

### ISSUE THREAD

**Issue by yindaheng98** [zotero/zotero#2637]
**More specifically, how to download my database from Zotero Web API and generate a zotero.sqlite, not in Zotero GUI, but in command line?**

I have 2 PC and 1 Laptop, all of them have Zotero installed and sync with my account. I also have a NAS in my home, and now I want to backup my Zotero database automatically into my NAS.
Just backup the zotero.sqlite file is not good for me since I can not go back home and upload zotero.sqlite file every night.

So, I want to find a command line program to download my database from Zotero Web API and generate a zotero.sqlite in command line, so that I can just deploy it in my home and automatically backup my zotero.sqlite to my NAS every midnight, even if I am not at home.

Does this command line program exist or how can I write it?

**Comment by dstillman** [comment]
Please post general Zotero questions to the Zotero Forums and development questions to <a href="http://groups.google.com/group/zotero-dev">zotero-dev</a>.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

What you're asking for doesn't exist and doesn't make sense. Just back up your Zotero data directory incrementally with the rest of your computer:

https://www.zotero.org/support/zotero_data#backing_up_your_zotero_data
