### ISSUE TITLE
Citaiton Key column disappears and Citation key format does not update 

### ISSUE THREAD

**Issue by DongGilKim** [zotero/zotero#2644]
Mac OS Monterey, Zotero 6.0.8, zotero-better-bibtex-6.7.1.xpi

I was trying to move from Mendeley to Zotero.... now I am observing some issues in Zotero
Literally, Citaiton Key column disappears and Citation key format does not update!!!

**Comment by dstillman** [comment]
BBT issues should be reported to the BBT developer on GitHub.
