### ISSUE TITLE
Add Edit button in proxies list

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#265]
http://forums.zotero.org/discussion/28186/

**Comment by rmzelle** [comment]
Would you like to see a similar button for the site-specific Quick Copy settings list? If I hadn't looked at the code, I'd never have figured out that double-clicking an entry allows it to be edited.

**Comment by dstillman** [comment]
Yeah, I was just thinking the same.

**Comment by rmzelle** [comment]
I'm taking this on.
