### ISSUE TITLE
Native wayland support

### ISSUE THREAD

**Issue by cvanelteren** [zotero/zotero#2653]
Hi,

Is there any update on native wayland support for zotero? Running zotero defaults to x11 and causes segmentation fault when running under wayland, i.e. `DISPLAY=wayland-1 zotero` fails with segmentation fault. Thanks in advance!

**Comment by dstillman** [comment]
As noted in the text that you deleted, we don't use GitHub Issues for support.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

We're planning to upgrade to a newer Firefox base later this year, so anything that works in current versions of Firefox will likely work after that.

**Comment by cvanelteren** [comment]
Good to hear! In the mean time, are there any possibilities to build this from source with the new version? Drag and drop is not registered properly under xwayland making dealing with local pdfs a bit cumbersome. Apologies for not reading the link, kinda used using git for this. Will look to the forums next time.
