### ISSUE TITLE
PDF reader: Shortcut keys for tools

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2657]
https://forums.zotero.org/discussion/97809/assign-hotkeys-to-the-different-notetaking-options-in-the-native-pdf-editor and many others

We should think about some options here, and see what other tools do. Single letters are probably too complicated — they'd kind of need to be localized, and some would conflict with existing shortcuts (e.g., Note can't be N if N is Next Page).

Maybe Option/Alt-number-key? So Option-1 is Highlight, Option-2 is Note, etc.? (Option-4 could even simulate a click on the color menu?) And if we add additional tools, or if the toolbar becomes customizable, they'd automatically adapt?

**Comment by mrtcode** [comment]
How about just 1, 2, 3, 4 keys without Option/Alt? 4 would switch color.

**Comment by dstillman** [comment]
Hmm, that's an interesting idea, but given that the number keys do tag assignment in the library view, I think it's a little confusing to trigger a totally different action here. (And once we unify tags more, it's not impossible we'd want to make it possible to assign tags to individual annotations with the number keys here as well.)

**Comment by mrtcode** [comment]
All right, then Option/Alt-1/2/3/4. And the key 4 will cycle over colors. If we introduce more tools, we will tweak the keys order as well.
