### ISSUE TITLE
Add context menu options to copy/save an image in pdf-reader and note-editor, as in web browsers

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2664]
https://forums.zotero.org/discussion/97815/how-to-copy-a-figure-from-note-editor
https://forums.zotero.org/discussion/98070/have-area-highlight-exported-as-image-using-export-note-feature

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/95447/pdf-viewer-ability-to-take-snapshot

**Comment by mrtcode** [comment]
I would suggest to allow drawing an area (in the same color as text selection) when Cmd/Ctrl is pressed, and then you would be able to copy it with Cmd-c or over context menu. It would just be like text selection, but for area.

**Comment by dstillman** [comment]
Oh, I don't think we need to support that at all — the OS provides area screenshot functionality that people can generally use here (and most people won't know or care about the subtleties of zoom level–dependent image resolution). I just think we're filling an obvious hole in functionality where you can't copy an image annotation that you've already created.
