### ISSUE TITLE
fx-compat: Use ACE or Monaco in Style Editor

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2665]
Our timed-textbox went away with XBL. Possible we'll need that somewhere else, but seems like we might as well replace this with ACE or Monaco anyway. I have no idea how hard the integration is, but any reason not to use Monaco for csledit.xhtml (and in the Run JavaScript window?) and stop bundling ACE?

If we could integrate validation against [the CSL schema](https://github.com/citation-style-language/schema/), that would be amazing, but we could start with just an XML mode.

**Comment by AbeJellinek** [comment]
Fixed by 9c837b3361985c66c067c7655250ee96a64f571f.
