### ISSUE TITLE
PDF reader: Fix double-click-and-drag text-selection behavior

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2667]
https://forums.zotero.org/discussion/98012/making-note-highlights-easier

This works in the pdf.js demo, but it looks like our selection-dragging functionality may be interfering?

**Comment by mrtcode** [comment]
PDF.js uses regular text for its text layer. We have a completely custom text layer that just calculates everything and draws on canvas (because interacting with text in browser is too limiting. 

But yes, we can implement this.

**Comment by dstillman** [comment]
This is great!
