### ISSUE TITLE
PDF reader: Remove "Rotate 180°" option

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2669]
https://forums.zotero.org/discussion/comment/410410/#Comment_410410

Maybe just "Rotate Right" and "Rotate Left"? We have "Rotate 180°" because rotating is a little slow, but it's a bit clumsy. If people need to rotate twice, is it really the end of the world?

@mrtcode?

**Comment by mrtcode** [comment]
Well, after doing rotation, PDF is reloaded and thumbnails view state is completely lost — scroll and selected pages. It means you have to scroll and reselect everything .Therefore I would need to fix that before removing the 180° option.

**Comment by dstillman** [comment]
OK, then I guess we could still do "Rotate Right", "Rotate Left", and "Rotate 180°" for now.
