### ISSUE TITLE
When Group Libraries is selected, adding new collection adds it to My Library

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#267]
1. Click on "Group Libraries"
2. Click on "New Collection..." button at the top of the collection tree.
3. Enter name and click OK

Collection is added to My Library. The correct behavior should probably be to either disable the "New Collection..." button when "Group Libraries" is selected, or alert the user that this action is only valid within a library.

Also, another nit, when adding a new collection, if you go with the default "Untitled" and keep adding collections like that, you get default names like "Untitled 1" "Untitled 2". The only "problem" is that the numbering is not library-specific, but appears to span group libraries as well. So if I have "Untitled" in My Library and I go to add a collection to the group library, the suggestion becomes "Untitled 2". I don't see any downside to this, but I thought I'd point it out.

Finally, a bit OT and also a nit, but either the "New Group..." or the "Group Libraries" icons are a bit misleading. I think that the individual group libraries should just have the current "Group Libraries" icon and we could possibly get rid of the whole "Group Libraries" item. Though it is somewhat useful if you want to collapse all group libraries.

**Comment by dstillman** [comment]
"Group Libraries" header is gone in 5.0, and "Untitled" issue is fixed on 5.0, so closing.
