### ISSUE TITLE
fx-compat: First dialog grows after displaying

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#2703]
The item/collection delete confirmation dialog, for example. Starts out a bit smaller and jumps to a bigger size as it's fading in. This always happens on the first display of a dialog since launching Zotero.

**Comment by AbeJellinek** [comment]
This is going to be annoyingly difficult to fix for an issue that seems so basic (but looks weird enough that it needs to be fixed). The bug is actually present in Firefox 102.0.1, too - quit the browser, start it again, then immediately open a container tab, go to `about:preferences#containers`, and try to delete the container that you just opened a tab in. The size will jump around a bit as it initializes.

I think the issue is caused by [this](https://searchfox.org/mozilla-central/source/toolkit/components/prompts/content/commonDialog.js#137) line. I'm pretty sure we could safely just remove it, but that would require patching Mozilla scripts, and I don't have any experience with that. @dstillman, thoughts?

**Comment by dstillman** [comment]
Unfortunately without it we get this, which is also not great (and something we see in Fx60, though this line isn't new):

![without](https://user-images.githubusercontent.com/783082/180113517-9383062f-bbef-44dc-acfa-131fdf550b03.png)

For reference, this is after `sizeToContent()`:

![sizeToContent](https://user-images.githubusercontent.com/783082/180113605-13e6ce77-90fd-40e2-a647-3a97b8700069.png)

Not great options.

This is the actually correct version, which is what happens on the second open:

![second-open](https://user-images.githubusercontent.com/783082/180113628-e454d5d7-677f-478a-a5e3-9faeb4e3287e.png)
