### ISSUE TITLE
PDF reader: Back/forward button in the toolbar

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2707]
https://forums.zotero.org/discussion/98442/feature-request-navigation-in-pdf-reader and many others

I think we've gotta do this. It would be better if we had a customizable toolbar (e.g., Preview doesn't include this in its default set, but it's an option in the palette), but given that we don't I think it merits being in the toolbar.

**Comment by raul-lezameta** [comment]
I have a feature suggestion. I would really appreciate it, if you also considered mapping the back and forward navigation to the mouse side buttons, like is done in web browsers for example to move to next/previous sites. A lot of other PDF readers also implement it like that, and I find it really intuitive to use.

Not sure if this is the right place to suggest this, but it seemed in context with the topic of the issue. Hope it's fine :).

Thanks for your hard work, all you guys. Zotero really is a masterpiece of a software, and the inbuilt PDF reader made it even better!!

**Comment by qqobb** [comment]
This could probably make use of the navigation buttons that are planned for Zotero's library tab (#803), at least in the longer run. An additional option could be a back button added to the PDF reader's context menu popup. (The PDF viewer in Firefox has this.)

**Comment by dstillman** [comment]
I think that's too prominent. I would just put them to the right of Previous/Next Page.

**Comment by dstillman** [comment]
We could also consider just having ←, unless we think that's too weird/unbalanced. But really it's Back that people want.

**Comment by dstillman** [comment]
I meant between. My first thought was that they shouldn't be separated, but I'm not really sure why — when you click Back you're generally going to be changing pages anyway, and the cleanliness of keeping the arrows together might be more important than any concerns about logical coherence.

**Comment by dstillman** [comment]
Maybe before Previous Page is fine, though…

**Comment by mrtcode** [comment]
> Maybe before Previous Page is fine, though… With a spacer?

Yes, we can try that.

**Comment by mrtcode** [comment]
Feels a bit weird, but maybe need to get used to it.

<img width="551" alt="Screenshot 2022-07-18 at 16 24 59" src="https://user-images.githubusercontent.com/6362989/179523020-5c1fbd2e-abb4-4dc2-a1e3-cdd043b2ffdd.png">

**Comment by qqobb** [comment]
> Feels a bit weird, but maybe need to get used to it.

I'd perhaps move the zoom buttons to the right of the annotation tools, next to the search button. The back button would then be close to where you'd expect it in a browser. The zoom buttons should probably be lower in the visual hierarchy, which usually goes from left to right in western cultures.

I think it should be ok if the search and zoom icons are not far from each other. They're similar, but people can clearly distinguish them.

**Comment by dstillman** [comment]
The arrows should be the same color. We can just rotate one of the other arrows 90°.

And @qqobb may be right that moving Zoom Out, Zoom In, and Zoom to Page Width somewhere else could make sense, but let's deal with that separately. (And I do think that having two magnifying glasses used in totally different ways next to each other isn't great.)
