### ISSUE TITLE
PDF reader: Add annotation author names to sidebar filter options

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2709]
https://forums.zotero.org/discussion/98356/pdf-annotations-authorship

**Comment by mrtcode** [comment]
How does it look?

<img width="240" alt="Screenshot 2022-07-19 at 17 25 51" src="https://user-images.githubusercontent.com/6362989/179775136-db43b3d1-c421-46c8-abdb-77cff58acb6d.png">

**Comment by dstillman** [comment]
`@Me` in bold just to make it more prominent, like colored tags?

I'm not sure the `@` is going to work with full names, which is what these will often be. E.g., `@Alfred Einstein` is a little awkward.

**Comment by mrtcode** [comment]
> `@Me` in bold just to make it more prominent, like colored tags?

Yes. Also we'll need to localise it as well. What else could be used instead of "Me"? Some symbol?

> The `@` is nice to differentiate, but I'm not sure it's going to work with full names, which is what these will often be. E.g., `@Alfred Einstein` is a little awkward.

It would look like this:
<img width="238" alt="Screenshot 2022-07-20 at 16 29 54" src="https://user-images.githubusercontent.com/6362989/179994547-b022173f-0db4-4ff6-83a8-35a2dc995691.png">


Or maybe italic?
<img width="242" alt="Screenshot 2022-07-20 at 16 32 07" src="https://user-images.githubusercontent.com/6362989/179995022-f42900b7-7ca2-49e0-8efb-097cde6033d4.png">

**Comment by dstillman** [comment]
That first one isn't bad, but the `@` is maybe still a little weird? It's sort of borrowing the mention concept and using it in a context where it doesn't really apply, and where there are some incongruities — specifically, "Me" (not a username) and spaces within names (generally not used in any system where you're using `@` to mention). What about a little monochrome user icon?

I guess it's also worth considering whether we'd ever actually support mentioning people by `@` in annotations. If you could type `@Alfred` and it would offer `@Alfred Einstein` as an autocomplete from group members and it would be styled within some shaded bubble to indicate that it was a single entity, maybe this would make more sense? (Though `@Me` would still be a little strange.)

**Comment by mrtcode** [comment]
We can just use the current user display name instead of "Me".

> What about a little monochrome user icon?

Do you have an example?

> I guess it's also worth considering whether we'd ever actually support mentioning people by @ in annotations.

We can think about that when we have a better understanding about comment threads that we consider implementing.

**Comment by dstillman** [comment]
Something like this?

https://fontawesome.com/icons/user?s=solid

**Comment by dstillman** [comment]
Oh, sorry, I meant that we'd show it before each user, instead of `@`.

**Comment by mrtcode** [comment]
Ok, this is how it looks:
<img width="239" alt="Screenshot 2022-07-22 at 12 20 48" src="https://user-images.githubusercontent.com/6362989/180408034-1109c1f8-e3b3-494b-baa5-ebcfe102aecc.png">

**Comment by dstillman** [comment]
Works for me

**Comment by mrtcode** [comment]
Maybe instead of "Me" it should show the current author name, because, I noticed, that we're showing the current author name for your own annotations as well. I forgot that we're doing this now, because originally we were keeping author name empty for your own annotations.

**Comment by mrtcode** [comment]
It could look like this:
<img width="254" alt="Screenshot 2022-07-27 at 12 49 55" src="https://user-images.githubusercontent.com/6362989/181218208-80593d28-c5e3-4e28-a139-81745fa2bb69.png">

Also, external annotations (in group libraries) don't have any author name, but maybe it could make sense to be able to filter on them as well? Or maybe to filter locked annotations?

**Comment by dstillman** [comment]
I don't think we need the bold. It's first, and people can recognize their own name.

I think we can hold off on filtering external and/or locked until people ask for it. I'm not totally sure what the use case would be.
