### ISSUE TITLE
Two hardcoded strings that need to be moved to locales

### ISSUE THREAD

**Issue by ezellohar** [zotero/zotero#2710]
The file:
`zotero/chrome/content/zotero/standalone/standalone.js`
has on line 196-199 the following code:
`menuitem.label = 'Export PDF…';
}
else {
menuitem.label = 'Export PDFs…';`

Those two string `export PDF` need to be moved to locales to be able to translate them

**Comment by dstillman** [comment]
Fixed — thanks!
