### ISSUE TITLE
fx-compat: Restore guidance panels

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2711]
https://github.com/zotero/zotero/commit/8ff75607a5aa38293bac19e801911c1abff429fc

Are these all broken?

**Comment by AbeJellinek** [comment]
Fixed in 26a239839919ea2d5d32c0f6e01b57bfa5f79792.

While we're at it, why do we [only show the creator guidance on `bookSection` items](https://github.com/zotero/zotero/blob/26a239839919ea2d5d32c0f6e01b57bfa5f79792/chrome/content/zotero/elements/itemBox.js#L1919)? Is that correct?
