### ISSUE TITLE
Broken "Add Item(s) by Identifier" box

### ISSUE THREAD

**Issue by julianbarg** [zotero/zotero#2715]
*Zotero 6.0.10 on Ubuntu*

The "Add Item(s) by Identifier" box does not display strings correctly and may have some issues with encoding. A simple example: I copy and paste a doi from a pdf into the search. The doi looks correct, but the search fails. So I c&p that doi into doi.org and notice that there is an extra space at the end of the string. Two issues: (1) the "Add Item(s) by Identifier" box does not show the extra space, so I can not delete it. (2) I would expect Zotero to do some basic cleaning up of the input in the background to ensure a successful search. Basic stemming of the string for sure. Other times I have had issues with presumably encoding where there was no mistake in the string. The search would fail, so I would paste it into the browser url bar. Looks correct, so I c&p it back into Zotero, and then it works. (3) Firefox and other browsers take care of encoding and styling--I would have expected Zotero to do the same. Another place where I noticed this issue is titles that use italics: every now and then I see titles with italics html tags (`<i>` and `</i>`) showing up in Zotero after adding an item by doi. Obviously that is not being parsed correctly.

**Comment by AbeJellinek** [comment]
Can you provide the exact identifier that failed to resolve in Zotero? With original spacing if you can remember where it was.

>I would expect Zotero to do some basic cleaning up of the input in the background to ensure a successful search. Basic stemming of the string for sure.

It does, so if the string you posted is correct apart from some spacing around the identifier, this is a bug and we'll fix it.

As for:

>I see titles with italics html tags (`<i>` and `</i>`) showing up in Zotero after adding an item by doi. Obviously that is not being parsed correctly.

It is being parsed correctly. See <a href="https://www.zotero.org/support/kb/rich_text_bibliography">this page</a> on the wiki. You should see the title rendered with correct italics in the center pane in Zotero, and generated citations will also contain correct italics.

(In the future, reports like this should be posted on the forums first. We'll open GitHub issues for specific bugs that are causing the incorrect behavior.)

**Comment by julianbarg** [comment]
Apologies, came across GitHub before I came across the forum! Just cleaned all the strings, but I come across these fairly frequently, so I will paste the next one I see and link the pdf so we can see if that is reproducible.

As for the html tags, can confirm that that works as intended then. I had some problems exporting those citations, but that would probably be an issue with the Better BibTex extension.
