### ISSUE TITLE
Don't add newline above annotation when dragging to empty note

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2717]
https://forums.zotero.org/discussion/comment/412860/#Comment_412860 (1)

(I could've sworn I've reported this before — it's bothered me for a long time — but I can't find a ticket for it.)

**Comment by mrtcode** [comment]
Yes, that's probably a regression.

**Comment by mrtcode** [comment]
Ok, so this issue reappeared after trying to fix #2556. Also [this](https://forums.zotero.org/discussion/comment/413061/#Comment_413061) is the same issue. And I can reproduce even more weird issues (i.e. note corruption) related to all this.

The thing is that I already tried to find the cause of insertion anomalies but without success. I'll try to dig deep now.
