### ISSUE TITLE
Add "Create Book Section" menu item above "Duplicate Item" for Book items

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2732]
https://forums.zotero.org/discussion/comment/413762/#Comment_413762

Duplicate, change type to Book Section, add related-items relation, maybe open Title field?

**Comment by AbeJellinek** [comment]
We could also support the opposite for Book Section items if you think that makes sense.

**Comment by AbeJellinek** [comment]
`setType()` doesn't already handle `bookSection` -> `book`, though.

**Comment by qqobb** [comment]
This is what Zutilo is currently doing: https://github.com/wshanks/Zutilo/blob/33723e3968b4809214b24d3608bbd1056e63010f/addon/chrome/content/zutilo/zoteroOverlay.js#L844-L954

**Comment by AbeJellinek** [comment]
Thanks, that seems like a reasonable approach and we can do something similar when we implement this.

FWIW, though, it doesn't seem like that code is actually making the creator modifications that it's trying to - [this line](https://github.com/wshanks/Zutilo/blob/33723e3968b4809214b24d3608bbd1056e63010f/addon/chrome/content/zutilo/zoteroOverlay.js#L874) replaces `author` creator objects with nothing but the ID for the nonexistent type `bookAuthors` (should be `bookAuthor`), and then the modified `creators` array isn't actually used.

**Comment by qqobb** [comment]
> FWIW, though, it doesn't seem like that code is actually making the creator modifications that it's trying to

Yeah, I haven't actually looked at the code. I'm also not dealing with book author creator types in my Zotero collection, so I'm not sure about that change. Usually, I'm dealing with book editors and authors of book sections.

As for a possible shortcut (I think you mentioned this somewhere), I think we could at some point change Zutilo to use Zotero's "Create book section" function. So people could use Zutilo for a shortcut. This way it would be more flexible, I think. (Unless you'd make the shortcut optional in Zotero.)

**Comment by dstillman** [comment]
Closed by https://github.com/zotero/zotero/pull/2755/commits/212fd56fae0c066531f6269abcfff7a26c83a7e7
