### ISSUE TITLE
Accessing UI Elements in MacOS 

### ISSUE THREAD

**Issue by hasantahir** [zotero/zotero#2733]
I have opened a new discussion on the forum as I could not post on the developer's mailing list. Separately opening an issue here to further describe the issue with the help of screenshots.

**Context**

In macOS, there has been some recent exciting development where independent applications such as Wooshy, Homerow, and Shortcat enable a user to access all the UI elements through the keyboard. While all of the three mentioned apps work flawlessly in native mac apps, there are issues when they are used in Zotero. 

The screenshots below describe the issue. Only the text in the `Item Pane` is accessible to the apps. 

When I type `Deep learning`, Wooshy is not able to access the `Title column` in the `Main pane`.
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/11236148/182110960-21275fab-d27f-41c9-b0ba-0ff0a7fabb5b.png">

However, when I type `Journal Article`, Wooshy is able to access the text field `Item Type` in the `Item Pane`.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/11236148/182111358-4fa8842f-59e3-4315-8689-458b587f6865.png">

Is it possible to make all the text elements accessible?

Thanks.

**Comment by dstillman** [comment]
Please don't open issues just for screenshots. All bug reports and feature request should be posted to the Zotero Forums, and you can link to screenshots on Google Drive, Dropbox, etc. as necessary.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/98772/exposing-zotero-ui-on-macos
