### ISSUE TITLE
long with load pdf ； But nothing are displayed

### ISSUE THREAD

**Issue by micrsun** [zotero/zotero#2746]
zotero 6 can sync， but can't open pdf files；

![image](https://user-images.githubusercontent.com/41136860/182748266-fe5390bb-be05-482f-9a5b-229b06976a5b.png)

**READ THIS BEFORE CREATING AN ISSUE**

Zotero does not use GitHub Issues for bug reports or feature requests.

Please post all such requests to the Zotero Forums at https://forums.zotero.org, where Zotero developers and many others can help. For confirmed bugs or agreed-upon changes, Zotero developers will create new issues in the relevant repositories.

Development questions involving code, APIs, or other technical topics can be posted to the zotero-dev mailing list at http://groups.google.com/group/zotero-dev.

See https://www.zotero.org/support/zotero_support for more information on how Zotero support works.

**Comment by dstillman** [comment]
As the issue template says, all bug reports and feature requests needs to be posted to the Zotero Forums, not here.

**Comment by dstillman** [comment]
But note that we won't provide support for a custom build. If you're running a build you made yourself, you'll need to reproduce this in an official build before reporting it.
