### ISSUE TITLE
Clicking Color button in reader toolbar repeatedly stacks popups

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#2749]
After ten or so clicks:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/1770299/182927146-4a2cde8d-1cc0-464c-86f3-40f647750f1b.png">

Each stacked popup requires one press of the Escape key to dismiss.

**Comment by mrtcode** [comment]
I can't reproduce that on master branch. Is that fx102?

**Comment by AbeJellinek** [comment]
Oh yeah, sorry, I was on fx102 when it happened.

**Comment by mrtcode** [comment]
Does it still happen for you? Because I can't reproduce it on fx102. Normally, if a context menu is opened, you can't click anywhere without closing it first. Is there a chance that you have changed something in prefs?

**Comment by AbeJellinek** [comment]
Yeah, on macOS fx102. In general, I'm able to click other elements without dismissing non-native popups, and I usually have to select a menu item or press Escape to get them to go away. Is there a preference that would cause that? (Now that I think about it, I don't think Zotero *always* behaved that way, but I have no idea what I could've changed.)

**Comment by dstillman** [comment]
Not clear if it's related, but there is a setting in the dev tools — `ui.popup.disable_autohide` — to prevent popup autohide.

**Comment by AbeJellinek** [comment]
Well, that was it.

I had no idea that persisted as a pref. I turned it on once to debug something with Add by Identifier and completely forgot about it. Sorry for the confusion.
