### ISSUE TITLE
[Upgrade PDF.js] PDF reader: "group is null" error opening PDF from IEEE Xplore

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2750]
https://ieeexplore.ieee.org/document/1652099
https://forums.zotero.org/discussion/98905/zotero-pdf-viewer-fails-with-message-group-is-null-for-this-pdf

I can reproduce

**Comment by mrtcode** [comment]
Fixed in Zotero 7 beta PDF.js.
