### ISSUE TITLE
Don't relate book sections to each other when creating from book

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2757]
https://forums.zotero.org/discussion/comment/414680/#Comment_414680

> To avoid this, this function would need to ignore related-item relations to either all book sections or to book sections where the title matches the book title. (The reason to do the latter would be to allow book sections to inherit relations to other book sections that the parent item is related to.)

**Comment by qqobb** [comment]
> Don't relate book sections to each other when creating from book

Yes, but perhaps still relate the book to its book section:
https://forums.zotero.org/discussion/comment/414742/#Comment_414742

**Comment by dstillman** [comment]
Yes, obviously.
