### ISSUE TITLE
Note editor: Expose option for adding image

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2759]
https://forums.zotero.org/discussion/comment/414899/#Comment_414899

We should add a way to insert an image through the UI — I guess popping up a filepicker? Not sure if there are any other modes to support (e.g., pasting an image URL to download, but that's a little confusing because it sort of suggests that it will be a remote image).

We could put this in the menu above "Insert Table" for now, and maybe add it to the toolbar later if we make an icon for it.

**Comment by mrtcode** [comment]
We were also discussing about `Edit -> Insert -> Image, Citation` [options](https://github.com/zotero/zotero/issues/2308#issuecomment-1023496931).
