### ISSUE TITLE
Item tree scrollbar not always displayed when needed

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#276]
Sorry for the vague title. This happens in the Firefox add-on when the tag selector is visible. Set the tag selector to 8 rows high, add 13 items to a collection. Now reduce the Zotero pane to the minimum. Some items go out of view without the scroll bar appearing.

If the tag selector is hidden, the scroll bar appears, but you can actually minimize Zotero pane to a point where the scroll bars go out of view. There should probably be a minimum height.

**Comment by dstillman** [comment]
No longer a problem in Standalone
