### ISSUE TITLE
When will you be able to support markdown-formatted link jumping in annotations?

### ISSUE THREAD

**Issue by YangWaldon** [zotero/zotero#2763]
When I want to create a link or reference relationship between the contents of two places in a pdf document, I can highlight one of them, then copy it, and highlight the other place to do the markup, and then paste the copied content into the markup, so that you get a jump link, but you can't click on the link to jump the operation ------, which is very chicken, please ask the developers if they have considered Have the developers considered implementing this feature?
![image](https://user-images.githubusercontent.com/49675185/185147529-ce7cbde0-156d-48fd-a47c-74d6c062e700.png)

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

**Comment by YangWaldon** [comment]
What does this mean, please, and is my query accepted, or do I need to go to the zotero forum and mention the request?
