### ISSUE TITLE
PDF reader: Error after deleting annotation in 6.0.13-beta.1

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2769]
https://forums.zotero.org/discussion/99133/pdf-viewer-cannot-highlight-text-after-deleting-highlighted-note-6-0-13-beta-1

I can reproduce.

**Comment by mrtcode** [comment]
I feel that we have too much "Reactism" in pdf-reader. Probably would make sense to rewrite things and reduce React usage which sometimes only complicates things.
