### ISSUE TITLE
PDF reader and note editor colors

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2774]
I have all the code necessary for note-editor text color button, but we need to decide about the colors. And it would be the best to solve text and highlight colors together.

We already have 5 highlight colors (pdf-reader renders them with 50% alpha). They are the same in pdf-reader and note-editor. I added 3 more colors which should be sufficient for most users. I currently picked Orange, Magenta and Gray (inspired by TextEdit color picker).

Next, I think it would be weird to have a very different text color popup, therefore I added a very similar one, just the text colors were intensified to be more readable.

<img width="372" alt="Screenshot 2022-08-22 at 15 14 48" src="https://user-images.githubusercontent.com/6362989/185928074-5fe1ad5a-1b76-47aa-9672-a874b7ed9677.png">

Three more colors added to PDF reader:

<img width="1078" alt="Screenshot 2022-08-22 at 15 48 03" src="https://user-images.githubusercontent.com/6362989/185927663-67e4ef36-6220-4f8d-b9c0-04f254da5bc3.png">

Color popups are now 2 x 4, previously it was 1 x 5. Colors order is changed as well (now more similar to TextEdit color picker).
<img width="360" alt="Screenshot 2022-08-22 at 16 00 13" src="https://user-images.githubusercontent.com/6362989/185930099-ce9ed1f4-9976-40f6-8afc-83a200749435.png">
Highlight popup now shows its true color (with 50% alpha). The rainbow line is also removed from the highlighter icon, to match the text color icon.
<img width="360" alt="Screenshot 2022-08-22 at 16 00 27" src="https://user-images.githubusercontent.com/6362989/185930108-f4b4bcd3-39a1-4028-8dad-95de1a82abc7.png">

To clear color:
<img width="359" alt="Screenshot 2022-08-22 at 16 01 49" src="https://user-images.githubusercontent.com/6362989/185935805-38ecc504-78d1-4334-ab0d-4a6ddb94abaf.png">

Displays existing colors (the empty swatch is just white):
<img width="359" alt="Screenshot 2022-08-22 at 15 58 40" src="https://user-images.githubusercontent.com/6362989/185936250-020a5ba0-5f68-49db-889d-b74c791f8b21.png">

Dark mode:
<img width="371" alt="Screenshot 2022-08-22 at 15 20 03" src="https://user-images.githubusercontent.com/6362989/185928087-9f76b723-47af-4254-b22e-6465220b4abe.png">

**Comment by ckotthaus** [comment]
Great job, @mrtcode, thank you so much! For me, any additional colors would be fine. The 20 ones in your last picture above seem absolutely sufficient to me. Any idea when a first version could be released?

**Comment by pdatlinger** [comment]
Thanks so much, @mrtcode. If you are still looking for more colors, here's a few ideas. I selected the colors back when I was still using Paperpile, and they work really well for highlighting.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/8570259/190090564-1ade4ae0-fe2a-4caf-b1a1-ef9d76b1957a.png">

**Comment by ashfaq92** [comment]
Gray color is must!

**Comment by QuinnYates** [comment]
> Thanks so much, @mrtcode. If you are still looking for more colors, here's a few ideas. I selected the colors back when I was still using Paperpile, and they work really well for highlighting.
> 
> <img alt="image" width="358" src="https://user-images.githubusercontent.com/8570259/190090564-1ade4ae0-fe2a-4caf-b1a1-ef9d76b1957a.png">

This is really a great set of colours. I would really appreciate it if you can add this to zotero.

**Comment by Tyrannidae** [comment]
@mrtcode
This is an awesome feature and will be very much appreciated!
Just two things:
1. It would be nice if we could modify the alpha to accommodate people with contrast sensitivity issues and other sight problems. 50% is workable but still a tad too intense in my case.
2. An option to change the colours to a palette compatible with colour blindness would be amazing. The one shared by @pdatlinger seems good. This [website](https://clauswilke.com/dataviz/color-pitfalls.html#not-designing-for-color-vision-deficiency) also has great examples.

**Comment by lisabuldeorai** [comment]
Looking forward to this! I second Tyrannidae's comment and would like to add:

3. A possibility to change every individual color in the preferences e.g., by entering #xxxxxx code

Thanks for this!

**Comment by kaijagahm** [comment]
Thanks for working on this! I'm really excited for more colors, as well as the ability to change the highlight and text colors independently (e.g. I want to be able to write in black).

Seconding the request for arbitrary colors by hex code--is there a reason that limiting it to just a few specific colors is easier? The more the better.

Really appreciate the Zotero team's dedication here. The new app is extremely exciting and it's already incredibly useful. These updates will make it more so.

**Comment by flowergas** [comment]
I apologize if this question is stupid.  I'm new to the world of Github, working on a PhD.  

How do I incorporate this update into Zotero?

**Comment by dstillman** [comment]
@flowergas: GitHub issues are for developers. Please post all Zotero questions to the Zotero Forums. This update will be included in a future version of Zotero.

**Comment by flowergas** [comment]
Thanks for clarifying.  Didnt realize I was intruding on your space, I'm
very very very sorry.  :((

**Comment by mrmotallebi** [comment]
@mrtcode Sorry I haven't followed the whole discussions about colors in all issues, but personally what I've noticed is that when I open a PDF that has been annotated in another app, there are for example two 'yellow' colors displayed in the annotations sidebar.

So looking at it, for instance I see Sumatra PDF is using a yellow that is more fluorescent (https://github.com/sumatrapdfreader/sumatrapdf/blob/b8e2c41f1f7356b3e96c53c894bf567a8708529b/src/EditAnnotations.cpp#L55) which itself seems to be coming from MuPDF (https://github.com/sumatrapdfreader/sumatrapdf/blob/b8e2c41f1f7356b3e96c53c894bf567a8708529b/mupdf/platform/gl/gl-annotate.c#L638 ). So my suggestion is to stick to colors that are more common among other PDF editors too, rather than adjusting them yourself.

**Comment by Raaaha** [comment]
need this very much 😭, when will it be released?

**Comment by JoshuaB-L** [comment]
I'm also desperately needing this for my Zotero to Obsidian workflow. Can you release the source code?

**Comment by TjardaR** [comment]
Would love to see this released! I've been hoping for extra Zotero highlight colors for so long....

**Comment by psydelle** [comment]
Thanks so much for working on this! Being able to use hex codes and select your own hex codes would be be a welcome feature. Although, expanding the color palette would work just fine too. Can't wait for this to be released. I need it so bad!!! 😭

**Comment by jeffkimbrel** [comment]
Following and excited for this release. Any chance the colors can be named? Having a yellow square with the word "yellow" isn't that useful. It would be great to be able to put a short title as to what a yellow highlight means in a workflow.

**Comment by medium-old** [comment]
Thank you for working on this! Excited to have so many colors!

**Comment by FarhadGSRX** [comment]
+1 Looking forward to this soon 🙃

**Comment by julienroyd** [comment]
+1

**Comment by MuiseDestiny** [comment]
I made this plugin that defines groups of pdf annotation colors and you can switch between them at will. Before the official color definition is made, you can achieve more color needs through this plugin.
![image](https://user-images.githubusercontent.com/51939531/216855307-91a952a0-ddca-4bf6-bacb-c17ba5fd98c4.png)

[zotero-style](https://github.com/MuiseDestiny/zotero-style)

**Comment by flowergas** [comment]
I appreciate this.  Is there any way to display the program interface in English?

**Comment by dstillman** [comment]
Available in the <a href="https://www.zotero.org/support/beta_builds">Zotero beta</a>

**Comment by erentar** [comment]
Where can I define my own colors in Zotero 7?
