### ISSUE TITLE
Increase relative font size of math in notes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2775]
![math](https://user-images.githubusercontent.com/783082/186047703-6d407647-44eb-4f24-a60f-086cc0663e17.png)

A little small relative to the surrounding text

**Comment by mrtcode** [comment]
But you are using inline math here.
<img width="261" alt="Screenshot 2022-08-23 at 09 25 00" src="https://user-images.githubusercontent.com/6362989/186085750-902d4fd1-613c-4424-8af6-aa2f812751b3.png">

**Comment by dstillman** [comment]
Ah, and it's smaller so that it doesn't increase the line height if there's a fraction or something?

**Comment by mrtcode** [comment]
Yeah, I think it makes sense to have different sizes. You want things to be more compact when in a line, and in a block there is a lot of space.

**Comment by mrtcode** [comment]
Although in all papers I checked, and also in Github comments inline and block size is the same.

**Comment by dstillman** [comment]
Yeah, I think it'll look better being the same size. E.g., you can already have superscript in regular text and it's definitely bigger.
