### ISSUE TITLE
Note editor: Add "Insert Math" to note context menu

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2778]
Since no one is going to know you can use math otherwise. Automatically inline if there's already text on the line and block if on a new line.

Can go below "Insert Table"

**Comment by mrtcode** [comment]
Soon I'm going to add "Insert Image", therefore maybe it makes more sense to have "Insert" and a submenu with "Image", "Math", "Table"?

**Comment by dstillman** [comment]
Yes
