### ISSUE TITLE
Note editor: `1. ` no longer creates numbered list

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2789]
I just get an empty indented line.

Regression from the empty-math-node fix, maybe?

Not yet pushed to a beta, and I'm going to hold off pushing one until this is fixed.

**Comment by mrtcode** [comment]
This is Firefox weirdness. If there is `li::before` with `position: absolute`, then `li::marker` has 0 x 0 size. I only tested this on Chrome and it was working as expected.
