### ISSUE TITLE
Note editor: Left/right arrows don't work on line with inline math

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2793]
I have `asfsfsdf $2+2^4$` on a line, and if I put the cursor in the middle of the regular text and press left or right arrow, the cursor disappears, and the line no longer seems to be focused — I can't even type new characters, though if I hold Shift and use the arrow keys I can select text.

Maybe related to https://github.com/zotero/zotero/issues/2788.

**Comment by mrtcode** [comment]
Can't reproduce it anymore. It appears to be resolved by upgrading to a newer version of Firefox.
