### ISSUE TITLE
Mendeley importer: Allow pasting in emailed confirmation links

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2795]
https://twitter.com/Swifthom/status/1563888190578216960 and various forum threads

**Comment by tnajdek** [comment]
I don't think we can implement this after #2871 happened?

However, I suspect people who need this can follow the following steps instead:

https://service.elsevier.com/app/answers/detail/a_id/33535/supporthub/mendeley/p/16075/

**Comment by dstillman** [comment]
OK, I've [added that](https://www.zotero.org/support/kb/mendeley_import#known_issues) to the import page.
