### ISSUE TITLE
PDF reader: Split view

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2821]
https://forums.zotero.org/discussion/88482/pdf-reader-feature-request-open-the-same-pdf-twice-in-split-screen

For viewing references/footnotes while viewing a PDF

On app restart, we'd restore the split and page positions, but only the first half would affect the synced page position, due to https://github.com/zotero/zotero/issues/2815.

**Comment by mrtcode** [comment]
There will be only one sidebar. Does it mean it would control only the left side PDF view? Controlling means page thumbs, navigating and filtering annotations, navigating outline. And the right side would be just a simple PDF view? Do we want annotations on the right side, if we don't support search and filtering?

How about zoom and different zoom modes?

I guess we have to look what other PDF viewers are doing.

**Comment by dstillman** [comment]
Right/bottom (maybe we want both options?) is just a simple view. No search, sidebar, etc.

View settings match parent on split, and can then be set separately. Those would be preserved separately across restart, but they wouldn't affect other tabs.

**Comment by mrtcode** [comment]
Would it be enough if you only be able to scroll and zoom the second view? For example there won't be annotations on it, text search wouldn't work, toolbar wouldn't work. It would be a completely dumb pages view.

**Comment by dstillman** [comment]
Yes.

**Comment by dstillman** [comment]
> I guess we should add two options for both PDF page views context menus: "Split Vertically" and "Split Horizontally". And maybe also add the same options to View menu.

Yup.

> Another question is how to control zoom for the second view. Over context menu? Do we want something in View menu?

Hmm, is there any concept of focus, where the relevant toolbar icons (i.e., not the annotation ones) could be active if you clicked in the split pane?

Resizable splitter would be good, yes.

**Comment by mrtcode** [comment]
> Hmm, is there any concept of focus, where the relevant toolbar icons (i.e., not the annotation ones) could be active if you clicked in the split pane?

The view that is currently focused receives keyword events, but for the toolbar buttons there isn't such a thing. I would need to either capture click events before PDF.js does, or modify PDF.js. For page number input it would be even more difficult.
Maybe it would be less confusing if we reserve all the UI (toolbar, sidebar) controls only for the primary view. The second view will be controlled over context and View menus.

**Comment by dstillman** [comment]
What would be in the View menu?

**Comment by mrtcode** [comment]
> What would be in the View menu?

It could have exactly the same options, but control the currently focused PDF view instead, or it could be another submenu called "Second View" that would have the same options as the main View menu. Except maybe we don't need hand mode, spreads and scrolling options.

Another PDF viewer that I just tried applies the same spread option for both PDF views. Maybe we could do the same for scrolling and hand mode options. Only zoom would individual for the second view.

**Comment by dstillman** [comment]
Yeah, I think it would have to be Second View if anything. Having the primary options in View control the second view while the toolbar buttons don't affect it seems weird and confusing.

But maybe for now we just apply the same spread/etc. options, and you can zoom via context menu or keyboard?
