### ISSUE TITLE
PDF READER: map mouse side buttons to back/forward navigation

### ISSUE THREAD

**Issue by raul-lezameta** [zotero/zotero#2827]
Could you map The mouse side buttons to back/forward navigation in the PDF reader? I think it would be a very convenient feature to have.

This was already mentioned in the following issue:

> I have a feature suggestion. I would really appreciate it, if you also considered mapping the back and forward navigation to the mouse side buttons, like is done in web browsers for example to move to next/previous sites. A lot of other PDF readers also implement it like that, and I find it really intuitive to use.

Yes, I think we should probably make those side buttons to work as well. Unfortunately I can't test them at the moment.

_Originally posted by @mrtcode in https://github.com/zotero/zotero/issues/2707#issuecomment-1187650612_

**Comment by mrtcode** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

---

They're already added and should work in Zotero beta.
