### ISSUE TITLE
fx-compat: Accept Fluent .ftl files in `Zotero.PreferencePanes.register()`

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2837]
In addition to .dtd, for developers who don't want to start with an obsolete format

(We should also document how to use localization.)

**Comment by AbeJellinek** [comment]
Is this necessary? Since FTL files aren’t needed at parse time, `<link rel="localization">` tags in the XHTML fragment should work, shouldn’t they? (Haven’t tested yet.)

**Comment by dstillman** [comment]
`<link rel="localization">` [doesn't seem to take absolute URLs](https://searchfox.org/mozilla-central/search?q=rel%253D%22localization%22), so it's not possible to just include `<link rel="localization" href="chrome://make-it-red/locale/make-it-red.ftl"/>`. We're adding our .ftl files to a [specific directory](https://github.com/zotero/zotero-standalone-build/commit/600b35d2bfbe0ad39c778d0e2f4a4bb8b530321a), and Fluent in Firefox seems *really* set up to pull from there and only there, but I'm guessing there's something along [these lines](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/Extension.jsm#3422-3432) to register a new localization file source?

But this would be a problem for using Fluent outside of the prefs too, so if we can get manual registration to work at all then maybe we need a more general solution for plugins to either register individual Fluent files via chrome locale URLs or make their chrome-registered locale path somehow accessible via `<link rel="localization">`…
