### ISSUE TITLE
Editing note in older Zotero breaks math nodes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2839]
If I make any change to a note with a math node in Zotero 6.0.11, even outside the math node, the math node is broken in the current version:

![Screen Shot 2022-09-27 at 11 58 23 PM](https://user-images.githubusercontent.com/783082/192684474-d14fd3ef-f136-4b93-a1fa-227756bcd46b.png)

Anything we can do to fix these in the current version?

(I didn't test editing in TinyMCE to see what happens with that.)

**Comment by dstillman** [comment]
(Holding off on 6.0.14 until we see if we can fix it)

**Comment by mrtcode** [comment]
Older note-editor converts `<pre class="math">$$fx(x)=1$$</pre>` into `<pre>$$fx(x)=1$$</pre>`, and `<span class="math">$f(x)=1$</span>` into `$f(x)=1$`. The only way to fix this in the newer note-editor is to look for `<pre>$$…$$</pre>` and `$…$` and convert accordingly. But the later might be too dangerous to do.

Editing TinyMCE just works.

**Comment by mrtcode** [comment]
Fixed in zotero/note-editor@f35bf0c.
