### ISSUE TITLE
Disable spell-checking in math nodes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2840]
Any way to do this?

**Comment by mrtcode** [comment]
`spellcheck="false"` does that if I add it manually. Although there might be difficulties for me to access the required nodes because they are controlled by `prosemirror-math` plugin.

**Comment by dstillman** [comment]
Seems like we could fork it and/or contribute patches as necessary.

**Comment by mrtcode** [comment]
Ok, I created a PR on `prosemirror-math` repo.

**Comment by mrtcode** [comment]
Already fixed.
