### ISSUE TITLE
Saving proxied resources in "don't remember history mode" doesn't work anymore

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero#285]
See e.g. here: http://forums.zotero.org/discussion/28533/error-with-sciencedirect-and-scopus/#Item_13 but also some other recent threads. This sounds like it's a recent issue - people report that this worked before with the same settings.
Can we fix this on the Zotero side? Otherwise, we should add it to the translator troubleshooting steps.

**Comment by dstillman** [comment]
No more Z4Fx
