### ISSUE TITLE
Item type menu steals focus during items tree key navigation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2885]
https://forums.zotero.org/discussion/100543/zotero-6-0-15-for-mac-periodic-error-typing-to-search-through-references-list

1) Click Title and press Shift so the item type menu gets the blue outline
2) Click an item in the items list
3) Press a letter key on the keyboard

Caused by #2833 (by definition, since you couldn't focus the item type menu via the keyboard, unless there's some other way to trigger this)

**Comment by dstillman** [comment]
Also happens with the field mode switcher (and maybe the minus/plus buttons — I didn't check):

https://forums.zotero.org/discussion/comment/421160/#Comment_421160

**Comment by qqobb** [comment]
Could this be related to #1810?

BTW, on Windows, if I click Title and press Shift-Tab, so the item type menu gets focus, I can't open the dropdown menu with Space. I think this should work in the same way as for the Creator Type menu.
