### ISSUE TITLE
Import confirmation missing for Framework Translators

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero#290]
Since 4.0, attachments are shown in the pop-up bubble confirming import via web translator (loving this btw.).
This does not work for Framework translators, e.g.
http://www.voxeu.org/article/green-growth-evidence-energy-taxes-europe (snapshot)
http://rsi.aip.org/resource/1/rsinak/v64/i7/p1868_s1 (snapshot and pdf)
The attachments are downloaded, but don't show up in the pop-up, which is rather confusing.

**Comment by dstillman** [comment]
All FW translators have since been updated by @zuphilip.
