### ISSUE TITLE
Searching for item using type-to-search can make Zotero unresponsive

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#2919]
I can't see anything useful in the debug output, it just freezes. Was able to reproduce on macOS and Windows.

Steps to reproduce:

1. Make a collection and add two empty items (it's required so that search doesn't match anything)
2. Select first item
3. Press two letters on a keyboard, e.g. `S` followed by `D`

Zotero becomes unresponsive.

**Comment by mjthoraval** [comment]
Thank you. It should be what I had observed here:
https://forums.zotero.org/discussion/99805/zotero-freezing-when-typing-letters-in-the-main-pane

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/zotero/commit/6a0ecd243d4513507b85bc9bd37deb2d61a3bad7
