### ISSUE TITLE
why my annotations from adobe reader Locked in Zotero pdf reader ?

### ISSUE THREAD

**Issue by mnkhprre** [zotero/zotero#2937]
I am using Zotero 6 with a couple of extensions like zotero-pdf-translate, and better-notes. sometimes I try to transfer my adobe annotations to Zotero. it is a little bit of pain in the neck. couldnt editing the annotations which is sad.
<img width="199" alt="Screenshot 2022-12-01 at 12 46 35" src="https://user-images.githubusercontent.com/54448793/205020732-58c03295-284e-4922-bc18-6537e3d82408.png">

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
