### ISSUE TITLE
[Feature Request] Ability to copy text on the annotated list

### ISSUE THREAD

**Issue by much-doge** [zotero/zotero#2945]
![image](https://user-images.githubusercontent.com/20739853/207264334-fc1559f1-b6af-482a-a9a3-e9795e23fd66.png)

When right clicking an annotated text, I wish I was able to copy the highlighted text. 

Example usage: I want to quote or incorporate the highlighted text into a paper that I am currently writing. Being able to do so would (IMO) makes it faster for me to copy the already highlighted text as opposed to selecting and ctrl+c-ing the text directly on the opened pdf (as the text is already highlighted, why should I deal with the pdf again).

Thanks in advance.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

You can just press Ctrl-C to copy the annotation after clicking on it.
