### ISSUE TITLE
Right click on URL and DOI fields

### ISSUE THREAD

**Issue by mronkko** [zotero/zotero#295]
Some fields (e.g. Title, Publication) have additional options available on right click (Transform case). The URL and DOI fields could have similar functionality to open the URL or DOI link on the browser.

**Comment by bwiernik** [comment]
I think this was closed by https://github.com/zotero/zotero/pull/716 ?

**Comment by dstillman** [comment]
Apparently. I didn't even remember that we did this.

One minor thing is that we're copying the URL with a percent-encoded DOI. At least in the case of slashes, that's not a problem for doi.org, so we could consider leaving those intact and just encoding other characters. (Or maybe we don't need to encode at all. `#` would break things, but hopefully that's not actually used in any DOIs. Not sure about other characters.)

**Comment by bwiernik** [comment]
Technically, `#` ` ` `%` `"` and `?` are all allowed in DOI names but their use is discouraged and in practice few if any publishers use them. I think we could safely not encode the DOI as part of Copy as URL. 

See https://www.doi.org/doi_handbook/2_Numbering.html#2.5.2.3
