### ISSUE TITLE
Collections pane scroll position is reset while feeds update

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2950]
I've been seeing this for a while: I open Zotero and try to scroll up in the collections pane, and it keeps resetting my position down to the selected row. I don't have debug output for this to confirm, but I think what's happening is that when you first start Zotero and a bunch of feeds update, the collection pane gets refreshed to update the feed rows, and that's causing the position to be reset. Pretty sure this is a relatively recent regression — I don't remember seeing it before the last few months.

**Comment by dstillman** [comment]
And likely related to this, if you have the classic citation dialog open while feeds are refreshing, the items list keeps refreshing, even if you're on My Library.

**Comment by adomasven** [comment]
I only see the scroll position reset if I manually refresh a feed and it is selected in the collection tree. If I select the refresh option and then switch to a different collection, then the scroll does not refresh. Is this also what you're seeing, or does it happen even if no feed is selected?

**Comment by dstillman** [comment]
I almost never have feeds selected, so I don't think it's that — I just see it when I start up the app after long enough that there are new feed items. Things go crazy during the initial auto-refresh. (And feeds don't show up in the classic citation dialog, so that couldn't have been it.)

Do you see this if you clear all feed items and history for a feed, push back the last-refresh time, and restart with the library selected?
