### ISSUE TITLE
Issue with launching "$CALLDIR/zotero-bin" -app "$CALLDIR/application.ini" "$@"

### ISSUE THREAD

**Issue by zenny** [zotero/zotero#2954]
Hi,

I had a working instance of zotero, but when I upgraded to v6.0.19-beta.12+0862e1e1b, the GUI shows up, but crashes with the following error:

```
/home/zenny/Downloads/Zotero_linux-x86_64/zotero: line 13:  4022 Killed                  "$CALLDIR/zotero-bin" -app "$CALLDIR/application.ini" "$@"
```
Any clue?

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
