### ISSUE TITLE
Every image in the article from Ultrasonics Sonochemistry shown in Zotero will have a black mask at the top-left corner.

### ISSUE THREAD

**Issue by heimi98** [zotero/zotero#2959]
Every image in the article from Ultrasonics Sonochemistry shown in Zotero will have a black mask at the top-left corner.
![image](https://user-images.githubusercontent.com/56879067/210695515-d4aa79fe-9456-4b6b-b8a3-0c67b565943e.png)

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

https://forums.zotero.org/discussion/102130/every-image-in-the-article-from-ultrasonics-sonochemistry-shown-in-zotero-will-have-a-black-mask
