### ISSUE TITLE
PDF reader: Allow word lookup on selected text

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2970]
https://forums.zotero.org/discussion/comment/425607/#Comment_425607

Cmd-Ctrl-D works in the PDF reader on unselected text, but it doesn't work on selected text the way it works in Firefox, either when the color popup is open or if you manage to hide the popup while keeping the selection with some awkward right-clicking.

This is necessary to look up words on PDFs with bad OCR where spaces in the text aren't detected.

**Comment by mrtcode** [comment]
This is going to be complicated because we are using our own custom selection layer that calculates everything and then renders selection in Canvas. But good that we have raised the issue now, because I'll try one trick to address this in the new reader version.

**Comment by mrtcode** [comment]
Already fixed.
