### ISSUE TITLE
Arabic script letters in citation keys

### ISSUE THREAD

**Issue by Serena-UB** [zotero/zotero#2989]
Hi! I originally posted this on Zotero forums, and was asked to open an issue for it here.

I hope someone can help me with this:

Something strange happens to the citation keys of my Zotero entries in Arabic script. Some of the Arabic letters are automatically converted to Latin characters, but some are converted to question marks.

My citation key formula is auth+year.

An example:

The article author is هناء زايد عباس

The citation key becomes this:

hn��z�ydaab�s2020

Why are some of the Arabic characters converted and others not? If I could access the convertion table for this and modify it, it would be great.

The characters not being read, are ا and ء .

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/102692/arabic-script-letters-in-citation-keys
