### ISSUE TITLE
Make "Add Note" button small and move elsewhere in toolbar

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2995]
Too many people are clicking "Add Note" while trying to insert a citation (and "Note" is confusing for some citation styles).

**Comment by adomasven** [comment]
Original

![image](https://user-images.githubusercontent.com/5899315/220628753-c395fdd8-5e3a-4477-9830-6cd1e0eb8375.png)

Changed

![image](https://user-images.githubusercontent.com/5899315/220628669-3f8bed63-bb8d-4412-9771-c7bb3f79e673.png)

I'm not a fan of this. Maybe if we change the order of the small icons, but even then, it's not great.

**Comment by dstillman** [comment]
It needs to move, but that layout obviously won't work. Are these the only two size options for buttons? Could there be half-height Add Annotation and Add Note buttons in one column and Doc Prefs/Refresh/Unlink in another column?

**Comment by adomasven** [comment]
Yes, these are the only one. You can look through other tabs in Word to see what options are available. I think we can have a vertical separator, but that only helps so much.

I would try to solve the issue of confusion by allowing users to switch between note and citation toolbars once they open them and make it clear that they are using the wrong one. Like if the search results are empty we could show an item that says "Adding notes. [Switch to items](#)" or something. And add a visible switch between the modes in the bar somewhere.

**Comment by dstillman** [comment]
Oh, well, MS does two small rows in a bunch of places, though:

<img width="399" alt="Screenshot 2023-03-02 at 5 47 58 AM" src="https://user-images.githubusercontent.com/783082/222407316-1e1c29e1-c861-490e-8672-25b360b79dbf.png">

Weirdly spaced, but it's doable.

Occurs to me that we'll probably have Add Selected as well. So we have a few options:

1) Three small stacked rows for Add Selected, Add Annotation, and Add Note
2) A vertical separator and then three big icons for Add Selected, Add Annotation, and Add Note
3) Big Add/Edit Citation, Add Selected, and Add/Edit Bibliography and two weirdly spaced small stacked rows for Add Annotation and Add Note
4) Big Add/Edit Citation, Add Selected, and Add/Edit Bibliography, a vertical separator, and then two big icons for Add Annotation and Add Note.

For now, until we have Add Selected and Add Annotation, I think we can just have vertical separator after Add/Edit Bibliography followed by Add Note followed by another vertical separator. Getting Add Note away from the two main buttons is the main thing.

(Also, maybe we should rename it to Insert Note, to try to convey that it's not editable once you insert it, unlike the add/edit things.)

**Comment by adomasven** [comment]
Interesting. This layout is not available on WinWord:

![image](https://user-images.githubusercontent.com/5899315/222410736-ddb18580-25ac-406d-b782-aab343aa7188.png)

Moreover, the XML we use to specify the button layout is poorly documented and may not support newer layout options even if they become available.

Putting the Insert Note button between separators away from the other two buttons may be a good enough start.

**Comment by adomasven** [comment]
How about this?

1)
![image](https://user-images.githubusercontent.com/5899315/222417495-532782ca-6162-4340-8482-402777baaedf.png)
2)
![image](https://user-images.githubusercontent.com/5899315/222417683-0d3ac0ee-d94e-40ef-9c6a-0af515e56ec9.png)

I think it belongs alone.

**Comment by adomasven** [comment]
I've also been reading https://interoperability.blob.core.windows.net/files/MS-CUSTOMUI/%5bMS-CUSTOMUI%5d.pdf and we can setup custom keytips for the Zotero tab and its children so that the commands can be executed via Alt-keypress. Z is taken for the tab. We could either do `ZO` or `C`

![image](https://user-images.githubusercontent.com/5899315/222418714-d964ce2f-0d54-4ee5-852b-39ab8a2af1ff.png)

Old/Updated commands:

![image](https://user-images.githubusercontent.com/5899315/222418816-b7002534-5bda-4d1e-8876-d15b610dc043.png)
![image](https://user-images.githubusercontent.com/5899315/222418864-4b9ee776-5dd8-4945-9038-bc2bf22262f1.png)

**Comment by dstillman** [comment]
Yeah, it belongs alone for now — we can hopefully add Add Annotation soon.

Also, if you have the original icon you used for that, you can remove the Z. I'm not sure why we have Z overlays at all for these, given that they're now all within a dedicated Zotero tab (or is there a way to add them to some quick-access toolbar where they'd be out of context?).

For the tab, what is Z taken by?

**Comment by dstillman** [comment]
Oh, I guess it's part of the two-letter ones?

**Comment by adomasven** [comment]
> or is there a way to add them to some quick-access toolbar where they'd be out of context?

There is.

**Comment by adomasven** [comment]
Done. Make sure you update WinWord template signature.
