### ISSUE TITLE
Port keyboard-accessible toolbar to fx102

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3001]
d866a10a2b56e96631a1563572d3f2918f1f006a

**Comment by abaevbog** [comment]
I'm essentially done with the conversion, except here's a question: I can't seem to find what this commit is initially supposed to do ...

I assumed it makes it possible to navigate through all tool bar buttons (new note, new item, advanced search) by pressing Tab. That commit was part of Zotero 6.0.26, so I expected it would be possible there but not in Zotero 7. 

However, repeatedly tapping Tab in Zotero 6.0.26 goes through the same fields as Zotero 7 beta, and the toolbar buttons  never end up being reached.  [This screenshot ](https://www.dropbox.com/s/mu9k1w9uhy42434/screenshot.png?dl=0) shows the fields that get visited. 

So I am a bit confused what is the behavior that we are trying to replicate. Was I looking at the wrong Zotero version for comparison?

**Comment by abaevbog** [comment]
Got it! I was looking at it on Mac and getting confused. 

I used a linux machine today, and it made much more sense. Had to tweak it a bit but with the last commit I could navigate all toolbar items with tabs and arrows
