### ISSUE TITLE
Referrer-gated PDF not downloaded

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3006]
https://forums.zotero.org/discussion/103273/unable-to-add-the-government-report

Without a cookie, the URL returns a language-selection page. It looks like we're sending cookies from the browser, but the client is still getting the language-selection page.

**Comment by adomasven** [comment]
Needs both an updated connector and client for the fix to work.

**Comment by dstillman** [comment]
This doesn't seem to be working in Firefox — the referrer isn't sent. It's working in Chrome.

**Comment by adomasven** [comment]
Ugh. Chrome sets `document.referrer` to the previous site you navigated from regardless of being redirected or not. Firefox does not. So we'd have to set up a custom code path in Firefox to keep the previous URL for every tab to fix this "the right way", which I don't think is reasonable for weird Canadian government document gating choices. Arguably this is a weird enough edge case to not handle it, unless we see someone else do this.
