### ISSUE TITLE
Rendering PDF error

### ISSUE THREAD

**Issue by Saunak626** [zotero/zotero#3008]
When opening some scanned PDFs that are more than 100MB, Zotero's built-in PDF browser will remain blank. But those PDFs can opened by Adobe
. And when opening many PDFs in Zotero, even if it is not browsed at the same time, it will be very stuttering. Hopefully, the authors can improve the performance of Zotero

**Comment by dstillman** [comment]
Please post all questions to the Zotero Forums:

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

For this, see https://forums.zotero.org/discussion/comment/429124/#Comment_429124
