### ISSUE TITLE
Add support for Global Menu in Zotero Standalone for Unity users

### ISSUE THREAD

**Issue by stragu** [zotero/zotero#302]
It would be amazing to see Unity's Global Menu supported in Zotero Standalone, so Ubuntu users can save some screen real-estate, and so they can use the Head-Up Display (HUD) to work more quickly.

Thanks a lot, and keep up the great work!

**Comment by darthoctopus** [comment]
I've managed to get this working. Do the following, assuming that you already have a copy of Firefox with the unity patches applied:

1. copy the `firefox` binary to overwrite `zotero-bin` (or make `zotero-bin` a symlink to `firefox`)
2. copy all the `*.so` files (including the directory `$LIBDIR/firefox/gtk2/`) into the zotero directory
3. add the following lines to `zotero.css` (in `zotero.jar`):

```
window[shellshowingmenubar="true"] menubar {
  display: none !important;
}

window[shellshowingmenubar="true"]
toolbar[type="menubar"]:not([customizing="true"]) {
  min-height: 0 !important;
  border: 0 !important;
}
```

**Comment by snippins** [comment]
@darthoctopus Your second methods still works in v5. The first one does not seem to be working, but I am not sure that I copy/override the files like you did.

**Comment by wa4557** [comment]
@darthoctopus Would it be possible to make a PR for that? I guess it would make sense to include that in the main version somehow right?

**Comment by darthoctopus** [comment]
the global menu is still present in other spins of ubuntu, like ubuntu MATE.

**Comment by ripefig** [comment]
@dstillman will you reopen the bug? Global  menu ships with KDE and Mate, as is available for Budgie and Xfce. It covers all programs on my Ubuntu system except Zotero.

**Comment by ripefig** [comment]
@darthoctopus do you know which patched version to use? i tried a bunch of them and they all made it impossible to launch the program.

**Comment by snippins** [comment]
So many DE have global menus now, either by default or with plugins.

**Comment by ripefig** [comment]
@darthoctopus are you saying you just need one file? can you share this file?

Seem like maintentance wouldn't be so bad that's the case, because Zotero only changes ESR base once every few years AFAIK.

**Comment by ripefig** [comment]
@darthoctopus, sorry to bother but can you share the file, assuming you've built firefox for x64?

**Comment by ripefig** [comment]
@darthoctopus sorry to bother you again, but would you consider uploading your built files?

**Comment by darthoctopus** [comment]
[Here](http://www.mediafire.com/file/ui28di2f14u5nkj/libxul.so) is a copy of libxul.so built for x86_64

**Comment by ripefig** [comment]
Thanks @darthoctopus - it runs.

Anyone reading this should note that darthoctopus built the it on arch, which means the libraries are bleeding edge. If you're on 18.10, you're going to need these two:

https://packages.ubuntu.com/disco/amd64/libhunspell-1.7-0/download

and 

https://launchpad.net/ubuntu/disco/+package/libicu63

**Comment by ripefig** [comment]
@darthoctopus. it's now broken on ubuntu 20.04

Any tips on compiling zotero with the unity patch from source?

**Comment by ripefig** [comment]
@darthoctopus. it's now broken on ubuntu 20.04

Any tips on compiling zotero with the unity patch from source?

**Comment by AliTajelsir** [comment]
> @darthoctopus. it's now broken on ubuntu 20.04
> 
> Any tips on compiling zotero with the unity patch from source?

Would be really helpful. I really like the application, but no global menu bar is a deal breaker.

**Comment by ripefig** [comment]
@AliTajelsir this is how I got it working (with one minor issue) since Firefox's update to the new ESR: https://github.com/ripefig/Firefox-ESR-52-Global-Menu/issues/1
