### ISSUE TITLE
PDF reader: Add search bar for outline view

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3021]
https://forums.zotero.org/discussion/103564/is-it-possible-to-search-table-of-contents-when-zotero-pdf-reader-can-detect-toc

Seems reasonable. Would be just like the annotations tab.

**Comment by nagi1999a** [comment]
I really need this feature!
I have been reading hardware specs for months and found it hard when I want to navigate to the definition/implementation of something under a multi-layer outline. If the feature is realized, it may be a lot easier to provide another option than just using full-text search!
