### ISSUE TITLE
Note HTML and Note Markdown options are shown for collection export

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3033]
https://forums.zotero.org/discussion/comment/431083/#Comment_431083

And, separately, we're overwriting the labels as "HTML"/"Markdown" when doing a direct note export. Not sure if that's a problem — do we actually need them to be called "Note HTML"/"Note Markdown" anywhere? — but it's a little weird.

**Comment by mrtcode** [comment]
> And, separately, we're overwriting the labels as "HTML"/"Markdown" when doing a direct note export. Not sure if that's a problem — do we actually need them to be called "Note HTML"/"Note Markdown" anywhere? — but it's a little weird.

I think we decided to rename them when we were implementing those two export options. "Note HTML" and "Note Markdown" are only visible on collections because the translators accidentally get listed there and skip the code that renames them.
