### ISSUE TITLE
fx-compat: Two browsers in basic viewer

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#3039]
There appear to be 2 `<browser>` elements in basic viewer causing incorrect rendering:

![Screenshot 2023-03-23 at 13 11 24](https://user-images.githubusercontent.com/214628/227199978-cd9fada4-d6f0-48d0-bc6a-9cfbc51cc216.png)

Also clicking on a style link triggers generic download dialog, instead of installing the style.

(I cannot add tags, this applies to`fx102` branch)

**Comment by dstillman** [comment]
You probably know this, but this was a regression from 5ea43bd65cf896a0f300d08b173ca978cdf6333d.
