### ISSUE TITLE
fx102: Menubutton interaction is broken on Linux

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#3041]
I see https://github.com/zotero/zotero/blob/53ace4876e90d1e2301cae3b99b31610ae093cbc/chrome/content/zotero/elements/splitMenuButton.js

It doesn't quite work right for me in the feeds view on Linux. The dropmarker bit is not properly separated, doesn't get highlighted when hovered over, and when clicking on the dropmarker ir triggers the button action.

However it seems that this is implemented in mozilla's own `toolkit/content/global/elements/button.js`, but the type attribute has been changed from `type="menu-button"` to `type="menu"`. Can we not use that?

**Comment by adomasven** [comment]
> That doesn't get us separately clickable button and menu segments, does it?

I didn't check, but that seems right. So we do need this.

**Comment by adomasven** [comment]
Z6, Z7 normal look on linux

![image](https://user-images.githubusercontent.com/5899315/227460338-40894dda-4a0b-4d61-86ba-983269e8a41b.png)

Z6, Z7 hover look on linux
![image](https://user-images.githubusercontent.com/5899315/227460570-023fea1d-3f3c-44bf-9d96-4a7fbb757235.png)

These need to be tested on Windows separately too.

**Comment by dstillman** [comment]
Z6 normal is wrong. Z7 normal/hover is what we have on macOS, so it's correct in that sense, but it's wrong in that there should obviously be a separator if the dropmarker is going to have a separator action.

So Z6 hover is really (some version of) what we should have for normal. If we can do just that, that would be OK for the moment. Ideally hover would have some other effect on the hovered portion, but we can deal with that later if need be.

**Comment by adomasven** [comment]
I don't like that it's not a full separator and the button is much fatter on linux and the separator line looks way too small, so maybe something like `height: 80%` is more appropriate.

**Comment by adomasven** [comment]
And also it needs some padding away from the text.

**Comment by adomasven** [comment]
Yep, that looks reasonable now.

![image](https://user-images.githubusercontent.com/5899315/228543178-6c2da09b-66ee-4e6d-8cf2-5f7086ceeebd.png)
