### ISSUE TITLE
Cannot use '[toc]' of markdown syntax to generate table of contents

### ISSUE THREAD

**Issue by realHongYuZhou** [zotero/zotero#3046]
When I use zotero entry notes to record the content of the thesis, the markdown here plugin is a very convenient tool, but the plugin does not support the display of the markdown directory. I hope that zotero can be updated to facilitate the use of markdown syntax `[toc] `to directly create the content of the entry notes.

**Comment by dstillman** [comment]
Please post all feature requests to the Zotero Forums.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
