### ISSUE TITLE
Replace react-virtualized with maintained library

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3055]
Currently requires `--force` to install in newer versions of React. Maybe they'll fix, but if not we should switch to another library.

Update https://www.zotero.org/support/dev/client_coding/building_the_standalone_client once this is resolved

(Used solely in the tag selector)

**Comment by dstillman** [comment]
Yeah, if I recall that's why I went with react-virtualized, even though react-window was already recommended as a replacement at the time. [react-virtuoso](https://virtuoso.dev/) was another alternative I saw listed, but I didn't check if that will work for what we need.

**Comment by dstillman** [comment]
I updated the [documentation](https://www.zotero.org/support/dev/client_coding/building_the_standalone_client) to include `--force`, so there's no real rush on this.

**Comment by tnajdek** [comment]
I believe `--legacy-peer-deps` would be sufficient here although there is no real difference other than it appears less scary.

**Comment by dstillman** [comment]
Ah, yeah, that works. I'll update the instructions.
