### ISSUE TITLE
CI/CD Pipeline Node.js fix

### ISSUE THREAD

**Issue by Nudelsalad** [zotero/zotero#3064]
Artifacts of pipeline can not be retreived due to usage of deprecated git hub actions (Node.js 12). Can someone pls update the .yml file
![image](https://user-images.githubusercontent.com/64224137/230381749-49e23238-a614-4328-b77b-7df6837bd930.png)

**Comment by dstillman** [comment]
Not sure what you mean here, but our actions are running successfully. The message in your screenshot is just a warning about a deprecation. Nothing has been discontinued yet.
