### ISSUE TITLE
The sidebars are misaligned when opening multiple PDFs at the same time.

### ISSUE THREAD

**Issue by Leonoves** [zotero/zotero#3068]
When two or more pdfs are opened for translation at the same time, the translation windows in the sidebar are misaligned. The first pdf window has two translation options while the second window has no translation options. 
![image](https://user-images.githubusercontent.com/85266230/230848822-b75dcab9-6a74-4563-9910-f239aafdd21f.png)
![image](https://user-images.githubusercontent.com/85266230/230848930-50017dc1-a028-4cc8-98cb-ea12d7779301.png)

**Comment by dstillman** [comment]
1) That's from a plugin, not from Zotero. You'll need to contact the plugin developer.

2) Please post all bug reports and feature requests about Zotero (not about plugins) to the Zotero Forums.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
