### ISSUE TITLE
[Already fixed in reader2 branch] Z7: Fix printing from PDF reader

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3072]
Currently pops up a browser window

See also https://github.com/zotero/zotero/issues/3071

**Comment by dstillman** [comment]
This might need the same fix as #3071 but let's first figure out what's triggering the browser window.

**Comment by dstillman** [comment]
Looks like the browser window happened when using `window.print()` and was fixed by switching to `PrintUtils.startPrintWindow(browser.browsingContext)` in 72ec5c64d9464e47f5630d43b35f4326b37fc8d8.

So we'll likely need to do something similar here (though presumably we'll have to call that from outside the reader).

**Comment by wzh4464** [comment]
still pop up a web window at 7.0.0-beta.5+4ca427863
