### ISSUE TITLE
Display more emoji tags than just 1-9?

### ISSUE THREAD

**Issue by huachuman** [zotero/zotero#3109]
Is there a way to display more emoji tags beside library items besides just the ones set as 1-9 shortcuts?

A lot of use use emojis to tag items and have them show up in the browsing view to the left of the items like so:

https://i.imgur.com/ws63HAd.png

However, it is for some reason currently limited to the amount of single digit numbers (1-9) available on the keyboard.

Is there a reason for these two to be coupled?

Would it be possible to make it so that emoji tags are always displayed instead of just the ones set as shortcuts?

The goal is not to tag a single item with dozens of tags and create clutter, but rather to expand the number of available emoji tags.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

**Comment by huachuman** [comment]
I didn't know this was a bug or feature request. I'm just trying to add emoji tags... So you're telling me this is not currently possible?

**Comment by asan-emirsaleh** [comment]
This is reasonable. Emojis to be displayed in the panel are often related to the state, workflow and domain knowledge. in total nine tags including both coloured and emoji, limits in implementing complex workflows.
