### ISSUE TITLE
Newer OS versions don't show in error reports

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3116]
`oscpu` is capped, so we just get, e.g.,`10.15`.

It looks like we can get something from `Services.sysinfo.getProperty("version")`. On macOS that's the Darwin version, but that's better than nothing and maps roughly to a macOS release. Even about:support doesn't have the actual OS release number.

I'm not seeing anything else that's not in native code. We could run something from the command line or use js-ctypes if we really needed to.

**Comment by adomasven** [comment]
Checking for newer macOS versions is available as part of Mac Word ctypes functions https://github.com/zotero/zotero-word-for-mac-integration/blob/fx102/components/zoteroMacWordIntegration.js#L117

**Comment by dstillman** [comment]
Fixed by f9dab9b04187fcb0f13c3228d38c490f0e385c06
