### ISSUE TITLE
Update SingleFile to 1.0.47

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3123]
Includes https://github.com/gildas-lormeau/SingleFile/issues/1161

**Comment by dstillman** [comment]
This will fix https://github.com/zotero/zotero-connectors/issues/434.

**Comment by adomasven** [comment]
I've set up zotero-connectors to use its own instance of SingleFile(-Lite), not dependant on the one in Zotero and updated https://github.com/zotero/zotero-connectors/compare/5c0e502320e1...cfe07f5d61e6. I've also updated the SingleFile submodule in this repo https://github.com/zotero/zotero/commit/885ef28a0dd5a0fff55f4f14e026db45e91a89a1
