### ISSUE TITLE
[Waiting until fixed in PDF.js] Image not shown in PDF

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3124]
https://forums.zotero.org/discussion/105109/problem-in-displaying-some-pdf-files

I can reproduce this. The chess diagram on page 25 doesn't show in Zotero 7, but it does show in Firefox.

**Comment by mrtcode** [comment]
Weird. It doesn't show up for me on Firefox 113.

**Comment by mrtcode** [comment]
There are image loading errors. I'll report the issue upstream, if it hasn't been reported yet.

**Comment by mrtcode** [comment]
Already fixed.
