### ISSUE TITLE
Customizing the {{citation}} format in annotations.noteTemplates.

### ISSUE THREAD

**Issue by HerstalR** [zotero/zotero#3158]
I'm using Zotero to add item notes with annotations.noteTemplates. I have tried changing {{citation}} in the editor preferences, but it doesn't affect the citation format in the item notes no matter what I do. I want to customize the format to be (page, title), but I couldn't achieve it.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
