### ISSUE TITLE
Zotfile related file loss in Zotero 7 transition

### ISSUE THREAD

**Issue by jlegewie** [zotero/zotero#3179]
As discussed [here](https://forums.zotero.org/discussion/comment/437146/#Comment_437146), one of zotfiles features might lead to file loss when transitioning from Zotero 6 to 7. This applies to people who are using zotfile to send and get files from the tablet (optional setting under "Tablet Settings") and have set the ".tablet.mode" setting to 1, which is the default called "background mode" in the documentation. With these settings, clicking on "Send to Tablet" essentially creates to two copies of files. One is a standard stored copy of a file in zotero (no problem here) and the second is an external file with information on location etc stored in the the attachment note only visible to the user as "(hidden zotfile data)". Happy to give more details.

Many unfortunate choices on the implementation of this feature going back 12 years or so. No idea how many users are impacted but I would like to address it in some way. One option would be to push a zotfile update that at least warns users or addresses the problem in some way. An alternative would be to add some transition code to Zotero 7. I would be happy to submit a pull request in early July if the developers are open to that.

(I can move this discussion to the Zotero forum if preferred)

**Comment by dstillman** [comment]
So when you use that feature, it stores the file and then makes a copy elsewhere, and the issue would be that someone might have modified the file elsewhere (e.g., on an Android tablet) but not yet transferred it back, so if they lost ZotFile that file would be orphaned with no mechanism for copying it back over the stored file?

How does background mode handle copying files back?

**Comment by jlegewie** [comment]
Yes, that is correct. The two main function are:

1. `Zotero.ZotFile.Tablet.sendSelectedAttachmentsToTablet()`. In background mode, this function creates a copy of a zotero attachment "on the tablet" (location selected by the user on dropbox or somewhere else). Location and status of this file is stored in the note for the zotero attachment.
2. `Zotero.ZotFile.Tablet.getSelectedAttachmentsFromTablet()`. Get the file back from the tablet. How this works depends on which file was modified and the preference `tablet.storeCopyOfFile` (relevant part of the code is [here](https://github.com/jlegewie/zotfile/blob/301bf61f8a4689fe098f9d3343a2ee20feb4d97f/chrome/content/zotfile/tablet.js#L631)):
- Both are not modified or only the zotero file changed: The "tablet file" is simply deleted and information removed from the attachment note in Zotero.
- Tablet file modified: The zotero attachment is replaced by the tablet file and the tablet file removed.
- Both modified: The user is promoted to decide what to do including the option to keep both files.

(this description is simplified because it ignores the preference `tablet.storeCopyOfFile`)

**Comment by jlegewie** [comment]
Here are possible solutions. All could be implemented on the Zotero or zotfile side:

1. Notify users who are impacted about the orphaned files.
2. Run some version of `getAttachmentFromTablet` for which impacted file. That might generate many prompts if a user regularly modified both files (unlikely). Another downside is that it would remove the files from the "tablet location".
3. Create linked attachments for each file on the tablet. Advantage is what all files remain where they are and can be accessed by the user. Downside is that it would create multiple copies of attachments in Zotero (one stored copy and one linked) even for files that are identical.

**Comment by jlegewie** [comment]
Just checking in on any preference to address this from the Zotero side. Otherwise, I will implement something on the zotfile side probably using approach 3 outlined above.

**Comment by dstillman** [comment]
Yes, I think addressing this pre-upgrade on the ZotFile side makes sense, but might be worth prompting before creating duplicates of all files. People may be content with just making sure they have the latest copies for their stored files. (Presumably some people who were using this feature have since switched to the iOS app — or could — and others will be planning to switch to the Android app when it's available.)

**Comment by jlegewie** [comment]
I just put a small Zotero 7 plugin on GitHub that makes it possible to recover the impacted files... Closing this issue. 
https://github.com/jlegewie/ZotFile-Recovery

**Comment by dstillman** [comment]
Great, thanks!
