### ISSUE TITLE
Remember per-file page position and split position for split views

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3181]
https://forums.zotero.org/discussion/comment/437126/#Comment_437126

**Comment by mrtcode** [comment]
I'm not entirely convinced that it should use the previously saved position if you split the view again. I think there is a high chance that you want to start from the same position as the primary view where you can scroll one of the views to compare the data from different sections.

The individual second view state (page and split position) is fully preserved until you unsplit the view, which means you no longer need it.

The references use case will be solved in other ways, in future. Split view won't be necessary for that.

**Comment by dstillman** [comment]
OK, that's fair.
