### ISSUE TITLE
Prevent orphaned BBT translators from breaking import

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3182]
https://forums.zotero.org/discussion/105719/cannot-import-ris-nor-bib-files and various others

**Comment by retorquere** [comment]
This orphaning shouldn't be happening anymore since BBT is compatible with both 6 and 7, but maybe bundled translators could be marked by having their plugin ID in the header? That way Zotero could more easily crosscheck translators dependent on a companion plugin.

**Comment by dstillman** [comment]
@adomasven: I can reproduce this by placing `BetterBibTeX JSON.js` in `translators/`. (`cat content/resource/BetterBibTeX\ JSON.json content/resource/BetterBibTeX\ JSON.js` from the [ZIP](https://github.com/retorquere/zotero-better-bibtex/archive/refs/tags/v6.7.132.zip) to create it.)

**Comment by retorquere** [comment]
I wouldn't mind adding code to my translators to bail more elegantly if BBT is not installed, but that won't help with translators already out in the wild.
