### ISSUE TITLE
Feature request: global search

### ISSUE THREAD

**Issue by WilczynskiT** [zotero/zotero#3187]
Hello

I have a suggestion for enhancing the application: introducing a global search feature. This functionality would greatly benefit users by allowing them to search within all opened articles simultaneously.

Currently, when I need to find specific information or quotations for my bibliography (but I don't remember which article include selected quote), I have to manually open each article and use Ctrl + F to search within them. It would be much more efficient if we had a global search option, similar to the one found in Visual Studio Code, where I could simply use Ctrl + Shift + F to search across all files in one place.

I believe implementing this feature would greatly improve the user experience.

Thank you for considering my suggestion.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
