### ISSUE TITLE
Window design became unusable

### ISSUE THREAD

**Issue by gernophil** [zotero/zotero#3197]
Today my Zotero started to look very weird. I started to used profiles some days ago, but no clue, if that is related. It is now mostly white text on very light background. Some stuff is completely black though. I removed the .app file and also removed the folder ~/Library/Application Support/Zotero and the file ~/Library/Preferences/org.zotero.plist. After that I reinstalled it, but I had no luck. It was still unusable. I was able to solve it partially, by installing while my system was using the light theme. But still some windows are unusable. Any ideas, if there could be any other settings files somewhere? I am not able to revert it completely.

I am in macOS Ventura (13.4.1)

![250403750-cb7f49fc-6c12-4c0c-9d84-ab6b6fef7e31](https://github.com/zotero/zotero/assets/19264855/dcf58ae9-afa3-4a93-af7b-d218e9d5e977)

![250403762-573219b9-08c2-49d3-a459-b0f0e29dc18b](https://github.com/zotero/zotero/assets/19264855/5dd24f82-5c91-4633-9378-e5494e530c22)

After installing in light system mode:
![Bildschirmfoto 2023-07-02 um 23 56 22](https://github.com/zotero/zotero/assets/19264855/5bc3859d-bd4b-4150-94f7-c9f2219e0489)

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
