### ISSUE TITLE
Disable File → Close in library tab if multiple tabs open

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#3198]
It doesn't close the window if library tab is selected and there are more than one tab.

If this is intentional, at least the Close option should be grayed out.

**Comment by dstillman** [comment]
Yes, that's [intentional](https://github.com/zotero/zotero/blob/aca86967bf3159d14b0eb4aa81b55d765b39a2f6/chrome/content/zotero/zoteroPane.js#L798-L804) (and yes, disabling Close would be good)

**Comment by fcheslack** [comment]
On linux this also means there is no shortcut that quits Zotero now. Firefox and many other things (in KDE at least) uses Ctrl-Q which I think we should do.

**Comment by dstillman** [comment]
There's still Alt-F + Q on Linux, but Ctrl-Q is supposed to work too. It looks like it's just broken.
