### ISSUE TITLE
Unicode "isolate" characters added to filenames

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3207]
https://forums.zotero.org/discussion/comment/438450/#Comment_438450

I assume we're now returning these characters for `getField('firstCreator')`, and that's used in `Attachments.getFileBaseNameFromItem()`.

Another bug after https://github.com/zotero/zotero/commit/6d5ce578e430380b633c4e8a32898ab4975dfa2e and #3135

**Comment by tnajdek** [comment]
I believe I've tripped over this while working on [Customizable renaming rules](https://github.com/zotero/zotero/pull/2297/files#top): (https://github.com/zotero/zotero/pull/2297/files#diff-188c76898ff9082f761a9204eeff48b1d8031c3a5b81795e4afffb53ab731339R2392-R2396)

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/106364/feature-or-bug-rename-attachments-in-zotero-7-beta-21
