### ISSUE TITLE
Item Box API

### ISSUE THREAD

**Issue by windingwind** [zotero/zotero#3224]
Register a custom row in the item box, including the library and reader's info panel.

- Editable
- Multi-line
- Update data
- Unregister when the plugin is disabled

**Comment by windingwind** [comment]
#3255

**Comment by retorquere** [comment]
Does this mean the API is completed? How do I use it?

**Comment by dstillman** [comment]
Not yet. https://github.com/zotero/zotero/pull/3255 needs to land.
