### ISSUE TITLE
`attachmentTitle` variable in filename template string?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3252]
https://forums.zotero.org/discussion/comment/440331/#Comment_440331

People will want a way to include an arbitrary string in the filename, and if you have multiple child attachments, that can't be a parent item field.

The problem is that you wouldn't want any attachment title to be used — you'd probably want the ability to test the value (`startsWith`, `includes`, or `regexp`) and extract a substring (index-based `slice` or `match` with a regexp). You could then either exclude anything with "PDF", "Accepted Version", or "Submitted Version" (to exclude all the default titles) or use a prefix like `fn: ` to specify a string to include in the filename. Just thinking out loud here:

Borrowing from jq/shell:

```
{{ if attachmentTitle | startsWith("fn:") }}{{ attachmentTitle | substring(4) }}{{ endif }}
```

Sticking closer to JS:

```
{{ if attachmentTitle.startsWith("fn:") }}{{ attachmentTitle.substring(4) }}{{ endif }}
```

Granted, at some point the question becomes why we're not just using an existing template language…

For this specific problem, we could also make the attachment note accessible, but we've been trying to deprecate those for years.

**Comment by dstillman** [comment]
Returning to this (because of https://forums.zotero.org/discussion/comment/468344/#Comment_468344), I'm not sure why I thought having people use a visible prefix `fn:` was a good idea — that seems like a gross hack. But maybe enough to be able to test for specific strings?

**Comment by tnajdek** [comment]
OK, I'll look into extending `generateHTMLFromTemplate` to allow this and then adding `attachmentTitle` to vars available in `getFileBaseNameFromItem`. I'm leaning more towards the JS-inspired syntax than the pipe syntax.

**Comment by tnajdek** [comment]
After [implementing a large portion of this](https://github.com/zotero/zotero/compare/main...tnajdek:zotero:3252-extend-filename-template-string), I've realized that I really dislike the new syntax: it's tricky to write, messy to parse and it seems to conflict with our existing mechanism of calling functions from templates.

I'm thinking about reusing our syntax instead, e.g., just adding `match` (which results in truthy or falsy string) could enable this:

````
{{ if {{ attachmentTitle match="^(full.*|submitted.*|accepted.*)$" }}}}
{{ firstCreator suffix=" - " }}{{ year suffix=" - " }}{{ title truncate="100" }}
{{ else }}
{{ attachmentTitle }}
{{ endif }}
````

we could add something like `start` to enable substrings with existing `truncate` (i.e. how `substr` used to work in JS):

````
{{ attachmentTitle start=3 truncate=5 }}
````

We could also borrow `strip_prefix`/`removeprefix` from rust/python; going back to your `fn:` example

````
{{ if {{ attachmentTitle match="^fn:.+$" }}}}
{{ attachmentTitle strip_prefix="fn:" }}
{{ else }}
{{ firstCreator suffix=" - " }}{{ year suffix=" - " }}{{ title truncate="100" }}
{{ endif }}
````
I feel like this would work much better, I'll try to implement this tomorrow.

**Comment by dstillman** [comment]
Yeah, that's a much better idea. It would also be a complement to https://github.com/zotero/zotero/pull/3562, which implements regex replace.

I wouldn't worry about prefixes for now — `fn:` was a bad idea, and it could be handled by #3562 anyway.
