### ISSUE TITLE
Extra click is required in reader to open three-dots context menu

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#3304]
First click to close currently opened context menu, second to actually open a context menu.

https://github.com/zotero/zotero/assets/214628/0d96212e-75ed-4c43-b8be-47e8dc4bc1ae

**Comment by mrtcode** [comment]
I agree, single click would be more convenient, but aren't all context menus are working like this?

**Comment by tnajdek** [comment]
Sorry, you're correct, that's how it works elsewhere in Zotero, let's keep it consistent then.

**Comment by dstillman** [comment]
(And not just Zotero — that's seemingly how it works most places (e.g., in the Firefox toolbar, in Finder, on this webpage)).

**Comment by tnajdek** [comment]
I agree, that seems to be more prevalent approach (surprisingly Firefox toolbar behaves differently for me, i.e. no extra click needed - weird)

**Comment by dstillman** [comment]
Oh, it varies by element.

Application menu button → open-tabs menu = 1 clicks
Bookmarks-bar overflow button → open-tabs menu = 2 clicks
