### ISSUE TITLE
Localize Word toolbar

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3314]
https://forums.zotero.org/discussion/106857/installation-de-zotero-dans-word-en-anglais-et-non-en-francais

Is there any mechanism for this in the template?

**Comment by adomasven** [comment]
Not with the template, but with the word js api there is.

**Comment by adomasven** [comment]
Also a duplicate of https://github.com/zotero/zotero-word-for-windows-integration/issues/18
