### ISSUE TITLE
Use any emoji from tag in middle pane

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3324]
You shouldn't have to make a tag a colored tag to use the emoji, and you should be able to include text as well.

Only question is whether happens if multiple emoji are separated by plain text. Are all the emoji used? Just the first contiguous span?

**Comment by asan-emirsaleh** [comment]
What is the progress? Is this feature available on Zotero beta now?

**Comment by asan-emirsaleh** [comment]
In case you need some help in testing this feature one possible approach would be to implement it in beta, with allowing it be optionally activated in Config editor. I would participate in testing with a pleasure.
