### ISSUE TITLE
PDF view: Moving mouse from internal link to external link breaks popup

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#3374]
1. Hover over an internal link
2. Quickly move mouse to external link so popup doesn't disappear while moving

Popup won't change to an external link popup as expected, but will lose its shadow and border.

(I can email a PDF that makes it easier to reproduce this if that would be helpful.)

**Comment by mrtcode** [comment]
Yeah, overlay popups are experimental so far.

**Comment by mrtcode** [comment]
It should be fixed.
