### ISSUE TITLE
PDF Reader: Changes to the same PDF opened in a tab and in a separate window do not sync

### ISSUE THREAD

**Issue by abaevbog** [zotero/zotero#3375]
If the same PDF is opened as a tab and as a separate window, `delete` actions don't sync between them.

1. Open the same PDF in a tab and in a separate window.
2. In the tab, add an annotation. Notice it appears in the PDF opened in a separate window.
3. Also from the tab, delete the annotation. 
4. Notice that it is gone from the tab but it remains on the PDF in the window.

<img width="1497" alt="reader_bug" src="https://github.com/zotero/zotero/assets/36271954/1ebf629b-50aa-4bf7-9f85-e83d4e24cee3">

The annotation is gone if the window is closed and reopened again.

**Comment by mjthoraval** [comment]
Probably this one: https://github.com/zotero/zotero/issues/3241
