### ISSUE TITLE
PDF view can't be scrolled with touch

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#3377]
https://forums.zotero.org/discussion/107256/zotero-7-desktop-no-scrolling-in-pdf-reader-on-touchscreen
https://forums.zotero.org/discussion/107271/touchscreen-behavior-in-zotero-7-reader-windows

**Comment by wisp3rwind** [comment]
For what it's worth, this issue also affects Linux with `MOZ_ENABLE_WAYLAND=1` and `MOZ_USE_XINPUT2=1` environment variables set. Like this, touch scrolling used to work in earlier betas. I also first noticed this in beta 32, some earlier version (maybe beta 26 or so?) worked.
