### ISSUE TITLE
Close tab of items that are moved to the trash

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#3386]
If an item is moved to the trash, Zotero should close that item's tab if it happens to be open.

**Comment by dstillman** [comment]
@abaevbog: Maybe add a Notifier observer in `Zotero_Tabs.init()` that watches for the `item`/`trash` event?

**Comment by dstillman** [comment]
Oh, yeah, works for me too. @stakats, reopen if you're not seeing this somewhere.
