### ISSUE TITLE
Split view remains enabled after restart even if it was disabled before restart

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#3390]
https://forums.zotero.org/discussion/107345/zotero-7-persistent-split-views-in-opened-tabs

**Comment by abaevbog** [comment]
I added a commit to my [PR](https://github.com/zotero/zotero/pull/3358) dealing with saving state and reopening reader and notes windows that should solve this.

**Comment by mrtcode** [comment]
@abaevbog Sorry, I haven't noticed your message and fixed this as well. The actual problem was inside the reader. But you can test as well if everything works correctly now.
