### ISSUE TITLE
Move proxies to JSON

### ISSUE THREAD

**Issue by simonster** [zotero/zotero#34]
Among other things, this would permit us to enable proxy redirection in Zotero for Firefox when Standalone is open.

**Comment by aurimasv** [comment]
Besides proxy redirection in Firefox, is there another reason to move proxies to a JSON file? IMO  proxy redirection in Firefox in connector mode should be handled by communicating with Standalone to retrieve proxy information. This would also allow proxy redirection in other connectors (where that is possible at all)

**Comment by simonster** [comment]
Proxy redirection should work in other connectors without Standalone open, so we need a solution that does not rely on Standalone.

**Comment by aurimasv** [comment]
I think proxy redirection settings should sync across computers, so it seems like having Zotero managing those settings (not the connectors) is the most straight-forward approach.

Without Standalone, connectors could communicate with zotero.org to retrieve the settings too, I suppose.

**Comment by simonster** [comment]
It would be good to sync proxies. I'm not sure it's critical, since they populate themselves. It also seems like it would not be fun, since you have to deal with cases where the proxy list was changed on two machines simultaneously. @dstillman would know better.

In any case, I don't think we need a full-fledged DB to handle proxies. They're not much data and we load them all at startup, so (I think) it's easier to store them as JSON. If we're going to sync them, we could store the JSON in the DB if it makes them easier to sync. Otherwise it's obviously easier to use the same code to load them in full and connector mode, which suggests they should live in a file.

**Comment by dstillman** [comment]
Stuffing the JSON into the DB with Zotero.SyncedSettings.set() at startup and on change would be fine, if we want them to sync.

We don't bother with conflict resolution for synced settings, though, and I don't think we would here, which means that a remotely changed proxy list would always overwrite a local one. But if people are using auto-sync (which will be push-based) that may be fine.

How good are we at avoiding using proxies unnecessarily when on a privileged network? (Is that the "Disable proxy redirection when my domain name contains" setting, which appears to be off by default?) Seems like syncing would cause more problems with that.

**Comment by aurimasv** [comment]
>How good are we at avoiding using proxies unnecessarily when on a privileged network? (Is that the "Disable proxy redirection when my domain name contains" setting, which appears to be off by default?) Seems like syncing would cause more problems with that.

"Enable proxy redirection" option would not be synced, so different computers could turn that off if needed. That would solve the problem for desktops, but the issue would remain for laptops (with or without syncing these settings).

**Comment by dstillman** [comment]
Yeah, but this problem would become much more common with syncing. And I'm not sure how much is really gained by syncing these to begin with. (This is rather tangential to the issue of moving them to JSON, though.)

**Comment by simonster** [comment]
What happens on privileged networks depends on proxy configuration. Some proxies will redirect to the unproxied site. In that case, we first try to redirect to the proxied site on the initial load and then we get redirected back. We don't try to redirect through the proxy when navigating the site because we recognize that the referrer was proxiable but unproxied.

Other proxies don't ever redirect. In this case, the "Disable proxy redirection when my domain name contains" setting is useful, although not always sufficient because not every IP has reverse DNS. But having to log in to your proxy even though you don't need it isn't necessarily the worst thing in the world.

Finally, there are places like MIT where most databases can be accessed on campus without a proxy, but because of the whole @aaronsw thing, JSTOR always needs to be accessed through the library proxy. So on my work machine, I have proxy redirection enabled, but only for JSTOR.
