### ISSUE TITLE
Impossible to "Edit Page Number" of annotation that isn't selected

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#3409]
`labelNode is null` in https://github.com/zotero/reader/blob/5f4c4b98cbb13560f67d984d251ee5bc94329741/src/common/reader.js#L1293

https://github.com/zotero/zotero/assets/214628/fe52185c-ab75-4c19-9876-5cbc7573abbf

**Comment by mrtcode** [comment]
Well, the primary issue is that page labels are missing for all visible annotations in the video . Any idea why?

**Comment by tnajdek** [comment]
ha that's a good question, I don't know, but it's from my test library so these annotations might have been created incorrectly at some point.

I guess not an issue then, though it might be worth considering some default value so it works even in this scenario.

**Comment by mrtcode** [comment]
Ok, I'll update the anyway.
