### ISSUE TITLE
Questions about snapshot and note table optimization.

### ISSUE THREAD

**Issue by pengxy0** [zotero/zotero#3447]
Questions about snapshot and note table optimization.
1. Hopefully the preview feature of Snapshot will be implemented in the next update soon, and this feature is simply too important;
2. The column width of the note table cannot be adjusted manually, I hope this function can be optimized;
3. I hope that the size of the pictures in the notes can be adjusted by dragging and dropping the mouse.
Thank you to the people behind them who have contributed to scientific research!

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
