### ISSUE TITLE
Mendeley importer creates annotations on non-PDF items

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#3454]
https://forums.zotero.org/discussion/108533/parent-item-15876345-ij9jpbjc-of-highlight-annotation-must-be-a-pdf-attachment

Should we discard annotations on non-PDF items during import? If we do, we could also sniff mime type of the actual file and correct it if it happened to be a PDF but Mendeley reported otherwise (we already do this for empty mime types).

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/446126/#Comment_446126

Looks like this was a PDF file without a .pdf extension that was imported as application/octet-stream. We could sniff these, the same way we're doing in Zotero 7 [on open](https://github.com/zotero/zotero/blob/c27bac2ad629b2ff216462515c220e2d5ce148ba/chrome/content/zotero/zoteroPane.js#L4716-L4724).

**Comment by tnajdek** [comment]
Importer will now also sniff for a mime type if content type is set to `application/octet-stream`, and then, unless item is a PDF, it will discard annotations.
