### ISSUE TITLE
'preprint' is not a valid itemType"

### ISSUE THREAD

**Issue by uniuuu** [zotero/zotero#3458]
When trying to upload paper from https://arxiv.org/ the Zotero 6 generates error:
![Preprint_error-message](https://github.com/zotero/zotero/assets/26146469/15cd1a13-8fb4-41bd-84b0-30e30adaae52)

Checking file https://github.com/zotero/utilities/blob/master/resource/zoteroTypeSchemaData.js there is preprint
But no preprint in  https://github.com/zotero/zotero/blob/main/resource/schema/system-107.sql as well as no such the in dataserver's itemsType https://github.com/zotero/dataserver/blob/master/misc/coredata.sql

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/108922/preprint-is-not-a-valid-itemtype

https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
