### ISSUE TITLE
Better/retina-style OS X toolbar icons

### ISSUE THREAD

**Issue by simonster** [zotero/zotero#347]
On OS X current toolbar icons are styled according to the Firefox 3.6 UI and not retina-sized (see https://forums.zotero.org/discussion/24669/zotero-and-retina-display/ and zotero/zotero-standalone-build#29). It would be great to have icons that look a little nicer.

There are actually two issues here. The first is that the button textures are non-standard and are bitmap images that aren't retina-sized (because they were derived from Firefox 3.6). It's easy to switch these to native OS X buttons, although I've avoided doing so because the contrast with the rest of OS X is even more glaring that way. I have a local branch where I tested that out, and I'll post a screenshot at some point.

Any new icons should be as similar to the current icons as possible, so that we can minimize changes to our documentation to deal with different icons on different platforms.

One possibility is to use monochrome "template" icons. This seems to be Apple's preferred style these days, but @dstillman raised the concern that monochrome icons might not be sufficiently recognizable for our use.

Another possibility is to use larger (32/48 px standard, 64/96 px Retina) toolbar icons, at least in Zotero Standalone, and remove the button shading entirely. These might consume too much vertical space for Zotero for Firefox, though, and it would be nice to maintain UI consistency at least on the same platform.

cc @dengemann

**Comment by dstillman** [comment]
Many 2x icons added in af871a3fd53a47561ed590f044bb82176faecf9f
