### ISSUE TITLE
zotero building error "epubjs@0.3.93 build"

### ISSUE THREAD

**Issue by cmf41013** [zotero/zotero#3477]
My operating system is Windows 10， when I build zotero source code  strictly following this article [https://www.zotero.org/support/dev/client_coding/building_the_desktop_app_windows_notes](https://www.zotero.org/support/dev/client_coding/building_the_desktop_app_windows_notes),
errors occurred while I was executing the command `app/scripts/build_and_run -r`

It shows :
![err_pic1](https://github.com/zotero/zotero/assets/51567730/f754fd7c-f78a-483f-adeb-51e8e1e2fd3d)
![err_pic2](https://github.com/zotero/zotero/assets/51567730/b680b482-9031-43ff-a8f5-59612e3481e9)

[ln] chrome.manifest

Error: Error: Command failed: npm ci
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: ht
tps://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recomme
nded you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recomme
nded you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recomme
nded you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recomme
nded you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated karma-phantomjs-launcher@1.0.4: PhantomJS development have stopped, use puppeteer or similar
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be proble
matic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be proble
matic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whi
ms, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please,
 upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path J:\zotero_dir\src\zotero-client\reader\epubjs\epub.js
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run compile && npm run build && npm run minify && npm run legacy && npm run productionLegacy
npm ERR! > epubjs@0.3.93 compile
npm ERR! > babel -d lib/ src/
npm ERR!
npm ERR! Successfully compiled 27 files with Babel (988ms).
npm ERR!
npm ERR! > epubjs@0.3.93 build
npm ERR! > NODE_ENV=production webpack --progress
npm ERR! Browserslist: caniuse-lite is outdated. Please run:
npm ERR!   npx update-browserslist-db@latest
npm ERR!   Why you should do it regularly: https://github.com/browserslist/update-db#readme
npm ERR! 'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
npm ERR! ���������ļ���

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cmf_ttkn\AppData\Local\npm-cache\_logs\2023-11-07T09_01_48_194Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npm ci',
  stdout: '',
  stderr: 'npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs\n' +
    'npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json\n' +
    'npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MD
N: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility\n' +
    'npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated\n' +
    'npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated\n' +
    'npm WARN deprecated har-validator@5.1.5: this library is no longer supported\n' +
    'npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated\n' +
    'npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies\n' +
    'npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies\n' +
    'npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated\n' +
    'npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead\n' +
    'npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is re
commended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)\n' +
    'npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is re
commended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)\n' +
    'npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is re
commended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)\n' +
    'npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is re
commended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)\n' +
    'npm WARN deprecated karma-phantomjs-launcher@1.0.4: PhantomJS development have stopped, use puppeteer or similar\n' +
    'npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.\n' +
    'npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated\n' +
    'npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be p
roblematic.  See https://v8.dev/blog/math-random for details.\n' +
    'npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be p
roblematic.  See https://v8.dev/blog/math-random for details.\n' +
    'npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\n' +
    'npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engin
e whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Pl
ease, upgrade your dependencies to the actual version of core-js.\n' +
    'npm ERR! code 1\n' +
    'npm ERR! path J:\\zotero_dir\\src\\zotero-client\\reader\\epubjs\\epub.js\n' +
    'npm ERR! command failed\n' +
    'npm ERR! command C:\\Windows\\system32\\cmd.exe /d /s /c npm run compile && npm run build && npm run minify && npm run legacy && npm run productionLegacy\n' +
    'npm ERR! > epubjs@0.3.93 compile\n' +
    'npm ERR! > babel -d lib/ src/\n' +
    'npm ERR! \n' +
    'npm ERR! Successfully compiled 27 files with Babel (988ms).\n' +
    'npm ERR! \n' +
    'npm ERR! > epubjs@0.3.93 build\n' +
    'npm ERR! > NODE_ENV=production webpack --progress\n' +
    'npm ERR! Browserslist: caniuse-lite is outdated. Please run:\n' +
    'npm ERR!   npx update-browserslist-db@latest\n' +
    'npm ERR!   Why you should do it regularly: https://github.com/browserslist/update-db#readme\n' +
    "npm ERR! 'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\n" +
    'npm ERR! ���������ļ���\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\cmf_ttkn\\AppData\\Local\\npm-cache\\_logs\\2023-11-07T09_01_48_194Z-debug-0.log\n'
}

How can I fix this error? thanks

**Comment by cmf41013** [comment]
When I execute the conmmand `npx update-browserslist-db@latest` in source code root path , the errors still apear.
 When I execute it in  `zotero-client\reader\epubjs\` directory,  more errors appears.
 
 Can someone help me ? thanks

**Comment by dstillman** [comment]
I'm afraid we're not able to help with Windows-specific build problems. If you can't figure it out, you should use WSL and follow the regular build instructions.
