### ISSUE TITLE
Use HTML XHR instead of hidden browsers for processDocuments

### ISSUE THREAD

**Issue by simonster** [zotero/zotero#348]
As long as translators aren't touching `defaultView` within `processDocuments` and don't need anything that requires the JS on the page to execute, we can load documents using HTML XMLHttpRequests instead of using hidden browsers. This would simplify a lot of things. @aurimasv and @adam3smith, do you know of anything this would break?

**Comment by adomasven** [comment]
@adam3smith , @zuphilip do we know if any translators rely on JS onload being evaluated? If not, I'll likely proceed with this on the connector side of things, because using hidden frames is bottlenecking [some features](https://github.com/zotero/zotero-connectors/issues/86) and causing [issues on firefox](https://forums.zotero.org/discussion/66416/pica-translator-does-not-work-for-multiple-entries)

**Comment by zuphilip** [comment]
For some translators we need `monitorDOMChanges` because some content is loady dynamically and without watching for this the `detectWeb` would fail. Moreover, e.g. this website https://theintercept.com/document/2017/02/22/mastering-the-internet/ loads as html only the basic structure and the data is then AFAIS filled with JavaScript, see also https://github.com/zotero/translators/pull/1365. Was this your question? Would the suggested way then open the website similar to a browser with JS deactivated?

**Comment by adomasven** [comment]
Yep, that answers the question. Loading via XHR is a no-go - it would indeed open the website as if JS was disabled. Looking for an alternative solution.

**Comment by dstillman** [comment]
Well, hang on. First, this would only affect search results, right? If we really wanted to switch to XHR, we could just not support saving from search results on sites that required JS for page content. But I'm not sure The Intercept is a good example. Most of the site seems to work fine without JS enabled — they appear to use React, but with server-side rendering, and aren't we using JSON-LD for the articles anyway? — and when it doesn't (e.g., [the document view](https://theintercept.com/document/2017/02/22/mastering-the-internet/) mentioned in the other ticket) we could still get the JSON they're using for the initial page state, get the Document Cloud id from that, and get the [document metadata/URL](https://www.documentcloud.org/api/documents/3470275-MTI.json) from that. So while it might be a little more brittle (e.g., they could change the initial-state JSON structure of the document views), I don't think that translator needs to be written to require page JS.

While we're certainly not heading to a world of less JS, I don't think that means we have to rely on page JS to extract metadata. Among other things, I would imagine using XHR would make saving dramatically faster.

/cc @owcz, who wrote that translator

**Comment by adam3smith** [comment]
> aren't we using JSON-LD for the articles anyway? 

no, as @owcz [explains](https://github.com/zotero/translators/pull/1365#discussion_r126536042), the JSON-LD is rather poor, so we mainly rely on the page proper

> First, this would only affect search results, right?

(prefacing this with an admission that I only very basically understand the technology involved)
right -- that's the only place where we'd run `detectWeb` on a document obtained using `processDocuments` -- and I'm not convinced it'd be impossible to work around that. That'd depend in part on how exactly the XHR we get returned looks.

**Comment by dstillman** [comment]
> no, as @owcz explains, the JSON-LD is rather poor, so we mainly rely on the page proper

Well, that was about documents (`scrapeDocument`), not articles (`scrape`). We appear to be using a combination of the page content (which we'd still have, because of the server-side React rendering) and JSON-LD for articles.

**Comment by dstillman** [comment]
> That'd depend in part on how exactly the XHR we get returned looks. 

I assume what we would do is make an XHR with `responseType: 'document'`, so you'd still get a `Document` to work with, could still use `querySelector()`, etc. It just wouldn't have been changed at all by JavaScript.

One thing I'm not totally clear on, which @adomasven would know better, is whether the same-origin policy is a factor here. Can we make cross-origin XHRs in injected code? If not, can we pass the URLs to the background page, make XHRs there, and pass the text back for parsing?

**Comment by zuphilip** [comment]
Maybe, better website which uses JS is Academic Search: https://academic.microsoft.com/ where the translator was also very challenging: https://github.com/zotero/translators/blob/master/Microsoft%20Academic.js . If I disable JS on in Chrome then I cannot use that website at all.

**Comment by adomasven** [comment]
> I assume what we would do is make an XHR with responseType: 'document', so you'd still get a Document to work with, could still use querySelector(), etc. It just wouldn't have been changed at all by JavaScript.

If we want this to work, then using only XHRs doesn't change anything fundamentally. Currently the source of issues is cross-origin `processDocument` calls, which we do exactly by passing the URL to the background page and making the XHR there, then passing the content back, embedding it in an `<iframe>` (the step which at the moment is broken in Firefox, but I have a hacky fix already) and passing `iframe.contentDocument` to the processor. Non cross-origin documents are loaded by setting `iframe.src` directly.

> So while it might be a little more brittle (e.g., they could change the initial-state JSON structure of the document views), I don't think that translator needs to be written to require page JS. <...> Among other things, I would imagine using XHR would make saving from search results dramatically faster.

We still run translators on fully loaded webpages when saving directly, so translators would need to handle both a JS processed and unprocessed pages (or we'd need to cache pages pre-JS evaluation, making the whole connector much slower). Furthermore, translator developers are community contributors and making their work more brittle is not ideal. We can handle the brittleness on our side.

**Comment by dstillman** [comment]
> Maybe, better website which uses JS is Academic Search […] If I disable JS on in Chrome then I cannot use that website at all.

Having the site not work with JS disabled isn't a problem, though. It's only a problem if you can't get metadata from the search page. From the looks of it, when you click on a search result on that site, the page makes a single API request that returns JSON, which it uses to display the page. And it looks like the translator is already using that. In fact, this translator doesn't use `processDocuments` at all.

**Comment by dstillman** [comment]
> Furthermore, translator developers are community contributors and making their work more brittle is not ideal.

The hierarchy here, in increasing order of importance, is 1) our experience, 2) community developers' experience, and 3) users' experience. If we can make saving much faster and lower-load, avoiding loading many multi-megabyte webpages in the background, we should definitely do that. As for brittle, I think the case of having to parse JSON out of a script tag as on The Intercept document-view pages would be quite rare, and it's entirely possibly that'd be more static than the page structure itself anyway.

Now that I think about it, we're actually [already doing this](https://github.com/zotero/translation-server/blob/c59c1d6a56aaa32ae69c613a4f07f9989e623bb5/src/hacks.js#L74) in translation-server.

**Comment by dstillman** [comment]
> embedding it in an <iframe> (the step which at the moment is broken in Firefox, but I have a hacky fix already) and passing iframe.contentDocument to the processor. Non cross-origin documents are loaded by setting iframe.src directly

I suspect this was written before DOMParser was widely available. So the modern, fast approach would be `responseType = 'document'` for same-origin requests and background responseText + DOMParser for cross-origin.

**Comment by dstillman** [comment]
Implemented in https://github.com/zotero/zotero/commit/d073dec84dc50e386cd2336fc8fd0be89d4cb81d
