### ISSUE TITLE
Unable to display tag icons on the item

### ISSUE THREAD

**Issue by yanyu2015** [zotero/zotero#3486]
In Zotero 6, when I add a tag to an item, a colored dot or an emoji is displayed on the left side of the item. However, after upgrading to Zotero 7, this feature is no longer visible. Could you help me?

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md

(But I'd guess that this is caused by some plugin you have installed.)

**Comment by yanyu2015** [comment]
But I closed all the plug-ins and restarted zotero, but the problem was still not solved.
