### ISSUE TITLE
Website registration is not working

### ISSUE THREAD

**Issue by ariymarkowitz** [zotero/zotero#3492]
I know this is the wrong place to post this, but I can't find anywhere to get support that does not require making an account.

Website registration does not work on Safari, Chrome, or Firefox. It looks like the problem is with the reCAPTCHA program, because on Firefox the reCAPTCHA box says "Could not connect to the reCAPTCHA service. Please check your internet connection and reload to get a reCAPTCHA challenge." On other web browsers, the reCAPTCHA box does not appear at all.

**Comment by dstillman** [comment]
You can email support@zotero.org with login issues (as noted on the [contact page](https://www.zotero.org/support/contact_us), but not much we can say on that. reCAPTCHA is working here, so if it's still not working for you it may indeed be an issue with your network connection. You can try again in a bit or try from a different network.

**Comment by dstillman** [comment]
If you have the same ad blocker in all browsers, it could also be that.
