### ISSUE TITLE
Sub-journals under GeoScienceWorld cannot be subscribed properly

### ISSUE THREAD

**Issue by wanlitang908** [zotero/zotero#3501]
Sub-journals under GeoScienceWorld cannot be subscribed properly

for example，RSS feeds of Geology( Sub-journals under GeoScienceWorld  )  can not importing properly

from url: https://pubs.geoscienceworld.org/rss/site_65/advanceAccess_33.xml

Furthermore, I turned on log debugging and found the following log entries
![image](https://github.com/zotero/zotero/assets/151995730/6b0cf1ca-58ef-44ee-a841-5175b2064299)

Thanks for helping with this issue!

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

(That feed is working fine for me, though, so this was likely either a temporary problem with the feed or some problem with your internet connection.)
