### ISSUE TITLE
Add new function: highlighter drawing straight lines and underline drawing straight lines

### ISSUE THREAD

**Issue by bin38121cn** [zotero/zotero#3509]
As we know, the software currently supports freehand drawing, but compared to mainstream note-taking software such as GoodNotes and Notability, they usually support highlighter drawing straight lines, underline drawing straight lines, especially for PDF files. Our software currently does not support drawing methods such as circles and straight lines, and the lines drawn by ourselves are always unable to meet the requirements. It is recommended to add this function, whether it is on the PC side or the mobile side.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
