### ISSUE TITLE
Zotero Entry Information Mysteriously Changing

### ISSUE THREAD

**Issue by lisch7** [zotero/zotero#3566]
Hello Zotero Community,

I've recently encountered a perplexing issue with Zotero. Some of the entries in my library have undergone unexpected changes. For instance, I noticed that the journal name of a particular entry, originally published in 'Cancer Cell', has inexplicably switched to 'Nature'. Additionally, there have been anomalies in the author names as well.

This isn't the first time I've observed this issue. I'm curious to understand what might be causing these changes. Could this be related to any recent updates or syncing errors?

For additional context, I am using the web dev synchronization solution, and I've synced my library across multiple devices. Could the cross-device synchronization be contributing to this problem?

I would appreciate any insights or solutions to ensure the accuracy and stability of my Zotero library.

Thank you for your help!

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
