### ISSUE TITLE
Test timeout: Item Tags Box "should update tag when pressing Enter in textbox"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3575]
We tried to fix this previously in a0ab7783ee2fae5551960bc1e99453f08e01229c, but possible that the `activate()` call doesn't work reliably on Linux?

Test is disabled for now

**Comment by abaevbog** [comment]
I played around with this while I had my linux setup working, and `activate()` promise does seem to be the culprit. I pushed how I got that test to pass

**Comment by dstillman** [comment]
Getting failures here again

https://github.com/zotero/zotero/actions/runs/9201561657/job/25309969100
