### ISSUE TITLE
Don't blur `editable-text` when window blurs?

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#3588]
While writing #3587, I noted that this is the current behavior - entering some text into an `editable-text` and switching to another window saves the field.

Is that actually what we want? Maybe not? I think we can detect whether the field itself is being blurred or the window as a whole; if it's the window, maybe we keep the field active when you switch back and don't save in the mean time?

Might fix the tags-box test, even!

**Comment by dstillman** [comment]
Not what we want — and, in fact, a regression from Z6. (Not sure about earlier Z7 beta.)

**Comment by dstillman** [comment]
On purpose!

https://github.com/zotero/zotero/commit/0b3b296e28305bb4a8e73ab3d1ba6ebdde4c7411
