### ISSUE TITLE
Conflict-resolution window broken in redesign

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3611]
https://forums.zotero.org/discussion/111209/zotero-7-beta-conflict-resolution-window

Much more broken than what @tnajdek saw!

**Comment by dstillman** [comment]
In dark mode too: https://forums.zotero.org/discussion/112705/dark-mode-ui-bug-in-sync-popup

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/113137/blank-conflict-resolution-page-on-startup-and-sync-debug-id-d1533522669-resolved-see-comment

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/113840/remote-synchronization-file-selection

**Comment by dstillman** [comment]
@windingwind: I can help with this (e.g., the dialog buttons), but probably easiest for you to fix things related to the item pane CEs.

To start, we can hide everything other than Info to match previous functionality. We could consider showing certain sections, like tags, but we'd have to review the actual CR behavior for those, so probably easiest to start with just Info for now. We'll also want to hide various things, like the Reindex and Migrate Item Note buttons in the attachments pane. (I assume Reindex was hidden before, but I'm not sure.)

**Comment by windingwind** [comment]
OK, I'll look into it. How do we usually debug the CR window?

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/113990/dark-mode-color-problems-when-there-is-a-sync-conflict

@windingwind: Sorry, missed your question. That'd be great. We have some tests that you could add delays to, but probably easier to just open two copies of Zotero (on separate computers, or in VMs, or in separate profiles), turn off auto-sync, and make conflicting changes. As long as you cancel, you can continue refining.
