### ISSUE TITLE
Remove or fix collection highlight on Ctrl

### ISSUE THREAD

**Issue by abaevbog** [zotero/zotero#3643]
Now that the collections appear in the `itemPane`, does it make sense to remove `ZoteroPane.collectionsView.setHighlightedRows`? It seems redundant now. 

Most importantly, if you press `Ctrl-C`,`Ctrl-V` to copy-paste something on windows, the initial `Ctrl` highlights the collection rows, which is somewhat unexpected (especially for new users who may be not aware of the shortcut).

**Comment by stakats** [comment]
We should definitely remove the highlighting. My only question is whether we would want to preserve ctrl as a way to open the `itemPane` collections section

**Comment by adomasven** [comment]
I need highlighted virtualized table colors for the citation explorer PR, so we should fix the colors even if we remove the behavior.

**Comment by abaevbog** [comment]
As a start, I removed highlighting on Cmd/Ctrl from everywhere in `ZoteroPane` though i kept the `setHighlightedRows` in collectionsView. It's not used anywhere right now but we might want to keep it in case if its's useful for something else later?

I tried a few different colors for the highlighted row of virtualized table, and `--accent-yellow` looked the best to me in both modes. I added it as a separate commit to that PR

**Comment by abaevbog** [comment]
> Sorry, late to this, but what's the argument for removing, other than that we wouldn't have to fix dark mode?

I suppose the arguments are redundancy (e.g. why have 2 solutions to one problem?) and the copy-paste behavior on windows where `Ctrl` from `Ctrl-C` triggers the highlight on windows right now. The later was the reason why I brought this up because if felt odd that as I was copy-pasting text in the `itemPane`, something got highlighted on the other side of the screen. As I am typing this, I am thinking that maybe a better way to address this is to just not do the highlighting if an `input` or `textarea` if focused? That way, it would really not get in the way by highlighting things when you want to copy something, while still being available for those who know about it.

And per @adomasven, the dark mode needs to be fixed regardless if we remove highlighting of collections or not. I think from our existing colors `--accent-yellow` works quite well as a dark-mode friendly substitute.
