### ISSUE TITLE
Show first line of Abstract in section header?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3647]
https://github.com/zotero/zotero/issues/3646#issuecomment-1918265118

To more or less mirror what we had before. Could also just be some generic indicator, which would let us keep the Abstract label, but might as well show some real text?

**Comment by yexingsha** [comment]
![library-compact-item](https://github.com/zotero/zotero/assets/57771795/b543d431-7b9a-4c86-93d4-45dcb17e4949)

**Comment by dstillman** [comment]
Depends on https://github.com/zotero/zotero/pull/3624
