### ISSUE TITLE
Move reader expand/collapse to the reader toolbar and hide sidenav on collapse

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3648]
https://forums.zotero.org/discussion/111115/zotero-7-beta-feature-request-option-to-hide-right-sidebar

Ignoring the confused terminology, I think this is right — we shouldn't be taking up space in the content view. It just doesn’t really provide much value vs. an expand button in the toolbar — it lets you switch to a different section than you were in before in one fewer click, but I don’t think that merits a permanent encroachment on the reader. We also actually occasionally get requests for the ability to view PDFs in full screen without the top chrome, and while that's complicated somewhat by the annotation toolbar (which could become floatable like on iOS), adding yet more things that cover the content is not good.

Mockup from @yexingsha:

https://github.com/zotero/zotero/assets/783082/44a34cab-e79d-43f5-b02f-cc835d8f3881

This can work the same way for Stacked view.

@mrtcode, does this have to be done as part of the reader?

**Comment by mrtcode** [comment]
> @mrtcode, does this have to be done as part of the reader?

Yes, it makes sense to add that button directly into the reader.

> This can work the same way for Stacked view.

But do we want to use the same icon for the button? Because the current icon clearly indicates that the sidebar is on the right side, not the bottom.

**Comment by dstillman** [comment]
(But we can go ahead and implement this before we have the icon for Stacked mode.)

**Comment by windingwind** [comment]
Sounds strange that during dragging the splitter only item pane is resized, but when collapsed, both item pane and sidenav will be... hidden?

**Comment by dstillman** [comment]
Why is that weird? Sidenav is just the right edge of the context pane in this view.

**Comment by windingwind** [comment]
During dragging, only the resizable content is regarded to be collapsible - but the non-resizable dragging anchor element (sidenav) is also suddenly collapsed when the resizable content (itempane) becomes too narrow. That sounds weird.

**Comment by windingwind** [comment]
It still feels unnatural when viewing the dragging target as the item pane, but it feels ok if viewing the dragging target as the reader.

Mentioning the horizontal space, I feel like we are frequently compromising on it and sacrificing other things, mostly the sidnav. That doesn't sound good, since the sidnav becomes somehow a second-class citizen and whenever we need space, we kill it.

What I have in mind to bring a better reading/note editing experience (where we are doing hiding to the sidenav) is to have a full-screen like mode (not really to be full-screen, only hiding all non-content elements, i.e. toolbar, left/right bar) and allowing opening notes as tabs.

**Comment by dstillman** [comment]
Like @yexingsha, I just genuinely don't see this as weird at all. Again, the sidenav is just part of the context pane in this view, with the toggle button outside of it.

> Mentioning the horizontal space, I feel like we are frequently compromising on it and sacrificing other things, mostly the sidnav. That doesn't sound good, since the sidnav becomes somehow a second-class citizen and whenever we need space, we kill it.

The sidenav is 100% a second-class citizen to the reader content. Making one of the reader sidebars not fully close was a regression, and we're just fixing that here. Content is sacred.

We will do a full-screen mode and notes-as-tabs, but that doesn't mean that we need to take up space for no reason in the default mode. We weren't doing it before and we shouldn't do it now.

**Comment by mrtcode** [comment]
@yexingsha

> Also on the topic of dragging, I have always wondered if we can add a bit of snap tolerance (20px maybe) after a pane is resized to its minimum width, so it doesn't instantly go from min width to nothing.

We have a similar behavior when resizing context pane in stacked mode, but I'm not actually sure why is that. But the tolerance is much bigger, probably too big.

@AbeJellinek Could you remove the no longer used code and icons from `ItemPaneSidenav` as I wasn't sure what exactly is still necessary and what isn't.

**Comment by windingwind** [comment]
For the context pane and sidenav changes, we could wait for #3624 - there's a big change

**Comment by mrtcode** [comment]
> For the context pane and sidenav changes, we could wait for #3624 - there's a big change

It's already done, but there are only a few changes and shouldn't be a problem. Probably earlier is even better if context pane rewrite is in progress.

**Comment by windingwind** [comment]
Yes, thanks @mrtcode . If you have time, please check #3624 if anything is missing during the rebasing
