### ISSUE TITLE
Change the position of Title and Locate

### ISSUE THREAD

**Issue by yexingsha** [zotero/zotero#3660]
Since we moved item Title into the new sidepane header, a lot of people have been looking for it in the Info section and missing it entirely, or not realizing that it can be edited in the header. It's also causing some trouble with manual item creation and merge.

Therefore, we are moving Title back to Info, with `position: sticky` so that it sort of becomes a header when you scroll down:

https://github.com/zotero/zotero/assets/57771795/e38c3f88-0774-4281-830c-27a5d6e24f57

Some implementation details:

1. The sticky title can be edited in place.

2. When a section below Info is pinned, switching to a different item should still have the sticky title on top.

3. When the Info section is collapsed, we no longer get this sticky title, but instead show title preview in the Info section header as in #3647:
	
	![library-compact-item](https://github.com/zotero/zotero/assets/57771795/3442bfbd-4ebc-4d87-a4be-ab4483dc7d86)

4. For attachments, the same design applies, putting the title below the Attachment Info section header and above preview.

5. This isn't shown in the mock, but ideally we should give the title slightly different styling when it's scrolled to the top:
	- More `padding-block` for this div (not the text area). +2px in compact, +3px in comfortable
	- `fill/quinary` bottom border
	- Set `max-lines: 5` so super long titles don't take up too much vertical space

6. The Locate button is moved to the sidenav, below the Related section button and a divider, with no dropmarker. With plugins, the order in the sidenav will be: Sections (+ plugin sections) | (plugins that create separate views like note editor in reader) | Locate (+ plugin buttons, either regular buttons or menubuttons).

**Comment by dstillman** [comment]
Depends on https://github.com/zotero/zotero/pull/3624

**Comment by dstillman** [comment]
While we're at it, can we try a different, non-page-based Locate button? Just a rightward-facing arrow of some sort, or something else? Now that it's in the sidenav, there's no need for the extra context of the page shape.

**Comment by yexingsha** [comment]
I think a single arrow looks too much like collapsing the side pane:
<img width="351" alt="Screenshot 2024-02-05 at 15 53 26" src="https://github.com/zotero/zotero/assets/57771795/7b6d462c-b43e-4915-afca-b5c3a32aed71">

So what if we do something totally different?
<img width="351" alt="Screenshot 2024-02-05 at 16 05 32" src="https://github.com/zotero/zotero/assets/57771795/270eaf6b-8c8c-44a9-a926-5c4191c8bfdc">

**Comment by yexingsha** [comment]
Ouch, you are right. I think map pin might be too... physical? Like we are getting location somehow. But compass is a great idea!

<img width="351" alt="Screenshot 2024-02-05 at 16 40 15" src="https://github.com/zotero/zotero/assets/57771795/745aa427-e832-476f-854f-233524d52942"> <img width="351" alt="Screenshot 2024-02-05 at 16 40 44" src="https://github.com/zotero/zotero/assets/57771795/22efbf20-87b1-4609-869c-44e4b9e952c5">

**Comment by dstillman** [comment]
I think that's too close to the Safari icon used in iOS webviews to launch the viewed page in Safari. This would strongly imply to me that it was going to just open the item's URL in the browser.

![image](https://github.com/zotero/zotero/assets/783082/9f4068d2-f131-4d32-8bd9-e94c895e09c9)

**Comment by dstillman** [comment]
(And by "too close" I guess I mean "identical".)

**Comment by yexingsha** [comment]
Right, back to arrows then:

<img width="351" alt="Screenshot 2024-02-06 at 13 08 13" src="https://github.com/zotero/zotero/assets/57771795/b45a7c20-0e38-44dd-983f-82c2510c4888">  <img width="351" alt="Screenshot 2024-02-06 at 13 08 48" src="https://github.com/zotero/zotero/assets/57771795/9a5f806d-9e00-4c6f-8872-41f813b02128">

**Comment by dstillman** [comment]
Let's try the arrow in the circle?

**Comment by yexingsha** [comment]
svg file: 
![locate](https://github.com/zotero/zotero/assets/57771795/a60ce81c-d562-4f57-a4c2-21766e852c8a)

**Comment by yexingsha** [comment]
[locate.svg.zip](https://github.com/zotero/zotero/files/14215073/locate.svg.zip)

**Comment by dstillman** [comment]
Superseded by https://github.com/zotero/zotero/issues/3746 and some outcome of https://github.com/zotero/zotero/pull/3747
