### ISSUE TITLE
Undo Functionality and Erasor in PDF Reader

### ISSUE THREAD

**Issue by K-Nick** [zotero/zotero#3677]
Hello,

I'm reaching out to request the addition of undo functionality (via Ctrl+Z or Cmd+Z) in the Zotero 7 PDF reader for actions such as pen strokes, highlights, and notes. Currently, if an error is made while drawing, highlighting, or noting, the only recourse is to delete and redo, which is particularly cumbersome with pen inputs as it often requires erasing large areas.

This lack of an undo feature can disrupt the workflow and efficiency, especially when engaging with documents in a dynamic or detailed manner. Implementing an undo option would greatly enhance the usability and editing flexibility of the PDF reader. Also, I guess an erasor would be helpful paired with existing pen function.

Thank you for considering this enhancement to improve user experience.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
