### ISSUE TITLE
Alt key behavior to trigger menu access keys is wrong on Linux and Windows

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#3684]
When the Alt key is held depressed, the access keys should be displayed until the key is released. This has been the Alt key behavior for as long as I can remember on both Linux and Windows.

**Comment by windingwind** [comment]
I've been thinking of this recently and found that the current `press alt to toggle access key hidden` is the behavior on Windows (Notepad and VSCode). So our current implementation is fine at least on Windows.

For Linux I am not sure, but if we would like to do what @adomasven suggests, there issues we have are:

1. The `alt` keydown event of window is actually triggered when keyup, which make it not possible to implement `hold to show`;
2. The `alt` key event is not triggered when the menu opens. It's not bubbled to either the window or the popup.

Any idea?

**Comment by adomasven** [comment]
> I've been thinking of this recently and found that the current press alt to toggle access key hidden is the behavior on Windows (Notepad and VSCode). So our current implementation is fine at least on Windows.

Testing on Windows 10 here, I see that both Notepad and Visual Studio 2017 highlight the access keys when the Alt key is depressed. The focus is not moved to the menubar until the key is released, but you can still see the access keys just by holding Alt and you can press the access key while holding Alt to open the menu.

> * The `alt` keydown event of window is actually triggered when keyup, which make it not possible to implement `hold to show`;
> * The `alt` key event is not triggered when the menu opens. It's not bubbled to either the window or the popup.

Not sure what you're saying here. The Alt keydown does not bubble to the window, because something else in our code handles it and calls `event.stopBubbling()`. It's certainly not impossible to do this.

**Comment by windingwind** [comment]
> Testing on Windows 10 here, I see that both Notepad and Visual Studio 2017 highlight the access keys when the Alt key is depressed. The focus is not moved to the menubar until the key is released, but you can still see the access keys just by holding Alt and you can press the access key while holding Alt to open the menu.

On windows 11, Notepad show tooltip text instead of underline for accesskey after pressing alt once and hide after the second pressing;

VSCode show underline and focus the first menu on alt key down, then hide underline and defocus menu after the second pressing of alt.

Generally I was thinking of the VSCode way when making this access key behavior.

> Not sure what you're saying here. The Alt keydown does not bubble to the window, because something else in our code handles it and calls event.stopBubbling(). It's certainly not impossible to do this.

The `alt` keydown do bubbles to window, but the callback is only triggered at the same time as the keyup event. Do you know which code causes this?

**Comment by adomasven** [comment]
> The alt keydown do bubbles to window, but the callback is only triggered at the same time as the keyup event. Do you know which code causes this?

For the record, I can hold down Alt and press F in current Zotero to open the File menu in both Linux and Windows. So I imagine there may be some native menubar code in Firefox that captures the Alt keydown and handles it for the menubar, but the access keys are not shown. I wonder if there is some setting or css property that can be applied to the native widget to highlight the access keys?

**Comment by windingwind** [comment]
I guess not, since in firefox they never hide the access key. But if you mean to provide a setting to users to let them decide whether only to show the access key underline when pressing alt, we could do that.

**Comment by adomasven** [comment]
> I guess not, since in firefox they never hide the access key. But if you mean to provide a setting to users to let them decide whether only to show the access key underline when pressing alt, we could do that.

Ideally we would make it work like it works in other apps like Notepad and Visual Studio - highlight the key on hold. Do you think it's really not possible?

**Comment by adomasven** [comment]
Ok, I just booted up the Windows 11 VM and see that they changed the Alt menu behavior at least for Notepad, but maybe that's everywhere where the native menubar widget is used. I hate it, but I guess the current behavior mimics that, so maybe we can just close this issue, since each Linux DE is using different paradigms anyway and we won't be able to conform to all of them.

**Comment by windingwind** [comment]
Across OS version software on Windows is a disaster. Currently I have no idea how to implement the holding (actually, how to detect alt key down), otherwise I would be glad to provide the choice of holding v.s. pressing to users.

**Comment by adomasven** [comment]
I think let's just close it for now and revisit if there's any actual interest in this beyond me. I think that good design of human-computer interaction is worth something even if nobody specifically asks for it, but there's value in uniformity of UI across apps too.
