### ISSUE TITLE
Fix citation preview in Style Editor in dark mode

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3694]
https://forums.zotero.org/discussion/111713/latest-beta-bug-reports

**Comment by windingwind** [comment]
That belongs to a bigger problem of - the XUL elements style on Windows. I would be glad to take it

**Comment by dstillman** [comment]
Sure, but what's the relation? And what do you mean by "XUL elements style"? This is HTML content in an iframe, right?

**Comment by windingwind** [comment]
> In the style editor, when dark mode is active, the citation preview is still using the light settings, i.e., the text will be black on gray.

I did some investigation before and seems like on Windows the tabpanel doesn't have correct color scheme in dark mode, which makes its children HTML doesn't look right, so I suspect the XUL element style is the cause
