### ISSUE TITLE
First-run dialog for Z6 upgraders linking to Zotero 7 blog post?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3698]
https://forums.zotero.org/discussion/comment/454869/#Comment_454869

We'd have to decide exactly what this would look like.

**Comment by yexingsha** [comment]
<img width="1280" alt="bullet-only" src="https://github.com/zotero/zotero/assets/57771795/98498d6f-2403-4a1b-ae8e-aedf64226001">

**Comment by dstillman** [comment]
Rough plan:

- Only show for upgraders
- Maybe set <code>firstRunGuidanceShown.z7Banner</code> to true as a default pref, set it to false via prefs.js in a pref migration, and show on zoteroPane init after checking the pref?
- On "Remind Me Later", set a timer to show again in 24 hours (if window is still open). No need to store timestamp. If app is closed, we can just show again on restart.
