### ISSUE TITLE
Zotero doesn't work in google docs

### ISSUE THREAD

**Issue by Michaelsqj** [zotero/zotero#3709]
Hi there,

I installed the zotero on my mac, and it works fine with the word. But when I try to use zotero on google docs, although the zotero icon and menu shows, when I click on no matter add citation / refresh/ xx anything under zotero button on google docs, it only shows a drop down menu of inserting online links rather than invoking zotero. 

Does anyone know how to solve this? Changed between safari and chrome, none worked.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/455406/#Comment_455406

https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
