### ISSUE TITLE
Select multiple results in Quick Format via keyboard

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3763]
https://forums.zotero.org/discussion/112343/accessibility-cannot-multi-select-in-quick-format-citation-via-spacebar

I wanted Shift+Up/Down-Arrow for Selected Items, mostly, and we're planning to change that to just having a single result that adds all, but this thread suggests it could be useful for other results too, so no reason not to support it more generally.

**Comment by adomasven** [comment]
> And Cmd/Ctrl+Up/Down-Arrow and space bar as well, I guess

I don't know if we can reasonably support this. You can use arrow keys to navigate the reference list, and Enter to add an item at any point while typing to search, and spacebar is part of the typing characters. We could change the behavior of spacebar specifically once the user moves focus to the reference list, but I think it is bad to overload a single key for multiple behaviors.
