### ISSUE TITLE
Quick Format: Black rectangle in dark mode

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3768]
https://forums.zotero.org/discussion/112353/zotero-7-beta-64-glitch-in-the-citation-dialog

I can reproduce on macOS.

**Comment by abaevbog** [comment]
That is the consequence of the dialog not fully working with the dark mode - it's background is always white. But the inputs try to have dark background and white text which looks ... really off. Temporary hardcoded colors seem to solve it until the dialog works with dark mode better.
