### ISSUE TITLE
Attachment note not saved when losing focus

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#377]
Notes on attachments are not saved when losing focus. They appear to be only saved on a timer, which is cancelled when focus is lost. Thus, if you edit a note and switch to another view before the note is saved by this timer, the changes are lost.

Easiest way to see this is to add a note on attachment, give it a few seconds to let it save, then select part of the note. Now delete the selection (using Delete key) and immediately switch to another item. When you switch back, the deletion is not saved.

**Comment by dstillman** [comment]
No longer happens
