### ISSUE TITLE
Color Formatting Improvements in Microsoft Word

### ISSUE THREAD

**Issue by gwiethaus** [zotero/zotero#3777]
Sorry about my English.
I really like using Zotero, a free and easy-to-use tool. However, there are some implementations and improvements that need to be made to it. I've been waiting for this improvement for 8 years when I started using it. **What Zotero lacks and is a hindrance for anyone. When a new item is added to the bibliographic references, the font color formatting in the Microsoft Word document is lost throughout the document. This way, it returns the black color of the original source.** So I would like these new features to be implemented. I've seen a lot of people talking about this on forums.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
