### ISSUE TITLE
Error reporting illegible in dark mode

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#3795]
<img width="550" alt="Screenshot 2024-03-05 at 12 48 57 PM" src="https://github.com/zotero/zotero/assets/244886/346e2b79-13d5-4b53-9964-33c91d8cf8ee">

**Comment by windingwind** [comment]
I think it's fixed by https://github.com/zotero/zotero/commit/23da0d70b0743371f8a50cd7ed3c482dbb062102
