### ISSUE TITLE
Popup note window resizing.

### ISSUE THREAD

**Issue by 0nyr** [zotero/zotero#3797]
Feature request: I have not find any method to make popup notes bigger. For now, only the font size in the popup window can be increased.

This is already asked [here](https://forums.zotero.org/discussion/105316/allow-users-to-adjust-font-and-pop-up-window-size-for-comment-and-highlight-comment-feature).

+ [x] **READ THIS BEFORE CREATING AN ISSUE**

Zotero does not use GitHub Issues for bug reports or feature requests.

Please post all such requests to the Zotero Forums at https://forums.zotero.org, where Zotero developers and many others can help. For confirmed bugs or agreed-upon changes, Zotero developers will create new issues in the relevant repositories.

Development questions involving code, APIs, or other technical topics can be posted to the zotero-dev mailing list at http://groups.google.com/group/zotero-dev.

See https://www.zotero.org/support/zotero_support for more information on how Zotero support works.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
