### ISSUE TITLE
Selected/Open item is added via Enter when editing existing citation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3811]
https://forums.zotero.org/discussion/112627/unwanted-item-is-added-via-enter-when-editing-existing-citation

This is tricky. It might be the kind of thing where the best behavior is subtle and hard to explain but ends up generally doing what you want when you use it — like, say, if you open via edit mode instead of add mode and you open a bubble and then close it, the selection stays on the bubble instead of moving to the right of it, so you can just press Enter twice after typing the page number. I suspect people in edit mode are much more likely to be adding page numbers than additional items.

But that wouldn't solve all problems, so I think that, regardless of any other changes, we need to add an "accept" button — like the right-arrow in the Firefox address/search bars — on the right side of the text field when there's any input. So you could always click on that or right-arrow over to that and press Enter. Left-arrow onto a bubble + Enter also works, but that's much less obvious and isn't a real solution.

**Comment by adomasven** [comment]
The intended behavior is not displaying the reference list until anything (including a space) is typed, so this is just behaving wrong. On the other hand, we also have this https://github.com/zotero/zotero/issues/3671 - always leaving the reference list open, but not focused, which would produce the same results, but also allow to navigate into the reference list via arrow-key down.

Regardless, the citation dialog should have an accept button, but I don't think it should be navigable to via arrow keys.

**Comment by dstillman** [comment]
I don't think space bar makes sense as any sort of expected trigger — that's not something anyone would know to do.

But yes, I guess #3671 is the right fix here (along with an accept button). In an empty dialog, we focus the results so that Enter works, but once there's a bubble (whether in add or edit mode), we keep the results open if there are still any to show but don't focus it, and you have to use down-arrow first to focus it.

**Comment by abaevbog** [comment]
I was always a bit confused by space as a trigger to reopen the references panel, so keeping the panel opened makes sense a lot of sense to me. I can tweak some of my earlier changes in the references panel logic for it to remain opened.

As a recap of what we are after (correct me if I'm mistaken):
- empty dialog opens => reference panel is opened and the first item is selected, so Enter will add the first item as a bubble
- dialog has bubbles => the reference panel is opened as long as there are selected/open items to show but no item is selected, so Enter will accept the current dialog's state
- after some query was typed into the editor and the reference panel's results refreshed, should the first item be selected then? I think it's reasonable to expect that after you type something and see the first matching result you would want Enter to add it?



Besides the accept button, I am wondering if something like Shift-Enter would be useful here? In other components, like multiline `editable-text`, Enter is used to add a new line but Shift-Enter means essentially "submit". In a similar manner, would it make sense to have Shift-Enter always accept the current result in the dialog, regardless of what is focused?

**Comment by adomasven** [comment]
> after some query was typed into the editor and the reference panel's results refreshed, should the first item be selected then?

Yup.

> Besides the accept button, I am wondering if something like Shift-Enter would be useful here?

Good idea.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/113406/enter-adds-second-item-to-citation-dialog-when-editing-citation
https://forums.zotero.org/discussion/113475/z7-beta-word-citation-red-dialog
