### ISSUE TITLE
Note editor / sidebar width keeps increasing after every restart

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#3813]
As I was testing https://github.com/zotero/zotero/issues/3804, I kept restarting Zotero, and clicking on a note. After a few dozen restarts, this is what my Zotero looks like on start:

![image](https://github.com/zotero/zotero/assets/5899315/5820bb24-0485-451e-8d00-6f9312ce90ec)

After clicking on an item:

![image](https://github.com/zotero/zotero/assets/5899315/704c9af4-8d8d-434e-af1b-528c28d88f30)

After clicking in the note editor:

![image](https://github.com/zotero/zotero/assets/5899315/eea43508-0dca-45cf-8edd-813df8b77761)

**Comment by windingwind** [comment]
I think this is fixed
