### ISSUE TITLE
Revert native textboxes in item pane on Windows?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3826]
https://github.com/zotero/zotero/pull/3727 switched us to native Win11 textboxes with the blue underline. I know we do this in Z6, but I think it's just distracting. It's one thing to do it for something like the search bar to feel more like a native app, but in the item pane there can be dozens of these fields, and showing the blue line for each one just seems bizarre. These aren't normal text fields — they're our special toggleable component — so I don't think there's any reason to style them like regular fields.

The new fields are also causing a bunch of problems. https://github.com/zotero/zotero/issues/3821 fixed a problem with the height of the fields in the item pane, but I'm still seeing a different thickness of the line every other row:

![Screenshot 2024-03-10 at 12 58 49 AM](https://github.com/zotero/zotero/assets/783082/30731d6d-c5eb-41e6-a8c1-c2aba10dc36d)

![Screenshot 2024-03-10 at 12 58 55 AM](https://github.com/zotero/zotero/assets/783082/237caff0-280e-410c-a6b2-262409cbfd2b)

I'm also seeing the text shift to the right when toggling between viewing and editing (which didn't happen in Z6 or previous Z7 betas).

I'm not sure if this change was just a style thing or we actually swapped in a native component that has functional differences. If the latter, that might be more reason to keep it and just fix these bugs, but stylistically I think it's just worse.

**Comment by windingwind** [comment]
yeah, it's just a style thing. totally agree!

do we want the `editable-text` CE to keep the previous looking everywhere, or only inside the item pane? we may use them elsewhere i don't know, and plugins will use them.

**Comment by dstillman** [comment]
I think it's fine to revert for all instances of `editable-text`. By definition these just aren't really going to be regular text fields.
