### ISSUE TITLE
Attachment preview can cause 60+ seconds hang

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#3863]
I'm able to reproduce this quite reliably, although not every time, when selecting a particular EPUB attachment. Zotero stops responding for over 60 seconds. Below is an excerpt from log when this happens where for 66 seconds nothing happens and Zotero is not responding.

I was able to narrow it down to `attachment-preview`, after disabling code related to that component, the issue no longer manifests.

````
zotero(3)(+0000001): Viewing item

zotero(3)(+0000003): Refreshing item box

zotero(4)(+0000012): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1031, '']

zotero(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1031, '']

zotero(3)(+0000000): Setting mode to 'edit'

zotero(3)(+0000001): Reloading tags box

zotero(3)(+0000028): Getting contents of /Users/doppler/Zotero/styles/modern-language-association.csl

zotero(3)(+0000002): Getting contents of /Users/doppler/Zotero/styles/american-sociological-association.csl

zotero(3)(+0000002): Getting contents of /Users/doppler/Zotero/styles/chicago-note-bibliography.csl

zotero(3)(+0000006): itemTree.render(). Displaying Item Tree

zotero(3)(+0000001): Viewing item

zotero(3)(+0000000): Setting mode to 'edit'

zotero(3)(+0000000): Refreshing attachment box

zotero(3)(+0000005): Reloading tags box

zotero(4)(+0066410): SELECT COUNT(*) FROM settings WHERE setting='mImport' AND key='cleanup'

zotero(3)(+0000000): BlockingObserver: Removed observer

zotero(4)(+0000040): Registering notifier observer 'fulltext_SL' for [sync]

zotero(3)(+0000009): Cached 15 styles in 66772 ms

zotero(3)(+0000000): HTTP GET chrome://zotero/content/locale/csl/locales.json

zotero(3)(+0000003): HTTP GET chrome://zotero/content/locale/csl/locales.json succeeded with 200

zotero(3)(+0000000): HTTP GET resource://zotero/schema/renamed-styles.json

zotero(3)(+0000001): Cancelling

zotero(3)(+0000000): Getting contents of /Users/doppler/Library/Application Support/Zotero/Profiles/da4rlb4l.Default User/treePrefs.json

zotero(3)(+0000002): itemTree.render(). Displaying Item Tree
````

**Comment by windingwind** [comment]
Thanks for the debug. The attachment preview does nothing special but opens a reader with some CSS injected. I am not sure what's the cause, here are something to check that I think might be helpful:

1. does this happen only to this epub? how big is it?
2. does this happen even if the attachment file is already locally available?
3. if selecting the item and clicking `reindex item` in the right pane, does it hang Zotero?
4. does opening the attachment in the reader hang Zotero?

**Comment by tnajdek** [comment]
1. That's the only one I've noticed, yes
2. Yes, I only tested with everything synced locally
3. No
4. No

I've spent few hours trying to pinpoint the cause but so far no luck. It seems to happen when I click away from the epub onto another item. I also verified this happens on another machine.

**Comment by windingwind** [comment]
> It seems to happen when I click away from the epub onto another item

That sounds like the issue is with discarding the attachment preview.

Does it happen if you comment this line out?

https://github.com/zotero/zotero/blob/0419c33e3d57c0c2cb0e7e4cc90b256c67ce89f8/chrome/content/zotero/elements/attachmentPreview.js#L249

If you don't mind, I would be glad to try to reproduce on my end with your epub file and see what's happening there.

**Comment by tnajdek** [comment]
I have not seen this in a while. I've tried to reproduce it with the same file as before, but the issue did not reoccur.
