### ISSUE TITLE
fx115: autocomplete error message

### ISSUE THREAD

**Issue by abaevbog** [zotero/zotero#3883]
Selecting an entry from the autocomplete popup logs the following error:
```
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAutoCompleteInput.popup]
```
But it does not seem to affect the functionality of autocomplete in any way

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/pull/3882#issuecomment-2025969205

If it's that, we can just add a `return;` from fetch_xulrunner.sh.
