### ISSUE TITLE
fx115: all fluent strings are empty

### ISSUE THREAD

**Issue by abaevbog** [zotero/zotero#3894]
<img width="1126" alt="Screenshot 2024-03-28 at 2 10 56 PM" src="https://github.com/zotero/zotero/assets/36271954/8870caaf-9e71-4ee7-9c47-2d6c9f4a64ee">

I tracked it down to changes from this commit: https://github.com/zotero/zotero/commit/51c3c3b977ba8ca45ad2126cd20fc872c2d63f2c

**Comment by abaevbog** [comment]
Adding back [this line](https://github.com/abaevbog/zotero/commit/4a2c31607fb86ff7f2e61e2c6cf853fbd8d72e34) fixes this for me. Not sure if anything else is required here @adomasven

**Comment by adomasven** [comment]
Ah, I didn't realise I had caused this. I thought this was part of some breakage on Linux or Windows.

Closed with https://github.com/zotero/zotero/commit/e031e8c01fe1e263ec71c3d8121dd23e4f4a4648
