### ISSUE TITLE
Text transform on authors

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#39]
http://forums.zotero.org/discussion/835/change-case-automatically/#Item_7
http://forums.zotero.org/discussion/1991/names-variant-spellings-entities/#Item_3
http://forums.zotero.org/discussion/6418/list-of-feature-requests/#Item_6
http://forums.zotero.org/discussion/12638#Item_5
http://forums.zotero.org/discussion/15434/right-mouse-click-transform-text-enabled-for-author-fields/
http://forums.zotero.org/discussion/20842/
http://forums.zotero.org/discussion/21613/transform-text-for-author-field/

https://www.zotero.org/trac/ticket/1307

Maybe we should do this.

**Comment by AbeJellinek** [comment]
https://forums.zotero.org/discussion/98444/feature-request-title-case-for-author-name
