### ISSUE TITLE
fx115: Browser context menu shows AutoFill and Services submenus

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#3902]
1. Generate a report
2. Select some text and right-click

![image](https://github.com/zotero/zotero/assets/1770299/71efd25b-f29e-4c34-bf76-72978046dd4f)

Services could(?) be useful; AutoFill definitely is not. These show in the `basicViewer` (e.g. reports), the note editor, EPUB/snapshot reader, and anywhere else we embed a browser.

**Comment by dstillman** [comment]
We'll address in https://github.com/zotero/zotero/issues/3927
