### ISSUE TITLE
fx115: Word processor add-on installation window is tiny

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#3906]
![image](https://github.com/zotero/zotero/assets/1770299/cdcd6c48-5035-466c-8a27-52f7b4ccdceb)

**Comment by tnajdek** [comment]
It seems that in fx115 `width` and `height` attributes are no longer recognized on `window`, `wizard` etc. I've replaced these in few places already with `min-width`/`min-height` css declarations.

**Comment by dstillman** [comment]
Added to the dev docs
