### ISSUE TITLE
Unreliable Back/Forward behavior in PDF reader

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3913]
If I click an intra-PDF link, Back works for me the first time, and then it seems to get confused.

Let me know if you can't reproduce and I can try to give precise steps, but I'm seeing this pretty generally across multiple PDFs.

**Comment by mrtcode** [comment]
Yes, I think I can reproduce a weird behavior when moving back and forward multiple times.

**Comment by mrtcode** [comment]
@dstillman Can you still reproduce this issue? I recently did some little fixes, but I was unable to reproduce the original problem anymore.

**Comment by dstillman** [comment]
It's definitely better, but I'm seeing cases where I click on a link and the Back button isn't activated. But then I scroll up and click again and then it's active that time. Testing with https://doi.org/10.1016/j.scs.2023.105098

**Comment by dstillman** [comment]
Related: https://forums.zotero.org/discussion/115427/zotero-7-beta-broken-back-navigation-button-in-pdf-reader

**Comment by mrtcode** [comment]
It should work as expected now.
