### ISSUE TITLE
此引注的Zotero字段代码已损坏

### ISSUE THREAD

**Issue by wongtx** [zotero/zotero#3922]
此引注的Zotero字段代码已损坏一它负责向Zotero告知此引注对应文库中的哪个条目。重新选择对应条目吗？点击“否”将删除引注中对应条目的字段代码，保留引注文本，但您的参考文献表中可能移除该引注。
![image](https://github.com/zotero/zotero/assets/46996862/ad13d6bf-eef4-4c24-becb-714eb6c95346)
背景是zt7+better-bibtex+zotero integration（obsidian）+pandoc（obsidian）

**Comment by adomasven** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
