### ISSUE TITLE
MacOS "Services" entry appears in context menu after certain actions

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#3927]
This is quite bizarre, seems to be fx115 related (I wasn't able to reproduce it in pre-fx115 beta). Once added, it appears in all context menus.

https://github.com/zotero/zotero/assets/214628/4c27df42-fe70-465b-bcf4-75eaa213be4e

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/113573/z7-beta-title-field-right-click-options
