### ISSUE TITLE
Stop using `width`/`height` attributes when restoring `extensions.zotero.pane.persist` dimensions

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3939]
They no longer work in fx115, so, e.g., the tag selector height isn't restored.

**Comment by dstillman** [comment]
Reverted due to https://github.com/zotero/zotero/pull/3944#issuecomment-2046116709. We'll need to figure out what's going on here.

**Comment by windingwind** [comment]
So, has anyone figured out what breaks the layout after #3944?

It's probably some width/height value we persisted in previous versions that conflicts/overwrites the rules we introduced/modified in fx115. If anyone can reproduce, does clearing the persist prefs fix the layout issue?
