### ISSUE TITLE
Duplicate Icon in Reader

### ISSUE THREAD

**Issue by windingwind** [zotero/zotero#3941]
We should either disable (which i guess will make some users unhappy) the notes section, or use a different icon:

<img width="361" alt="image" src="https://github.com/zotero/zotero/assets/33902321/2f6f0aa4-2422-4a48-83c6-b6872fd64a39">

**Comment by dstillman** [comment]
No, the item notes section isn't supposed to be there. Child notes are available in the Notes pane. It was the same with horizontal tabs before.
