### ISSUE TITLE
fx115: Plugin update check fails

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3942]
https://forums.zotero.org/discussion/113514/z7-beta71-error-when-check-for-plugin-update

It calls `XPIDatabase.jsm::isBuiltinColorwayTheme()` on `resource://default-theme/`, which doesn't have an `id`.

**Comment by dstillman** [comment]
Seems like this theme is supposed to be `default-theme@mozilla.org`:

https://searchfox.org/mozilla-esr115/rev/a2f10990d517fe06936e7df4050e73bc36fdba8e/toolkit/mozapps/extensions/internal/XPIProvider.jsm#2554-2558

**Comment by windingwind** [comment]
The defaut theme addon has been a problem since fx102. Maybe adding another replace_line in XPIDatabase -> getAddonList() to filter out theme addons?
