### ISSUE TITLE
Restore creator-field-mode button

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3959]
https://forums.zotero.org/discussion/113471/z7-user-interface

A bunch of complaints like this, so I think we probably need to do this.

And then we should probably increase the pane min-width to 320px.

**Comment by abaevbog** [comment]
Right, the main question is what would this look like? We could just add another switch button to the right. My concern with this is that 4 buttons looks a bit busy and it feels odd that about a 4th of the visible row is taken up by buttons (this is with future min-width of about 320px). Also buttons appear on hover and shift the creator names, so if the first name is long and you hover over any part of it's right half, your mouse ends up over one of the 4 buttons. This is the behavior now but I feel like it is not as pronounced with only 3 buttons.

(Duplicated `-` button just to see what spacing would look like)
<img width="387" alt="Screenshot 2024-04-30 at 10 43 51 PM" src="https://github.com/zotero/zotero/assets/36271954/9c289501-2a3e-46d3-8312-28f926106e16">

Every row but the last one has a disabled `+` button. I wonder if there's a way to rearrange buttons a bit to use up that space for the new button?

It also could very much be that I'm overthinking it after all the time spent with `itemBox` and 4 buttons are not an issue at all.

**Comment by dstillman** [comment]
> Every row but the last one has a disabled `+` button. I wonder if there's a way to rearrange buttons a bit to use up that space for the new button?

Unfortunately that's a fairly common complaint, and, [as you noted](https://github.com/zotero/zotero/issues/3674), we should just make those all functional.

I did suggest that we could consider hiding the button at narrow pane widths, but I believe @yexingsha thought that was too weird. I do think it would be fine if the ⋯ menu were actually an overflow menu with a », but at least on macOS it's fairly non-standard to conditionally hide something within a ⋯ menu. I'm not sure if that icon is used that way more on other platforms. And, regardless, it's obviously a little weird to do it for a single icon, and I don't think we have any intention of adding additional icons for the other options in the menu even at much wider widths.

So I guess we could just ignore this for now, and see if there's more reaction after Z7 is out. (The other thing is that you can also right-click anywhere in the row and select "Switch to Single Field", so it's not like you actually have to click on the little button.)

**Comment by abaevbog** [comment]
Gotcha! So we'll try to add it just as a 4th button for now and maybe rework it later if needed.

There is another tweak to itemBox I started looking into based on one of vpat issues - itemBox has ztabindex logic that causes some issues, is fairly complex, and, I think, is no longer necessary. I summarized it in #4076. Since switching creator field mode does lead to some focus handling, is it better to do this first with existing ztabindex setup, or should I try to incorporate it into my work-in-progress branch where I try to remove explicit ztabindex focus handling?

**Comment by dstillman** [comment]
Sorry, I was suggesting that we just leave it as is for now — with the option only in the context menu — and see how it goes. I think we've only actually had a few complaints about it.

**Comment by abaevbog** [comment]
Oh, gotcha. Apologies. I thought the "ignore" bit referred to the issue of what 4 buttons would look like. 

We can wait up on it then, the good thing is once ztabindex logic is gone, adding the extra button will be way easier, since there will be no need to keep track of when/how it should get focused.

**Comment by quachpas** [comment]
Hello @dstillman,
> Sorry, I was suggesting that we just leave it as is for now — with the option only in the context menu — and see how it goes. I think we've only actually had a few complaints about it.

Is there anyway I could convince you to actually revert to previous behaviour and not wait until Z7 is released? As it stands, I think users are going to click the three-dots to access the "Switch to single field" command and not discover the context menu as they are used to the previous behaviour (as did I, I just discovered it was possible thanks to your comment).

> (The other thing is that you can also right-click anywhere in the row and select "Switch to Single Field", so it's not like you actually have to click on the little button.)

The beta has been working perfectly in my case, but one of the pain points is not having easy access to this command.

Thanks for all your work!
