### ISSUE TITLE
Update Attachment and Annotation preview sections whenever annotations are added/modified/deleted for the current attachment

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#3995]
https://forums.zotero.org/discussion/113632/zotero-7-beta-pdf-attachment-preview-and-annotations-not-refreshed-after-adding-annotations

**Comment by mrtcode** [comment]
@windingwind Now we can also render missing cached images using PDF worker to display them in the annotation preview section:

```js
await Zotero.PDFWorker.renderAttachmentAnnotations(attachmentItemID);
```

(You can test that by deleting `zotero_data_dir/cache` directory)

**Comment by windingwind** [comment]
Thanks! I've updated to #4031. Works well!
