### ISSUE TITLE
Citation Dialog: Clicking in the citation dialog outside of the <input> field creates another input.

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#4041]
1. Open the citation dialog
2. Type some text
3. Click with the mouse somewhere in the middle of the dialog (a non-text cursor appears)
4. Another input is inserted before the current one

![image](https://github.com/zotero/zotero/assets/5899315/ec4792dc-5aa5-410f-8514-c6efd601f455)

**Comment by abaevbog** [comment]
Yeah, I can reproduce. Thank you. Another thing I noticed while working on it is that the references list at the bottom is ... no longer scrollable? I see it on my mac and windows 11 vm. Must be one of the post-fx115 issues, so I'll look into that as well.

**Comment by abaevbog** [comment]
This should address it.

I also realized that after fx115, some of the workarounds related to drag-drop are not required anymore. Before fx115, any change to DOM while dragging was happening caused unexpected glitches (mainly related to subsequent drag-drop attempts failing). So there are some not-so-pretty workarounds that we could get rid of now. There are plans of larger changes for the QF, so do you think it make sense to look into it at this point or is it better to wait for next iteration of QF updates?

**Comment by adomasven** [comment]
> There are plans of larger changes for the QF, so do you think it make sense to look into it at this point or is it better to wait for next iteration of QF updates?

I think there's no point in refactoring the current QF any further, but I'll keep that in mind.
