### ISSUE TITLE
Excessive tree row spacing on Windows [was: Firefox 25.0 adds extra "tree row spacing" between items in the library view]

### ISSUE THREAD

**Issue by StianOby** [zotero/zotero#406]
After upgrading to Firefox 25, there is now unneccessary extra whitespace between all items in the library view (both in the collections pane and the items pane). 

My guess is that this issue is the same that has been reported and fixed for other extensions lately, including Newsfox: https://support.mozilla.org/en-US/questions/975790
(see also screenshots attached to the second post on that page, which very clearly illustrates the issue on Zotero/FF25).

From the Newsfox patch notes: "Firefox change: They changed the default tree row spacing in FF25 to something horrible (for NewsFox)! This changes it back."

**Comment by dstillman** [comment]
I don't think this is an issue anymore.
