### ISSUE TITLE
Can't enter zotero

### ISSUE THREAD

**Issue by longshixuan** [zotero/zotero#4061]
I don't do anything and suddenly can't enter Zotero when I open it. I need help!!!
![image](https://github.com/zotero/zotero/assets/62831586/7c124dc0-fa40-4162-b7d7-193fd8f1aef1)

**Comment by windingwind** [comment]
Zotero does not use GitHub Issues for bug reports, feature requests, or support questions. Please post all such requests to the [Zotero Forums](https://forums.zotero.org/), where Zotero developers and many others can help. See [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more information.

https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
