### ISSUE TITLE
Ink annotation merging

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4063]
https://forums.zotero.org/discussion/comment/460995/#Comment_460995

Via context menu after selecting multiple ink annotations on the same page

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/115668/zotero-7-ink-drawing-annotation-request

**Comment by mrtcode** [comment]
https://forums.zotero.org/discussion/116716/ink-annotation-tool-optimization
