### ISSUE TITLE
Remove ztabindex logic  from itemBox?

### ISSUE THREAD

**Issue by abaevbog** [zotero/zotero#4076]
Based on VPAT review, focus is not properly landing on some components during tabbing (e.g. merge button in the duplicates panel) or exiting the `itemBox`. The main culprit there is the `ztabindex` logic and I think instead of trying to force all components to have their `ztabindex` attribute, we should remove it to not have to explicitly state when which element should be focused and let mozilla handle it. The main reason for `ztanindex`, as I understand, was no longer used pre-`editable-text` component that would insert and delete inner `<input>` on focus/blur which confused default mozilla tabbing.

Besides being just unnecessarily complex, @windingwind also pointed out that `ztabindex` logic might cause issues if plugins insert rows into the `itemBox`. It can lead to tabbing navigation being essentially broken if `ztabindex` is not set exactly right.

Finally, there were [reports](https://forums.zotero.org/discussion/113227/zotero-7-beta-cant-tab-past-authors-last-name#latest)  related to issues with tab navigation that I could not reproduce but I think it might be related to `ztabindex` as well.

**Comment by dstillman** [comment]
Yeah, I suspect we can get rid of that now.
