### ISSUE TITLE
"DOI » View Online" opens infinite browser tabs

### ISSUE THREAD

**Issue by tajmone** [zotero/zotero#4095]
Zotero Desktop edition v6.0.36 for Windows.

When I right-clik on the **DOI** entry of a bibliographic entry, and select them menu "View Online", it ends up opening infinite tabs on my browser (Chrome), forcing me to shut down the browser before it eats-up all PC resources.

The page(s) that it opens at the DOI server is correct, except that it keeps opening it infinitely.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
