### ISSUE TITLE
 The window cannot be resized!!!

### ISSUE THREAD

**Issue by yangzhangstl** [zotero/zotero#4107]
**Issue**: The window cannot be resized
Hardware Report:  macos Monterey Version: 12.5.1 Macbook Apple M1 Pro 16 GB
Zotero Version: 7.0.0-beta.77+adaa61f2c
<img width="1512" alt="截屏2024-05-10 11 29 15" src="https://github.com/zotero/zotero/assets/88226594/6700262c-f806-4f19-8826-1d252558906f">

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md

**Comment by yangzhangstl** [comment]
After updating to the latest version, I'm unable to resize the window. It can only be maximized. Please resolve this issue as soon as possible. Thank you very much!
