### ISSUE TITLE
Rename `PaneHeader` to `ItemPaneHeader`?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4114]
Any reason this shouldn't be `ItemPaneHeader`, like `ItemPaneSection(ElementBase)` and `ItemPaneSidenav`?

**Comment by windingwind** [comment]
Makes sense. Renamed in #4031

**Comment by windingwind** [comment]
Mentioning this, maybe we should consider renaming some other CEs, e.g. `ItemBox` to `InfoBox`/`ItemInfoBox`. The meaning of `ItemBox` is quite vague.

**Comment by dstillman** [comment]
Yeah, that's just historical from `itembox.xml`, but I was thinking the same. `InfoBox` is probably clear enough?

**Comment by windingwind** [comment]
InfoBox is clear to me. We can wait for #4096 to be merged and then rename the ItemBox in a new PR.
