### ISSUE TITLE
fx115: Fix styling in Document Preferences and Bibliography dialog

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4126]
Things got messed up in fx115, with huge headers and extra space, and some styles can be way too large now:

<img width="646" src="https://github.com/zotero/zotero/assets/783082/d46f810e-b2fa-4cf1-83e2-a0037a6c6805"/>

This causes some very weird behavior on small screens:

https://forums.zotero.org/discussion/comment/462121/#Comment_462121
https://forums.zotero.org/discussion/comment/462638/#Comment_462638

**Comment by adomasven** [comment]
https://github.com/zotero/zotero/commit/d236058351af3792927581a6f5dbce0627999cbb

This is what caused this change, not upgrade to fx115. We can just remove that line.

**Comment by dstillman** [comment]
It's not. That line just switched it to actually use our SCSS rules, which we definitely want — various things, like the table padding and UI font size, are wrong without them, and the headers and spacing are still wrong:

<img src="https://github.com/zotero/zotero/assets/783082/a37eded3-7828-428b-adae-61116a082f14" width="646"/>

We need to actually fix this for real.

**Comment by dstillman** [comment]
We could probably move the "Footnotes" / "Endnotes" radiogroup inline with "Display Citations As" (like "Language:") to save space for note styles.

**Comment by dstillman** [comment]
This is separate from fixing the basic style issues, but do we think all of this text is still necessary? Is there anything (about file formats or whatever) that's obsolete and/or that can be removed/hidden? Should Bookmarks even show up this prominently, or can we hide that in some advanced settings pane (if we even still need to support it)?

**Comment by dstillman** [comment]
Like if Fields is "recommended", we should just default to that, and you should be able to click on "Advanced…" or something to switch to another format.

**Comment by adomasven** [comment]
This applies to `bibliography.xhtml` used in the Create Bibliography from Items and `setDocPrefs.xhtml` used in Document Preferences from word processor plugins.

**Comment by adomasven** [comment]
> Is there anything (about file formats or whatever) that's obsolete and/or that can be removed/hidden? Should Bookmarks even show up this prominently, or can we hide that in some advanced settings pane (if we even still need to support it)?

We support bookmarks, but I agree that it makes sense as a checkbox under an Advanced collapsible section. As would Medline abbreviations, and Automatic Citation updates. Although if any of the advanced options are enabled then the Advanced section should appear expanded.

The default dialog should just have styles, language and Footnotes/Endnotes when applicable.

**Comment by adomasven** [comment]
We could improve this dialog by displaying a preview of the citation and bibliography entry, but that could be a separate issue.

**Comment by yexingsha** [comment]
Removed headings, moved options into a collapsible advanced section, and also added a preview of citation and bibliography:

<img width="800" alt="document-preferences" src="https://github.com/zotero/zotero/assets/57771795/8910c06c-b2ab-44cb-b66d-e6820c31da8b">
<img width="800" alt="document-preferences-advanced" src="https://github.com/zotero/zotero/assets/57771795/04955a8e-4bdd-4699-ae52-db869b87fb96">

The preview height is very limited so that all options except those under "advanced" can be seen at first glance.

**Comment by adomasven** [comment]
The citation style preview should be more clearly separated from the list of item styles. We also have limited height for this dialog, but don't want it to be scrollable, so the dialog should fit in something like 800px height-wise with the advanced options expanded. Which means that for the style preview we might want to do something more creative, like maybe a preview on hover over some popover or similar.

**Comment by dstillman** [comment]
I agree on what we'd need for the preview — separated, certainly, but probably something that doesn't take up permanent space — but I actually don't think we particularly need or even want a preview here. This is one of various places in Zotero you can select a citation style from among those that are installed, and I think at the point where you're making that choice, you probably know what you style you want and don't need a preview to decide (since there's no particularly reason to think the style you'd choose based on a preview is even installed). We also don't have any obvious data to use for these previews.

We have an existing style preview tool that generates previews from actual items you've selected, and we could improve or incorporate that better into the Style Manager in the Cite prefs. I think that's fine as a solution. The styles page also has previews, and there's a search-by-example tool on the CSL site. All of those seem like better places for previews.

So I'd just drop the preview here.

For the rest, yeah, this definitely can't scroll. A disclosure section is the easiest way to do the advanced options, but I'm not sure if it works given the height constraints — I guess expanding that could shrink the style list, but I think that'd be fairly non-standard for a dialog. Another option would be to just make it a modal dialog triggered by a button. That makes it hard to show any options that are selected, but maybe there could be some indicator or text next to the button conveying that some advanced options were enabled.

I also worry a bit about hiding "Automatically update citations" by default, just since it is pretty important in large documents (though we do try to turn it on by default if operations start to get slow). Also, for some styles, "Automatically update citations" would actually be the only item in Advanced, which is sort of dumb. One advantage of moving it out would be that, for some note styles, we could then not show an Advanced disclosure/button at all, whereas, since "Automatically update citations" is always an option, we'd otherwise always have to have an Advanced disclosure/button.

**Comment by yexingsha** [comment]
Not that it can't be done, but I'm curious why we must disallow scroll for this window. If it's about the discoverability of advanced options, I think with proper cutoff it won't be an issue:

<img width="800" alt="document-preferences-advanced" src="https://github.com/zotero/zotero/assets/57771795/17f16121-a14d-41aa-adb3-6a2304794b8c">

If we don't allow scroll, then we should also set a minimum size for this window, which we don't seem to have at the moment. With all options visible (please let me know if there can be more), this window is at 670px. But it could be taller if people set their font size larger.

<img width="800" alt="document-preferences" src="https://github.com/zotero/zotero/assets/57771795/20f44489-4f21-4a09-b0a1-fef90f01ae25">

Also, I moved "Switch to a Different Word Processor" out of Advanced as well, since it seems like it's an option for every style, so it would be the only item left in Advanced for some.

**Comment by dstillman** [comment]
Ah, sorry, missed "Switch to a Different Word Processor". Yes, definitely want that out too.

It can't scroll because dialogs like this just don't really scroll, at least in native apps. Some two-column settings windows scroll (because there are essentially two subviews), EULA dialogs scroll (because the long text is a subview), but dialogs like this with a single set of elements and buttons at the bottom just don't really do that.

The last mockup looks good. No other settings that I can think of. We could probably set a max-height on the style list and set the max-height of the window to the viewport height so that if you have a small screen and large font size you'd just have a short style list?
