### ISSUE TITLE
Unable to update file

### ISSUE THREAD

**Issue by UchihaItachi777** [zotero/zotero#4128]
![微信图片_20240516080613](https://github.com/zotero/zotero/assets/125756537/b13b4676-7ac9-4b80-882a-908c57206320)

Unable to update file D:\Zotero\cache\storage\lBCVQEQFN\2024.pdf".
Make sure that the file is not occupied, has write permissions, and has a valid file name.
Restarting your computer or disabling your security software may also resolve the issue.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
