### ISSUE TITLE
Item box: Title field tab order is wrong

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4134]
https://forums.zotero.org/discussion/114435/zotero-beta-tab-order-and-behavior-in-right-hand-panel

**Comment by abaevbog** [comment]
Another report of this for the record: https://forums.zotero.org/discussion/114519/zotero-7-beta-title-field-2nd-one-is-pushing-against-creator-field-and-tabbing-skips-creator

But all of these should be take care by #4096
