### ISSUE TITLE
Reconsider textbox-style focus effect for read-only fields

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4138]
In the conflict-resolution window, the textbox-style focus effect we use for read-only fields is kind of confusing:

https://github.com/zotero/zotero/pull/4130#issuecomment-2117465957

I don't think it's a problem for Date Added/Modified, so I was going to say that we should just override it in the CR window, but it occurs to me that in a read-only library/view you'd have the same problem for all fields, where it's not really clear that something isn't editable until you try to type (or if you happen to notice that there's no caret).

Maybe we should just get rid of the white background in read-only fields?

**Comment by yexingsha** [comment]
I think we can get rid of both the white background and blue focus outline for read-only fields. The abstract field in read-only libraries already does this.

**Comment by dstillman** [comment]
Sounds good.
