### ISSUE TITLE
Improve feed item pane header

### ISSUE THREAD

**Issue by yexingsha** [zotero/zotero#4141]
The most pressing issue is at smaller pane widths, the long header buttons cause the entire pane to overflow:

<img width="342" alt="Screenshot 2024-05-20 at 23 22 52" src="https://github.com/zotero/zotero/assets/57771795/47087c8d-ae7c-4e5d-bfb9-f2c0b9baa58e">

I think we should enable truncation for the "Add to My Library" button, because it might be even wider in other locales, and the button should still be intelligible with only icon and "Add to My...". There are other things we should improve as well (mocks in Figma):

1. There is currently almost no spacing between the title area and the buttons. Should be 4px in tight, and 8px in comfortable 
2. Decrease the margins around and between the buttons to 8px
3. Improve the paddings of the two buttons. They are meant to look like system native buttons, but right now they look slightly off on both mac and windows. The padding before the icon in "Add to My Library" is especially large
4. Are the quotation marks around "My Library" necessary? I think we can remove those
5. We should use `accent-blue` for the library icon
6. The color of the divider and the chevron are both wrong in dark mode

**Comment by windingwind** [comment]
> Are the quotation marks around "My Library" necessary? I think we can remove those

Maybe necessary? It can be weird without the quotation, e.g. `Add to Add to`, if the collection name is "Add to".

**Comment by dstillman** [comment]
Yeah, annoying in the case of My Library, but they're there because the collection/group name can be anything.
