### ISSUE TITLE
Improve merge pane

### ISSUE THREAD

**Issue by yexingsha** [zotero/zotero#4142]
1. Both 'groupbox' and 'zotero-duplicates-merge-item-box-container' have 8px inline padding. One of those is unnecessary.

2. Right now when the item pane is collapsed, users have to drag on the edge of the sidenav or go into the View menu to open it back up. I think when people go into Duplicate Items and select items, they almost always want to do merge actions, so it makes sense here to automatically open the item pane if it was previously collapsed.

3. When #4141 causes the feed item pane to overflow, the overflow state can persist into merge panes, but not regular item panes, so there might be something going on.

**Comment by windingwind** [comment]
Thanks!

> Right now when the item pane is collapsed, users have to drag on the edge of the sidenav or go into the View menu to open it back up. I think when people go into Duplicate Items and select items, they almost always want to do merge actions, so it makes sense here to automatically open the item pane if it was previously collapsed.

Maybe we should also consider auto-open item pane in trash?

> the overflow state can persist into merge panes

That's because the two panes share the same element. No worry

**Comment by yexingsha** [comment]
> Maybe we should also consider auto-open item pane in trash?

I feel like that's unnecessary, because:

- Unlike merge actions which are can only be done in item pane, Restore to Library and Delete Permanently both exist in context menu. In fact context menu might even be the preferred action here, especially for multiple items, which makes accessing those buttons via the item pane less important.

- Sidenav is enabled in trash, so if users do want to reopen the item pane, they only need one click, which is less troublesome than dragging the resizer or navigating the View menu.

Combining these two factors, I think we should preserving the collapsed state of the item pane in trash.

**Comment by yexingsha** [comment]
Looks good, just need to fix the merge button menu so that it doesn't hug the screen edge.

Current menu placement:

<img width="353" alt="Screenshot 2024-06-03 at 23 26 19" src="https://github.com/zotero/zotero/assets/57771795/15a2eace-b560-4608-b69b-7f988f96490a">

Compared to regular item info context menu:

<img width="347" alt="Screenshot 2024-06-03 at 23 39 38" src="https://github.com/zotero/zotero/assets/57771795/dd2d50a4-ae16-4c68-b739-68d75d2a58ff">
