### ISSUE TITLE
Improve attachment preview

### ISSUE THREAD

**Issue by yexingsha** [zotero/zotero#4147]
I think some of these issues have been discussed before, but I don't see an open issue or PR, so I'm compiling them here (feel free to close this if it's redundant):

https://github.com/zotero/zotero/assets/57771795/2cfb789c-9d90-4815-b988-788ee9fecf19

1. The PDF preview area has an unnecessary background color in dark mode

2. PDF previews always jump to reposition at first render

3. After the jump, PDFs are still not scaled & positioned perfectly within the preview area. This is more of an issue when the pane width is narrow, which cuts off the preview

4. Some PDFs get "scrolled" at first render, but can be fixed by going to next page then back

5. Some EPUBs are rendered with a large margin that do not appear in reader

6. The arrow buttons should use `color-background` and `fill-secondary` that changes when content is using dark mode, since right now they are not visible enough when overlaid on text

**Comment by windingwind** [comment]
For 2, 3, 4, and 5, we may need some comments from @mrtcode . 

Some details that might be helpful to the positioning issue: we are currently overriding the `_getState` to initialize the position and scale of the viewer, is there anything else we can do?
https://github.com/zotero/zotero/blob/88221d5fc74e7585351be91d75980db8ecc430c7/chrome/content/zotero/xpcom/reader.js#L1431-L1446

**Comment by mrtcode** [comment]
> For 2, 3, 4, and 5, we may need some comments from @mrtcode .

That’s right, I need to fix that. Also, the Zotero reader (PDF view) is currently doing many things it shouldn’t in preview mode. I need to pass a flag to the reader when it’s running in preview mode and disable various features.

**Comment by windingwind** [comment]
Thanks! Good to know the preview reader can be more efficient. Let me know in case of any discussion/help needed.

**Comment by dvictori** [comment]
I'm using Zotero 1.0.11 in Ubuntu (24.04) and dark mode. I just noticed that when I view the preview of an attached pdf, the colors are inverted. Not sure this closed issue dealt with this, so I'm adding it here as a comment.

This is what I'm seeing  

![Image](https://github.com/user-attachments/assets/1f6736ac-59c0-4294-b215-251fae0536a4)

This is how this is supposed to look like

![Image](https://github.com/user-attachments/assets/528e0c40-a6a1-414d-9577-c5f83ff9806f)

**Comment by windingwind** [comment]
@dvictori A brief answer: you enabled the `use dark mode for reader content` feature.

Also please read the README before posting/replying here. This should be posted to https://forums.zotero.org/discussions

**Comment by dvictori** [comment]
Thanks, I was not aware of this feature. I'll use the discussions next time. In my defense, the `use dark mode for reader content` option only only appears in the View menu when we open the attachment. I can´t set that option when looking at the attachment preview, which threw me off.
