### ISSUE TITLE
Exec line in .desktop file no longer valid in Ubuntu 24.04

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4163]
https://forums.zotero.org/discussion/114585/zotero-stopped-opening-from-launcher-application-pane

```
Failed to launch "Zotero"
Desktop file didn't specify Exec field
```

Current line:

https://github.com/zotero/zotero/blob/a6076ce76c2401b4313d2905afac74836834681c/app/linux/zotero.desktop#L3

We'll also need to put out another Z6 build with this fixed.

**Comment by dstillman** [comment]
@lbhm: Did you actually run into a problem with the desktop file before the additional backslashes, or did you just run it through `desktop-file-validate` and see the warnings? The file isn't working for some people on Fedora 40 after this, so we're going to revert this for now.

**Comment by dstillman** [comment]
Reverted the additional backslashes from https://github.com/zotero/zotero/commit/06741ceb623db8de3ae9972bcae73ee4e0049dcb for now

**Comment by imzoc** [comment]
Heya,

Just upgraded to Ubuntu 24.04, and Zotero no longer launches.

I added backslashes before the `$` symbols as in `06741ce`, and tried the backslashes in commit `94f061b` (the first one). My system still thinks the exec field is not specified. `desktop-file-validate` runs clean.

Until a solution is found, how can I launch Zotero from CLI?

**Comment by FlyingPumba** [comment]
Same here, Zotero won't launch after upgrading to Ubuntu 24.04. Running it from CLI seems to work just fine.
