### ISSUE TITLE
[Mac] Can't reopen main window after closing if reader windows are open

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4171]
https://forums.zotero.org/discussion/114657/reopening-library-window-on-mac

There should be a Window menu option for this. E.g., in Thunderbird, `Mail & Newsgroups [Cmd-1]` shows up in standalone message windows.

**Comment by thekswenson** [comment]
Thanks for the really impressive and seriously useful software!

I would just like to add that this makes zotero very difficult for me to use, I am currently doing a huge literature review and I have many papers open with the zotero PDF viewer, organized across 9 desktops. When I accidentally close the main window I have to close all of these viewers, and then open zotero again, and then sort all the papers onto desktops once again.

**Comment by thekswenson** [comment]
Thanks folks!
