### ISSUE TITLE
`should tab across the zotero pane` test fails when run on its own

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4180]
```
$ ./test/runtests.sh -g "should tab across the zotero pane"

[…]

  ZoteroPane
    #focus()
    ❌️ [FAIL] should tab across the zotero pane
      expected 'zotero-tb-sync' to equal 'zotero-tb-tabs-menu' at
@resource://zotero-unit-tests/zoteroPaneTest.js:1583:18
```

(I noticed this because of the failure in https://github.com/zotero/zotero/actions/runs/9298506593/job/25590537739, though I'm not sure what that was about.)

**Comment by abaevbog** [comment]
Ah yes, it's because the tabs menu is disabled and skipped during tabbing when only the library tab is opened. This messes up the expected order from tests. We should just make sure that if there is only 1 tab opened (as if the test is ran on its own), we open up a test.pdf tab.
