### ISSUE TITLE
Graphical option to fast transition dark/light modes in Zotero 7

### ISSUE THREAD

**Issue by jamarav** [zotero/zotero#4209]
First of all my congratulations to the developers. 

I have recently downloaded the new version of Zotero 7 Beta and I am delighted with the new look and speed, plus the additional support for ebooks. I am still evaluating the changes but I have noticed the following regarding dark mode. Currently, you can select in settings to transition between dark and light mode. Generally, the theme is great and looks very elegant. However, I am missing two things:
- To enable dark mode as the main theme but keep the light mode when reading documents. This can be useful when consulting documentation with a lot of images or graphics.
- Two graphical buttons would be useful to quickly transition between dark/light mode, both at global theme and document levels.

This is something already implemented by the Zotero-night plugin. However, I believe it would be beneficial to include it natively. I can think of two cases where at least for me it is necessary this feature:

- When I consult feeds I usually switch to clear mode. It is much easier to visualize new communications.
- Depending on the type of document it may be required to display it in dark or light mode depending on its content.

I hope you find my comments useful. 

Thanks in advance.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
