### ISSUE TITLE
Use default attachment titles for child attachments

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4211]
Currently, if you drag a PDF onto an existing item, the filename gets set based on the parent item metadata (if it's the first attachment file) and the attachment title gets set to that filename. The same thing happens if you drag in a PDF and it's recognized.

These are inconsistent with what we do (out of necessity, since there's often no filename, or it's gibberish) when saving from the web, where the attachment title gets set by the translator to something like "ScienceDirect Full Text [sic] PDF" (which will be [localized](https://github.com/zotero/zotero/issues/3078) in the future). It also means that, if the file is again renamed via parent metadata (which will happen [automatically](https://github.com/zotero/zotero/pull/3860) soon), we change the attachment title, whereas Zotero 7 [no longer changes the title if it doesn't match the filename](https://forums.zotero.org/discussion/comment/439553/#Comment_439553).

This has confused many, many beta users.

For consistency, clarity, and cleanliness, we should set the title to just "PDF" when adding a first PDF to an existing item or when we successfully retrieve metadata and create a parent item. Same for "EPUB". "Image" for known image types? Not sure about other file types, like Word documents, since even if those are the "primary" attachment they're less likely to be a representation of the parent item, and the filename might be the best description of what they are.

What happens if you create a parent item either by identifier or manually? By identifier seems like it should work the same as retrieving metadata. For manual entry, the parent item is already set to the same title as the attachment title and filename, so probably reasonable to change the attachment title to "PDF" then too.

It will also be possible to [change the primary attachment for an item](https://github.com/zotero/zotero/pull/3333). Does that change anything?

Secondary files I guess need to keep their filenames as titles? But then if you rename based on parent metadata, the title would change. Maybe we should just never change the title to match the filename? If we're taking care of the common cases here, then for other situations like secondary files, maybe you just set the attachment title manually?

A lot to think about!

(Possible this will need to be done on top of https://github.com/zotero/zotero/pull/3860 to avoid conflicts.)

**Comment by dstillman** [comment]
(We can also do some of the low-hanging fruit here before resolving all these questions.)

**Comment by dstillman** [comment]
> Do you mean that we'd just remove the current attachment box behavior where we keep the title up to date with the filename when you rename the file? Or are there other cases in which this happens?

It's not attachment-box behavior (unless I'm misunderstanding) — the title and filename fields are totally separate in Z7. I'm talking about the behavior of Rename File from Parent Metadata (or the upcoming continuous renaming) when the title matches the filename. We still change the title along with the filename in that case in Z7. I'm saying we could just have automatic file renaming never change the title. So in the situations where you add a local file and we don't use "PDF"/etc. (e.g., secondary files), the title would initially match the filename (or maybe the filename without the extension?), so you'd still have whatever context that provided, but any further title changes would be on you.

**Comment by dstillman** [comment]
A few more easy changes:

1. When dragging in a file and not setting it to "PDF"/etc., set the attachment title to the filename minus the extension rather than keeping the extension.
2. Never change the attachment title when renaming the file by parent metadata. 1 will mostly take care of this, since the title will no longer match the filename, but we can just take out the code in `ZoteroPane.renameSelected[something]` that does this when they match.
3. Rename the file automatically when retrieving metadata on an existing attachment. Currently we do that when dragging a file in but not when running on an existing attachment. (This mostly doesn't come up because if a file could be recognized it likely would've been when it was first added, but I noticed this inconsistency while testing.)

**Comment by dstillman** [comment]
Leaving open, since I think we haven't addressed at least Create Parent Item → Manual Entry, but removing from the Z7 milestone.

**Comment by dstillman** [comment]
> We do! Unless I'm misunderstanding what you're referring to.

Hmm, not sure what I was seeing, but looks OK now.

**Comment by Macmillanzhong** [comment]
> Secondary files I guess need to keep their filenames as titles? But then if you rename based on parent metadata, the title would change. Maybe we should just never change the title to match the filename? If we're taking care of the common cases here, then for other situations like secondary files, maybe you just set the attachment title manually?

I would support to set the attachment title manually for the secondary file. In my personal case, I would set the attachment titles of the secondary files as "SI" or "Data" or "Peer Review" - as you can see there might be multiple "secondary attachments" for one literature. Renaming is needed to distinguish them. And I would not prefer to set the file name (not attachment title) of these attachment as "SI" or "Data", because in that case there will be loads of "SI"s in the file explorer which are not recognizable. 

In current Zotero7, it seems the users are not allowed to change the attachment title at all. So could you please consider at least adding an option to rename the attachment title for secondary files.

**Comment by dstillman** [comment]
@Macmillanzhong: You can change the attachment title from the item pane.

If you have further questions or feedback, please post to the Zotero Forums.
