### ISSUE TITLE
Can't close annotation "Add tags…" popup with Esc

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4226]
1. Open sidebar
2. Click "Add tags…" in annotation widget
3. Press Esc once, which closes the input field but leaves the popup open
4. Press Esc again, which deselects the annotation widget while leaving the popup open

I'm not sure if we should close the popup on the first Esc, but certainly the second one should close it. And, actually, it's a problem even when not editing: if an annotation has tags and you click on them to open the popup to view them without an active input field, Esc doesn't close the popup.

**Comment by dstillman** [comment]
In other words, it doesn't close it from this mode, which is where you end up with both scenarios above:

![Screenshot 2024-06-10 at 11 16 29 PM](https://github.com/zotero/zotero/assets/783082/80326776-de5a-48ba-b844-259022bf79d0)

**Comment by abaevbog** [comment]
This was brought up by the vpat folks, so I had the tags popup behavior as a part of #4222. I have a few tweaks to address this among other things related to the tags popup in #4231
