### ISSUE TITLE
Poor outline extraction results

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#4229]
https://forums.zotero.org/discussion/114981/z7-beta-random-sentences-in-the-outline-view

Disable this feature if it can’t be improved before the release.

**Comment by plhijk** [comment]
Glad to see this feature in the beta. Could you point me to the implementation code? 
I'm making a tool for extracting pdf outline (still working on the algorithm). Zotero plugin was part of the plan.

**Comment by mrtcode** [comment]
@plhijk This is just an early alpha [version](https://github.com/zotero/pdf.js/blob/f51dff302ae5cd65d4d1c702beab279ed9bd66b6/src/core/module/outline-extractor.js). The main idea is to group text blocks by their font properties (name, size, all uppercase) and then determine hierarchal level.

**Comment by mrtcode** [comment]
Since false positives are now much rarer, this shouldn’t be a problem anymore.
