### ISSUE TITLE
Items in subcollections in trash show up when using Show Items in Subcollections

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4271]
https://forums.zotero.org/discussion/115411/zotero-7-beta-deleting-a-sub-collection-leaves-ghost-items

**Comment by abaevbog** [comment]
I can't seem to reproduce this anymore. I think it may have been fixed in a612c1227efd3adbfec86a854e97ce751f24c1f8. This does happen before and does not happen after that commit.


https://github.com/zotero/zotero/assets/36271954/07818f7c-28d6-42db-82aa-ad345aee9de8

**Comment by dstillman** [comment]
Yes, looks to be fixed. I've added a test.
