### ISSUE TITLE
Preferences: Filename Template field overflows unless window is very wide

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4291]
![image](https://github.com/zotero/zotero/assets/1770299/99b8844b-460f-4c7e-8e25-8ef5c3bf62b6)

It always grows to be slightly wider than its container until the window is very wide:

![image](https://github.com/zotero/zotero/assets/1770299/e708dc07-b9b9-4fa8-badd-6a382da7bf4a)

(Separately, there's extra padding around the documentation link there. That's probably some global style we apply to `<label>s` in preference panes, which we should maybe consider removing.)

**Comment by tnajdek** [comment]
I'm pretty sure this worked correctly before, I'll have a look!
