### ISSUE TITLE
Import Wizard might navigate to the incorrect page if the database is busy

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#4300]
As reported [here](https://forums.zotero.org/discussion/comment/466337/#Comment_466337), my guess is that this is caused by the fact that there are two database queries run as async function calls before the `pageadvanced` handler is installed. If the button is pressed before the handler is installed, the wizard reverts to its default behavior, and the next page displayed is the 'Mendeley Intro' page.

**Comment by dstillman** [comment]
Ah, good call. Yeah, it's trivial to reproduce with `await Zotero.Promise.delay(10000);` above the handler.

But I guess we actually want to disable the Continue button until those queries are done, since they're necessary for an accurate options pane.
