### ISSUE TITLE
Add space in tab bar for dragging window on macOS

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4313]
https://forums.zotero.org/discussion/comment/465165/#Comment_465165

Us:

![Screenshot 2024-07-02 at 6 35 53 AM](https://github.com/zotero/zotero/assets/783082/9fb25779-d72e-4a83-9eec-4cd358b2afd5)

Firefox:

![Screenshot 2024-07-02 at 6 36 09 AM](https://github.com/zotero/zotero/assets/783082/d4e2de74-abba-4fe8-b392-3084600c0f00)

It's kind of a waste of space, because there's tons of free space in the toolbar that works for dragging, but if you don't realize that, you might become very frustrated (like the person in the thread). It's also slightly unsettling to drag from the toolbar. So we should probably add a little bit of space to the right of the stoplight buttons.

**Comment by yexingsha** [comment]
Firefox has 43px between the zoom button and the recent browsing button. I think we can squeeze that a bit, `#tab-bar-container {--safe-area-start: 95px;}` equals 30px between the zoom button and the pinned tab, which is imo plenty of space to drag. And then `.tab-bar-inner-container .pinned-tabs {padding-right: 4px;}` aligns the tab scroll border and the collection tree border when the latter is at minimum width:

<img width="239" alt="Screenshot 2024-07-02 at 13 44 19" src="https://github.com/zotero/zotero/assets/57771795/ec444811-8cc2-46dd-bff8-91e4c65d16bd">

**Comment by dstillman** [comment]
I went with 90px, which seems pretty OK to me. (The stoplight buttons themselves are obviously much smaller.)

I didn't change the padding-right yet, and now the lines are off by a pixel, but are we concerned that the end of My Library is faded whenever the tab bar is scrollable?

Reasons not to worry:

1. Any collection of any length can be selected
2. There are other languages besides English with longer "My Library" strings
3. It's still readable, and leaving space for tabs is important

Reasons to worry:

1. It's a little weird that even My Library is faded?

**Comment by yexingsha** [comment]
It is a little weird, and I think the weird part here is fading the end of the text when the text doesn't actually overflow. I guess it can be solved with some effort, but probably not something we want to focus on right now?
