### ISSUE TITLE
Race condition causes context pane to remain when switching back to Library tab

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4314]
https://forums.zotero.org/discussion/115661/zotero7beta-bug-report-duplicated-right-panes-after-closing-the-pdf-or-html-reader-tab
https://forums.zotero.org/discussion/106980/zotero-7-duplication-of-right-side-pane-after-fast-switching-between-tabs

I'm able to reproduce this by opening two PDFs and holding down Cmd-Shift-] to quickly switch between tabs for a few seconds, then releasing on the library tab. Might take a few tries.

@windingwind, maybe you'd be able to take a look?

**Comment by windingwind** [comment]
Hopefully, this can be fixed by #4289
