### ISSUE TITLE
Reader eats access keys on Windows?

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4319]
https://forums.zotero.org/discussion/115665/zotero-7-file-menu-keyboard-shortcuts-dont-work-in-reader-tabs

e.g. Alt-F to open the File menu. They work from the page number input, but not when the reader content itself is focused.

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/reader/commit/8836db602c0d4fe26e56266d6411bc7a77b94c96
