### ISSUE TITLE
"Assign Color…" colorpicker is blank on Windows

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4325]
https://forums.zotero.org/discussion/115687/cant-see-color-palette-when-assigning-color-to-a-tag

From this line:

https://github.com/zotero/zotero/commit/a6076ce76c2401b4313d2905afac74836834681c#diff-addfc1f4adbaca701f44381e81086bda6976514ac5d707b9b0574a8ea57fb79cR10

**Comment by windingwind** [comment]
working on it
