### ISSUE TITLE
No focus ring in tabs menu on Linux

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4340]
https://forums.zotero.org/discussion/115754/z7-beta-tab-list-not-navigable-from-tab-search

I can reproduce.

**Comment by abaevbog** [comment]
On my ubuntu 20, the focusring wasn't appearing anywhere at all, not just in the tabs menu. It seems like `-moz-accent-color` just doesn't exist on linux. So I thought we can just do the same thing as what is already done in [reader](https://github.com/zotero/reader/blob/01197740a9e3d012f8bfc001c9258824df456e85/src/common/stylesheets/base/_base.scss#L52) and use `SelectedItem` instead.
