### ISSUE TITLE
Sync error after modifying item in collection in trash

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4346]
https://forums.zotero.org/discussion/115817/z7-beta-problematic-citation-collections-not-loaded-for-item

The problem is that items only in deleted collections no longer load collections at all, because the rows get excluded after 2401a34031:

https://github.com/zotero/zotero/blob/4f780424e88ddd0088fcb1b072a33aedb5b63d51/chrome/content/zotero/xpcom/data/items.js#L800-L801

So `item.toJSON()` then throws `'collections' not loaded for item`.

I think the approach here is wrong and we should remove that `deletedCollections` JOIN so all collections are loaded in and then just change `Item::getCollections()` to exclude deleted collections on-demand:

```javascript
Zotero.Item.prototype.getCollections = function (includeTrashed) {
	this._requireData('collections');
	
	var collections = this._collections;
	if (includeTrashed) {
		collections = collections.concat();
	}
	else {
		collections = collections.filter(function (id) {
			var obj = this.ContainerObjectsClass.get(id);
			if (!obj) {
				throw new Error("Collection " + id + " not found for item " + this.libraryKey);
			}
			return !obj.deleted;
		}.bind(this));
	}
	return collections;
}
```

If we were worried about performance, we could add some caching in like we have for `getAttachments()`, with `Items::loadCollections()` following `Items::loadChildItems()` and loading a `trashed` property on `.rows` and setting cache entries to `null` that are then populated in `getCollections()`. But we can probably do that later if necessary.

**Comment by dstillman** [comment]
This will also require reverting various things to not update the item collections cache when moving a collection to/from the trash, since collections will always be present until they're deleted for real.

**Comment by abaevbog** [comment]
Ooh, yeah. I didn't realize not loading trashed collections may lead to `item._loaded.collections = true` never being set. 

I reverted that change and replaced the logic of moving collections in and out of the `_collection` cache with `item.getCollections` that by default returns only non-deleted collection. It seems to have resolved the issue on my end. 

Caching results from `item.getCollections` is certainly something that's worth adding to avoid unnecessary filtering! I'm looking into adding it next but I wanted to get this PR out first to make sure these changes make sense
