### ISSUE TITLE
Bring back ability to annotate/ highlight snapshots (/html) (and save them).

### ISSUE THREAD

**Issue by cannycartographer** [zotero/zotero#435]
This was an incredibly useful feature, would be great if it could be restored to within zotero's code (I guess this specifically applies to the firefox plugin rather than standalone).

Cheers.

See also the forum thread about it here: https://forums.zotero.org/discussion/22330/highlight-text-on-webpages-before-saving-to-zotero/#Item_2

**Comment by devnoname120** [comment]
@cannycartographer Did you find a request on the forums? This would be super useful especially or complementing the recent introduction of PDF highlights.
