### ISSUE TITLE
React 18: Tag selector mouse scrolling is laggy

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4368]
React 17:

https://github.com/zotero/zotero/assets/1770299/e46578b6-476d-429c-a44b-e9a1ff33a744

React 18:

https://github.com/zotero/zotero/assets/1770299/c269c478-8c9d-4877-ab70-417d361d9909

React 18 feels like it's rendering at about half the frame rate, and the scroll distance per click of the scroll wheel is also about halved. The frame rate change doesn't quite come through on the screen recording, but it's very noticeable when scrolling.

I tried upgrading to the latest `react-virtualized` (one minor version newer), but that didn't change anything.

**Comment by abaevbog** [comment]
Interesting. For me, mouse scrolling seemingly works without issues but I am noticing the lag if I scroll with `arrowUp`/`arrowDown` keys

**Comment by abaevbog** [comment]
> Are you using a mouse with a scroll wheel or something like a Magic Mouse / trackpad?

Nope! Just the usual trackpad on mac. This is the scroll using mouse at first and the focusing and holding `arrowDown`. Somewhat hard to see but I think the difference is still noticeable

https://github.com/zotero/zotero/assets/36271954/0133f997-c9a3-479b-9008-da9fbe252ef5

**Comment by abaevbog** [comment]
Gotcha! 

> React 18 feels like it's rendering at about half the frame rate

I did notice that the rendering pattern has changed a bit in react 18, which made me move around some awaiting for promises in the tag selector tests. Potentially, due to [automatic batching](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#automatic-batching)?

It indicates that we can opt out of that new behavior by using `flushSync` - not sure if this is really the root of this issue but perhaps worth a shot.

**Comment by abaevbog** [comment]
So I tried to track down where in `react-virtualized` scrolling is handled to see if the `flushSync` wrapper would help, and I think it did... At least, as far as holding `arrowDown` key for me.

Before doing anything else, @AbeJellinek, do you mind checking if the same tweak solves the lagginess for you? 

I went to `./node_modules/react-virtualized/dist/umd/react-virtualized.js` and wrapped `_this.setState` on line 1342 with `ReactDOM.flushSync`. So the block of lines 1342-1347 became

```
    _this.state.isScrolling || isScrollingChange(!0), ReactDOM.flushSync(()=>_this.setState({
        isScrolling: !0,
        scrollLeft: scrollLeft,
        scrollPositionChangeReason: scrollPositionChangeReason,
        scrollTop: scrollTop
    }));
```
If this works for you, I believe `ReactDOM` is already being patched for something else in `babel-worker.js`, so perhaps we could add it there too?

**Comment by abaevbog** [comment]
Awesome! Thank you for pointing this out
