### ISSUE TITLE
Reader: Auto-scroll with middle mouse button not working

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4384]
https://forums.zotero.org/discussion/107529/7-0-beta-middle-click-not-working

I haven't tried, but a lot of reports. In theory @AbeJellinek fixed this in a7f1235fd18905f6b44a3ca1e8c1b4521d8be62d.

**Comment by mrtcode** [comment]
As I mentioned earlier, it starts to work after opening Error Console, although the appeared circle doesn’t have any icon.
