### ISSUE TITLE
Alt key doesn't highlight collections containing an item on Linux

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4386]
https://forums.zotero.org/discussion/107378/zotero-7-beta-identifying-collections-key-malfunction-on-ubuntu-22-04

Not sure when this regressed.

**Comment by abaevbog** [comment]
@dstillman we were running into issues with Alt key on linux conflicting with shortcuts for menu access keys (https://github.com/zotero/zotero/issues/3683) so during the discussion that spanned multiple issues and PRs we ended up deciding (https://github.com/zotero/zotero/pull/3412#issuecomment-1932616490) to highlight collections on linux on Ctrl instead (https://github.com/zotero/zotero/pull/3689). I just tried and holding Ctrl does highlight the collection for me as expected.

**Comment by dstillman** [comment]
Ah, right, sorry.
