### ISSUE TITLE
Styling of annotation-mode toggle in text-selection popup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4392]
Tweaks we can make here?

https://github.com/user-attachments/assets/d58f0a8c-2189-46ba-a552-401e6a492c76

In particular, I don't think we need a hover style on the selected tab, but we might want an active style.

Follow-up to https://github.com/zotero/zotero/issues/3352

**Comment by dstillman** [comment]
Also, there's not enough space above at the moment, and way too little space below:

<img src="https://github.com/user-attachments/assets/4362b24b-2ace-4d61-898d-6b443eff88cf" width="226"/>

Compare to https://github.com/zotero/zotero/issues/3352#issuecomment-2224898985

**Comment by yexingsha** [comment]
The hover style on both active and inactive tabs are indeed unnecessary. What do you mean by active style?

**Comment by dstillman** [comment]
As in CSS `:active` — when being clicked

**Comment by yexingsha** [comment]
Ah, got it. Active style can be setting button background color to `var(--color-button)` at 50% opacity:


https://github.com/user-attachments/assets/e26cbb94-7dc4-4c3d-b49c-f212c7430565

**Comment by mrtcode** [comment]
> Ah, got it. Active style can be setting button background color to `var(--color-button)` at 50% opacity:

It seems that in dark mode, `background-color: rgba(var(--color-button), 0.5)` doesn’t have any effect. Are you seeing this too, or is it just on my end?

**Comment by mrtcode** [comment]
Actually, that’s a problem with color calculation on my end. I’ll solve it. Sorry.
