### ISSUE TITLE
Find Available PDF: URL normalization skips Atypon PDFs

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4396]
e.g.:

﻿﻿﻿﻿﻿﻿https://www.liebertpub.com/doi/full/10.1089/cmb.2009.0238
https://www.tandfonline.com/doi/full/10.1080/01457632.2023.2255811

PDF download URL is the same as the reader URL but with `?download=true`, and query strings are ignored, so it gets skipped.

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/zotero/commit/629c5ecab28c3d3557bf3fb7998c54db6c0f8f04
