### ISSUE TITLE
Problems in attachment-item conflict-resolution window

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4418]
![Screenshot 2024-07-22 at 8 27 18 AM](https://github.com/user-attachments/assets/ef6926f1-d020-42cd-a067-55ec35c4738b)

Not sure what we had before, but Pages and Indexed definitely shouldn't be there, I'm not sure if Filename should be there but it definitely shouldn't be empty, and there shouldn't be a white rectangle at the bottom.

**Comment by dstillman** [comment]
Z6, for reference:

![Screenshot 2024-07-22 at 8 37 23 AM](https://github.com/user-attachments/assets/807ee985-f198-4663-a561-79a4defaef09)

**Comment by windingwind** [comment]
I can confirm it's from our new logic of making sure the attachment exists in the new attachment box. The `item` provided by CR is virtually generated and its `getFilePathAsync` doesn't resolve a correct return value. I will try to fix this.

**Comment by dstillman** [comment]
Fixed in #4430
