### ISSUE TITLE
Mendeley import: Make sure annotations are only saved on PDF attachments

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4422]
https://forums.zotero.org/discussion/comment/468647/#Comment_468647

Still waiting for info here, but we should make sure we have a check that we're only saving annotations on a PDF.

**Comment by tnajdek** [comment]
Must be Zotero 6. 

This has been [fixed](https://github.com/zotero/zotero/commit/124b64f3a2b74b4c6c7b111a22a83b0df23c650b) in Zotero 7 few months ago, the relevant code is here:

https://github.com/zotero/zotero/blob/0944f3bdc6df0304c8c67975c558eaa51182ec9c/chrome/content/zotero/import/mendeley/mendeleyImport.js#L1629-L1637

Should I port it back?

**Comment by dstillman** [comment]
Ah, no, that's OK.

**Comment by dstillman** [comment]
Would reimporting with Z7 delete any such annotations, or would they have to delete these attachments (or run code we give them to delete the annotations of affected annotations)? I assume the latter? What did we tell whoever encountered this previously?

**Comment by tnajdek** [comment]
I believe re-importing fixes the most common scenario where Mendeley misreported the MIME type, but the attachment file was indeed a PDF. After re-importing with Z7, it should be correctly marked as a PDF (lines 1632-1633 in the code snippet above handle that), and thus annotations should be allowed to sync.

I believe that was the case the last time we encountered this issue, but I can't remember if we asked to re-import or just delete the invalid attachment items.

**Comment by dstillman** [comment]
In this case the file seemed to actually be a ZIP file, so I guess deleting would be necessary here.
