### ISSUE TITLE
Style issues in redesigned Select Items dialog on Windows

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4440]
https://github.com/zotero/zotero/pull/4406#issuecomment-2252507071

**Comment by windingwind** [comment]
Maybe using `drawintitlebar-platforms` (title.js) is better? Like the scaffold and main window.

**Comment by windingwind** [comment]
the logic of title.js should be inherited from Mozilla's code, and we use it in most dialogs/windows where we don't want a native titlebar. Ideally, all window's no-titlebar logic should be the same, and sharing the same code could be easier to maintain.

> (Also, the chromemargins that titlebar.js sets aren't correct for this dialog!)

I'll check why's that later. Thanks for letting me know

**Comment by windingwind** [comment]
it's from https://searchfox.org/mozilla-central/source/browser/base/content/browser-tabsintitlebar.js#70-84 . not sure if it's still the case on fx115, but back to fx102, setting `chromemargin` does control the window's margin for me (on some platforms, it only has an effect if larger/smaller than a threshold).

also, the `drawintitlebar` seems to be deprecated after fx115:

https://searchfox.org/mozilla-esr115/search?q=drawintitlebar&path=&case=true&regexp=false

v.s.

https://searchfox.org/mozilla-central/search?q=drawintitlebar&path=&case=true&regexp=false

**Comment by windingwind** [comment]
> (Also, the chromemargins that titlebar.js sets aren't correct for this dialog!)

Weird but I didn't see any difference:

titlebar.js:

<img width="800" alt="image" src="https://github.com/user-attachments/assets/162f950f-6384-4046-8315-a119e1deadd2">

<img width="805" alt="image" src="https://github.com/user-attachments/assets/d9ccf42e-96bb-4cac-bba7-b295d4d3c954">

<img width="977" alt="image" src="https://github.com/user-attachments/assets/49cccea4-bcca-42d5-94d0-e3456bc4ed2a">


current `drawintitlebar`:

<img width="800" alt="image" src="https://github.com/user-attachments/assets/9fd0d101-c39d-40bf-bf54-a479a073b6c3">

<img width="803" alt="image" src="https://github.com/user-attachments/assets/9ce56238-6deb-4ff1-a0b4-d766a77457f7">

<img width="963" alt="image" src="https://github.com/user-attachments/assets/d7357b7c-bb8f-4c74-93fc-69174695819d">
