### ISSUE TITLE
First item in items list not read by NVDA?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4444]
https://forums.zotero.org/discussion/116335/zotero-beta-7-accessibility-regression

**Comment by abaevbog** [comment]
Yeah, I could reproduce this. The glitch appeared after refactoring to have default virtualized table (e.g. style manager in preferences) announce selections. This little tweak takes care of it for me:

https://github.com/user-attachments/assets/6123c96a-0794-45a7-99f1-18754598011f
