### ISSUE TITLE
Add banner suggesting that Windows users running x86/x86_64-on-aarch64 switch to ARM64 build

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4463]
Follow-up to 14a0a8ab2466aa1bd73af933cedbbae01590b96f

There's a separate `isWowARM64` flag that we can use for x86-on-aarch64. Not sure what the best way is to identify x86_64-on-aarch64 (though once we figure it out, we should update `Zotero.getSystemInfo()` to identify it too).

**Comment by tnajdek** [comment]
Closed in #4473
