### ISSUE TITLE
`react.development.js` and `react-dom.development.js` potentially causing significant memory leak

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#4481]
I'm wondering why we aren't linking `react-dom.js` and `react.js` to their production equivalents.

<img width="1045" alt="Screenshot 2024-08-01 at 16 39 27" src="https://github.com/user-attachments/assets/a74aeeba-f3c4-4a95-a58f-92c334abfa4e">

**Comment by dstillman** [comment]
We patch both of those in babel-worker.js. Maybe because of that?

But if we can switch, we should switch.
