### ISSUE TITLE
`-jsdebugger` doesn't show Zotero sources in Debugger tab

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4503]

**Comment by dstillman** [comment]
As discovered by @windingwind, it's `-jsconsole` in `build_and_run` that's breaking this. No reason to start both anyway, so we should just skip `-jsconsole` when `d` is passed.

**Comment by windingwind** [comment]
> (Weirdly, chrome://zotero shows as just chrome://, but all the right files are there.)

Same for plugins' links. The `chrome://` directory in the debugger is so crowded.
