### ISSUE TITLE
Show banner before trying to install Mac Word plugin on Sequoia

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4526]
Sequoia locks down writes to Group Containers, so we need to show a dialog before actually doing the write, warning that there'll be a system prompt (with Continue and Cancel). We need this mostly for automatic installs, but we might as well show for manual installs too, just since the dialog is vague and kind of scary.

We can limit this to Sequoia and up (`Zotero.isMac && (await Zotero.getOSVersion()).split(' ')[1].split('.')[0] >= 15`).

I can write the text.

![Screenshot 2024-08-08 at 2 03 06 AM](https://github.com/user-attachments/assets/045aebd1-b777-4a52-b0d1-a2d71412c647)

**Comment by dstillman** [comment]
Oh, though one catch is that showing a modal at startup isn't very nice, and might cause problems. Do we want to start using a banner across the top with a button to actually trigger the Word install? Or just wait a few seconds after the main window appears?

**Comment by adomasven** [comment]
I think plugin installation only starts after Zotero is fully initialized anyway, so dialog after delay is fine. Installing the plugin update shouldn't be optional and bound to create more confused users.

**Comment by dstillman** [comment]
Sequoia will probably come out in September, so we should do this. (I did update the [troubleshooting page](https://www.zotero.org/support/kb/word_processor_plugin_installation_error#libreoffice) linked from the error dialog if you click "Don't Allow".)

**Comment by dstillman** [comment]
We can use a banner instead. Still limited to Word being installed. Better than a modal that pops up randomly shortly after startup, and it can keep showing up on restarts unless they explicitly choose "Don't Show Again". "Remind Me Later" and "X" could just mean "show again on the next restart".
