### ISSUE TITLE
Two item panes occasionally appear at startup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4531]
https://forums.zotero.org/discussion/116606/z7-beta-two-item-panes-after-startup

@windingwind, I think you had an idea for what might be causing this?

**Comment by windingwind** [comment]
What's their Zotero version? It should have been fixed. I may need their debug output

**Comment by dstillman** [comment]
7.0.0-beta.115+4c32317ba

**Comment by windingwind** [comment]
OK, managed to reproduce. Will fix that.
