### ISSUE TITLE
"User canceled primary password entry" errors while setting up syncing

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4540]
Fixed by deleting the profile folder, as noted first by @adam3smith in April:

https://forums.zotero.org/discussion/comment/460050/#Comment_460050

https://forums.zotero.org/search?Search=%22User+canceled+primary+password+entry%22

**Comment by dstillman** [comment]
Relevant Mozilla code is here:

https://searchfox.org/mozilla-esr115/rev/e18c37524d5224010fa1b7c4ba01008c858dfeb6/toolkit/components/passwordmgr/crypto-SDR.sys.mjs#78-90

**Comment by dstillman** [comment]
@adam3smith Do you remember what precipitated this for you?

**Comment by adam3smith** [comment]
Not in detail, no. Since I say Windows 10, this must have been on my secondary laptop, possibly right after switching to Zotero 7 and would likely have been a non-admin account

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/472140/#Comment_472140

I've reproduced this with a profile from a user with files from 2013. Deleting secmod.db fixes it. I'll add some code to do that automatically.
