### ISSUE TITLE
What does ZoteroPane.getCollectionTreeRow() do?

### ISSUE THREAD

**Issue by StevenGLee** [zotero/zotero#4542]
I'm developing a plug-in that shows some self-defined searching on the `itemView`, like

``` typescript
const s = new Zotero.Search();
s.addCondition("some", ""conditions");
const collectionTreeRow = {
  view: {},
  ref: s,
  isSearchMode: () => true,
  isSearch: () => true,
  // some other codes.
}
ZoteroPane.itemsView.changeCollectionTreeRow(collectionTreeRow);
ZoteroPane.collectionsView.selection.clearSelection();
```

The last line above is to unselect the item in the `collectionsView`, indicating that the items shown in the `itemView` is not a collection listed in the `collectionsView`.

The searching is able to be displayed on the `itemTree`. However, when an item is selected, the content in `ItemPane` (right side bar) does not change, and when right click on the item, context menu does not pop up.

I located the above problem on `ZoteroPane.itemSelected()`, which returns immediately when `ZoteroPane.getCollectionTreeRow()` returns 0. `ZoteroPane.getCollectionTreeRow()` tries to return the `ZoteroPane.collectionsView.selection.focused`-th row, which I have just cleared.

I noticed that `ZoteroPane.getCollectionTreeRow()` is called many time elsewhere, but I don't know the its difference from using `ZoteroPane.itemsPane.collectionTreeRow`. Is there any possibility to change the implementation of `ZoteroPane.getCollectionTreeRow()` to directly returning `ZoteroPane.itemsPane.collectionTreeRow`? Or providing a new API that enabling showing some self-defined searching on the `itemView`?

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md

Development questions should be posted to <a href="https://groups.google.com/g/zotero-dev">zotero-dev</a>.
