### ISSUE TITLE
Blurry creator plus/minus buttons on low-res displays

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4549]
https://forums.zotero.org/discussion/116713/tiny-create-creator-button-difficult-to-recognize

**Comment by yexingsha** [comment]
![plus-circle](https://github.com/user-attachments/assets/af9dcabc-af5c-480c-979c-d6acc67a0865) ![minus-circle](https://github.com/user-attachments/assets/49b61c72-69a4-4cb3-affe-994aa78ba428) ![input-single](https://github.com/user-attachments/assets/339d4453-44ad-41dc-9dc5-abaa1cb5726b) ![input-dual](https://github.com/user-attachments/assets/e2abd960-5d9f-4b02-bc65-08017647cbec)

Looks like this with updated icons:

<img width="332" alt="Screenshot 2024-08-12 at 13 08 47" src="https://github.com/user-attachments/assets/646a7777-eb80-4394-9968-11566e8284ef">
