### ISSUE TITLE
Show error if word processor plugin can't be automatically upgraded

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4566]
A bunch of people have non-working plugins after the Z7 update with no explanation why. We should add a warning and then push an update with a new version number so everyone gets an upgrade.

(Doing this for Word is the priority.)

**Comment by adomasven** [comment]
We should link to a dedicated troubleshooting page. https://www.zotero.org/support/kb/word_processor_plugin_installation_error ?

**Comment by wiraki** [comment]
Hello! I would rather get a message that describes the error and why the plugin could not be installed, instead of a link to the troubleshooting page. Or both, that would be the best.
