### ISSUE TITLE
Consider inverting the order of tag colors

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#4569]
https://forums.zotero.org/discussion/comment/470853#Comment_470853

I was wondering the same thing while porting this to the web library (where, arguably, it works better because the tags are aligned to the right-hand side).

Perhaps we should invert it? (We could leave it as is for users who opt in for right-hand side tag colors using a hidden preference.)

**Comment by dstillman** [comment]
Oh, yeah, that's wrong. We should fix. (I don't really understand the logic of doing it the way we're doing it now, even on the right side.)
