### ISSUE TITLE
Mendeley importer fails to import attachments on Windows

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero#4588]
Potential regression?

https://forums.zotero.org/discussion/117019/not-able-to-import-whole-directory-from-mendeley

and probably 

https://forums.zotero.org/discussion/117025/incomplete-import-from-mendeley-and-no-attachment-pdfs-have-come-through

I was able to reproduce on Windows. Curiously the path has a "/" at the beginning.

````
DOMException: PathUtils.parent: Could not initialize path: NS_ERROR_FILE_UNRECOGNIZED_PATH
````

**Comment by tnajdek** [comment]
I believe this might be the culprit?

https://github.com/zotero/zotero/blob/06eb1d7341da44a31b21b79ee4f873d200133a58/chrome/content/zotero/osfile.mjs#L353

**Comment by dstillman** [comment]
Looks like I only added the Unix version. I've added in the Windows code, which should fix this. (I'm not totally clear on what path was being passed in, though.)

**Comment by tnajdek** [comment]
@dstillman this is still producing invalid paths. It now prepend "\".

**Comment by dstillman** [comment]
What's the actual input here? I didn't actually reproduce this — I just swapped in the code for Windows.

**Comment by dstillman** [comment]
OK, I see, the problem is in our shim of `fromFileURI`:

```
OS.Path.fromFileURI('file:///C:/Users/dan/foo')
```

Zotero 6:

```
C:\Users\dan\foo
```

Zotero 7:

```
/C:/Users/dan/foo
```

And it's just from the `URL` `pathname` property;

```
var url = new URL('file:///C:/Users/dan/foo');
url.pathname
```

```
/C:/Users/dan/foo
```

**Comment by dstillman** [comment]
Oh, because I forgot to copy the Windows version of that, too. I'll fix.

**Comment by tnajdek** [comment]
yes, I believe that's the one. During the import I'm seeing that `OS.Path.fromFileURI` for

````
file:///C:/Users/doppler/AppData/Local/Temp/Zotero/m-api-6af151ce-e9e6-f5ed-147b-2db6645cbc47.pdf
````

produces

````
\C:\Users\doppler\AppData\Local\Temp\Zotero\m-api-6af151ce-e9e6-f5ed-147b-2db6645cbc47.pdf)
````

**Comment by dstillman** [comment]
OK, try that.

**Comment by tnajdek** [comment]
Ok now it works!

for
````
file:///C:/Users/doppler/AppData/Local/Temp/Zotero/m-api-6af151ce-e9e6-f5ed-147b-2db6645cbc47.pdf
````
produces
````
C:\Users\doppler\AppData\Local\Temp\Zotero\m-api-6af151ce-e9e6-f5ed-147b-2db6645cbc47.pdf
````

and attachments are successfully imported

**Comment by dstillman** [comment]
OK, sorry about that — pushing a new build.

**Comment by dstillman** [comment]
(I wonder what other functions in our shim I only copied the Unix version of…)
