### ISSUE TITLE
Proxy reverse DNS lookup request should have a timeout

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#460]
https://forums.zotero.org/discussion/34984/zotero-makes-firefox-hang-on-some-pages/

If the DNS lookup hangs (due to firewall rules, say), Zotero hangs, possibly forever.

Until this request is async, can we at least set a timeout on the socket? This might be as easy as adding ``transport.setTimeout(Components.interfaces.nsITransport.TIMEOUT_CONNECT, 5);`` after the ``sts.createTransport()`` line in proxy.js? I'm not sure what would actually happen when it timed out, though.

**Comment by nalimilan** [comment]
Bump! I'm still experiencing hangs quite often, which is really painful.

**Comment by nalimilan** [comment]
Thanks!
