### ISSUE TITLE
Erroneous prompt to install LibreOffice plugin on first run

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4613]
I've had this happen on macOS and in a Windows VM, and I don't have LibreOffice on either. Happens when I first run Zotero from source after upgrading from a pre- 0cac4f5c86e807bd09df7448a0025c9daec9b72e build.

**Comment by dstillman** [comment]
I can reproduce this.

**Comment by dstillman** [comment]
This is already in the latest release, so we should fix this ASAP and push a new version.
