### ISSUE TITLE
LibreOffice installation error appears twice

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4652]
![libreoffice-installation-error](https://github.com/user-attachments/assets/48b61bbf-050f-4444-ae7f-12bdd1848743)

Once in the window and once in an alert

**Comment by adomasven** [comment]
Steps to reproduce? Do you have libreoffice installed without java?

**Comment by dstillman** [comment]
(But I would think this would be happening for any installation error. I was really just reporting the UI issue here, not the error, though I'm not sure why it's failing to install.)
