### ISSUE TITLE
Attachment preview viewport isn't centered on page

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4653]
On first load, it's cutting off the top of some PDFs and showing me part of the following page:

![Screenshot 2024-08-31 at 2 08 47 AM](https://github.com/user-attachments/assets/49e79f25-313e-4121-b271-751dcf1005be)

After clicking forward and back:

![Screenshot 2024-08-31 at 2 08 53 AM](https://github.com/user-attachments/assets/bbd8ae2a-851d-4bd2-a0a9-c36b75205c3b)

**Comment by windingwind** [comment]
Similar to https://github.com/zotero/zotero/issues/4147#issuecomment-2153752368. It's probably from certain inner behavior of the reader, may be because the state initialization happens too early or because of some race condition of page positioning.

**Comment by mrtcode** [comment]
I'll look into that.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/118354/bug-in-the-attachment-panel-misaligned-pages
