### ISSUE TITLE
Automatically switch to Stacked mode when resizing window in reader tab

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4669]
We're getting lots of posts complaining about the minimum width of reader tabs. [One suggestion](https://forums.zotero.org/discussion/comment/473243/#Comment_473243):

> Would it perhaps be an intuitive solution for the library tab to automatically collapse the item pane when the window is shrunk beyond the usable minimum and to expand it again automatically if the window is made big enough? 

My first thought was that this would be very confusing, but it might actually make sense? If you did switch back to the library tab while the window was too narrow, the item pane would be gone, but the sidenav is right there, and hopefully most people would figure out they could click one of the buttons. And we already expands the window to fit the item pane if you click a sidenav button while the pane is closed and the window was made too narrow.

I'm not sure whether we'd do this in the library tab too. It's possible that would cause more confusion, but it's also sort of clearer than the item pane only disappearing while you're in another pane. As long as it auto-expands as you enlarge the window, maybe it's fine, and better to be consistent?

**Comment by adomasven** [comment]
Could also switch to stacked layout in this case.

**Comment by dstillman** [comment]
Hmm. If there's ever a choice between thinking about stacked layout and not thinking about stacked layout, I prefer the latter, but I guess as long as we have it, it's hard to argue that that's not the friendlier, less-alarming option. And we also already automatically expand the window as necessary when moving from stacked to standard. So maybe that makes the most sense. We'd still want to automatically switch out of it on a resize-out if we switched into it due to a resize-in in the same session. (If people panic and restart Zotero to try to fix the problem…I guess they need to find the menu option.)

**Comment by windingwind** [comment]
I was thinking that if the window is already in its min-width with the item pane open, you just cannot resize the window anymore, and dragging the window border does not trigger a resize event. How can we know people are resizing the window in that case and take actions to collapse the item pane or switch to stack mode or something?

**Comment by dstillman** [comment]
Can we avoid setting an actual min-width when the item pane is showing, and just adjust the UI?

**Comment by windingwind** [comment]
Could we try to set a max-width for the item pane based on the window width, so that it won't get ridiculously large and thus won't feel like that it prevents the window from being resized?
