### ISSUE TITLE
make comment window resizable and render latex in comment window

### ISSUE THREAD

**Issue by Mr-Grin** [zotero/zotero#4671]
1. make comment window resizable, when there is a lot of text in the comment window, the window is too small that make the text looks crammed, make the window resizable using the mouse to drag the edge of the window

2. comment window does not support latex rendering, both in-line and whole-line latex. I hope this functionality can be added

<img width="775" alt="tns307jf0lv2taqngp7d" src="https://github.com/user-attachments/assets/ca08e0a3-e4e2-48b5-9800-0ce237c0069a">
<img width="408" alt="hh8nwhikcekg42viq27y" src="https://github.com/user-attachments/assets/d6385a97-cffc-4124-b247-b3d27d75f494">

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
