### ISSUE TITLE
zoom function cannot work well in the latest version 7.0.5

### ISSUE THREAD

**Issue by Jones-match** [zotero/zotero#4698]
when I use zotero6, I press ctrl and scroll middle mouse button, the page will zoom quickly. but when I update to the 7.0.5, it seems not quick. I must press [ctrl] several times, and then the page will change.

**Comment by mrtcode** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md

**Comment by mrtcode** [comment]
Please report your issue in this thread https://forums.zotero.org/discussion/comment/474737#Comment_474737
