### ISSUE TITLE
Support lowercase /s for silent installation on Windows

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4713]
https://forums.zotero.org/discussion/comment/475345/#Comment_475345

This seems easy enough:

https://nsis.sourceforge.io/Which_command_line_parameters_can_be_used_to_configure_installers%3F#Case-sensitivity

**Comment by tnajdek** [comment]
This seems to work already (this is with unmodified installer from zotero.org):


https://github.com/user-attachments/assets/7ceada52-3ad7-41af-8710-cacf09354e93

https://github.com/user-attachments/assets/c42060f6-6e83-4159-9673-b88a745e8629
