### ISSUE TITLE
Error merging ink annotations with tags

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4720]
https://forums.zotero.org/discussion/118414/merge-tagged-ink-annotations

`tags` is an array of objects with property `tag`, not an array of strings. Annotation tags would never be automatic, so there wouldn't be a `type`. I guess it's possible there could be other properties in the future, so we should preserve any that exist, though it's unlikely.

**Comment by mrtcode** [comment]
Fixed. Sorry.
