### ISSUE TITLE
Remember last-used text annotation font size

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4729]
Now that you can change the size explicitly, we should default to the last-used size when creating a new text annotation instead of defaulting to 14.

Not sure if it should also update the last-used size when you drag to resize a text annotation. Probably? So if you resize an annotation to a given size and then create a new one, it would be the same size.

**Comment by mrtcode** [comment]
Perhaps it should remember everything in the toolbar? This includes:

1) Individual colors for each annotation tool.
2) Text annotation font size.
3) Ink annotation width.
4) Eraser width.

Additionally, does changing one of these values in one reader instance should immediately update the toolbar in all other reader tabs or windows?

**Comment by dstillman** [comment]
Oh, sorry, duplicate of #4439.
