### ISSUE TITLE
Can't get to annotation widget popup via keyboard

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4732]
1. Close sidebar
2. Press Tab to focus a highlight annotation
3. Press Return
4. Press Tab to focus the three-dots menu
5. Press Return to open the menu.

The context menu opens, but focus remains in the document, so the arrow keys don't navigate the menu.

**Comment by abaevbog** [comment]
This seems related to #4681. Currently you can't get into the context menu of any annotation via keyboard, regardless if the sidebar is collapsed or not.

I have https://github.com/zotero/reader/pull/139 that allows to navigate the context menu. I did just notice that with the new keyboard navigation, if the sidebar is collapsed, arrows will not navigate the menu but instead try to move the annotation. I'll to try to tweak that PR to not do that if the context menu is opened.

**Comment by mrtcode** [comment]
@abaevbog Context menu navigation was working a few months ago, but there was a regression at some point. I'm pushing a fix for that now, but let me know if there are any further issues.

**Comment by abaevbog** [comment]
Ah, I was wondering how the VPAT review happened to skip over the context menu but the regression must have appeared after the review of that section happened.

In any case, that seems to have done it! I'll drop all focus-related pieces from that PR of mine and only keep the part related to selecting a menu option by typing (like with native context menu)
