### ISSUE TITLE
Annotations support markdown format

### ISSUE THREAD

**Issue by caibimiaokong** [zotero/zotero#4745]
- When reading papers, I often encounter questions I don't understand, and then ask the AI. Its answer format is markdown, and it will look messy when I paste it into the comments.
- As a programmer, I prefer to use markdown for annotations. Can you support markdown while supporting rich text annotations?
![image](https://github.com/user-attachments/assets/932746a8-4677-4963-9035-b894e8fa38c7)
 
Looking forward reply

**Comment by windingwind** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
