### ISSUE TITLE
How to achieve such highlighting in the PDF function of the recall function？

### ISSUE THREAD

**Issue by 0xChrisJL** [zotero/zotero#4769]
Please tell me how I can realize this kind of highlight recall function in PDF function, other notes can be adjusted by css style style, zotero can also be used in this way?
![HighlightMemories](https://github.com/user-attachments/assets/017bfe11-eefb-4802-810f-367ca0589425)

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
