### ISSUE TITLE
Error running `localize-ftl` after swapping English strings used in variable-only strings

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4773]
`localize-ftl` still has trouble with some edge cases. In this case, [two English strings were swapped](https://github.com/zotero/zotero/commit/d2c8f5f1862c0d4073334d2b8454b1118d152f8a). I'm now getting this error:

```
> zotero@7.0.0 localize-ftl
> node ./js-build/localize-ftl.mjs

[localize] af-ZA/zotero.ftl
[localize] af-ZA/preferences.ftl
[localize] af-ZA/scaffold.ftl

Error: Error: Failed to localize "af-ZA": Could not determine type of "pdfReader-underlineText" in message named "pdfReader-toolbar-highlight"
    at guessReferenceType (file:///Users/dan/Development/Zotero/Client/node_modules/ftl-tx/src/json-to-ftl.js:38:9)
    at parseString (file:///Users/dan/Development/Zotero/Client/node_modules/ftl-tx/src/json-to-ftl.js:128:32)
    at JSONToFtl (file:///Users/dan/Development/Zotero/Client/node_modules/ftl-tx/src/json-to-ftl.js:168:20)
    at getFTL (file:///Users/dan/Development/Zotero/Client/js-build/localize-ftl.mjs:79:17)
    at async file:///Users/dan/Development/Zotero/Client/js-build/localize-ftl.mjs:105:14
```

English reader.ftl:

```
pdfReader-underlineText = Underline Text
pdfReader-highlightText = Highlight Text
```

af-ZA reader.ftl:

```
pdfReader-underlineText = Underline Text
pdfReader-highlightText = Verligmerk teks
```

af-ZA zotero.json:

```
	"pdfReader-underlineText": {
		"string": "Underline Text"
	},
	"pdfReader-highlightText": {
		"string": "Verligmerk teks"
	},
```

`pdfReader-toolbar-highlight` doesn't exist in the af-ZA zotero.json because that's a variable-only string in en-US reader.ftl:

```
pdfReader-toolbar-highlight =
    .aria-description = { -pdfReader-a11yTextualAnnotationInstruction(number: "1")  }
    .title = { pdfReader-highlightText }
pdfReader-toolbar-underline =
    .aria-description = { -pdfReader-a11yTextualAnnotationInstruction(number: "2")  }
    .title = { pdfReader-underlineText }
```

Something about the en-US string changing and now having a different variable from the af-ZA version, so it tries to rewrite the string from the af-ZA reader.ftl (even though it never changes in af-ZA) and it no longer matches the en-US definition? Need to always rewrite variable-only strings from en-US and ignore the existing "localized" version (which is just a copy of the (possibly now outdated) en-US version)?

**Comment by tnajdek** [comment]
I’ve fixed [this problem](https://github.com/tnajdek/zotero/commit/7c44a044eaccadcb391a7e769a958703611d2f1a) but encountered another issue with the `-pdfReader-a11yTextualAnnotationInstruction(number: "1")` syntax not going through the translation. I’ll address that first thing tomorrow morning and then commit the fix to `zotero/zotero`.
