### ISSUE TITLE
Printing bibliography resets dark mode to light mode

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4782]
https://forums.zotero.org/discussion/118990/printing-bibliography-reset-dark-mode-lost-tags

I can reproduce.

**Comment by abaevbog** [comment]
When a browser is initialized, there is a call to [updateFxaToolbarMenu](https://searchfox.org/mozilla-central/source/browser/base/content/browser-init.js#217), which in turn [tries](https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#814) to call a method from `chrome://browser/content/browser-sync.js`, which tried to load [UIState.sys.mjs](https://searchfox.org/mozilla-central/source/browser/base/content/browser-sync.js#17), which we currently don't have. This is what throws the first error from the stack. So I suppose we'd either want to have `UIState.sys.mjs` available (if it is useful for something else in the future), or maybe we could patch `updateFxaToolbarMenu` to just do nothing.

**Comment by abaevbog** [comment]
Actually, `updateFxaToolbarMenu` error seems to not be what's causing this breakage. There are a few other errors logged, so I'll play around to see if I run into the actual root of the issue.

**Comment by abaevbog** [comment]
Aha, so it looks like [LightweightThemeConsumer](https://searchfox.org/mozilla-central/source/toolkit/modules/LightweightThemeConsumer.sys.mjs) is to blame. If we remove it from browser.js [here](https://searchfox.org/mozilla-central/source/browser/base/content/browser-init.js#112), printing does not change the color scheme for me. And our normal color scheme changes are not affected.
