### ISSUE TITLE
Tab key in reader window changes focus in main Zotero window

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4823]
This routine:

https://github.com/zotero/zotero/blob/682cceca2dc7943256e050dae3de3e6b14c36355/chrome/content/zotero/xpcom/reader.js#L504-L517

is only correct when in a tab (`if (this.tabID)`). Right now it affects the main window when tabbing in a separate reader window.

**Comment by abaevbog** [comment]
@AbeJellinek thank you for pointing that out! Yes, we definitely should not be trying to move focus out of the reader iframe if there is nowhere to move focus to in the standalone window... This small tweak should do it, I think!
