### ISSUE TITLE
ZU.parseContextObject returns an object that's read-only

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#483]
From within translators, calling `ZU.parseContextObject` (and I guess `ZU.createContextObject(,,,, true)` returns an object that is not wrapped/proxied and cannot be modified. (or maybe it is proxied and that's why it cannot be modified?)

This breaks Library Catalog (PICA) translator (see reported translator errors: `Permission denied to access property 'fieldMode'`) under some very specific circumstances (COinS contains an institutional author and no authors can be scraped from page). But it's easy enough to test it by trying `delete newItem.creators[0].firstName` on [line 78](https://github.com/zotero/translators/blob/master/Library%20Catalog%20%28PICA%29.js#L78). http://gso.gbv.de/DB=2.1/SET=5/TTL=26/SHW?FRST=37/PRS=HOL should be a good sample.

I tried using `Zotero.Translate.DOMWrapper.wrap` to wrap the return from this function in utilities_translate.js and also tried to use `this._translate._sandboxManager.sandbox.Zotero._transferItem` within a wrapper function, but with no success. Do we have to set `__exposedProps__` on creator objects? (I'm actually confused why we're allowed to read the value, since I don't see where the `__exposedProps__` are set on these items with read permission)

**Comment by dstillman** [comment]
If this was still relevant, it was likely fixed by 5216f1188531627fd7543d2d149b72a9301622c5.
