### ISSUE TITLE
Tab Reload Issue in Zotero with More Than Five Open Documents

### ISSUE THREAD

**Issue by ParkourX** [zotero/zotero#4831]
I've encountered a reloading issue in Zotero when switching between open literature tabs. **With about five tabs open**, I can switch quickly without noticeable reloads. However, when I open a sixth or more tabs, **switching back to previously opened documents often results in reloading**.

This occurs even with all plugins disabled and is consistent across multiple PDFs. I couldn't find any relevant settings in Zotero's advanced editor that might adjust this behavior, **possibly related to cache capacity or tab limits**.

Any suggestions or solutions would be appreciated.

Thanks!

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md
