### ISSUE TITLE
The window interface is glaring

### ISSUE THREAD

**Issue by KKBLH-101** [zotero/zotero#4852]
The window interface design is too glaring compared to similar readers (regardless of whether the eye protection mode is enabled). Below is a comparison chart
![2bf0a3431442449d649808c7204ab56](https://github.com/user-attachments/assets/0557199f-12ad-4a0b-965e-966675db2d33)
![17ca74fca9cac7c6c2727a1cee15c8e](https://github.com/user-attachments/assets/cabb6b9b-02d7-41b9-b108-3c8cfcdbf965)
![ac07671b09f902295a94038b83513e7](https://github.com/user-attachments/assets/9c2cd693-98d9-443e-ba73-9d75120ca4ce)
![d86f91cd196c05727239b74aeffb348](https://github.com/user-attachments/assets/67783df2-1444-4131-801c-644a09698173)

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md

https://forums.zotero.org/discussion/119774/suggestion
