### ISSUE TITLE
add "Export Library" option for right-click context menu for group libraries

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero#487]
Also export the currently selected library when choosing "Export Library" from Actions menu, ideally put library name at the top of the export dialog.
https://forums.zotero.org/discussion/22217/export-zotero-group-library-to-endnote/#Item_14

**Comment by retorquere** [comment]
If I were to write a patch to add right-click export, against what baseline would you want that? The 4.0 branch, the 4.0.26.4 tag, the master branch?

**Comment by aurimasv** [comment]
4.0 branch

**Comment by retorquere** [comment]
Is there a build procedure beyond zipping things up, and is there a test suite that I should pass?

**Comment by adam3smith** [comment]
you'd typically run straight from the git checkout and not build while coding, but if you do want to build, zipping is all you need to do, though make sure you do have a recursive checkout, since you'll be missing a bunch of components otherwise. 

Simon and Aurimas have been working on a [test suite](https://github.com/zotero/zotero/tree/4.0/test), but I don't think there's anything relevant in there yet, so you can submit without running this.

**Comment by retorquere** [comment]
Crap, I didn't do a recursive clone. Can his still be done after the initial checkout? The patch is ready, just 50-odd lines of code.

**Comment by aurimasv** [comment]
See https://www.zotero.org/support/dev/source_code#running_git_installations for running Zotero from source.

At this point, the test suite coverage is far from complete, but you should still run all currently available tests to make sure that your changes are not breaking anything else. You can run the tests by running `runtests.sh` from the "test" directory of zotero repo. It would be great if you could also write new tests for the features you are submitting, but that is not always trivial to do, so I don't think this will currenlty be enforced.

**Comment by dstillman** [comment]
`git submodule init`
`git submodule update`

**Comment by aurimasv** [comment]
`git submodule update --init --recursive` in one step

**Comment by retorquere** [comment]
OK, done all that (needed to start afresh anyhow as I had done a checkout from the main repo, not a clone), but when I checkout 4.0 and do `zip -r /home/emile/zotero/zotero.xpi . -x *.git*`, I get a sort-of-working Zotero that has no translators loaded. This is without my mods on a different branch, and after I did a "reset translators"; the translators directory remains empty. Possibly related to an error spit out on the console: https://gist.github.com/retorquere/71bac09c0cbd468e94e6

**Comment by dstillman** [comment]
You can't ZIP up a Git checkout. You need to run it directly, as explained in the linked page above.

**Comment by retorquere** [comment]
OK, will do, but @adam3smith said above I could just zip it up.

**Comment by adam3smith** [comment]
sorry, my bad. I misremembered what the recursive clone does.

**Comment by retorquere** [comment]
Hmm, the #mention of 487 didn't put a link here, but running from git worked, and a pull request is at https://github.com/zotero/zotero/pull/712. Perhaps it's waiting for the travis run to finish.

**Comment by dstillman** [comment]
Closed by #712
