### ISSUE TITLE
fx128: UI issues in drop-down menus on macOS

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4880]
Z7:

![Screenshot 2024-12-03 at 4 52 13 AM](https://github.com/user-attachments/assets/9d02ba0c-b5e6-48e4-ab97-ec979f4b86d9)

fx128:

![Screenshot 2024-12-03 at 4 52 38 AM](https://github.com/user-attachments/assets/1623ff22-1bc7-4817-b338-35d8252825b4)

1. Checked menuitem is incorrectly indented again
2. Something weird is going on with the menuseparator — too thick or wrong opacity?
3. Missing padding, so selected menu item is touching the separator

On the other hand, the highlight color and the checkmark now match system menus.

**Comment by dstillman** [comment]
Oh, but it's specifically that menu (and probably some others). But, e.g., the item tree menu is correct.

**Comment by dstillman** [comment]
And from Windows, which maybe makes clearer what's happening:

![Screenshot 2024-12-04 at 1 56 36 AM](https://github.com/user-attachments/assets/42331612-4fa0-492f-987b-1194f4b394ed)

**Comment by windingwind** [comment]
Working on a fix. We used to have some custom CSS for bringing the correct native looking to menupopup, some can be removed and some need to be fixed.
