### ISSUE TITLE
PDF outline items are no longer(?) expanded by default

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4904]
https://forums.zotero.org/discussion/comment/481059/#Comment_481059

Was the outline actually fully expanded in Z6? That does seem like a sensible default to me (and it's what EPUB and snapshot do), but I don't know if we changed it on purpose for some reason.

**Comment by warwickmm** [comment]
It seems that in version 6.0.15, the outline items were collapsed by default.

https://forums.zotero.org/discussion/100667/ios-collapse-outline-entries-by-default#latest

**Comment by mrtcode** [comment]
Yes, it has always been this way. PDF outlines can be very long, so it makes the most sense to only expand the first level by default. This allows you to quickly see the document structure and expand further if needed.

Sometimes the top-level outline is just the document title, which is meaningless, and I plan to remove it and unwrap the second level.
