### ISSUE TITLE
fx128: Dialog backgrounds are white

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4917]
At least on macOS

fx115:

![Screenshot 2024-12-10 at 3 34 42 AM](https://github.com/user-attachments/assets/e5bf6336-c098-4dbb-b8ca-1fcb716781be)

fx128:

![Screenshot 2024-12-10 at 3 34 22 AM](https://github.com/user-attachments/assets/9cac4caf-0d37-4652-aebf-e4aae5f13f2d)

Some things are white in macOS these days — toolbar backgrounds and the background of modal dialogs in settings (e.g., Desktop & Dock → scroll down → "Shortcuts…" (but not "Hot Corners…"!)) — so I'd guess that this came from there, but I'm not sure we want this for entire dialog backgrounds. @yexingsha?

Wizards, by comparison, are still gray (though a slightly different one from 115 dialogs):

![Screenshot 2024-12-10 at 3 36 37 AM](https://github.com/user-attachments/assets/3a737718-2a68-4bdd-a28b-490b7350e529)

**Comment by yexingsha** [comment]
Yeah, this looks really weird, and the white titlebar looks even weirder with the gray background. Though I'm not seeing the white titlebar in fx115. I guess it's a Sequoia thing?

If I understood the apple design resources correctly (it does not provide enough explanation for its materials), the background color of dialogs should be:
- light mode: `background: rgba(246, 246, 246, 0.84); backdrop-filter: blur(15px);`
- dark mode: `background: rgba(0, 0, 0, 0.45); backdrop-filter: blur(15px);`

And the titlebar is overlaid on this background:
- light mode: `background: rgba(234, 234, 234, 0.80); backdrop-filter: blur(15px);`
- dark mode: `background: rgba(60, 60, 60, 0.80); backdrop-filter: blur(15px);`

If we don't care for the macOS translucency effects, then we can apply `var(--material-sidepane)` to both titlebar and dialog backgrounds. It's consistent with the main interface, and close enough to macOS dialog colors.
