### ISSUE TITLE
High Memory Usage and Lag When Zooming in on PDFs in Zotero on Ubuntu (Even with Single PDF)

### ISSUE THREAD

**Issue by liusheng2020** [zotero/zotero#4956]
When reading papers, we sometimes need to zoom in to view details in images. However, what’s strange is that on Ubuntu, zooming in on a PDF in Zotero leads to high memory usage and noticeable lag. I’ve tried several versions of Zotero, including version 7 and beta versions, but the issue persists. Even with just a single PDF opened and zoomed to the highest level, Zotero consumes over 2.5GB of memory. What should I do?
![image](https://github.com/user-attachments/assets/1178a7ca-625b-4ab9-a53f-25dc377cc4e4)
The Zotero version is 7.0.11, OS: Ubuntu 20.04.6 LTS x86_64.
![image](https://github.com/user-attachments/assets/286e4d46-220f-4d97-9d5f-79675a5c8f7a)
Even when I test with a short 5-page IEEE letter article (file size only 779.3 kB) and disable all plugins, the memory usage still can exceed 1.5GB after continuously zooming in on the interface. The lag becomes noticeably severe. I am unsure why this is happening—is there a bug in Zotero? What should I do? Could this be a case of a 'memory leak' issue?
![image](https://github.com/user-attachments/assets/5869930a-df1d-4a3c-a2de-1e5193c3a24e)
![image](https://github.com/user-attachments/assets/a88a16c1-7a0b-4ba0-922f-1f90e2bc55a5)

**Comment by mrtcode** [comment]
Yes, zooming in can increase memory usage. The numbers you see are expected when a single PDF file is opened, but the memory usage does not increase linearly when additional PDF files are opened.

Also you can try with all plugins disabled.

Next time please post in [Zotero Forums](https://forums.zotero.org/) instead.
