### ISSUE TITLE
Opening zotero links (zotero://...) also opens an empty window

### ISSUE THREAD

**Issue by jlegewie** [zotero/zotero#498]
Hi,

when I open a zotero link from a note in Standalone such as `<a href="zotero://select/items/0_PZJQAHCA">test</a>` Zotero first opens an empty window and then selects the Zotero item. Is there a way to prevent that?

[Here](https://forums.zotero.org/discussion/37171/opening-zotero-links-zotero-from-notes-also-opens-an-empty-window/#Item_8) is a brief discussion about the issue. fbennett uses a hack in MLZ to circumvent the problem but maybe there is a better solution from the Zotero side.

**Comment by pashtetGP** [comment]
Hello, I set up everything so that now can open zotero://select links from OneNote - the only problem is with empty window. Can please anyone tell where this file chrome/content/zotero/zoteroPane.js
 is located for editing? Win 7, Zotero FF.

**Comment by pashtetGP** [comment]
Hello, I set up everything so that now can open zotero:// links from OneNote - the only problem is with empty window. Can please anyone tell where this file chrome/content/zotero/zoteroPane.js is located for editing? Win 7, Zotero FF.

**Comment by fbennett** [comment]
https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/zoteroPane.js

**Comment by pashtetGP** [comment]
Thank you for the answer. I mean where it can be found on my local machine to edit? I am not a programmer so sorry if the question is a bit stupid :)

**Comment by zuphilip** [comment]
..\zotero\zotero\chrome\content\zotero\zoteroPane.js

**Comment by rameloot** [comment]
Is there an update on this? Conveniently opening links from Onenote would still be absolutely awesome!

**Comment by xiaoronglv** [comment]
How to open a collection through Zotero link?

"zotero://select/collections/9" doesn't work.

**Comment by et2010** [comment]
I use zotfile to extract annotations to a note and then generate a report from it. I have successfully set Zotero to open the links with [pdf-tools](https://github.com/politza/pdf-tools). I usually save the report as an html file. However, when I try to open zotero links in the saved html file, an empty browser window is opened. Anyone has the same issue? How can I open the link with pdf-tools?

**Comment by bwiernik** [comment]
This issue appears to be fixed on Windows 10 and macOS High Sierra with the current Zotero 5 beta.
