### ISSUE TITLE
Promisification

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#518]
As a prelude to API syncing, in a private branch I've been working on switching the data layer to use asynchronous database access, which is necessary to avoid freezing the UI. (Zotero predates asynchronous database access in Mozilla, but synchronous access on the main thread is now strongly discouraged because of its effect on UI responsiveness.) Unfortunately, due to conflicts between synchronous and asynchronous access, it looks like we'll need to switch over all DB queries in Zotero to be async. More unfortunately, async DB access means returning [promises](https://github.com/petkaantonov/bluebird#what-are-promises-and-why-should-i-use-them) from many core data layer methods, which means rewriting essentially the entire codebase to use promises. This seems like a terrible idea that we'll regret later, but we also haven't come up with a better solution.

This will have fairly major effects on the Zotero client ecosystem, so I'm creating this ticket to share some of the issues involved. I'll be pushing my private ```async_db``` branch up to GitHub so that people can start playing with it. (It should go without saying that you shouldn't use this branch with a real database.)

1) I've switched us from the Q promise library (which we were using in various places) to [Bluebird](https://github.com/petkaantonov/bluebird), which based on published tests is much faster than Q and uses much less memory. With ES6 generators, Bluebird is supposedly nearly as fast as callbacks alone.

2) I'm using ES6 generators and yield almost exclusively, since for data layer code they're the most natural way of using promises, resulting in code very similar to the previous synchronous code. Using ES6 generators means we'll have a Fx26 dependency, which is too bad for Fx24 ESR users, but Fx31 ESR is already available.

3) I'm rewriting many existing methods instead of renaming everything as *Async. We can't keep synchronous versions around anyway, and having everything named *Async seems silly. The main benefit would be that we'd get more obvious breakage for calls that hadn't been updated, but since we're only getting run-time errors either way, I don't think it's worth the code ugliness. (There are still separate non-async and async DB methods, but I'll be making those use non-*Async names once all the synchronous methods have been replaced.)

4) All Zotero plugins are going to break. I don't think there's really any pleasant way to deal with this. (As far as I know Mozilla's add-on dependency checking can't help here.) Once we have a firm version number for this release, I think we'll just have to tell plugin authors that they should add in error messages telling people running the old version of the plugin against the new Zotero version to upgrade to a newer version of the plugin and vice versa.

5) I've experimented with a few different approaches to adding promises, with varying implications for existing code:

To do a more-or-less straight conversion of the existing JS API, we'd have to make nearly everything return a promise. This is what I started off doing, but it would result in a much wider spread of asynchronicity to other parts of the code, with generators and yields and promises everywhere. For example, anything that needed to know if an item was a note would have to become asynchronous, because ```if (!this.isNote()) {``` would have to become ```if (!(yield this.isNote())) {```, because ```isNote()``` would have to do ```(yield this.itemTypeID)``` instead of just ```this.itemTypeID```, because getting the itemTypeID might require loading primary data from the 'items' table, which would have to be an asynchronous database query.

In addition to creating much more overhead and requiring many more changes, this spread of asynchronicity would also mean that there wouldn't be a good way to predict whether a given method was async due to some internal dependency on some other async method, which I think would make it very hard to make changes down the line, since some small new bit of functionality might require making an async call from a previously synchronous method.

We can cut down on the number of promises by adjusting where database access happens. So for the above example, we can just say that any ```Zotero.Item``` with a ```libraryID``` and ```id``` or ```key``` will have its primary data loaded (which happens to usually be the case already). That means that ```Zotero.Item``` methods will never need to load primary data themselves, which means that anything that only needs primary data (such as ```itemTypeID```) can remain synchronous.

Unfortunately that still leaves a lot of things that are currently lazily loaded. For example, item field data is currently not loaded until there's a ```getField()``` call for a non-primary data field. This allows you to do something like:

```
var item = Zotero.Items.get(123); // primary data loaded if not already
var title = item.getField('title'); // item data loaded if not already
var date = item.getField('date'); // returns without loading data
```

With promises and generators, that would turn into this:

```
var item = yield Zotero.Items.get(123);
var title = yield item.getField('title');
var date = yield item.getField('date');
```

However, that would mean that anything that needed any non-primary item field would have to be asynchronous as well, which would have pretty far-reaching effects.

Unfortunately, the lazy-loading is pretty important for performance. Right now, when first opening Zotero, we load all data necessary to display and sort the middle pane, and for large libraries that can already result in a notable delay. If we loaded all of an item's field data whenever generating a ```Zotero.Item``` object, starting Zotero would require loading all field data in the database.

My solution has been to trade some elegance for backwards-compatibility and efficiency, with new public ```Zotero.Item.loadItemData```/```loadCreators```/```loadRelatedItems```/etc. methods (which were previously private and lazily called) that have to be called asynchronously before the ```get*``` (and similar) methods can be used. An attempt to use a ```get*``` method when the associated data isn't loaded throws an error, but the ```get*``` methods remain synchronous. Some part of the calling code still has to be promise-based in order to call the ```load*``` methods, but everything after that can be synchronous:

```
var item = yield Zotero.Items.get(123);
try {
    var title = item.getField('title'); // item data not yet loaded; throws an error
}
catch (e) {}
yield item.loadItemData(); // this is a no-op if data is already loaded
var title = item.getField('title');
var date = item.getField('date');
```

This results in many fewer promises/yields and allows more existing code to remain unchanged. The synchronous methods also only fail if their cached values don't exist, which allows for more granular loading in some situations — for example, right now we load entire columns of field data for the middle pane and stuff them into the objects without triggering full loads.

Along with ```.load*```, various other classes of operations will be predictably async: ```.save()```, ```.erase()```, attachment file operations. Some one-off methods called from only one or two places in the UI can also be made async without causing much trouble.

6) Debugging can be trickier with promises. For now, Bluebird's long stack traces are enabled, which sometimes produce useful stack traces but also hurt performance and will likely need to be disabled for release. We can perhaps turn them on conditionally when debug logging is enabled.

7) Along with various known issues mentioned in the megacommit, there will certainly be lots of other broken things. Feel free to create new GitHub issues for any bugs you find, being sure to specify that they're about the async DB branch.

**Finally, be aware that I will likely rebase this branch before merging it into master (in order to keep a sane commit history, avoid breaking git bisects, and keep upgrade steps as efficient as possible), so if you base any work on it, be prepared to [handle the rewind](https://www.kernel.org/pub/software/scm/git/docs/git-rebase.html#_recovering_from_upstream_rebase). Apologies in advance.**

**Comment by dstillman** [comment]
The bulk of promisification work is now complete (with [a few big issues remaining](https://github.com/zotero/zotero/issues?q=is%3Aopen+milestone%3A5.0+async), plus a few minor things that aren't on that list), so I'm renaming the ```async_db``` branch to ```api_syncing```, since that's the central work on it going forward. (Really this is just the new master, but I don't want to merge to master until we're sure the DB upgrades steps are set, since a handful of people ill-advisedly try to run that.) I'll post more on zotero-dev when we're closer to a release.

**Comment by retorquere** [comment]
Should I also be looking at the async-translators branch?

**Comment by dstillman** [comment]
No, that's been merged. (I just deleted the one on here.) Translation is still broken, but hopefully @simonster will get to that soon.

**Comment by dstillman** [comment]
The api_syncing branch is now the master branch, so feel free to follow that for updates as we get closer to 5.0. (Syncing won't work on that branch yet, and it definitely shouldn't be used with a production data directory.)

**Comment by retorquere** [comment]
OK, so this is happening. Any news (hopefully positive) on the plugin API changes I requested? And is there a place where I can follow specifically when the translators in this branch work again?

**Comment by jlegewie** [comment]
Thanks for the update. What is the timeline for the 5.0 update?

**Comment by retorquere** [comment]
Have custom fields made it into 5.0?

**Comment by dstillman** [comment]
No — and they can't, because 4.0 will need to continue to sync for a while and would break with unknown fields. But the idea is for 5.0 to lay the groundwork for it to happen later, after a 4.0 sync cut-off.

**Comment by jlegewie** [comment]
An update on this would be great particularly with Deasyncification in https://github.com/zotero/zotero/commit/daf4a8fe4db46ed29de2babed79610a2522821df. Any idea on timeline? Is deasyncification final? Thanks!

**Comment by retorquere** [comment]
@dstillman I might have relevant experience for the kind of thing described in https://github.com/zotero/zotero/commit/daf4a8fe4db46ed29de2babed79610a2522821df ... I've just ran  few quick tests, and it looks like I can load/save a 3k (OK, OK, 2885) item database in approx 95/100 ms respectively on average. I can't say that the constraints I'm willing to work under fit your case though.

**Comment by dstillman** [comment]
@jlegewie I <a href="https://groups.google.com/d/topic/zotero-dev/efFuMEqLarY/discussion">posted</a> to the dev list with an update. Let's follow up there.

@retorquere Feel free to open a separate issue to discuss.
