### ISSUE TITLE
Zotero cannot deal with data directory paths that contain non-ascii characters on Windows

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#523]
Zotero stores the user-selected data directory path that it retrieves from `nsILocalFile.persistentDescriptor`. This is supposed to return ACString, which is meant to be treated as binary data (It doesn't store encoding information and is just an array of single-byte chars). Of course we receive it as a `string`, which is transcoded to UTF-8 (although it already seems to have been UTF-8). In any case, `á` turns into `Ã¡` and we can't really restore it back.

I'm not entirely sure why we're using `nsILocalFile.persistentDescriptor`. Supposedly it's needed to retrieve files on Mac, which is why we can't use `path`. What we might be able to do, is use `nsIPrefBranch.setComplexValue` and store the `nsiLocalFile` "object" itself. On Windows, this just seems to be the value of `nsILocalFile.path` (with correct encoding), which may just be the properly interpreted `nsILocalFile.persistentDescriptor`. I'm hoping that on a Mac it's whatever the `nsILocalFile.persistentDescriptor` would be.

**Comment by aurimasv** [comment]
Seems like we can use [nsIScriptableUnicodeConverter](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIScriptableUnicodeConverter) to convert ACString to AString and back again if needed. Assuming there's still any need to use persistentDescriptor

**Comment by dstillman** [comment]
We now use string paths for the data directory setting, so this is probably no longer a problem.
