### ISSUE TITLE
Saving of Reports in Standalone is broken

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero#545]
Likely a regression in 4.0.21 or 4.0.22
Generate report --> File --> Save
Use default settings and click OK. Dialog closes, but no file is actually saved. 
Reported here for OS X and Windows, confirmed on Widows:
https://forums.zotero.org/discussion/40664/unable-to-save-reports/#Item_1

Less critically, but likely related, same behavior for debug logs.

**Comment by bjohas** [comment]
Error is still persists in 4.0.26.2 (Zotero standalone, OS X).

**Comment by bjohas** [comment]
Issue still persists in 4.0.26.2 (Zotero standalone, OS X).

**Comment by adam3smith** [comment]
(issues are closed when they're fixed; otherwise please only post with patches or questions related to implementing patches).

**Comment by sbyrnes321** [comment]
In zotero 5 (beta) on windows, I can save reports just fine. (I followed the instructions in the first comment, and it worked.)

**Comment by dstillman** [comment]
Confirmed on macOS. Thanks.
