### ISSUE TITLE
Use %Documents%/Zotero Data as default data directory location

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#552]
Follow up from https://github.com/zotero/zotero/issues/551#issuecomment-57949989

**Comment by bwiernik** [comment]
I can confirm that folders placed in the root of the Users folder (or the root of the OS drive) on Windows 8 and 10 are retained through a system reset/refresh if the user chooses for files to be retained (but obviously not if they select to keep nothing).

**Comment by dstillman** [comment]
Closed by 79700969e15f604f3a05781287468d14d8f1936b
