### ISSUE TITLE
Permission denied exception in current Firefox Nightly

### ISSUE THREAD

**Issue by tobiasdiez** [zotero/zotero#570]
I use the current Nightly version of Firefox (36.0a1) and get on every page which I want to import the following error: 
(2)(+0000005): Translate: Detect using Embedded Metadata failed: 
string => Error: Permission denied to access property 'apply'
stack => @chrome://zotero/content/xpcom/translation/translate_firefox.js:430:59

There seems to be an error with the sandbox permissions.

**Comment by averissimo** [comment]
Commit 5c76347 seems to fix the problem in pubmed and google scholar in non-e10 mode (even in nightly). 

Maybe the issue can be closed?

ps. thank you very much Simon!

**Comment by tobiasdiez** [comment]
You are right, the problem seems to be fixed in google scholar. However on other pages the bug still persists (for example on arxiv or Physical Review Letters).
