### ISSUE TITLE
Confirmation dialog for remove from collection

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#582]
https://forums.zotero.org/discussion/42302/

**Comment by guitorri** [comment]
I have just been bitten by this. I accidentally pressed delete a couple of times (I thought the focus was elsewhere) and items were removed from one of my collections. They were not yet tagged and I cannot find them back by memory.

**Comment by rmzelle** [comment]
I call dibs on this one (hope to provide a fix in a few days).
