### ISSUE TITLE
Sort styles by display title

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#587]
Styles are currently sorted and displayed in alphabetical order by style ID. This doesn't always match the display title. E.g. http://www.zotero.org/styles/apa (American Psychological Association 6th edition) sorts after http://www.zotero.org/styles/antiquity (Antiquity). http://www.zotero.org/styles/lluelles (Guide des références pour la rédaction juridique 7e édition...) sorts under L

Also, ignore "The" prefix when sorting. E.g. http://www.zotero.org/styles/the-american-journal-of-cardiology

**Comment by dstillman** [comment]
This appears to have been done. (Articles aren't ignored, but that doesn't seem like a big deal.)
