### ISSUE TITLE
Add "More Styles" button to Document Preferences dialog

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#588]
Would open https://www.zotero.org/styles in the browser

For bonus points (and not as a substitute for the above), would show a text box where you would type in the name of the journal and it would display a short list of matching styles as suggestions from the repo, so you could select and import the style, all within the Document Preferences dialog.

(moving misclassified issue zotero/zotero-word-for-windows-integration#6)

**Comment by dstillman** [comment]
Addressed by https://github.com/zotero/zotero/commit/474420620ef3fc44b76f48b0f5bedd099fc37728
