### ISSUE TITLE
extensions.zotero.export.bibliographyLocale should default to environments locale

### ISSUE THREAD

**Issue by ronalde** [zotero/zotero#600]
When changing the environments (OS or users) locale, zotero should default to the same/appropriate zotero-locale. For instance, when I change the default locale of my Debian installation (`dpkg-reconfigure locales`) and select `"nl_NL.UTF-8"`, zotero's UI should change it's `extensions.zotero.export.bibliographyLocale` to `"nl-NL"`. Currently, the user has to find that carefully hidden option and appropriate value (and is even confronted with the "warranty void" warning when entering `about:config`). 

In my opinion, it would be even better if the `bibliographyLocale` could be set in the wordprocessors' plugin-ui, on a per document basis, defaulting to the documents (general) language.

**Comment by dstillman** [comment]
Bibliography locale [became a document option](https://www.zotero.org/blog/zotero-4-0-27-streamlined-saving-easier-bibliography-language-selection-and-more/) in 2015.
