### ISSUE TITLE
item type "web page" missing from drop-down menu in Mac standalone 4.0.23

### ISSUE THREAD

**Issue by JackDougherty** [zotero/zotero#606]
Thanks for all you do to improve Zotero. Here's a minor glitch that I haven't seen reported anywhere.
In standalone for Mac 4.0.23, item type "Web Page" is missing from the drop-down menu, as shown in screenshot.
![zotero_and_ontheline_and_images](https://cloud.githubusercontent.com/assets/649719/5711704/7fd6f69e-9a7a-11e4-91f6-423130994da9.png)

**Comment by simonster** [comment]
See #571

**Comment by dstillman** [comment]
For lots more context, see https://forums.zotero.org/discussion/22041/what-type-for-a-web-site/#Item_13 and beyond

**Comment by JackDougherty** [comment]
Thanks for clarifying.
