### ISSUE TITLE
Merge identical attachments when detecting duplicates

### ISSUE THREAD

**Issue by simonster** [zotero/zotero#61]
http://forums.zotero.org/discussion/22025/merging-documents-zotero-303/

A potential pitfall here is that many websites timestamp the PDF, so the first page won't be identical, even if subsequent pages are and the content is the same. We might want to come up with a good heuristic to detect equality in these cases. One option would be to use pdftotext or pdf.js. Another option would be to assume that attachments with the same name are identical.

**Comment by gagarine** [comment]
Using the name + the size off the pdf should works no? Or the timestamp can change the size of the PDF?

**Comment by KarlHegbloom** [comment]
SHA1 or MD5 perhaps?

**Comment by KarlHegbloom** [comment]
Timestamp as in operating system filesystem modified time won't change file
size. If I edit annotations inside two different copies,  it is possible
for the file sizes to be the same. That is why I suggest using a hash
function to compare them.

**Comment by aurimasv** [comment]
MD5 would be sufficient for the simplest merge, but see what Simon says above
>some sites (e.g. Sage Publications) date-stamp every page

We also have to take into account highlighting embedded notes (if both have them, we shouldn't discard one, but if only one has notes/highlights, we could throw out the one without notes).

I think looking at text content is not a bad idea. We could identify pdfs as the same if they are >95% identical by text content. That could account for timestamp and preface pages that a lot of publishers attach. Not sure exactly which one we would pick, but probably it doesn't really matter. Maybe the longer one.

**Comment by aurimasv** [comment]
Then again, we have things like PubMed central pdfs (working drafts in general, which I think are also published on arxiv) vs publisher pdfs, which are nearly identical as far as content goes. We could maybe pick one with more columns.

We would do this detection before the merge and show user what will happen, allowing them to decide the final action.

This doesn't have to work perfectly right away either. We'd start will the least aggressive and turn the dial up. So starting with MD5 is good. The important hurdle here is UI. We should never do this without giving the user a chance to keep the attachment.

**Comment by KarlHegbloom** [comment]
I think merge when they are identical,  keep both when they are not. Err on
the side of caution with automated processes that might discard a file
somebody worked on. I wonder if there's a diff tool for PDF? There is for
XML and of course for text.  Maybe create a note attachment with the
contents of:

pdftotext file1.pdf - > /tmp/blah/file1.txt
pdftotext file2.pdf - > /tmp/blah/file2.txt
(cd /tmp/blah/; diff -u file1.txt file2.txt)

Perhaps ensuring that file2 is the newer.  /tmp/blah should be a unique per
user directory per normal conventions. That only works when the document is
a new pdf or has OCR text inside,  and only if pdftotext can see
annotations. A special purpose pdfdiff would be better if it exists.

**Comment by KarlHegbloom** [comment]
https://github.com/vslavik/diff-pdf

**Comment by KarlHegbloom** [comment]
Okay I just did a quick survey. In Ubuntu, there is both diffpdf and
diff-pdf. Neither one displayed the addition of a highlight annotation from
one copy to the next.  pdf-diff knows they differ but it's diff output
doesn't display the addition of a highlight annotation. diffpdf thinks they
are identical. I think a custom solution using the same javascript library
that is used to extract annotations will be required.

**Comment by KarlHegbloom** [comment]
Wow.  I just ran it again... diffpdf does show the added highlight
annotation.  I must have run it with the wrong command line before. Doh.
diff-pdf does not display the annotation in the big display but does in the
thumbnail.

**Comment by adam3smith** [comment]
> We should never do this without giving the user a chance to keep the attachment.
FWIW, I disagree with this. MD5-equivalent duplicates should just get deleted on merge. It's more tricky as we branch this out to be more forgiving, but why would anyone want the same file twice attached to the same item?

**Comment by aurimasv** [comment]
Sorry, I think I meant it for UI consideration for future criteria. MD5 is a pretty solid reason to delete.

**Comment by bwiernik** [comment]
Can a preview of the two files be displayed side by side in the UI? At least the first page?

**Comment by KarlHegbloom** [comment]
In the case where multiple users might annotate a PDF it would be nice if
the system will automatically append the appropriate suffix for the persons
name, and also if the person annotates the PDF, then a noticeable flag
should be placed automatically on the first page to make it obvious when
you view it. I think that it should also merge all of the annotations into
one, so that if you have a group collection, send it to your tablet,
annotate add notes, then pull it from your tablet, and someone else did the
same thing, then when you put it on your tablet another time, the other
person's comments are in there too. Obviously this only makes sense for
shared folders and perhaps it should be a setting on the folder?

**Comment by qwerty** [comment]
I would place as first version a manual flag of the PDF in the merging window, so that the user can manually choose whether to keep both the PDFs or to leave just one. This will already be an added value compared to the current workaround that you have to do ([Zotero forums](https://forums.zotero.org/discussion/21120/delete-duplicates)).
