### ISSUE TITLE
Glitch in item count in the right-hand pane

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#611]
Not exactly how this happened. I right-clicked Trash and hit Empty and Zotero may have not loaded the item list yet by the time the Trash was emptied (I can't really reproduce this).

![item-count-glich](https://cloud.githubusercontent.com/assets/1381759/5793171/942db25c-9eff-11e4-96ae-58e65e654d69.png)

**Comment by aurimasv** [comment]
Reported on the forums https://forums.zotero.org/discussion/49707/

**Comment by dstillman** [comment]
No recent reports of this
