### ISSUE TITLE
ISI Web of Knowledge records are not saved, but refs citing them are

### ISSUE THREAD

**Issue by chtfn** [zotero/zotero#613]
I use [Web of Science](http://apps.webofknowledge.com) for most of my article research, and the connector (4.0.25.2) does not save the record properly when using the "save to zotero" icon in Firefox (35.0).
Instead of saving the actual record, it saves all the publications that cited this record (listed in the right pannel on the website), sometimes resulting in a large series of unwanted publications in the library.

**Comment by dstillman** [comment]
Bug reports should go to the [Zotero Forums](https://forums.zotero.org), not here. Also be sure to include an example URL or search term.

**Comment by chtfn** [comment]
Thank you Dan. I forgot about that. Here it is: https://forums.zotero.org/discussion/45778/bug-isi-web-of-knowledge-records-are-not-saved-but-refs-citing-them-are/
