### ISSUE TITLE
rft.pages not supported ?

### ISSUE THREAD

**Issue by jajm** [zotero/zotero#631]
Hi,

it seems than rft.pages in COinS is not supported by Zotero.

I tested with the following span (notice rft.pages=186 near the end)

    <span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.title=Climate+change+and+groundwater&amp;rft.btitle=Climate+change+and+groundwater&amp;rft.isbn=978-1-86239-235-9&amp;rft.issn=&amp;rft.aulast=&amp;rft.aufirst=&amp;rft.au=+&amp;rft.pub=Geological+Society&amp;rft.date=2008&amp;rft.pages=186" class="Z3988"></span>

and the number of pages is not retrieved in Zotero.

Am I missing something ?

**Comment by aurimasv** [comment]
You're looking for rtf.tpages http://ocoins.info/cobgbook.html

**Comment by dstillman** [comment]
http://ocoins.info/cobgbook.html

**Comment by jajm** [comment]
Oh, ok thanks :-)
