### ISSUE TITLE
Complete content-type migration for CSL styles

### ISSUE THREAD

**Issue by rmzelle** [zotero/zotero#633]
As we discovered in https://github.com/validator/validator/issues/30, Zotero still registers CSL styles as "text/x-csl" in the local file system, at least on Windows, even though Zotero started to switch to "application/vnd.citationstyles.style+xml" several years ago.

Outdated documentation, mentioning "text/x-csl":
https://www.zotero.org/support/dev/citation_styles
https://www.zotero.org/support/dev/client_coding/building_the_standalone_client

Related error report:
https://forums.zotero.org/discussion/27577/validatornu-io-error

We might want to wait with addressing this until I succeed in registering the "application/vnd.citationstyles.style+xml" content type with IANA.

**Comment by rmzelle** [comment]
Oops, duplicate of https://github.com/zotero/zotero-standalone-build/issues/36.

@dstillman, wouldn't it be preferable to register the content-type for Zotero for Firefox as well? Otherwise you can't double-click styles on the hard drive to install them, right?

**Comment by dstillman** [comment]
> wouldn't it be preferable to register the content-type for Zotero for Firefox as well?

There's no installer/Info.plist under our control for Firefox.

> We might want to wait with addressing this until I succeed in registering the "application/vnd.citationstyles.style+xml" content type with IANA.

No, no reason to wait. A registration doesn't make a difference in terms of usage.

**Comment by rmzelle** [comment]
> No, no reason to wait. A registration doesn't make a difference in terms of usage.

I just thought we might end up with a different content type. "application/vnd.citationstyles.style+xml" is already quite established, though, and nobody on xbiblio-dev ever complained about it, so I guess we'll stay with it unless IANA objects.

By the way, do you think there is any value in using "application/vnd.citationstyles.locale+xml" for CSL locale files, or is the added benefit minimal since they are already readily identifiable as XML due to their ".xml" extension?

**Comment by dstillman** [comment]
> By the way, do you think there is any value in using "application/vnd.citationstyles.locale+xml" for CSL locale files

Using where?

**Comment by rmzelle** [comment]
APIs for generating citations/bibliographies where you can supply your own locale files? Locale file validation?

Anyway, I guess the use case is not as obvious as for CSL styles.
