### ISSUE TITLE
field „extra“ ~ variable „note“?!?

### ISSUE THREAD

**Issue by nitsnatsnok** [zotero/zotero#635]
In zotero there’s a field called „extra“, but the underlaying variable is named „note“ – this is quite confusing and not really consistent. For the sake of usability please change to one single denomination, preferably „extra“ (cf. the variable „annote“ which can be confused). Thank you!

**Comment by gracile-fr** [comment]
Zotero and <a href="http://citationstyles.org/">CSL</a> are two different projects (with strongs links, though). CSL is used by many others programs, and I doubt that the CSL "note" variable will be renamed. As for the zotero "Extra" field, it has the advantage of avoiding confusion with zotero's yellow sticky notes.
*Anyway, please use the Zotero forums for questions, feature request or bug reports. This tracker is reserved for developer use.*

**Comment by fbennett** [comment]
(what @gracile-fr says above, but as I've written this ...) I know it can be confusing at first, but the two values are from completely separate namespaces, maintained by independent projects. It's not really possible to merge them. The Zotero database field name for it is "extra"; "note" is the field name in the separately maintained CSL schema, to which it maps. There is a full description of the mappings [here](http://aurimasv.github.io/z2csl/typeMap.xml).

**Comment by nitsnatsnok** [comment]
ok, i get it now, thank you for explaining and especially for the very useful link!
