### ISSUE TITLE
preferences entry for UI language

### ISSUE THREAD

**Issue by nitsnatsnok** [zotero/zotero#636]
As described in https://www.zotero.org/support/supported_languages, it’s possible to change the UI language of zotero in about:config. As this way is not really convenient, please add the possibility to choose the language in the (general?) preferences, e.g. with a simple dropdown menu. Standard entry should be „system language“, and beneath all the languages available. Thanks!

**Comment by gracile-fr** [comment]
*Please use the Zotero forums for questions, feature request or bug reports. This tracker is reserved for developer use.*

[If you need to change the UI language often, use the <a href="https://addons.mozilla.org/en-US/firefox/addon/quick-locale-switcher/">Quick Locale Switcher</a> add-on (for Firefox). If you use another language for your citations and bibliographies, use the <a href="https://addons.mozilla.org/fr/firefox/addon/zotero-bibliography-locale-swi/">Zotero Bibliography locale switcher</a>. See also : https://forums.zotero.org/discussion/45805/ ]
