### ISSUE TITLE
Move shortcut keys prefpane to tab of Advanced

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#646]
Very few people likely use them, and even fewer have the need to customize them. And we could use the space.

**Comment by gracile-fr** [comment]
@dstillman That seems easy enough for me, but… I can't align the textbox with the text: cf. the red lines added to the <a href="http://imgur.com/sTMMcRH">screenshot here</a>. Any ideas?

**Comment by aurimasv** [comment]
Adjust this https://github.com/zotero/zotero/blob/4.0/chrome/skin/default/zotero/preferences.css#L239

**Comment by gracile-fr** [comment]
oh! thanks aurimas!
