### ISSUE TITLE
Zotero in Firefox calling incorrect callbacks

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#647]
On http://www.dlib.org/dlib/january15/assante/01assante.html the DOi translator displays only one result in the selection dialog, while the Chrome add-on displays a handful.

Looking a bit into this, I can see that the [DOI itemDone callback](https://github.com/zotero/translators/blob/master/DOI.js#L108) is being called for all DOIs on the page, but the `DOI` variable in the scope for all of the callbacks is that for the last DOI on the list. This leads to only one DOI being stored in the `items` object. From the translator side, it looks like everything should be working fine (i.e. closures are in place to avoid this exact problem).

Beyond that, I'm having trouble tracing this through all the wrappers, proxies, content forwarders, and asynchronous execution. I'm still working on it, but maybe @simonster can fix this faster.

Re https://twitter.com/27point7/status/569957784659341312

**Comment by zuphilip** [comment]
Any news on this issue? Is there still someone working on it?

**Comment by dstillman** [comment]
This seems to be fixed.
