### ISSUE TITLE
for each in loops deprecated

### ISSUE THREAD

**Issue by simonzack** [zotero/zotero#656]
I'm getting a lot of these in the console:

```
JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
```

Code:

```
for each(var node in nodes) {
```

translators/rdf.js

**Comment by dstillman** [comment]
Thanks — we're aware of this. Note that this is in the Firefox beta only, not in the current release version of Firefox. It will be addressed by the time Firefox 37 is released.

**Comment by dstillman** [comment]
Closing this. It seems these are only deprecated, not removed, and only logged in UI code, where we've now removed most of these. Unless support for these loops is removed entirely, we can ignore this and try to gradually phase them out as we rewrite only code.

**Comment by dstillman** [comment]
Well, we fixed the ones in the UI code in the client itself. They still exist in translators, and I guess those are logged to the console. I think @simonster was considering bulk-converting those. I'll leave this open until those are addressed.

**Comment by adomasven** [comment]
Note that [we still have code](https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/translation/translator.js#L209) in the codebase which addresses this in translator code. There are no instances of `for each` in translators at the moment, but we should keep the code until a [travis warning](https://github.com/zotero/translators/pull/1156) is added on the translator repo

**Comment by zuphilip** [comment]
@adomasven Travis test should be active now and fail when deprecated `for each` codes in translators are trying to re-introduce.
