### ISSUE TITLE
[Beta] Show Zotero icon in windows with "toolbar=no"

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#669]
E.g. double-click an image in [one of the Artstor collections](http://webcache.artstor.org/library/#3%7Ccategories%7C1034602260%7C%7CARTstor20Collections2026gt3B20Ezra20Stoller20Archive2028Esto292028313438313229%7C%7C%7C)

Firebug is able to position a button next to the location bar, so we should be able to as well.

Edit: to be clear, I mean the former "URL bar icon". What are we calling it now?

**Comment by dstillman** [comment]
The "Save to Zotero button", I think, or the "save button" if we're in a hurry.

**Comment by dstillman** [comment]
No more Zotero for Firefox
