### ISSUE TITLE
Upgrade PDF tools

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#688]
Unfortunately, because of the temporary issue addressed by https://github.com/zotero/zotero/commit/40b349edcae23fc816bab8bf0e350861c96ccd76 (and fixed server-side), some users will be stuck with broken PDF tools, so we should probably upgrade them for everyone. Assuming pdf.js isn't up to the task yet, we have to decide:

1. When to prompt for the upgrade (assuming we don't do it automatically)
1. Which version of Xpdf or Poppler to send
1. Whether I remember the steps necessary to customize the binaries on various platforms

For Standalone, we should probably just remove the pref installer altogether and bundle the relevant binaries.

The upside is that I believe later versions of pdftotext can handle files that ours doesn't.

**Comment by dstillman** [comment]
Automatic background installation for people who already have the tools installed would be easiest, but I guess we need to ask in case they're on a mobile connection? On the other hand, these days 2MB is a handful of web pages...

**Comment by aurimasv** [comment]
How is bundling the binary (or even automatic installation of the binary)
going to work with extension signing. I assume Mozilla is not going to sign
this blindly (or at least shouldn't according to what they want to
accomplish).

**Comment by dstillman** [comment]
Bundling would just be for Standalone, but I'm not concerned about Mozilla blocking Zotero.

**Comment by dstillman** [comment]
(To clarify, I'm concerned about false positives from the automated scanner delaying releases (though we should know ahead of time as long as the scanner code is available), but not their blocking Zotero after a review — and I'd like to think we would get on a whitelist if that started happening.)

**Comment by dstillman** [comment]
Anyway, thinking about this more, I think we should just have the translator/style repo send the latest (hard-coded) PDF tools version number in the daily response. If the client has an older version installed, it should download the new version in the background and move it into place. We could show a prompt before installing, but it's probably not necessary if you're set up to get potentially hundreds of KBs of translators at a time anyway — and we're going to be doing this possibly once, assuming pdf.js eventually becomes sufficient.

**Comment by dstillman** [comment]
Automatic upgrading added in d6e19a9f25cb779dd486d0c6c1a69d545dde5712

Now just need to create new builds and roll out a hotfix.
