### ISSUE TITLE
Problems pasting zotero URLs in editor

### ISSUE THREAD

**Issue by kalliopeargentina** [zotero/zotero#697]
When I paste in word or any other software zotero URLs are pasted  and all links work properly. The problem is when I paste this in Zotero´s editor, all zotero protocol urls are getting erased:
```
<!-- Begin Cita ZK -->
<a href="zotero://report/items/0_X7I4G5GT/html/report.html" 
title="A new history of anthropology">(Kuklick 2008)</a> 
<a href='zotero://select/items/0_X7I4G5GT'>(Zotero)</a>
 <a href='http://zotero.org/users/933006/items/X7I4G5GT'>(Website)</a>
 <a href='zotero://open-pdf/0_8JXBMSBB/1'>(pp 1)</a>
<!-- End Cita ZK -->

```
Gets pasted as:

```
<p><a title="A new history of anthropology">(Kuklick 2008)</a>
 <a>(Zotero)</a>
 <a href="http://zotero.org/users/933006/items/X7I4G5GT">(Website)</a>
 <a>(pp 1)</a></p>

```

For a discussion about this issue and the problem to paste quick copy translator output as HTML

https://forums.zotero.org/discussion/43030/quick-copy-export-translator-html-code/

**Comment by dstillman** [comment]
Should be fixed now in the latest <a href="https://www.zotero.org/support/dev_builds">4.0 Beta</a>. Try it out and let me know if it works for you.

**Comment by kalliopeargentina** [comment]
I couldn´t install beta version in this machine but what I did was to replace editor_plugin from the paste plugin folder in the JAR.  And I performed several tests. The scenario that worked was that where I pasted the links in the zotero HTML editor then went back to normal view, copied it again and repasted it. If I copy and paste this directly (as specified in the forum post) it doesn´t work for me.  I am using zotero standalone.

![image](https://cloud.githubusercontent.com/assets/3958383/7100474/38b3902c-dffa-11e4-86c5-d2e3b0f7cdb4.png)

Here is a sample code generated from the translator that I´am using:

```HTML
<p><a href="zotero://report/items/0_49C39C6M/html/report.html" 
title="El queso y los gusanos: el cosmos, según un molinero del siglo XVI&#13;">(Ginzburg et al. 1997)</a>&nbsp;
<a href='zotero://select/items/0_49C39C6M'>(Zotero)</a>&nbsp;
<a href='http://zotero.org/users/933006/items/49C39C6M'>(Website)</a>&nbsp;
<a href='zotero://open-pdf/0_ZVTS8UUD/1'>(pp 1)</a></p>

```

I  also tried to enclose this with `<html><body>` tags as suggested in a forum post but the result was the same.

Anyway I´ll wait for version 4.0.27 to perform the test again  just in case there where other files that where modified in other issues that could affect this, but I thought that I should let you know.

**Comment by dstillman** [comment]
Standalone caches files, so that won't work without additional steps. What you describe was the previous behavior — pasting from other Zotero notes was fixed over a year ago in #452.

**Comment by kalliopeargentina** [comment]
Ok, thanks!!

**Comment by kalliopeargentina** [comment]
I tested it in another computer. Works ok! thanks again!
