### ISSUE TITLE
Rename tests to *Test.js

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#701]
And allow fooTests.js to be run with `./runtests.sh foo`.

This avoids having lookup.js and lookup.js in editors.

**Comment by aurimasv** [comment]
maybe `.test.js`? This would make things like `itemTreeView.test.js` clearer I think

**Comment by aurimasv** [comment]
Also, how do we want to name tests within `data`, `connector`, etc. directories?

**Comment by dstillman** [comment]
I think .test.js is sort of unseemly, and there won't necessarily be a 1-to-1 mapping between a source file and a test, but I was going to say that fooTest.js was also be a possibility. (PHPUnit uses fooTest.php.)

**Comment by dstillman** [comment]
> Also, how do we want to name tests within `data`, `connector`, etc. directories?

I started to create some tests for data/* files (search.js) on api_syncing, and I wasn't going to bother with the prefix. I'd love to have code coverage info, but I'm not interested in formal unit testing of every function such that we would need to replicate the source file hierarchy exactly. I'm more inclined to just group tests thematically, and I expect we'll have a mixture of unit tests and integration tests (or whatever the formal term is). So searchTest(s).js might have tests for both creating a saved search via code and also, say, opening the search window and saving a search.
