### ISSUE TITLE
Creating the possibility to launch a dedicated instance of firefox for zotero [plugin] [standalone]

### ISSUE THREAD

**Issue by goyou** [zotero/zotero#702]
Hello,

I think  Zotero as a Firefox  extension is cool because it is easy to install and to allow it to access the web. Even If you don't have administrative rights on your computer.

Creating a standalone version will give some usage agreement but you will lost this advantage.

I don't know if it's the right place for asking it but I think it will be cool to have a firefox plugin for example, that allows you to create a desktop shortcut that launches a single instance of firefox, with zotero opened. And if you launch firefox from another shortcut you will have another instance of firefox, for surfing the web.

It will look as if you have a clone of firefox, like having two different versions, one dedicated to zotero and one dedicated to surfing.

(maybe it's possible to do it only using bash scripts ???)

Thanks for your attention

**Comment by aurimasv** [comment]
This is not really the place to discuss new features. Please post to the forums.

I'm not really clear on what issue you are trying to solve, so it's not clear to me why Zotero Standalone is not sufficient for your needs. If Zotero Standalone is, in fact, somehow insufficient, Zotero in Firefox can be launched in a dedicated tab (there's a button right next to the sync button to do this).

In any case, please follow up on Zotero forums and describe in more detail the problem you're experiencing.
