### ISSUE TITLE
% characters in url fields break bibtex references on export

### ISSUE THREAD

**Issue by arejensen** [zotero/zotero#708]
The % character is used for comments in LaTeX. 
When Zotero exports bibtex references, and a url field contains a % character, the reference will break a LaTeX document if the reference is included *if* the bibliography style supports the use of url fields.
I have reprodused the issue with an MWE using natbib with one style using url fields (plainnat) and one that doesn't (apalike). The first ends up with overflowing fields (due to the url field being read, but never closed), while the second one is fine.

Below is an example of the problem:

```latex
@article{pelletier_associations_2001,
	title = {Associations {Among} {Perceived} {Autonomy} {Support}, {Forms} of {Self}-{Regulation}, and {Persistence}: {A} {Prospective} {Study}},
	volume = {25},
	issn = {0146-7239, 1573-6644},
	shorttitle = {Associations {Among} {Perceived} {Autonomy} {Support}, {Forms} of {Self}-{Regulation}, and {Persistence}},
	url = {http://link.springer.com/article/10.1023/A%3A1014805132406},
	doi = {10.1023/A:1014805132406},
	abstract = {snipped},
	language = {en},
	number = {4},
	urldate = {2015-04-28},
	journal = {Motivation and Emotion},
	author = {Pelletier, Luc G. and Fortier, Michelle S. and Vallerand, Robert J. and Brière, Nathalie M.},
	month = dec,
	year = {2001},
	keywords = {autonomy support, Clinical Psychology, Developmental Psychology, persistence, Psychology of Personality, self-determination theory, self-regulation, Social Psychology},
	pages = {279--306}
}
```

Notice the url field and how the % character makes the rest of the line a comment.

**Comment by aurimasv** [comment]
Thank you for reporting, but unfortunately this is not the right place. Please post this on Zotero forums https://forums.zotero.org/
