### ISSUE TITLE
Zotero.defineProperty() lazy mode doesn't work

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#714]
Getters defined with `Zotero.defineProperty()` with `lazy: true` are being run repeatedly and not replaced with the static value. It looks like doing `delete this[prop]` before `this[prop] = val;` fixes this when `defineProperty()` is called directly on an object (e.g., `Zotero.Items._primaryDataSQLParts`), but it doesn't work when it's called on a prototype (e.g., `Zotero.DataObjects.prototype.primaryFields`), because the getter is on the prototype. (`delete obj[prop]` might work, but that would also clobber the getter for other objects.) Not sure if there's a good solution here that works with inheritance.

/cc @aurimasv

**Comment by aurimasv** [comment]
A little more messy, but we can do the following
```
defineProperty = function(obj, prop, desc, opts) {
	if (typeof prop != 'string') throw new Error("Property must be a string");
	var d = { __proto__: null, enumerable: true, configurable: true }; // Enumerable by default
	for (let p in desc) {
		if (!desc.hasOwnProperty(p)) continue;
		d[p] = desc[p];
	}
	
	if (opts) {
		if (opts.lazy && d.get) {
			let getter = d.get;
			d.configurable = true; // Make sure we can change the property later
			d.get = function() {
				let val = getter.call(this);
				
                                // Redefine getter on this object as non-writable value
				delete d.set;
				delete d.get;
				d.writable = false;
				d.value = val;
				Object.defineProperty(this, prop, d);
				
				return val;
			}
		}
	}
	
	Object.defineProperty(obj, prop, d);
}
```

**Comment by dstillman** [comment]
Yeah, that looks good.

**Comment by aurimasv** [comment]
Feel free to commit that if you want. I won't be able to get to it until later tonight.

**Comment by dstillman** [comment]
Thanks!
