### ISSUE TITLE
translate._sandboxManager.sandbox.Array undefined in child translators

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#719]
@ https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/translation/translate.js#L263

Re https://github.com/zotero/translators/pull/871/files#r27721361 (DNB -> COinS -> looks for search translator)

**Comment by dstillman** [comment]
If this was still relevant, it was likely fixed by 5216f1188531627fd7543d2d149b72a9301622c5.
