### ISSUE TITLE
Items in My Publications are hidden sometimes

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#726]
After restarting Zotero they seem like they're gone. But when I add a new item to My Publications, they reappear. This is very cheeky behavior, to say the least.

**Comment by dstillman** [comment]
So cheeky that I can't reproduce it, in fact, but possibly fixed by b21e07d700ad10d904151a3ea2a36c78be797c7a

**Comment by stakats** [comment]
Yes, appears to be fixed now!
