### ISSUE TITLE
Can't add new styles

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#729]
Using the "+" button in Preferences->Cite->Styles. Console reports
  
TypeError: Zotero.HTTP.promise(...).when is not a function
    Zotero.Styles</this.install<@chrome://zotero/content/xpcom/style.js:218:21

**Comment by dstillman** [comment]
Depends on #529

**Comment by dstillman** [comment]
This has been working for a while. Actual bib output doesn't yet work.
