### ISSUE TITLE
[Async DB] Import/export fails

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#734]
Using a Zotero RDF export file. Seems like we're getting a little farther now since Simon worked on translation.

**Comment by dstillman** [comment]
This is a follow-up from ff7919553c1a8a984f48ee5247786362f742d1a7.

**Comment by stakats** [comment]
Now getting "File read operation failed" when trying to import Zotero RDF. This may be a regression?

**Comment by dstillman** [comment]
Call me crazy, but I think import is working too.

**Comment by stakats** [comment]
Exporting a collection produces an empty RDF file, e.g.

<rdf:RDF
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
</rdf:RDF>

Report ID: 1324321173, and I also have debug output.

**Comment by dstillman** [comment]
Your move, Takats.
