### ISSUE TITLE
Translation with tags generates error

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#735]
Looks like tags aren't yet handled properly by translation, e.g. https://books.google.com/books?id=KP_3AgAAQBAJ

Item imports with an error, sans tags:

Error: Unimplemented
Zotero.Item.prototype.addTags@chrome://zotero/content/xpcom/data/item.js:3331:8

**Comment by simonster** [comment]
@dstillman: Do you plan to implement this, or should I just use `addTag`?

**Comment by simonster** [comment]
Fixed by #753
