### ISSUE TITLE
arxiv.org translation reveals several translation problems

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#736]
Tried http://arxiv.org/abs/1409.7168 and found several problems. Not sure whether these constitute separate issues. In descending order from weird to prosaic:
* The item note is duplicated as a standalone note
* The PDF isn't attached
* The snapshot isn't attached

Note that none of these problems appear when translating this item using the current 4.0 release.

several errors generated:

Error: Item [object Promise] not yet loaded
Zotero.Exception.UnloadedDataException@chrome://zotero/content/xpcom/error.js:156:16

and

Translate: Translation using arXiv.org failed: 
message => Item [object Promise] not yet loaded

and 

Unhandled rejection:
Error: Not in transaction
Zotero.DBConnection.prototype.requireTransaction@chrome://zotero/content/xpcom/db.js:589:9

**Comment by simonster** [comment]
Fixed by #753.
