### ISSUE TITLE
Point of no return with CC license for My Publications wizard

### ISSUE THREAD

**Issue by fcheslack** [zotero/zotero#738]
1. click ahead to choose a CC license
2. change my mind and go back a page

I can now only proceed forward to "Choose a License"

**Comment by dstillman** [comment]
I'm not seeing that. Are you getting an error?

**Comment by fcheslack** [comment]
No errors

**Comment by dstillman** [comment]
I blame Linux.

**Comment by dstillman** [comment]
I can't reproduce on Linux either (though I do get an ugly horizontal scrollbar). Screenshot after clicking Back? And what checkboxes/radios have you selected?

**Comment by fcheslack** [comment]
Seems to actually be persistent. I can no longer progress any further than either "Sharing" or "Choose a License" depending on what is selected. This appears to be the case no matter what I check.

**Comment by dstillman** [comment]
After restarting Zotero?

**Comment by fcheslack** [comment]
Many times.
