### ISSUE TITLE
Feature Request: add Migration Manager

### ISSUE THREAD

**Issue by hyiltiz** [zotero/zotero#748]
Importing from Mendeley preserving the tags, notes, PDFs, annotations, forder structures as well as added date is seemingly a much requested feature, and due to Mendeley's buggy export, could only be resolved from their API.

I guess a Import Wizard could be implemented (along with the Import feature) in the gear, so that:

1. In step one, we could select the system we are migrating from;
1. In step two, we are provided with two methods: a) manual export then import or b) auto-migrate. Could be selected using a radio button. 
  1. In manual export then import, we are told based on that system what is the recommended way to export our database and to do that manually;
  1. In auto-migrate, we are provided with an interface where we could `locate` the filesystem folder where the previous database could be found, such as the Mendeley database folder. Go to Step four after finish.
1. In step three (when not using the auto import in the second step in the wizard but rather using manually export then import), provide an locate interface for the exported file(s) generated manually during step two. Go to Step four after finish.
1. Everything will be automatically imported to Zotero under a separate library (so that users could organize that later manually if necessary) and this is the end of the wizard.

Please refer to the feature request and discussions at the official Zotero users forum:
https://forums.zotero.org/discussion/28786/mendeley-import/

**Comment by dstillman** [comment]
This tracker is for developer use only. Please post all feature requests to the Zotero Forums, and technical discussions (e.g., discussion of actual coding issues) on <a href="http://groups.google.com/group/zotero-dev">zotero-dev</a>.

**Comment by hyiltiz** [comment]
Thanks! Moving to the zotero-dev then.

**Comment by dstillman** [comment]
Just to clarify, unless you're planning to implement this yourself and have code-level questions, this should stay on the forums, where the broader community can participate.

**Comment by hyiltiz** [comment]
I am not planning to implement this myself, since I am not that familiar with JS. So the forum is the only place appropriate? Maybe I should delete the post at the zotero-dev then.
