### ISSUE TITLE
In-client style search and installation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#767]
You should be able to install styles directly from the client without going to the styles page. Anywhere we display a style list in the client, there should be a button to get more styles, and that button should open a style installation dialog.

This will require the styles page to have an API, but that page has outgrown a purely client-side approach anyway.

**Comment by dstillman** [comment]
(Or perhaps speed up the styles page separately and then in the client just open a web view and intercept the click.)

**Comment by dstillman** [comment]
(I don't think there's any good reason we're not just showing the styles page in a web view in Standalone already, so that would be a good first step.)

**Comment by aurimasv** [comment]
I would definitely vote for option 1. It would be much more streamlined for the user _if_ the user knows the style he/she is looking for. If not, they should have the option to view the full list on the web page.

**Comment by dstillman** [comment]
Not sure what you mean. They're the same option, really. Just saying it might not make sense to reimplement this in XUL.

**Comment by dstillman** [comment]
XUL is basically in maintenance mode at this point, so we should be avoiding it as much as possible. For most new client dialogs, we should probably use HTML, local or otherwise. The main thing that's keeping us from doing so for local stuff (e.g., My Publications) is that we don't have any nice UI frameworks (e.g., Bootstrap) locally, but we could fix that by deciding on some. And if there's an existing web page anyway, as in this case, we can just make sure that it's responsive (in all respects) and use that.

**Comment by aurimasv** [comment]
I wouldn't even open a new window. Just a search box above/below the list with results popping up/down as we do in word add-on for citations

**Comment by aurimasv** [comment]
To be less distracting/cluttered, I would start with a button ("add style" or just "+") on bottom right. Clicking that would hide the button and make a search box, disabled "download" button, "view full list online" button, and "add from local file" buttons appear (from left to right, all buttons are just icons with hover tooltips). Typing on the search box would provide up to top 5 suggestions from the online API. Once selected (by Tab for top choice or down arrow + enter) you would click download button (maybe a second enter) to download the style.

**Comment by dstillman** [comment]
We could consider that if it could be made not to work in the various dialogs, but we need the web view part for Standalone anyway, because you definitely shouldn't need to download a style outside of Zotero in order to install it.

**Comment by aurimasv** [comment]
Certainly agree with that. My view of the ideal interface is described above, but of course baby steps.

**Comment by rmzelle** [comment]
> XUL is basically in maintenance mode at this point, so we should be avoiding it as much as possible. For most new client dialogs, we should probably use HTML, local or otherwise.

Is that documented anywhere? Is the long-term plan to recast the entire Zotero UI in HTML?

> And if there's an existing web page anyway, as in this case, we can just make sure that it's responsive (in all respects) and use that.

Maybe the page could be sped up with something like http://nexts.github.io/Clusterize.js/ ?

**Comment by dstillman** [comment]
> Is that documented anywhere? Is the long-term plan to recast the entire Zotero UI in HTML?

Long-long-term, we probably won't have a choice, since I suspect [browser.html](https://github.com/mozilla/browser.html) or something similar is the eventual future of Firefox.

In the meantime, there's [Mozilla XUL and Extension](http://people.mozilla.org/~roc/Samsung/MozillaXUL.pdf) (see the last slide, "The Future of XUL") and [a recent mailing list thread](https://groups.google.com/d/msg/mozilla.dev.platform/HDJl1iBifB8/1TG876POw8cJ) where they declared a moratorium on new XUL features. Firefox obviously has a ton of XUL usage that isn't going away anytime soon, but some new Firefox features (e.g., Sync setup) are being implemented as HTML. I'd guess that more transition work will wait for [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components).

For now, things that need to work like native dialogs have to be XUL, but things with more leeway can be done as HTML, which can be embedded basically anywhere in XUL.

> Maybe the page could be sped up with something like http://nexts.github.io/Clusterize.js/ ?

Yeah, if we want to keep a full list, we should probably use that. (It breaks Cmd-F, but so does not having a list at all.) If we just want to switch to an API-based search, we wouldn't need it. Personally I like the full list as a demonstration of the scope of styles, but I'm not sure how useful it is, particularly without Cmd-F. It also requires sending the full list, which at this point is very big, to the browser. If the page just loaded much faster and the search worked much more quickly, I'm not sure I'd care about the list.

In any case, the primary in-client interface should be search only.

**Comment by rmzelle** [comment]
Also, I'd almost be willing to give a kidney for having a more vendor-neutral distribution system for CSL styles. Basically I'd like to have a CSL-branded version of the Zotero Style Repository, available via a citationstyles.org subdomain. It should provide styles with the correct MIME type, have a snappy front-end to filter and search styles, and ideally provide style previews. A more flexible version of "search by example" (as we have with http://editor.citationstyles.org/searchByExample/ ) would also be very useful (especially if it works with references created with arbitrary metadata).

If you think there is any way we could collaborate on that, that would be great. (cc'ing @adam3smith, @inukshuk)

**Comment by aurimasv** [comment]
@rmzelle, what's your blood type?

**Comment by rmzelle** [comment]
Don't know, but I try to eat healthy.

I contemplated using GitHub pages and relying mostly on client-side JS, but even with a webhook and a server instance to push new styles I'd be missing out on previews, and a full server solution is way outside my comfort zone.

**Comment by aurimasv** [comment]
We should probably move this discussion out of this issue.

I think a CSL style repo API is in everyone's best interest. If that were available, each vendor could build branded UIs of their choosing, but in the end everyone would just fetch styles/style lists directly from CSL repo.

The preview is not as straightforward though, since the actual result may vary from vendor to vendor, so I'm not sure that CSL should be supplying that (unless, maybe, it could supply previous for various CiteProc engines).

I don't think the API can be built on top of github pages though.

**Comment by rmzelle** [comment]
Maybe create an issue in the "styles" CSL repo?

For APIs, there is http://wiredcraft.com/blog/static-rest-apis-on-github-pages/

**Comment by aurimasv** [comment]
>For APIs, there is http://wiredcraft.com/blog/static-rest-apis-on-github-pages/

You could do that for basic functionality, but it wouldn't work for things like searching.

**Comment by bwiernik** [comment]
@adam3smith Could we just ask Dan to set up a mirror of the Zotero Style Repository at https://citationstyles.org/styles with a CSL banner?
