### ISSUE TITLE
[papercut] Create linked files with drag and drop

### ISSUE THREAD

**Issue by mronkko** [zotero/zotero#77]
On OS X, command+option+drag in Finder creates an alias to a file. Using the same key modifiers when dragging a file to Zotero should create linked file. Also, cmd+option should change the mouse cursor similarly as it does in Finder

The modifiers on Windows and Linux are CTRL+Shift

I wrote added the paper cut prefix because the current behavior is not consistent with the operating system and because this is probably easy to fix.

**Comment by Olifair** [comment]
It is a pity that this has still not been implemented

**Comment by dstillman** [comment]
It has, which is why the issue was closed with a commit in 2013:

> The cursor effect doesn't work reliably anywhere other than on Linux,
> but external files can now be linked instead of stored with
> Cmd-Option-drag on OS X and Ctrl-Shift-drag on Win/Linux.

**Comment by Olifair** [comment]
Oh, sorry. I had searched a bit and not found that information. You are right that there is no cursor effect on Windows 10, I had tried shift and Ctrl separately, but not both together ... well, at least the information is now in this issue. Thanks for the good news.

**Comment by Sieboldianus** [comment]
I tested this in 2023 on Windows and indeed, if I use <kbd>CTRL+SHIFT+DRAG<kbd>, the file is added as a link and not imported. Great!
