### ISSUE TITLE
Support download parameters for downloading attachments

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#772]
We should support
- Referer header (e.g. https://forums.zotero.org/discussion/50036/zotero-connector-extension-for-chrome-cannot-get-pdf-from-httpprojecteuclidorg/)
- POST + parameters (I don't recall the example from the top of my head right now, but this exists)
- Captcha solving (this one might be quite difficult and it's not very widely needed) (e.g. https://forums.zotero.org/discussion/47644/no-attempt-to-download-pdf-from-aps-journal-website/#Item_29)
- Maybe other arbitrary headers, though I don't have an example that requires this in mind

Should not be terribly messy on 5.0 given that we're now using `options` to pass parameters to `Zotero.Attachments`

**Comment by psisquared2** [comment]
Earlier today I was trying to fix Project Euclid and now I have working code for the Referer problem, which was relatively straightforward to implement.

The Captcha problem no longer exists for the provided example, and I wouldn't be sure what the best way to tackle it anyways. For now I think it's best to leave it.

Do you have a particular example to test the POST problem on? If not, I'd soon make a pull request for the Referer solution.

Concerning arbitrary headers: What would be your suggested interface in the translator? Right now I use
`item.attachments[i].referrer = url;`
which is obviously limited to Referer issues. A more general option would be to pass an object of parameters, e.g.
`item.attachments[i].special_header = {Referer: url};`
which could then directly get passed on in attachments.js like
`Zotero.Utilities.Internal.saveURI(wbp, nsIURL, tmpFile, special_header);`
I guess POST + data would need an additional field in the attachment anyways.

**Comment by dstillman** [comment]
A `headers` property on `item.attachments[i]` and in the `options` objects passed to the Zotero.Attachments functions would be fine. We can ignore POST in the absence of an example.

**Comment by psisquared2** [comment]
This can be closed as SSRN is fixed as https://github.com/zotero/translators/pull/1560 was merged.
