### ISSUE TITLE
Zotero combo icons dispersed under more tools

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#773]
The new zotero combo icons are dispersed when they are under more tools ("Mehr Werkzeuge..." in German) when the windows for firefox is too small. E.g. when firefox fills only half of my screen, then:
![zotero-combo](https://cloud.githubusercontent.com/assets/5199995/8391860/3925d08a-1cd4-11e5-80f8-7d53fcf1a288.jpg)

FF 38.0.5 (de), Win 7, Zotero e868c758b66971c2eaa2c6cb289196f5b0e1ee87

**Comment by zuphilip** [comment]
In the current release version this looks e.g.
![zotero-combo-current](https://cloud.githubusercontent.com/assets/5199995/8391972/fb8bb1e0-1cd8-11e5-8402-016b94042c2d.jpg)

**Comment by dstillman** [comment]
OK, try that out and let me know if everything looks all right.

**Comment by zuphilip** [comment]
Yes, everything looks fine now:
![clipboard01](https://cloud.githubusercontent.com/assets/5199995/8406599/3c536d9a-1e5e-11e5-9d08-b3a80f352395.jpg)

Thank you!

**Comment by dstillman** [comment]
Great. Thanks for catching this.
