### ISSUE TITLE
Opening Firefox after Standalone breaks Zotero for Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#783]
If I open Standalone and then open Firefox, I consistently get an error when clicking on the Z button:

> Zotero Standalone was launched but is not accessible. If you experienced an error opening Zotero Standalone, restart Firefox.

If I start Zotero for Firefox in full mode first and then open Standalone, it continues to work after Standalone opens.

**Comment by aurimasv** [comment]
WFM on Windows 7
