### ISSUE TITLE
Import button should import PDFs

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#785]
Since we're displaying the button for all pages now, we should make it import PDFs as standalone attachments (for now anyway). We can also make it handle other content, like images (#40)

**Comment by dstillman** [comment]
It does this already...

**Comment by aurimasv** [comment]
Not for me https://youtu.be/oq5UVfMZ0Bc

**Comment by dstillman** [comment]
Does it if the snapshot pref is on.

**Comment by aurimasv** [comment]
Indeed. Then it should be independent of the pref. Perhaps it should also be independent of the PDF pref also

**Comment by dstillman** [comment]
This works as expected in the connectors.
