### ISSUE TITLE
Zotero 4.0.27 installation problems

### ISSUE THREAD

**Issue by Blaisorblade** [zotero/zotero#786]
Since a short while (I think a crash & update?) whenever booting Zotero standalone as installed, I get two issues:
- Upon startup, a warning: "You are on a custom Zotero build (4.0.27.SOURCE)". The warning keeps appearing after downloading and reinstalling Zotero. I saw a similar warning before update. I never did any custom Zotero build.
- The "Zotero" Menu lacks many items, including preferences. I can only get there from the Addon manager, clicking Preferences for addons that have one, and then navigating in the preference dialog (which also include general Zotero preferences, luckily).

**Comment by aurimasv** [comment]
Please report Zotero errors to Zotero forums. The GitHub tracker is for developer use only.

* https://forums.zotero.org/discussion/50345/you-are-on-a-custom-zotero-build-zotero-4027source-betterbibtex-broke/ and should be addressed with a new version of both Zotero Standalone and Better BibTeX

* https://forums.zotero.org/discussion/50380/zotero-menu-broken-mac-standalone/

**Comment by Blaisorblade** [comment]
Apologies, and thanks for the help!
