### ISSUE TITLE
PLOS screenshot is out of date

### ISSUE THREAD

**Issue by egh** [zotero/zotero#792]
The PLOS site has been updated since the screenshot displayed on: http://zotero.org/download/ 

It would be great if this could be updated. I have attached a new screenshot if you would like to use it.

Thanks so much for considering this, and for highlighting PLOS on your screenshot for download!
![zotero](https://cloud.githubusercontent.com/assets/22718/8605055/56c70be2-2637-11e5-87b4-c98deb626c66.png)

**Comment by egh** [comment]
You know, rethinking this, I kind of like that the old site lives on. But if you should ever need another screenshot, feel free to use that one. :)

**Comment by stakats** [comment]
Updated screenshot attached that matches the existing one's content and dimensions.
![firefox1](https://cloud.githubusercontent.com/assets/244886/8605537/025381e0-2654-11e5-8346-bd949da26813.png)

**Comment by stakats** [comment]
Thanks for bringing this to our attention!

**Comment by egh** [comment]
Thanks, Sean!

**Comment by egh** [comment]
Looks good!
