### ISSUE TITLE
Update website screenshots and icons

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#793]
Capture screenshot from home page
![capture-research-data](https://cloud.githubusercontent.com/assets/244886/8606253/62bbb2e2-2658-11e5-94dd-6e7f0cc5605f.png)

**Comment by stakats** [comment]
Safari icon from download page
<img width="16" alt="32-safari" src="https://cloud.githubusercontent.com/assets/244886/8606282/8a956d8a-2658-11e5-886b-7c95267e4612.png">

**Comment by stakats** [comment]
Firefox icon from download page -- not dramatically different, but still...
![32-firefox](https://cloud.githubusercontent.com/assets/244886/8606834/887f63b2-265c-11e5-9f64-151fc71c11af.png)

**Comment by stakats** [comment]
![firefox1](https://cloud.githubusercontent.com/assets/244886/8607383/81b84964-2660-11e5-8e47-0e31341906c1.png)

**Comment by stakats** [comment]
<img width="150" alt="retina save" src="https://cloud.githubusercontent.com/assets/244886/8607674/b28132fc-2662-11e5-8b9d-0d750b0a8686.png">

**Comment by stakats** [comment]
<img width="32" alt="compass" src="https://cloud.githubusercontent.com/assets/244886/8607747/3d74ea98-2663-11e5-8de1-8164b5be80ba.png">

**Comment by jryans** [comment]
I'm going to go ahead and say this seems done a long time ago... The website screenshots are vastly different now.
