### ISSUE TITLE
Localization : Zotero Style Preview/Editor

### ISSUE THREAD

**Issue by gracile-fr** [zotero/zotero#796]
csledit.dtd and cslpreview.dtd which were added in https://github.com/zotero/zotero/commit/f2ffc307283afcde9a6f5d6b57aae5fab17496b6 are not available on Transifex at the moment.
(and btw [styles.editor.suppressAuthor] (https://github.com/zotero/zotero/blob/4.0/chrome/locale/en-US/zotero/csledit.dtd#L3) is redundant with [zotero.citation.suppressAuthor.label] (https://github.com/zotero/zotero/blob/4.0/chrome/locale/en-US/zotero/zotero.dtd#L193))

**Comment by dstillman** [comment]
Added to Transifex. Thanks.

**Comment by gracile-fr** [comment]
These two files have not been updated from Transifex in the last relevant commit 535d3340e365caf31ec529cc3d081afb039cb2b0 [whereas they are localized at least in Chinese (China), Chinese (Taiwan), French (France), German, Icelandic (Iceland), Romanian (Romania), Slovak (Slovakia), Slovenian (Slovenia), Spanish (Spain), Swedish (Sweden), Turkish (Turkey), Ukrainian (Ukraine)].

**Comment by dstillman** [comment]
Fixed, thanks.
