### ISSUE TITLE
Localize connectors

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#798]
https://forums.zotero.org/discussion/50602/

Not sure what support, if any, the Chrome/Safari extension frameworks provide.

Putting this here because we should probably just add strings to the main Transifex project and copy them over to the connector repos in a script.

I can take care of adding the files to Transifex once there are en-US files in whatever the desired format is.

**Comment by bbbear2002** [comment]
Bump. I think this issue should be addressed. Thanks @dstillman

**Comment by dstillman** [comment]
Please don't bump issues.

**Comment by gracile-fr** [comment]
Chrome extensions can be localized with messages.json file : https://developer.chrome.com/extensions/i18n .
As for Safari extensions, there's no official method seemingly (<a href="http://stackoverflow.com/questions/27604429/multiple-language-safari-extension">here</a> and <a href="http://openradar.appspot.com/8788131">there</a>).

**Comment by adomasven** [comment]
This is being triaged in the zotero/zotero-connectors#58 issue, so I am closing it here
