### ISSUE TITLE
UI breakage when dragging between monitors with different scaling factors

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#799]
https://forums.zotero.org/discussion/50570/

(Tagging as upstream, but this doesn't happen in Firefox.)

**Comment by dstillman** [comment]
Looks like this is still an issue, and the fix is still to set layers.acceleration.disabled to false.

**Comment by Nio-av** [comment]
I think, that you have to add the following line to the file:
https://github.com/zotero/zotero/blob/master/defaults/preferences/zotero.js

`pref("layers.acceleration.disabled", false);`

Can anyone confirm that? And, if so, please include the fix?

**Comment by dstillman** [comment]
@simonster We should do this for 4.0.29.9 if possible.
