### ISSUE TITLE
Add an Item's bibtex key to the Info Panel

### ISSUE THREAD

**Issue by Erotemic** [zotero/zotero#802]
I'd like to request a feature where the bibtex key of an item that would be generated on File->Export Library (with BibTex) selected is added as a row in the Info tab. 

I find myself having to export my whole library to the .tex file and then searching for the name of the paper in the .bib file so I can find the bibtex key. It would make writing latex documents much easier if this feature were implemented. 

If someone can point me at where to start, I wouldn't be opposed to trying to implement it myself.

**Comment by dstillman** [comment]
This will happen in Zotero in a future version. For now, you can look at the third-party [Better BibTeX](https://github.com/ZotPlus/zotero-better-bibtex) plugin.

(Beyond that, please post feature requests to the forums or technical questions to <a href="http://groups.google.com/group/zotero-dev">zotero-dev</a>. We don't accept feature requests or bug reports here.)
