### ISSUE TITLE
Google Patents translator does not recognize https://patents.google.com

### ISSUE THREAD

**Issue by bisoldi** [zotero/zotero#804]
The Google Patents translator only recognizes patents served up under https://www.google.com/patents, however Google also has https://patents.google.com, which I believe to be the newer site design.  It's the same data, however patents.google.com wraps the layout in additional functionality and IMO lays out the patent in a cleaner (though similar) format.

E.g. https://patents.google.com/patent/US7853881B1/en?q=networks

Could another translator be written for this site?

**Comment by dstillman** [comment]
Unless you're contributing, requests and bug reports should generally go to the Zotero Forums, not GitHub.

This request is valid, but this is the wrong repo. Translators are here: https://github.com/zotero/translators
