### ISSUE TITLE
Zotero for Firefox may have zombie compartment memory leak when other addons installed

### ISSUE THREAD

**Issue by adbull** [zotero/zotero#810]
Zotero for Firefox seems to suffer from a [zombie compartment memory leak](https://developer.mozilla.org/en-US/docs/Zombie_compartments) when certain other add-ons are also installed. I think the problem lies with Zotero rather than the other add-ons, as I can only reproduce the bug when Zotero is present, and it only applies to pages which Zotero has a translator for.

To reproduce:
  * in Firefox 39.0, on a fresh profile, install Zotero for Firefox 4.0.27.5, as well as one of the following add-ons: 
     - GNotifier 1.8.9.1
     - Send to XBMC 2.3.0.1
     - maybe others?
  * in the first tab, open any website which causes the Save to Zotero icon to light up
  * in a second tab, open about:memory
  * close the first tab
  * in the second tab, click Minimize Memory Usage
  * once it's finished, click Measure
  * memory for the first tab will still be allocated under explicit / window-objects

Over time, this causes Firefox's memory usage to grow without bound.

**Comment by dstillman** [comment]
Thanks. We received another report of this last night and are investigating.

https://forums.zotero.org/discussion/50747/zotero-causing-firefox-to-leak-memory-like-crazy/

**Comment by adbull** [comment]
That's great, looks like the same issue. I've edited the top post to note that the problem seems to occur only with pages that Zotero has a translator for.

**Comment by adbull** [comment]
Simon's patch seems to fix this on my machine. Thanks!
