### ISSUE TITLE
Add DOI field to Magazine Articles

### ISSUE THREAD

**Issue by rolve** [zotero/zotero#815]
Some magazine articles have DOIs (example: http://dl.acm.org/citation.cfm?doid=2808213.2699415), so it would be nice to have support for that in Zotero.

(Btw, the translator for the ACM Digital Library imports these articles as journal articles. Maybe because magazine articles do not support DOIs.)

**Comment by gracile-fr** [comment]
(Please post feature requests (and report errors) to the Zotero forums. This GitHub tracker is for developer use only.)
There's a <a href="https://forums.zotero.org/discussion/15636/changes-to-fields-and-item-types-for-zotero-42-/#Item_0">thread about new fields</a>. As for your specific request, <a href="https://github.com/avram/zotero-bits/issues/1">DOI will probably be added</a> to all item types after Zotero 5.0.
