### ISSUE TITLE
HTML editor damages the URL input box

### ISSUE THREAD

**Issue by borisxm** [zotero/zotero#829]
It seems, that Zotero HTML editor called from the note editor is incompatible with the Firefox General/"Open new windows in a new tab instead" feature.

If this option is unchecked, then pressing an "HTML" button from built-in editor properly opens a separate window. But if this option is checked, then pressing an HTML button causes editor to be opened in the new tab instead, which is fine, but it hides URL input box even after editor is closed. Only closing of the "damaged" Firefox window restores the URL bar. It is also noticed, that "Customize" functionality are also frozen/broekn in this case.

How to repeat: open "Preferences", check the above mentioned option, open Zotero in the split view mode, locate a note, make sure it displayed on the right pane. Now press the "HTML" button, watch HTML editor opened in the new tab, close it by clicking on "Update" or "Cancel" button, notice, that URL bar is not restored.

This has been tested on Firefox 40, Ubuntu 14.04, x64.

**Comment by dstillman** [comment]
I think you must either have some other extension enabled or some other pref changed that affects this. "Open new windows in a new tab instead" has been the default setting in Firefox for years, and as far as I can recall it has never prevented the HTML view from opening in a separate window in a standard installation, nor does it for me.

**Comment by borisxm** [comment]
Correct, I've installed Zotero to a new profile and feature works as expected. The only suspect was the TabMixPlus, but disabling it had no effect. Disabling all extensions except of Zotero also had no affect.
Futher investigation revealed, that offending option named as "browser.link.open_newwindow.restriction" which described here: http://kb.mozillazine.org/Browser.link.open_newwindow.restriction
In my case it was 2, resetting it to 0 recovered the correct behavior. This is a very old profile and I do not remember why it was set to 2, but probably for a good reason.

**Comment by dstillman** [comment]
Do you have that backwards? Based on the description, it seems like 0 should be what breaks this, and it does for me — and 2 is the default. In any case, given that this is dependent on a non-default hidden pref, I'm not going to worry about this. (It also seems like a Mozilla bug, so if someone cares about this, they should try to create a simple non-Zotero test case using window.open() with "features" and submit that to Mozilla. I can give a pointer to the TinyMCE code that triggers this if necessary.)

**Comment by borisxm** [comment]
Yeah, numbers are reversed. I'm not sure if this setting was edited by hands, it might be some kind of popup-blocker extension installed in the past.
