### ISSUE TITLE
Zotero Standalone for FreeBSD

### ISSUE THREAD

**Issue by vasili111** [zotero/zotero#839]
Any plans to port Zotero to FreeBSD?

**Comment by dstillman** [comment]
I don't think this is something we'll support — even if people contributed code, I doubt we'd start building and supporting a FreeBSD version — so it would probably have to be done by someone else.

**Comment by henningninneh** [comment]
As a workaround: The windows binaries run just fine under FreeBSD with Wine. In principle, you should also be able to run the Linux binaries with Linuxulator (but I wasn't able to).
