### ISSUE TITLE
Clicking on another item loses unsaved text while cursor is in field

### ISSUE THREAD

**Issue by adunning** [zotero/zotero#840]
Under Zotero 4.0.28, if one follows the following steps, the edits made to a field will not be saved, without warning:

1. Edit the text of a field in an item (e.g. change the Book Title).
2. Click on another item in the library listing.

Workaround: one must click on another field in the current item or press return in order to save the modified text.

This might be a duplicate of #686.

**Comment by dstillman** [comment]
This works for me in Zotero for Firefox on OS X.

**Comment by adunning** [comment]
I've realized that it's something that appears (using Standalone) only intermittently, and is fixed by restarting Zotero. But it has happened to me on multiple occasions in the last month or so.

Installed add-ons, in case it matters, are Zotero Better Bib(La)TeX and ZotFile.

**Comment by adunning** [comment]
I haven't run into this again in the last couple of weeks; closing for now.
