### ISSUE TITLE
Stop the full Firefox pluging and only develop the standalone

### ISSUE THREAD

**Issue by gagarine** [zotero/zotero#843]
What the point to have two systems? Their are also hard to make them work together. Of course a plugin is needed to add a reference but it can add it directly the standalone app.

I know it's already possible today, but I think the documentation and code can be simplified if their is only one good way.

**Comment by dstillman** [comment]
We can discuss this, but you should post it to the Zotero Forums or <a href="http://groups.google.com/group/zotero-dev">zotero-dev</a>. This tracker is for developer use only.
