### ISSUE TITLE
CSL field "issued" in Extra is not translated correctly to CSL

### ISSUE THREAD

**Issue by retorquere** [zotero/zotero#845]
If I have this in the 'Extra' field of a reference:

```
{:issued:2014-12-31/2015-01-01}
```

Zotero.Utilities.itemToCSLJSON(item) translates this to

```
"note"=>"{:issued:2014-12-31/2015-01-01}",
...
"issued"=>{"date-parts"=>[["2001"]]}}
```

where I had expected it to translate to

```
"issued"=>{"date-parts"=>[[2014, 12, 31], [2015, 1, 1]]}}
```

(see http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#dates on date ranges)

**Comment by aurimasv** [comment]
The Extra field parsing is performed in citeproc-js atm. What you see in `Zotero.Utilities.itemToCSLJSON` is exactly* what's passed to citeproc-js from Zotero.

There is no issue currently filed to fix this, but parsing out values from Extra field is on the agenda (at least I have it in mind)

* except for ID value

**Comment by retorquere** [comment]
So I should file this as an issue against citeproc-js?

**Comment by retorquere** [comment]
I'm looking through Zotero.Utilities.itemToCSLJSON, but that doesn't look like it's part of the citeproc-js code. It references the Zotero internal API quite extensively.

**Comment by aurimasv** [comment]
No, it's not an issue with citeproc-js. It might be considered an issue with Zotero, but, technically, Zotero hasn't officially endorsed the Extra field format invented by citeproc-js.

@dstillman has agreed that we should support simple `CSL label: value` format in the Extra field, so that is likely to get added. I'm not sure if @dstillman would want to parse out `{:label:value}` format as well. Personally, I think we have a sufficient population using this format already, so the benefits of supporting it outweigh the costs.

**Comment by retorquere** [comment]
Alright, then I'll just temporarily work around it. Thanks for the feedback.

**Comment by retorquere** [comment]
The `label: value` should always be understood to be CSL variables then? I hadn't picked up on that; I thought the `{:label:value}` format was uniquely CSL. I'll have to think about that for a bit on where I handle that.

**Comment by aurimasv** [comment]
Followed up in #846

>The `label: value` should always be understood to be CSL variables then?

Only if the label is a CSL field.

**Comment by fbennett** [comment]
Both the line-entry and braced-entry forms should be recognized correctly in the processor now (as of [tag 1.1.133](https://github.com/Juris-M/citeproc-js/tree/1.1.133)). I've checked date ranges, and that also seems to be working now.

**Comment by bwiernik** [comment]
This issue can be closed.
