### ISSUE TITLE
Make API_URL and SYNC_URL available as config options

### ISSUE THREAD

**Issue by ralight** [zotero/zotero#849]
It would be very helpful if the API_URL and SYNC_URL options could be exposed (as advanced options/through about:config only if necessary). This will make it easier to use a dataserver hosted in a different place once extension signing hits.

Thanks for your consideration.

**Comment by dstillman** [comment]
Closed by https://github.com/zotero/zotero/commit/084f5a72df24912820724e8fe46b39b837deb554
