### ISSUE TITLE
Fix "this.registry<...> is undefined"

### ISSUE THREAD

**Issue by fbennett** [zotero/zotero#850]
There has been a long run of these errors (see below). The last of them was recently isolated to styles that make use of the CSL `first-reference-note-number` variable, and a fix for it was checked in on [July 30](https://bitbucket.org/fbennett/citeproc-js/commits/53990e9983d230629862009a83b22966d9d61e3d). Zotero 4.0.28.5 is using a release from July 28, so the bug is still live. It can be cleared by updating the processor.

[Aug 3rd 2015](https://forums.zotero.org/discussion/50951/restarting-work-on-an-old-paper-and-zotero-unable-to-sync-with-word/)
[Jun 8th 2015](https://forums.zotero.org/discussion/49840/1849152803-error-updating-document/)
[Apr 1st 2015](https://forums.zotero.org/discussion/48018/mlz-client-citation-style-list-error/)
[Aug 14th 2014](https://forums.zotero.org/discussion/39244/error-mlz-citation-processor-only-works-second-time/)
[Jul 14th 2014](https://forums.zotero.org/discussion/38371/citations-corrupted-and-other-issues-error-report-id-977223379/)
[Sep 27th 2013](https://forums.zotero.org/discussion/32169/error-zotero-thisregistryiddisambiggiveni-is-undefined/)
[Feb 18th 2012](https://forums.zotero.org/discussion/22029/error-report-858737348-making-citation-in-word/)
[Feb 9th 2012](https://forums.zotero.org/discussion/21832/error-while-trying-to-include-a-citatio-into-a-word-document/)
[Feb 9th 2012](https://forums.zotero.org/discussion/21817/zotero-has-stopped-working-after-firefox-v10-upgrade/)
[Feb 7th 2012](https://forums.zotero.org/discussion/21791/ms-word-addin-set-doc-preferences/)
[Feb 7th 2012](https://forums.zotero.org/discussion/21784/error-id-753695998/)
[Feb 4th 2012](https://forums.zotero.org/discussion/21714/error-this-entry-does-not-exist-anymore-in-your-zotero-database/)
[Feb 3rd 2012](https://forums.zotero.org/discussion/21689/urgent-failed-to-update-the-document-after-upgrade-pls-help/)
[Jan 6th 2012](https://forums.zotero.org/discussion/21215/insertation-of-citations-doesnt-work-any-more/)
[Jan 3rd 2012](https://forums.zotero.org/discussion/21167/word-addin-citation-problem-report-id1788723077/)
[Jul 30th 2011](https://forums.zotero.org/discussion/18959/zotero-standalone-stopped-working/)
[Jun 2nd 2011](https://forums.zotero.org/discussion/18225/error-thisregistrycitationregcitationbidc0-is-undefined/)
[Apr 26th 2011](https://forums.zotero.org/discussion/17728/formatregistry-undefined/)
[Apr 2nd 2011](https://forums.zotero.org/discussion/17333/problem-with-microsoft-word-2007-citations/)
[Mar 23rd 2011](https://forums.zotero.org/discussion/17028/zotero-experienced-an-error-updating-your-document-after-upgrading-to-21/)
[Feb 10th 2011](https://forums.zotero.org/discussion/16367/cant-add-or-refresh-citations-after-upgrade-to-b6/)
[Jan 9th 2011](https://forums.zotero.org/discussion/15832/updating-citations-in-word-document/)
[Jan 4th 2011](https://forums.zotero.org/discussion/15777/error-updating-openofficeorg-document-in-21b/)
[Nov 11th 2010](https://forums.zotero.org/discussion/15137/thisregistrycitationregcitationbyidc0-is-undefined/)
[Feb 1st 2010](https://forums.zotero.org/discussion/10916/word-plugin-error-thissessionstyle-is-undefined/)
[Jan 25th 2010](https://forums.zotero.org/discussion/10765/problems-syncing-with-windows-7/)

**Comment by dstillman** [comment]
Thanks. (4.0.28.4 and 4.0.28.5 were critical fixes, so it didn't get the usual release-time updates.)

**Comment by dstillman** [comment]
Included in 4.0.28.6, available now
