### ISSUE TITLE
Recent citeproc-js patches

### ISSUE THREAD

**Issue by fbennett** [zotero/zotero#854]
This issue applies to Zotero 4.0.28.7, which is using citeproc-js 1.1.58.

Two changes applied to the processor since the 1.1.58 release are bugfixes:
* `hg export 425257f12335` corrects the parsing of particles when combined with an articular (i.e. "Jr.", "III"). With the fix, the parser recognizes the entry order used in Chicago-style bibliographies, which should be (more) intuitive for users. Discussion with Emiliano Heyns and Nick Bart that lead to the change is [here](https://bitbucket.org/fbennett/citeproc-js/issues/183/particle-parser-returning-non-dropping).
* `hg export 5c0ca3c964dc` includes all date fields except "accessed" in internal "subsequent" cite forms used for disambiguation comparison. The change addresses the bug reported [here](https://forums.zotero.org/discussion/52758/disambiguation-enabled-when-not-needed-with-date--original-date/).

The changes above are reflected in citeproc-js tag 1.1.60.

**Comment by dstillman** [comment]
Updated for the next release — thanks.
