### ISSUE TITLE
copy bibtex to clipboard

### ISSUE THREAD

**Issue by fccoelho** [zotero/zotero#855]
This is a feature request. 

Many times I have wished Zotero would let me copy the bibtex records of selected references to the clipboard.

**Comment by dstillman** [comment]
You can already do this:

https://www.zotero.org/support/creating_bibliographies#quick_copy

Please post feature requests to the Zotero Forums. This tracker is for developer use only.

**Comment by fccoelho** [comment]
Quick_copy is not what I was talking about. But I'll post to the forums.
thanks

**Comment by dstillman** [comment]
OK. You'll have to clarify in the forums, because "copy the bibtex records of selected references to the clipboard" precisely what Quick Copy does.

**Comment by fccoelho** [comment]
Just for the record, I found out how to do it. I requires installing an
extra "BibTeX generic citation style", the full explanation is here:
https://github.com/willsALMANJ/Zoterodactyl/issues/3

On Tue, Oct 13, 2015 at 5:19 PM, Dan Stillman <notifications@github.com>
wrote:

> OK. You'll have to clarify in the forums, because "copy the bibtex records
> of selected references to the clipboard" precisely what Quick Copy does.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zotero/zotero/issues/855#issuecomment-147840333>.
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by dstillman** [comment]
And if you keep reading that thread, you can see that Will was mistaken about his recommendation:

> Ah, sorry about that. I think I misled you. I haven't used QuickCopy with BibTeX before. It was probably unnecessary to add that BibTeX generic citation style. I think what you want to use for "Default Output Format" is the entry just called "BibTeX" at the bottom of the list of options (under the "Export Formats" section of the drop down list rather than the "Bibliographic styles" one).

All you should need to do here is select BibTeX from the drop-down.
