### ISSUE TITLE
Firefox signing

### ISSUE THREAD

**Issue by wbt** [zotero/zotero#857]
As of FF41.0.2, Zotero (and several other useful extensions) now bear a warning in the Add-ons Manager that the add-on has not been signed, and [this post](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u) says such add-ons will be automatically disabled as of FF43.  

If this is already on your radar, apologies for the duplication.  If not, it's something that might become important!

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/51154/sign-addon-httpswikimozillaorgaddonsextensionsigning/
