### ISSUE TITLE
Recent issues in the translator framework

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#858]
Acting on behalf of @aurimasv's <a href="https://github.com/zotero/translators/commit/16ab9ed264dd173d7bd0631de9bfdaac0adda295#commitcomment-13922822">comment</a>: Recently some issues in the translator framwork occured. Some functions `.translate()` or `` are not working but some replacement may work. We temporarily fixed some of these in the translators to offer quick solutions. However, it should also be investigated what the actual reason is behind that and fix it.

1) In <a href="https://github.com/zotero/translators/commit/2c8885b50efc40ead3f42d81b44eb31b79ed1a7c">update of the Highwire 2.0 translator for Sage</a> the function
```
translator.translate();
```
was not working but the function
```
translator.getTranslatorObject(function(trans) {
        trans.doWeb(doc, url);
});
```
is working.

2) In <a href="https://github.com/zotero/translators/commit/16ab9ed264dd173d7bd0631de9bfdaac0adda295">update of the Summon 2 translator</a> the `url` from `doWeb` is not correct but `doc.location.href` is corrrect. @adam3smith : Is that correctly describing the problem?

What is the explanation of these behaviours and how can we deal with that in the future?

**Comment by aurimasv** [comment]
I split off (1) on its own with more details (see reference above).

(2) is explained here: https://github.com/zotero/zotero/pull/592#issuecomment-150206948
