### ISSUE TITLE
Document is not passed correctly to child translator

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#859]
Calling `translator.translate()` from a parent translator after setting `translator.setDocument(doc)` is not passing the document object correctly to the child translator (**need reference to original forum thread where this was discussed. I can't find it right now**). The current workaround is to use `translator.getTranslatorObject` and then invoke `translObj.doWeb` directly with the document.

Three translators are currently using this workaround:
Ubiquity Joirnals: https://github.com/zotero/translators/commit/f7792b93b62731a9f405c9dbe6aa5f0fa31a485d
SAE Papers: https://github.com/zotero/translators/commit/f712da1921d24571847c9c6f6be33f2068a1384c
Highwire 2.0: https://github.com/zotero/translators/commit/2c8885b50efc40ead3f42d81b44eb31b79ed1a7c

We have a lot more translators that call EM translator and this is not a good solution, so we need to fix this sooner rather than later. Some translators have a legitimate reason to use `.getTranslatorObject` when calling EM and those should not be affected. (also, this should only affect Firefox, since connectors do not sandbox translators)

I don't think we have other web translators that are being called by web translators, though we do call Google Scholar from Retrieve Metadata for PDFs. I'm assuming that is not affected, since we would have a lot more reports of this. (Maybe DOI/ISBN methods work sufficiently often for people to not be reporting this though).

Split off from #858

**Comment by zuphilip** [comment]
I guess that the 'Retrieve Metadata for PDFs' is not giving the same problems, because there the following code is used
```js
translate.setDocument(Zotero.HTTP.wrapDocument(doc, url));
```
See https://github.com/zotero/zotero/blob/3ef3d943b01dcc64c27e7b0c1de67f15c49c1778/chrome/content/zotero/recognizePDF.js#L724

**Comment by dstillman** [comment]
Oh, I probably fixed this with https://github.com/zotero/zotero/commit/ad45c3e51aecc2acd864511b32227a81f2d8ad8f. @zuphilip, can you confirm that the translators above work without the workaround in the latest 4.0 beta (4.0.29.12-beta.r2+ad45c3e)?

**Comment by zuphilip** [comment]
I tried the newest beta and changed the translator code to use `.translate()` again and it seems to work. Moreover, I tried out one commit before and there were some issues. Looks good for me!

(BTW I the workaround is IMO also a good way to call the EM translator.)
