### ISSUE TITLE
Trash doesn't refresh properly when emptying deleted attachments

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#866]
Steps to reproduce:

Add an attachment to an item. Trash the attachment. Go to the trash and empty the trash. 

The entire item should disappear from the trash, but it doesn't.

**Comment by dstillman** [comment]
Still broken when there are non-deleted sibling items.

**Comment by BurgessX** [comment]
I have counter to this problem, too. I have about 250 items in the `Trash`. When I `Empty Trash`, it takes long time to excuate. Sometimes nothing happens. Sometimes the software broken up and warn me to restart...

**Comment by dstillman** [comment]
This should be fixed since 6.0.13.

@BurgessX, if you're having trouble please [post to the Zotero Forums](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md).
