### ISSUE TITLE
Unable to autorecognize page type thus no autofill for page details(no auto pdf download as well) under e10s

### ISSUE THREAD

**Issue by extraymond** [zotero/zotero#874]
When enabling firefox e10s, the addon was unable to achieve the above function. While in none e10s firefox it's possible and very useful.

**Comment by pchampin** [comment]
I noticed the same problem, and I concur that it makes Zotero hardly usable when e10s is enabled :-/

**Comment by dstillman** [comment]
pchampin: https://www.zotero.org/support/kb/multiprocess_firefox
