### ISSUE TITLE
Uncaught error in getTypesForItemType with valid input

### ISSUE THREAD

**Issue by mvolz** [zotero/zotero#876]
In this file: https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/connector/cachedTypes.js

the method getTypesForItemType has an uncaught error if you give it the parameter '1', since the corresponding data in https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/connector/typeSchemaData.js has an array containing false instead of an index so creatorType is undefined and the line 	
```
		outputTypes[i] = {"id":creatorType[0]/* id */,
			"name":creatorType[1]/* name */}; 
```
throws an error.

Something like 
```
		if (creatorType){
			outputTypes[i] = {"id":creatorType[0]/* id */,
			"name":creatorType[1]/* name */};
		}
```
fixes it if you don't mind the method returning an empty array.

On a related note, is this schema still valid? The file hasn't changed in 4 years... does it need to be updated?

**Comment by dstillman** [comment]
This is probably fixed, but I'm not sure in what context you're testing it, so let me know if not.

Types and fields haven't changed in years for technical reasons, so the data is still valid (though those creator type arrays for 'note' and 'attachment' were probably in error). There's a long queue of type and field changes that we'll be making after 5.0.
