### ISSUE TITLE
Firefox PDF viewer saves PDF twice

### ISSUE THREAD

**Issue by owcz** [zotero/zotero#881]
Not sure if this is a translator or Zotero import issue. When I am viewing a PDF in the browser (latest OS X), and click on the "save" icon in the upper right, I get a dialog box:
>![screenshot 2015-12-09 12 37 02](https://cloud.githubusercontent.com/assets/778011/11694929/48827608-9e72-11e5-9a48-ceeefa5bd3db.png)

But no matter whether I choose to scrape for metadata or not, Zotero tries to import the file twice:
>![screenshot 2015-12-09 12 37 23](https://cloud.githubusercontent.com/assets/778011/11694952/5e197566-9e72-11e5-83c5-b02ef7a9357e.png)

And when scraping for metadata, does the process twice (one behind the other):
>![screenshot 2015-12-09 12 38 13](https://cloud.githubusercontent.com/assets/778011/11694966/6c8b801c-9e72-11e5-9ce9-5248d0253809.png)

This second dialog box sometimes disappears after a few seconds. In the end only one file is imported, so this isn't urgent, but thought it'd be worth reporting.

**Comment by dstillman** [comment]
This was fixed in 1d4dd9faac4869be5055ef77d07dded02457b7ca
