### ISSUE TITLE
Add support for ubuntu phone

### ISSUE THREAD

**Issue by extraymond** [zotero/zotero#884]
It would be nice if zotero can support ubuntu unity with its latest iteration unity8,
with the mechanism of scopes and lenses zotero can really sit in the heart of the ecosystem of ubuntu.

**Comment by dstillman** [comment]
Please post feature requests and bug reports to the Zotero Forums — this tracker is for developer use only. We don't have any current plans to support these Ubuntu features, though if someone wants to work on it, they're of course more than welcome to.

**Comment by extraymond** [comment]
Thx for replying!
I was assuming this repo accept wishlist as bug tag.
I'll try to discuss this with others in the forum.
