### ISSUE TITLE
Issue with civil law case law title in single citation

### ISSUE THREAD

**Issue by f-mb** [zotero/zotero#893]
Hi,

When you cite two (or more) "civil law case law" in a single citation, except for the first, court name and date are omitted.

>**Individual Citations :**
>CJCE, 31 mai 1978, C-102/77, Hoffmann-La Roche / Centrafarm, Rec. 1978.1139.
>CJCE, 17 octobre 1990, C-10/89, CNL-SUCAL / HAG (HAG II), Rec. 1990.I‑3711.
(FYI: `court`, `date`, `docket number`, `short title`, `reporter` `reporter volume`.`first page`.)

>**Single Citation :**
>CJCE, 31 mai 1978, C-102/77, Hoffmann-La Roche / Centrafarm, Rec. 1978.1139; CNL-SUCAL / HAG (HAG II), Rec. 1990.I‑3711.

>**Should be :**
>CJCE, 31 mai 1978, C-102/77, Hoffmann-La Roche / Centrafarm, Rec. 1978.1139; **CJCE, 17 octobre 1990, C-10/89,** CNL-SUCAL / HAG (HAG II), Rec. 1990.I‑3711.

I am not sure if it's a Zotero issue per se; the issue could with citeproc.js around lines 4197-4203.

I know there is a hook with for case. Multiple citations of a case law items with the same title will be merged into one.

I guess the issue is that every "civil law case law" has technically an identical title :  ""/false. 
(reminder: civil Law format is created by omitting the `title` field in favour of the `short title` field)

A fix would be for citeproc to first check if there is any title at all...

**Comment by dstillman** [comment]
Would have to defer to @fbennett on this one.

**Comment by f-mb** [comment]
@fbennet: any update regarding this issue?

**Comment by f-mb** [comment]
Transfered to https://github.com/Juris-M/citeproc-js/issues/10
