### ISSUE TITLE
Firefox Developer Edition cannot handle zotero:// protocol

### ISSUE THREAD

**Issue by CxRes** [zotero/zotero#897]
When I try to open an item, say an attached pdf file or a snapshot, using zotero, FF asks me 
"This link needs to opened with an application."

If I send it to FF itself, since the link is `zotero://attachment/<x>`, it just recursively opens tabs. 

This was not occuring when I was using regular FF on windows 7. Now I am using FF dev edition on windows 10.

**Comment by dstillman** [comment]
The problem actually isn't Developer Edition but Electrolysis — custom protocol handlers don't work with e10s enabled. It looks like Mozilla has [a plan](https://bugzilla.mozilla.org/show_bug.cgi?id=1095484) to fix this generally without every extension that registers a custom protocol handler needing to work around it, so we'll wait to see what happens with that.

In the meantime, if you want to use Zotero with Developer Edition, you'll need to disable e10s.

**Comment by CxRes** [comment]
Thanks, sorted for now...

**Comment by dstillman** [comment]
The full Zotero for Firefox is being discontinued, so this is no longer relevant.
