### ISSUE TITLE
Change fields order for cases in system.sql

### ISSUE THREAD

**Issue by f-mb** [zotero/zotero#900]
Would it be an issue if we change fields' order?

I think the following order for cases would make more sense :
```
...
INSERT INTO itemTypeFields VALUES (17, 44, NULL, 3);
INSERT INTO itemTypeFields VALUES (17, 96, NULL, 4);
INSERT INTO itemTypeFields VALUES (17, 117, NULL, 5);
INSERT INTO itemTypeFields VALUES (17, 43, NULL, 6);
INSERT INTO itemTypeFields VALUES (17, 97, NULL, 7);
INSERT INTO itemTypeFields VALUES (17, 98, NULL, 8);
INSERT INTO itemTypeFields VALUES (17, 42, NULL, 9);
...
```
(in system.sql)

**Comment by aurimasv** [comment]
Could you elaborate what exactly this is changing?

**Comment by f-mb** [comment]
Current order:
- Reporter
- Reporter volume
- Court
- Docket
- First page
- History
- Date decided

Proposed order:
- Court
- Date decided
- Docket
- Reporter
- Reporter volume
- First page
- History

It would order the fields in a similar way than for other items. It makes more sense to group "court" and "reporter" details.

**Comment by f-mb** [comment]
Ideally, we should add `INSERT INTO itemTypeFields VALUES (17, 15, NULL, 4); `

Different courts are organised in sections or chambers, this line would add the 'section' field after 'court'. But it might be refused, as a major change in the database.

**Comment by dstillman** [comment]
Field order is done for 5.0. (Can't do this on 4.0.)

We can't change fields until after 5.0 is out, but "Court Division" is [on the to-do list](https://github.com/avram/zotero-bits/issues/32), which sounds like what you want.

**Comment by f-mb** [comment]
Thank you!!!

I looked at https://github.com/avram/zotero-bits/issues/32, yes this is what I would like. Not sure we need a new field in the database though; I think that adding the "section" field to cases would be perfect.
