### ISSUE TITLE
Move library creation buttons into menu

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#905]
Instead of separate buttons for "New Collection…", "New Group…", and "New Feed…" (and later other things), we should keep "New Collection…" as a frequently used (and context-sensitive) button and have one other button with a menu to create groups, feeds, subscriptions, etc. (all library types). Button description can be "New Library". Can keep the group icon for now and just turn it into a menu.

(Alternatively, we could have a single button menu that includes "New Collection…", but collections are pretty different from the others and much more frequently created. I'm also not sure what possible description could be used to cover that other than just "New".)

/cc @adomasven

**Comment by adomasven** [comment]
Could we instead have a primary button "New Collection" with an arrow on the side to open a context menu for other types? Seems like a pretty standard practice in these sorts of UIs.

LibreOffice example:
![screenshot from 2016-02-05 12-05-24](https://cloud.githubusercontent.com/assets/5899315/12845874/d5d35dfe-cc00-11e5-91c9-7515d0c309ad.png)

![image](https://cloud.githubusercontent.com/assets/5899315/12845863/ad737858-cc00-11e5-972c-64cb4f962314.png)

**Comment by dstillman** [comment]
That's a possibility, but we're not set up to do that design-wise at the moment — our button shapes (at least on OS X) are hard-coded.

Also, while LibreOffice and Mac Word do split menu-buttons like this (the former possible getting it from the latter), it's not really a convention that's used on OS X. It makes for a very small click area, and it hides the menu functions more than we might want — it seems more appropriate when the menu has infrequently used, power-user variations on the main button (e.g., in Word, "New Blank Document", "New Blank Notebook Layout Document", "New Blank Publishing Layout Document"), which isn't really the case here.

Another factor to consider, though: for discoverability, we might want to provide the ability to create a saved search from the same place as "New Collection…". You can create a saved search from the Advanced Search window, and that makes sense because you can vet the results immediately, but I imagine a lot of people don't discover that (pretty cool) feature. So "New Collection…" might need to be a menu-button (or a split menu-button) anyway.

Anyhow, we can revisit with a new design, but for now, the easiest solution is just to make the existing "New Group…" button into a menu — can even keep the existing icon.
