### ISSUE TITLE
Regression: Zotero RDF loses mimeType for PDF attachments on import

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero#906]
reported https://forums.zotero.org/discussion/56637/subset-of-pdfs-not-recognized-as-pdf/#Comment_245774
replicated on linux

Likely group fix with https://github.com/zotero/zotero/pull/889

**Comment by aurimasv** [comment]
Are you suggesting that the export of mimeType is failing? I don't think this should have anything to do with import. For export, [mimeType should be working](https://github.com/zotero/zotero/blob/e206d7059516245e920026cc40826d9a12d1772f/chrome/content/zotero/xpcom/utilities_internal.js#L503)

**Comment by adam3smith** [comment]
I don't know yet what's happening, but PDFs lose their mimeType on a simple roundtrip import/export in Zotero RDF

**Comment by aurimasv** [comment]
OK, just tried exporting and you're right. mimeType needs to be added to uniqueFields.

**Comment by dstillman** [comment]
Fixed in https://github.com/zotero/zotero/commit/220cf2c29b51631c367ead1d085ef37006314ed6
