### ISSUE TITLE
Turn of the GitHub-issues if you don't want to use them.

### ISSUE THREAD

**Issue by buhtz** [zotero/zotero#910]
Turn of the GitHub-issues if you don't want to use them.

This would prevent contributers and users against confusions.

**Comment by dstillman** [comment]
From CONTRIBUTING.md:

> In order to keep product discussions open to as many people as possible, Zotero does not use GitHub Issues for bug reports or feature requests. Please use the Zotero Forums to report problems and suggest changes.

> For confirmed bugs or agreed-upon changes, new issues will be created in the relevant repositories on GitHub by Zotero developers.
