### ISSUE TITLE
Offer a bug-tracking-system with capabilities to monitor a ticket and upload files to it.

### ISSUE THREAD

**Issue by buhtz** [zotero/zotero#911]
It is your decission not to use GitHub. But a forum is not a nice solution for that.

Offer a bug-tracking-system with capabilities to monitor a ticket and upload files to it.

**Comment by dstillman** [comment]
The forums send email notifications by default, and we've used them quite successfully for bug reporting for a decade. You can upload images to a free image-sharing site and provide a link. An upcoming upgrade to the forums may support image uploads.
