### ISSUE TITLE
Toolbar buttons on the right

### ISSUE THREAD

**Issue by buhtz** [zotero/zotero#912]
You could see in two screenshots that the rigtht buttons ("sync") in the toolbar dissapear when the width of zotero/firefox window is to small.
No overflow button is offered.
And there still is enough space for the buttons. But it looks like that there is a space between the left and right buttons with a fixed (to big) width.

![zotero_ok](https://cloud.githubusercontent.com/assets/11861496/13266839/3edb16fc-da7a-11e5-8364-c2477723dd80.png)

![zotero_notok](https://cloud.githubusercontent.com/assets/11861496/13266833/3450599a-da7a-11e5-838b-93f94381c2df.png)

Please keep in mind that the two pictures have different widths but GitHub stretch same to the same size.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/57014/
