### ISSUE TITLE
Save proxy password in Standalone

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#913]
Firefox asks to save the password in the login manager after login.

There's also signon.autologin.proxy, disabled by default (in Firefox too), which controls whether the saved password is used or whether the user has to click OK in the dialog.

I'd take a patch for this, but otherwise it may just need to wait until after the architecture switch. (I'm not sure if we even can do this in XPCOM. Maybe with our own nsIAuthPrompt2? Some relevant code in http://mxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/nsLoginManagerPrompter.js, if someone wants to look into it, but I wouldn't spend much time on it, given that XPCOM's days are numbered.)

**Comment by tolot27** [comment]
Is there any progress on this issue?

**Comment by dstillman** [comment]
No, sorry.

**Comment by dstillman** [comment]
Zotero 5.0.88 shows a checkbox to remember the username and password.

See https://github.com/zotero/zotero/issues/1836 for a follow-up about proxy autologin.
