### ISSUE TITLE
Automatically retrieve metadata when saving PDF

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#917]
Now that the next release of the Chrome connector (and possibly the Safari connector) will support direct saving of PDFs, we should probably start running Retrieve Metadata automatically on those files (and in Zotero for Firefox too). We should also enable the Retrieve Metadata checkbox by default when "Save to Zotero" is selected in the Firefox open/save dialog. We could also do it when dragging individual files or linking/storing individual files, but I don't think we want to do it yet for multiple-file adds.

Any thoughts on how best to do this and account for misses, false positives, and CAPTCHA/other failures? I think the progress dialog would be too disruptive, so I think we have to do things automatically:
- A miss could trigger "Create Parent Item" automatically
- A false positive isn't that much worse than an empty parent item, if you have to edit it by hand anyway. You're probably best off just going and finding the article and saving it normally, and dragging the PDF over to that item if necessary, so then the only downside is needing to delete the old parent (and needing to know you can drag child items between parents). There could also be a more general system for approving metadata on new items — both to fill in details on saved items and to clear data for false positives from Retrieve Metadata — but not sure if we want to do that.
- A failure could leave the PDF as a top-level item, with the idea that you'd run it again yourself after that issue is resolved? Alternatively, it could just create a parent item if there were an "Update Parent Metadata from PDF" option on child attachments. I'm not sure exactly how such a feature would work. Probably can't just overwrite the parent, so might need to let the user confirm (or undo).

/cc @aurimasv, @adam3smith

**Comment by adam3smith** [comment]
I'm actually in the proces of importing a massive collection of PDFs to a group via retrieve metadata, so I have some recent first hand experience. I'm leaning towards option 3, i.e. leaving the item a top-level PDF. That way you can easily keep track of where retrieve metadata failed.

If we do attach to a parent item, we need to somehow label those very clearly -- Mendeley has a "needs review" banner at the top of the equivalent of the info pane. I feel like we don't currently have good enough UI means to do that -- just tagging is, imo, not enough.
Also, we are getting more query limit failures now, as google has gotten more restrictive and uses different technologies (I recently had to pick bodies of water and street signs in pictures), so having an easy way to re-run failed retrieval is important. That could also be via updating (which would be nice for other purposes, too, like updating from a early publication to a regular item), but we would need a full merge dialog for that.

Hope that helps a little.

**Comment by KarlHegbloom** [comment]
I agree that leaving them with no parent item when no Metadata was found is
better,  especially if a search can easily find all of them.

What possibility is there for using publicly shared Zotero collections as a
source for finding metadata? Would it be worth it? Adding Mendeley also
perhaps...? I'm not sure there's likely to be other copies of PDF's (that
metadata was not found for elsewhere), in Zotero.org, in other people's
public collections.

**Comment by zuphilip** [comment]
I also agree with @adam3smith that for failures/misses the best would be to 
<blockquote>leaving the item a top-level PDF</blockquote>
The parent item in these cases could otherwise only be a dummy item and I guess that all of these dummy items would also then be recognized as potential duplicates, which would be wrong.

On the other hand, if you want to give the users some checking mechanism, then I would suggest to make it similar to checking for duplicates, e.g. (where the folder "Needs Review" would be filled automatically):
![pdf-checks](https://cloud.githubusercontent.com/assets/5199995/13549695/a8374776-e30b-11e5-9c1b-960358800551.jpg)
This could involve quite some work and I am unsure how much this feature would be used at all.

@KarlHegbloom AFAIK no pdfs are currently shared publicly over Zotero collections and moreover one would need indexing the full texts...

**Comment by gagarine** [comment]
[bookends](http://www.sonnysoftware.com/bookends/bookends.html) as a very good workflow to import new attachments one by one or by bulk.

A 3min video show this features in actions: https://www.youtube.com/watch?v=uHmHdk_SOjg

This dialogue show up when you import a new files:
![screen shot 2016-11-22 at 14 59 00](https://cloud.githubusercontent.com/assets/164074/20526444/6096bc26-b0c4-11e6-8f26-3beadfc137ad.png)
