### ISSUE TITLE
Enabling "Show Unfiled Items" or "Show Duplicates" breaks UI

### ISSUE THREAD

**Issue by stakats** [zotero/zotero#918]
Testing on deasync branch. On restart Unfiled Items mostly behaves as expected, except that items dragged into collections do not immediately disappear from Unfiled. Show Duplicates appears to display dupes properly after restart.

**Comment by dstillman** [comment]
Probably fixed

**Comment by stakats** [comment]
Still seeing this. Error report 226992364. Can provide debug output if needed.

**Comment by dstillman** [comment]
Yeah, I'll take debug output for this. I was seeing this error before, but I can't reproduce it.

**Comment by dstillman** [comment]
Now?

**Comment by stakats** [comment]
UI no longer breaking, but items dragged into collections still do not immediately disappear from Unfiled.

**Comment by dstillman** [comment]
Now?
