### ISSUE TITLE
Modify item type and metadata of multiple files

### ISSUE THREAD

**Issue by pcuinty** [zotero/zotero#924]
I am thinking about selecting multiple items -> right click -> change Metadata -> window opens -> change item type and other meta data -> save for all

EDIT: or better, no additional window opens, but one selects the item type in the right pane and then save for all.

As pointed out in the [forum](https://forums.zotero.org/discussion/56702/i-need-auto-change-from-webpage-style-to-journal-for-all-my-citations/) something like this is not possible yet.

**Comment by adam3smith** [comment]
the issue tracker is for development use. The forum is the right place for feature requests, please keep them there -- it's a better place for discussing details of features, their implementation, having other users chime in etc.

**Comment by dstillman** [comment]
(Batch editing is planned, though.)
