### ISSUE TITLE
Selecting two-field creator autocomplete with Tab should populate both fields

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#926]
Right now it puts both values into the open field

https://forums.zotero.org/discussion/57712

**Comment by fbennett** [comment]
For a start on this one, changing the [ontextentered](https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/bindings/itembox.xml#L1488) event to onchange triggers handleCreatorAutoCompleteSelect(), which does the two-field placement. It doesn't move the cursor, though, and leaves the field open for editing, so usage for rapid keyboard entry would be type - arrow-scroll - tab - tab - tab. Not sure if that would satisfy users wanting TAB to work there.

**Comment by dstillman** [comment]
That was the key to fixing this properly — `ontextentered` is triggered on Return, and `onchange` is triggered on Tab/Shift-Tab, so by assigning both we can tell `handleCreatorAutoCompleteSelect` whether to allow the regular field advancing to work or whether to force the current textbox to stay open as it was doing for Return. Thanks!

**Comment by fbennett** [comment]
Nice!
