### ISSUE TITLE
Feed items out of order

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#933]
A block of new entries for http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml just showed up in the middle of my feed items list. I can look into specifics if it'd be helpful, but it seems like there's a bug with ordering once feed entries go out of the feed. (The NYT feed only has entries for the last day or so, so the ones above and below are no longer in the feed.)

@adomasven, if you're not seeing this, I can try just clearing the feed — it's possible I created this on a previous version of the branch that handled ordering differently.

**Comment by adomasven** [comment]
I thought my feed ordering was off sometimes too, but didn't pay much attention until now. Currently ordering on `itemID`, but it doesn't seem to be properly auto-incrementing. Need to introduce a separate autoincrement id field for feed items? Why is `itemID` non auto-increment?

**Comment by dstillman** [comment]
Fixed (and explained) in fabc2ba6a252c356b7e082cbc47856e607fa42c2
