### ISSUE TITLE
UI not updating when dragging child item between parents

### ISSUE THREAD

**Issue by willsALMANJ** [zotero/zotero#940]
In master, if you have an item with a single child (I mainly tested with notes) and you drag the child to another item, the child item appears as a child to both items after it is dropped. If you refresh the items pane by selecting a different collection and then come back, the child item no long appears as a child of the original parent (so this is just an issue of the UI not updating and not an item data problem). If the parent item had multiple children of the type that was dragged, it seems to update okay. I only see this when the item dragged is the only child of its type.

**Comment by dstillman** [comment]
Thanks — I have a fix coming for this later today.

**Comment by willsALMANJ** [comment]
Nice, thanks. I found this while porting one of the funcitons in my plugin to 5.0 and this fix didn't require any additional changes to the plugin.
