### ISSUE TITLE
icons are weirdly stretched on HiDPI

### ISSUE THREAD

**Issue by JonathanReeve** [zotero/zotero#943]
This may or may not be a HiDPI issue, but I'm guessing it is, since HiDPI causes a lot of problems like this. Generally speaking, Zotero looks fine, but the icons in the toolbar look weirdly squashed, both in the browser and in Zotero Standalone. Screenshot below.

![zotero-screenshot](https://cloud.githubusercontent.com/assets/1843676/14412292/3f9fa2ba-ff2d-11e5-9034-ecfed83c674b.png)

**Comment by dstillman** [comment]
What OS/version/etc.? It obviously looks right for most users.

**Comment by dstillman** [comment]
OK, I can reproduce this on HiDPI Linux. Will fix, thanks.

**Comment by dstillman** [comment]
The toolbar isn't in great shape in general on Linux, but the 2x icons should be sized correctly now.

(Seems like HiDPI on Linux is still a bit of a mess — I'm not even seeing HiDPI icons for most of the built-in icons (except for Firefox Hello) in the Firefox toolbar…)

**Comment by JonathanReeve** [comment]
Awesome, thanks. Firefox looks pretty perfect for me on HiDPI, using the latest GNOME under Arch Linux. But Zotero and Zotero Standalone don't look great. You're probably already seeing this, but I'm getting tiny UI elements in Zotero Standalone, for instance: 

![zotero-screenshot2](https://cloud.githubusercontent.com/assets/1843676/14412910/019e731c-ff3a-11e5-827d-dff235d69cc9.png)

**Comment by dstillman** [comment]
I'm seeing various problems in Firefox itself with 45.0.1 on Ubuntu 15.10.

Low-res toolbar icons (except for Refresh and Firefox Hello), tiny scrollbars:

<img width="530" alt="toolbar" src="https://cloud.githubusercontent.com/assets/783082/14412997/be11e80c-ff3b-11e5-90e9-9d3ed5fc41f5.png">

Tiny checkbox in close prompt:

<img width="587" alt="checkbox" src="https://cloud.githubusercontent.com/assets/783082/14413001/c3859ae0-ff3b-11e5-8a40-7a8a472d02b9.png">

I suspect some of these (the scrollbars in particular) are from my running in a VM, but I assume some are just issues that haven't been fixed yet by Mozilla.

Anyhow, we're leaving the Mozilla platform in the not-too-distant future, and I don't know how representative my VM experience is, so unless someone contributes a patch, I'm afraid those UI issues in Standalone will need to wait for either Mozilla to address them generally or for our new platform.

**Comment by JonathanReeve** [comment]
Some of those issues might be fixed in the latest Firefox. I don't think
it's a VM issue, but an Ubuntu issue--Arch usually gets the latest software
from upstream months or years before Ubuntu does. I am seeing the toolbar
fuzziness that you are, though, although that's fixed for me using the Arc
theme. Scrollbars and checkboxes look fine for me.
