### ISSUE TITLE
Clicking away from author field after entry can lose entered author

### ISSUE THREAD

**Issue by wbt** [zotero/zotero#944]
Workflow: 
1. Click to manually add a new paper.
2. Change the Author field to be the single full name format.
3. Select & copy author name from web page (no good translator).
4. Paste name in author field.
5. Click away from field to save author name.
6. Click the plus button to add another author.
7. Repeat steps 3-6 for remaining authors.
8. After pasting the last author, click away by clicking on the format control boxes next to the first author's name.
9. Go down the list clicking that icon to convert all authors to the first & last names format.
10. Manually clean up cases where the split was incorrect (e.g. particles in name).

Steps 5 and 6 should be combinable, but for some reason aren't (you can't press the plus button to add an author until after the previous one's information has been saved).  That's probably a feature request for another thread. 

The issue being reported here is that step 8 deletes the last author from the author list, instead of saving the author name.

**Comment by dstillman** [comment]
Simpler STR:

1) Create an empty item.
2) Add creator "A".
3) Enter second creator "B" but leave text field open.
4) Click field-mode toggle on creator "A" row.

The field mode of creator "A" will change, but creator "B" will disappear instead of being saved.

**Comment by dstillman** [comment]
I can't reproduce this in 5.0.33.
