### ISSUE TITLE
Preferences: help URL does not open if browser.preferences.instantApply is "true"

### ISSUE THREAD

**Issue by retorquere** [zotero/zotero#949]
window.opener.ZoteroPane_Local is undefined in `openURL`

**Comment by dstillman** [comment]
STR?

**Comment by retorquere** [comment]
Sorry: https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/preferences/preferences.js#L64

**Comment by dstillman** [comment]
Yes, but what are the STR?

**Comment by retorquere** [comment]
Oh sorry, I thought you meant Spot The Reference. I don't know what else it could stand for, so I don't understand your question.

**Comment by dstillman** [comment]
Steps to reprofuce

**Comment by retorquere** [comment]
Ah! Open Zotero preferences, click question mark (in my case bottom right, I don't know if that's platform specific), nothing happens. Set `browser.preferences.instantApply` to false, and clicking that question mark opens the browser with a help page.

**Comment by retorquere** [comment]
I've been able to make it work on my machine by using `Zotero.getActiveZoteroPane().loadURI(...)`, but I really don't understand the meaning and workings of the `ZoteroPane_Local` concept so I honestly don't know what the fallout from that could be.

**Comment by dstillman** [comment]
OK, that's why I ask, because clicking the question mark works for me on OS X with Fx46 and 5.0 branch in normal pane mode. I'll take a look later, but maybe try in a new profile to see if it still happens there.

**Comment by retorquere** [comment]
I'm still on 4.0 (FF45 on OS X)

**Comment by retorquere** [comment]
In a clean profile it does work if I open the [references from the gear menu, not if I open them from the addins menu.

**Comment by dstillman** [comment]
Oh, is this all from the Add-ons pane? I can reproduce that.

**Comment by retorquere** [comment]
Turns out yes. I thought it was generally, but it's only from the addons
tab.

**Comment by dstillman** [comment]
No longer relevant in Standalone
