### ISSUE TITLE
Cannot start Zotero 5.0 Alpha on Windows

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#955]
I tested the installation of 5.0 on a new Firefox 45.0.2 profile in Windows 8 as well as Windows 10. Starting installation was possible but after restart of Firefox there is no Zotero icon and also starting it over the menu or shortcut is not possible:

![zotero-5-0-not-starting](https://cloud.githubusercontent.com/assets/5199995/14762685/309d083a-0981-11e6-83d9-2b6be0ccbe3b.png)

**Comment by dstillman** [comment]
Sorry, you need to change general.useragent.locale to en-US in about:config to test this.
