### ISSUE TITLE
5.0: Drag items to collections

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#958]
Sometimes (*) when drag an item to a collection an error occurs:
```
[JavaScript Error: "TypeError: treeRow is undefined" {file: "chrome://zotero/content/xpcom/collectionTreeView.js" line: 1441}]
Zotero.CollectionTreeView.prototype.canDropCheck@chrome://zotero/content/xpcom/collectionTreeView.js:1441:1
Zotero.LibraryTreeView.prototype.onDragOver@chrome://zotero/content/xpcom/libraryTreeView.js:261:8
ondragover@chrome://zotero/content/tab.xul:1:8
```
(*) It is hard to say what triggers it exactly and how many times. Not every item seem to behave the same and also after some amount of errors the same item will be okay for some time...

**Comment by dstillman** [comment]
I can't reproduce this. Let me know if you notice any pattern here.

**Comment by dstillman** [comment]
(Also, if this only happens in tab mode, all bets are off for now.)

**Comment by zuphilip** [comment]
I didn't see this lately and therefore closing the issue here now.
