### ISSUE TITLE
5.0: Feed options in tab mode

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#960]
The feed options `From Page...` should be deactivated in tab mode of firefox (currently the also produce some errors/warnings):
![feeds-in-tab-mode](https://cloud.githubusercontent.com/assets/5199995/14763399/fc1dad08-0994-11e6-98e2-cac6ccbe5a70.png)

**Comment by dstillman** [comment]
We're not testing tab mode at all at the moment, since it [may not exist in 5.0 Final](https://groups.google.com/d/msg/zotero-dev/20KD_Sy6FkM/W19IYhlSFwAJ).

**Comment by dstillman** [comment]
Tab mode removed in https://github.com/zotero/zotero/issues/1135
