### ISSUE TITLE
5.0: An error occurred during syncing

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#965]
I just created a new account at zotero.org and tried to sync with that in my 5.0 profile. Report ID is 1703075507 with
```
HTTP POST https://api.zotero.org/users/3072654/items/43HN8STH/file failed with status code 400:

JSON Error: Syntax error, malformed JSON
```

**Comment by dstillman** [comment]
That's a misleading error, at least, but just to understand this better, what's the provenance of this database? Is this a new 5.0 database or an upgraded one? If the latter, has it previously been synced to a different account in 4.0? (If so, did you get a warning when you tried to link the new account?)

**Comment by zuphilip** [comment]
Yes, it is a new database created in my new Firefox profile which is just some hours old. It hasn't been synced before.

![zotero-database](https://cloud.githubusercontent.com/assets/5199995/14767181/e41d4ffc-0a1f-11e6-8ab8-b31e89c1d8d4.png)

 I can upload the sqlite files or whatever helps you to debug

**Comment by dstillman** [comment]
I'll probably be able to reproduce this, but just in case, seeing that DB would be helpful, thanks.

**Comment by zuphilip** [comment]
Okay, here is my DB: https://bibserv24.bib.uni-mannheim.de/owncloud/index.php/s/hqQbZ5xwIIZFwvR/download (please note this link will expire in two weeks).

**Comment by dstillman** [comment]
OK, thanks — you can delete that if you want.

But the state of that DB is actually a little different from what I expected. If you're getting this each time you try to sync, could you provide a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> for a sync attempt that triggers this?

**Comment by zuphilip** [comment]
Yes, I am getting this each time zotero tries to sync. Debug ID for a sync attempt D1705374840

**Comment by dstillman** [comment]
@zuphilip: Could you grab the latest (r18) and generate another Debug ID with that?

**Comment by zuphilip** [comment]
The Debug ID is D1457753063.

**Comment by dstillman** [comment]
Well that was probably a good bug to fix. Should be set in r19. Thanks!
