### ISSUE TITLE
5.0 "An error occured during sync

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero#968]
Red exclamation mark next to sync arrow On clicking
"An error occured during sync"
"Last-Modified Version not provided"
error report ID 787521419
Sync seems to go through? But error persists after re-sync.

**Comment by adam3smith** [comment]
Has gone away after a couple of syncs. Not sure why/how

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/dataserver/commit/2a5d797aa02ba034f924acdf13f3d13bd2497bad, I believe. (Dragging an item to My Publications would've fixed it.)

**Comment by adam3smith** [comment]
yes, I did that at some point around where the error disappeared, so that makes sense.
