### ISSUE TITLE
Sync error in Firefox 46.0 and 5.0-alpha.r19+95ba68a

### ISSUE THREAD

**Issue by rmzelle** [zotero/zotero#983]
I have the 5.0 alpha installed in Firefox Portable, and just tried syncing to my Zotero account to my local empty library.

I'm getting an "An error occured during syncing" error on my first try:

```
[JavaScript Error: "Cannot edit item in read-only library devTesting" {file: "chrome://zotero/content/xpcom/data/dataObject.js" line: 774}]
```

Report ID: 191735634

**Comment by dstillman** [comment]
Could I get a Debug ID for this?

**Comment by dstillman** [comment]
Actually, try the latest XPI first — hopefully that will fix it.

**Comment by rmzelle** [comment]
Sync went through with 5.0-alpha.r22+14ce455, so feel free to close.
