### ISSUE TITLE
hypothes.is integration?

### ISSUE THREAD

**Issue by bijang** [zotero/zotero#996]
Hi I'm a non programmer outsider, this is more of a feature request than an issue...I just found a separate discussion here after searching zotero hypothes.is, as I thought it would be a good idea to, someday , have private and or public hypothes.is generated annotations, highlights and notes, exported into zotero the way zotfile does for certain pdf viewers currently.
Integration with hypothes.is would be fantastic, to selectively export the private/ones own /or entire collaborative annotations, into zotero, like zotfile with appropriate citation and page indexing etc. Would this be possible? 
If my question is out of turn out in the wrong place or this is an inappropriate use of a thread, apologies, i'm just very excited about this concept being developed, as much as I am about hypothes.is coming to Firefox and epub.js + hypothes.is!
Thank you for your time and work on zotero and I hope to have more immdiately useful issues in the future

**Comment by dstillman** [comment]
You can post feature requests on the [Zotero Forums](https://forums.zotero.org/).
